# Append one CLK-03 driver and preserve the complete prior CLK-02 registration.
if(NOT DEFINED CLK03_REPOSITORY_ROOT)
  message(FATAL_ERROR "CLK-03 requires an explicit repository root")
endif()
if(DEFINED CLK02_REPOSITORY_ROOT AND NOT CLK02_REPOSITORY_ROOT STREQUAL CLK03_REPOSITORY_ROOT)
  message(FATAL_ERROR "CLK-03 and CLK-02 repository roots must agree")
endif()
set(CLK02_REPOSITORY_ROOT "${CLK03_REPOSITORY_ROOT}")
include("${CLK03_REPOSITORY_ROOT}/tools/porting/clk02_reference.cmake")
if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
  get_property(_clk03_scheduled GLOBAL PROPERTY CLK03_REFERENCE_SCHEDULED)
  if(NOT _clk03_scheduled)
    set_property(GLOBAL PROPERTY CLK03_REFERENCE_SCHEDULED TRUE)
    set_property(GLOBAL PROPERTY CLK03_REFERENCE_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}")
    function(clk03_add_original_reference)
      if(NOT TARGET energypluslib)
        message(FATAL_ERROR "CLK-03 requires the unchanged genuine GNU core")
      endif()
      get_property(_clk03_dir GLOBAL PROPERTY CLK03_REFERENCE_DIRECTORY)
      get_target_property(_clk03_target_defs energypluslib COMPILE_DEFINITIONS)
      get_directory_property(_clk03_directory_defs DIRECTORY "${CMAKE_SOURCE_DIR}/src/EnergyPlus" COMPILE_DEFINITIONS)
      set(_clk03_defs ${_clk03_target_defs} ${_clk03_directory_defs})
      list(FILTER _clk03_defs EXCLUDE REGEX "-NOTFOUND$")
      list(REMOVE_DUPLICATES _clk03_defs)
      add_executable(clk03_reference_helper "${_clk03_dir}/clk03_reference_helper.cpp")
      target_include_directories(clk03_reference_helper PRIVATE "$<TARGET_PROPERTY:energypluslib,INCLUDE_DIRECTORIES>")
      target_compile_definitions(clk03_reference_helper PRIVATE ${_clk03_defs})
      target_link_libraries(clk03_reference_helper PRIVATE energypluslib project_options project_fp_options project_warnings bcrypt)
      target_compile_features(clk03_reference_helper PRIVATE cxx_std_20)
    endfunction()
    cmake_language(DEFER CALL clk03_add_original_reference)
  endif()
endif()
