# Add only the supplemental matched-caller driver; retain all previous targets.
if(NOT DEFINED CLK03_REPOSITORY_ROOT)
  message(FATAL_ERROR "Matched CLK03 helper requires explicit repository root")
endif()
include("${CLK03_REPOSITORY_ROOT}/tools/porting/clk03_reference.cmake")
if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
  get_property(_clk03_prod_scheduled GLOBAL PROPERTY CLK03_PRODUCTION_REFERENCE_SCHEDULED)
  if(NOT _clk03_prod_scheduled)
    set_property(GLOBAL PROPERTY CLK03_PRODUCTION_REFERENCE_SCHEDULED TRUE)
    set_property(GLOBAL PROPERTY CLK03_PRODUCTION_REFERENCE_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}")
    function(clk03_add_production_original_reference)
      if(NOT TARGET energypluslib)
        message(FATAL_ERROR "Matched CLK03 requires unchanged genuine GNU core")
      endif()
      get_property(_clk03_prod_dir GLOBAL PROPERTY CLK03_PRODUCTION_REFERENCE_DIRECTORY)
      get_target_property(_clk03_prod_target_defs energypluslib COMPILE_DEFINITIONS)
      get_directory_property(_clk03_prod_directory_defs DIRECTORY "${CMAKE_SOURCE_DIR}/src/EnergyPlus" COMPILE_DEFINITIONS)
      set(_clk03_prod_defs ${_clk03_prod_target_defs} ${_clk03_prod_directory_defs})
      list(FILTER _clk03_prod_defs EXCLUDE REGEX "-NOTFOUND$")
      list(REMOVE_DUPLICATES _clk03_prod_defs)
      add_executable(clk03_production_reference_helper "${_clk03_prod_dir}/clk03_production_reference_helper.cpp")
      target_include_directories(clk03_production_reference_helper PRIVATE "$<TARGET_PROPERTY:energypluslib,INCLUDE_DIRECTORIES>")
      target_compile_definitions(clk03_production_reference_helper PRIVATE ${_clk03_prod_defs})
      target_link_libraries(clk03_production_reference_helper PRIVATE energypluslib project_options project_fp_options project_warnings bcrypt)
      target_compile_features(clk03_production_reference_helper PRIVATE cxx_std_20)
    endfunction()
    cmake_language(DEFER CALL clk03_add_production_original_reference)
  endif()
endif()
