# Add only a new read-only same-ABI dynamic original API observation target.
include("${CMAKE_CURRENT_LIST_DIR}/psy02_reference.cmake")
if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
  get_property(_geo01_scheduled GLOBAL PROPERTY GEO01_REFERENCE_SCHEDULED)
  if(NOT _geo01_scheduled)
    set_property(GLOBAL PROPERTY GEO01_REFERENCE_SCHEDULED TRUE)
    set_property(GLOBAL PROPERTY GEO01_REFERENCE_SOURCE "${CMAKE_CURRENT_LIST_DIR}/geo01_reference.cpp")
    function(geo01_add_original_reference)
      if(NOT TARGET energypluslib)
        message(FATAL_ERROR "GEO-01 requires the verified unchanged original core")
      endif()
      get_property(_geo01_source GLOBAL PROPERTY GEO01_REFERENCE_SOURCE)
      get_target_property(_geo01_target_defs energypluslib COMPILE_DEFINITIONS)
      get_directory_property(_geo01_directory_defs DIRECTORY "${CMAKE_SOURCE_DIR}/src/EnergyPlus" COMPILE_DEFINITIONS)
      set(_geo01_defs ${_geo01_target_defs} ${_geo01_directory_defs})
      list(FILTER _geo01_defs EXCLUDE REGEX "-NOTFOUND$")
      list(REMOVE_DUPLICATES _geo01_defs)
      add_executable(geo01_reference "${_geo01_source}")
      target_include_directories(geo01_reference PRIVATE "$<TARGET_PROPERTY:energypluslib,INCLUDE_DIRECTORIES>")
      target_compile_definitions(geo01_reference PRIVATE ${_geo01_defs})
      # Array allocation queries reference original IndexRange::npos. Link only
      # the unchanged container library, not a second EnergyPlus core/state.
      target_link_libraries(geo01_reference PRIVATE project_options project_fp_options project_warnings objexx bcrypt)
      target_compile_features(geo01_reference PRIVATE cxx_std_20)
    endfunction()
    cmake_language(DEFER CALL geo01_add_original_reference)
  endif()
endif()
