# Append GEO-03 only. Every prior card target keeps its original source/flags.
include("${CMAKE_CURRENT_LIST_DIR}/geo02_reference.cmake")
if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
  get_property(_geo03_scheduled GLOBAL PROPERTY GEO03_REFERENCE_SCHEDULED)
  if(NOT _geo03_scheduled)
    set_property(GLOBAL PROPERTY GEO03_REFERENCE_SCHEDULED TRUE)
    set_property(GLOBAL PROPERTY GEO03_REFERENCE_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}")
    function(geo03_add_original_reference)
      if(NOT TARGET energypluslib)
        message(FATAL_ERROR "GEO-03 requires the verified unchanged original GNU core")
      endif()
      get_property(_geo03_dir GLOBAL PROPERTY GEO03_REFERENCE_DIRECTORY)
      get_target_property(_geo03_target_defs energypluslib COMPILE_DEFINITIONS)
      get_directory_property(_geo03_directory_defs DIRECTORY "${CMAKE_SOURCE_DIR}/src/EnergyPlus" COMPILE_DEFINITIONS)
      set(_geo03_defs ${_geo03_target_defs} ${_geo03_directory_defs})
      list(FILTER _geo03_defs EXCLUDE REGEX "-NOTFOUND$")
      list(REMOVE_DUPLICATES _geo03_defs)
      # Dynamic observer: genuine API-owned state, no duplicate static core.
      add_executable(geo03_reference "${_geo03_dir}/geo03_reference.cpp")
      target_include_directories(geo03_reference PRIVATE "$<TARGET_PROPERTY:energypluslib,INCLUDE_DIRECTORIES>")
      target_compile_definitions(geo03_reference PRIVATE ${_geo03_defs})
      target_link_libraries(geo03_reference PRIVATE project_options project_fp_options project_warnings objexx bcrypt)
      target_compile_features(geo03_reference PRIVATE cxx_std_20)
      if(NOT DEFINED GEO03_HEIGHT_FRAGMENT OR NOT EXISTS "${GEO03_HEIGHT_FRAGMENT}")
        message(FATAL_ERROR "GEO-03 requires exact original SurfaceGeometry.cc455-546")
      endif()
      if(NOT DEFINED GEO02_SETUP_FRAGMENT OR NOT EXISTS "${GEO02_SETUP_FRAGMENT}")
        message(FATAL_ERROR "GEO-03 reuses the immutable original source273-289 trig fragment")
      endif()
      # Direct numerical helper: genuine core/state and original inherited ABI.
      add_executable(geo03_reference_helper "${_geo03_dir}/geo03_reference_helper.cpp")
      target_compile_definitions(geo03_reference_helper PRIVATE ${_geo03_defs}
        GEO03_TRIG_FRAGMENT="${GEO02_SETUP_FRAGMENT}" GEO03_HEIGHT_FRAGMENT="${GEO03_HEIGHT_FRAGMENT}")
      target_link_libraries(geo03_reference_helper PRIVATE energypluslib project_options project_fp_options project_warnings)
      target_compile_features(geo03_reference_helper PRIVATE cxx_std_20)
    endfunction()
    cmake_language(DEFER CALL geo03_add_original_reference)
  endif()
endif()
