//! Persistent CP382 total-output-assignment state.

use ep_model::IdealLoadsAirSystemId;

use super::PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputAssignmentSnapshot;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(in crate::ideal_loads::calc) enum PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputAssignmentRetainedRoute
{
    UnitOff,
    NonCooling,
    PositiveGuardFalseFallthrough,
    HeatingAvailabilityGuardFalseFallthroughCapacityLimitGuardFalseFallthrough,
    HeatingAvailabilityGuardFalseFallthroughDehumidificationTotalOutputAssigned,
    HeatingAvailabilityGuardFalseFallthroughDehumidificationGuardFalseFallthrough,
    HumidificationControlGuardFalseFallthroughCapacityLimitGuardFalseFallthrough,
    HumidificationControlGuardFalseFallthroughDehumidificationTotalOutputAssigned,
    HumidificationControlGuardFalseFallthroughDehumidificationGuardFalseFallthrough,
    DehumidificationControlHumidistatMaximumAssignmentExecutedCapacityLimitGuardFalseFallthrough,
    DehumidificationControlHumidistatMaximumAssignmentExecutedDehumidificationTotalOutputAssigned,
    DehumidificationControlHumidistatMaximumAssignmentExecutedDehumidificationGuardFalseFallthrough,
    DehumidificationControlNoneMaximumAssignmentExecutedCapacityLimitGuardFalseFallthrough,
    DehumidificationControlNoneMaximumAssignmentExecutedDehumidificationTotalOutputAssigned,
    DehumidificationControlNoneMaximumAssignmentExecutedDehumidificationGuardFalseFallthrough,
    DehumidificationControlGuardFalseFallthroughCapacityLimitGuardFalseFallthrough,
    DehumidificationControlGuardFalseFallthroughDehumidificationTotalOutputAssigned,
    DehumidificationControlGuardFalseFallthroughDehumidificationGuardFalseFallthrough,
}

/// Persistent bounded state and exact source/lineage counters for one system.
#[allow(missing_docs)]
#[derive(Clone, Debug, PartialEq)]
pub struct PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputAssignmentRuntimeState
{
    pub system: IdealLoadsAirSystemId,
    pub transition_count: usize,
    pub unit_off_skip_count: usize,
    pub non_cooling_skip_count: usize,
    pub positive_guard_false_fallthrough_skip_count: usize,
    pub heating_availability_guard_false_fallthrough_count: usize,
    pub humidification_control_guard_false_fallthrough_count: usize,
    pub dehumidification_control_humidistat_supply_humidity_ratio_maximum_assignment_count: usize,
    pub dehumidification_control_none_supply_humidity_ratio_maximum_assignment_count: usize,
    pub dehumidification_control_guard_false_fallthrough_count: usize,
    pub heating_availability_guard_false_fallthrough_capacity_guard_false_count: usize,
    pub heating_availability_guard_false_fallthrough_dehumidification_body_entry_count: usize,
    pub heating_availability_guard_false_fallthrough_dehumidification_guard_false_count: usize,
    pub heating_availability_guard_false_fallthrough_dehumidification_total_output_assignment_count: usize,
    pub humidification_control_guard_false_fallthrough_capacity_guard_false_count: usize,
    pub humidification_control_guard_false_fallthrough_dehumidification_body_entry_count: usize,
    pub humidification_control_guard_false_fallthrough_dehumidification_guard_false_count: usize,
    pub humidification_control_guard_false_fallthrough_dehumidification_total_output_assignment_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_capacity_guard_false_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_dehumidification_body_entry_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_dehumidification_guard_false_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_assignment_count: usize,
    pub dehumidification_control_none_maximum_assignment_capacity_guard_false_count: usize,
    pub dehumidification_control_none_maximum_assignment_dehumidification_body_entry_count: usize,
    pub dehumidification_control_none_maximum_assignment_dehumidification_guard_false_count: usize,
    pub dehumidification_control_none_maximum_assignment_dehumidification_total_output_assignment_count: usize,
    pub dehumidification_control_guard_false_fallthrough_capacity_guard_false_count: usize,
    pub dehumidification_control_guard_false_fallthrough_dehumidification_body_entry_count: usize,
    pub dehumidification_control_guard_false_fallthrough_dehumidification_guard_false_count: usize,
    pub dehumidification_control_guard_false_fallthrough_dehumidification_total_output_assignment_count: usize,
    pub dehumidification_total_output_assignment_count: usize,
    pub source_site_execution_count: usize,
    pub cp330_supply_mass_flow_rate_owned_read_count: usize,
    pub cp329_same_call_supply_mass_flow_rate_bit_corroboration_count: usize,
    pub cp339_same_call_supply_mass_flow_rate_bit_corroboration_count: usize,
    pub supply_mass_flow_rate_read_count: usize,
    pub cp329_mixed_air_enthalpy_owned_read_count: usize,
    pub cp329_same_call_recirculation_enthalpy_bit_corroboration_count: usize,
    pub cp339_same_call_mixed_air_enthalpy_bit_corroboration_count: usize,
    pub mixed_air_enthalpy_read_count: usize,
    pub cp379_post_saturation_supply_enthalpy_owned_read_count: usize,
    pub cp379_same_call_supply_enthalpy_bits_corroboration_count: usize,
    pub supply_enthalpy_read_count: usize,
    pub enthalpy_difference_calculation_count: usize,
    pub cooling_total_output_calculation_count: usize,
    pub cooling_total_output_assignment_write_count: usize,
    pub latest: Option<
        PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputAssignmentSnapshot,
    >,
    pub(super) latest_route: Option<
        PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputAssignmentRetainedRoute,
    >,
    pub(super) latest_transition_ordinal: Option<usize>,
}

impl PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputAssignmentRuntimeState {
    /// Creates zeroed CP382 state for one system.
    #[must_use]
    pub const fn new(system: IdealLoadsAirSystemId) -> Self {
        Self {
            system,
            transition_count: 0,
            unit_off_skip_count: 0,
            non_cooling_skip_count: 0,
            positive_guard_false_fallthrough_skip_count: 0,
            heating_availability_guard_false_fallthrough_count: 0,
            humidification_control_guard_false_fallthrough_count: 0,
            dehumidification_control_humidistat_supply_humidity_ratio_maximum_assignment_count: 0,
            dehumidification_control_none_supply_humidity_ratio_maximum_assignment_count: 0,
            dehumidification_control_guard_false_fallthrough_count: 0,
            heating_availability_guard_false_fallthrough_capacity_guard_false_count: 0,
            heating_availability_guard_false_fallthrough_dehumidification_body_entry_count: 0,
            heating_availability_guard_false_fallthrough_dehumidification_guard_false_count: 0,
            heating_availability_guard_false_fallthrough_dehumidification_total_output_assignment_count: 0,
            humidification_control_guard_false_fallthrough_capacity_guard_false_count: 0,
            humidification_control_guard_false_fallthrough_dehumidification_body_entry_count: 0,
            humidification_control_guard_false_fallthrough_dehumidification_guard_false_count: 0,
            humidification_control_guard_false_fallthrough_dehumidification_total_output_assignment_count: 0,
            dehumidification_control_humidistat_maximum_assignment_capacity_guard_false_count: 0,
            dehumidification_control_humidistat_maximum_assignment_dehumidification_body_entry_count: 0,
            dehumidification_control_humidistat_maximum_assignment_dehumidification_guard_false_count: 0,
            dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_assignment_count: 0,
            dehumidification_control_none_maximum_assignment_capacity_guard_false_count: 0,
            dehumidification_control_none_maximum_assignment_dehumidification_body_entry_count: 0,
            dehumidification_control_none_maximum_assignment_dehumidification_guard_false_count: 0,
            dehumidification_control_none_maximum_assignment_dehumidification_total_output_assignment_count: 0,
            dehumidification_control_guard_false_fallthrough_capacity_guard_false_count: 0,
            dehumidification_control_guard_false_fallthrough_dehumidification_body_entry_count: 0,
            dehumidification_control_guard_false_fallthrough_dehumidification_guard_false_count: 0,
            dehumidification_control_guard_false_fallthrough_dehumidification_total_output_assignment_count: 0,
            dehumidification_total_output_assignment_count: 0,
            source_site_execution_count: 0,
            cp330_supply_mass_flow_rate_owned_read_count: 0,
            cp329_same_call_supply_mass_flow_rate_bit_corroboration_count: 0,
            cp339_same_call_supply_mass_flow_rate_bit_corroboration_count: 0,
            supply_mass_flow_rate_read_count: 0,
            cp329_mixed_air_enthalpy_owned_read_count: 0,
            cp329_same_call_recirculation_enthalpy_bit_corroboration_count: 0,
            cp339_same_call_mixed_air_enthalpy_bit_corroboration_count: 0,
            mixed_air_enthalpy_read_count: 0,
            cp379_post_saturation_supply_enthalpy_owned_read_count: 0,
            cp379_same_call_supply_enthalpy_bits_corroboration_count: 0,
            supply_enthalpy_read_count: 0,
            enthalpy_difference_calculation_count: 0,
            cooling_total_output_calculation_count: 0,
            cooling_total_output_assignment_write_count: 0,
            latest: None,
            latest_route: None,
            latest_transition_ordinal: None,
        }
    }
}
