# Append GEO-02 targets without mutating any previous CLK/PSY/GEO target.
include("${CMAKE_CURRENT_LIST_DIR}/geo01_reference.cmake")
if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
  get_property(_geo02_scheduled GLOBAL PROPERTY GEO02_REFERENCE_SCHEDULED)
  if(NOT _geo02_scheduled)
    set_property(GLOBAL PROPERTY GEO02_REFERENCE_SCHEDULED TRUE)
    set_property(GLOBAL PROPERTY GEO02_REFERENCE_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}")
    function(geo02_add_original_reference)
      if(NOT TARGET energypluslib)
        message(FATAL_ERROR "GEO-02 requires the verified unchanged original core")
      endif()
      get_property(_geo02_dir GLOBAL PROPERTY GEO02_REFERENCE_DIRECTORY)
      get_target_property(_geo02_target_defs energypluslib COMPILE_DEFINITIONS)
      get_directory_property(_geo02_directory_defs DIRECTORY "${CMAKE_SOURCE_DIR}/src/EnergyPlus" COMPILE_DEFINITIONS)
      set(_geo02_defs ${_geo02_target_defs} ${_geo02_directory_defs})
      list(FILTER _geo02_defs EXCLUDE REGEX "-NOTFOUND$")
      list(REMOVE_DUPLICATES _geo02_defs)
      add_executable(geo02_reference "${_geo02_dir}/geo02_reference.cpp")
      target_include_directories(geo02_reference PRIVATE "$<TARGET_PROPERTY:energypluslib,INCLUDE_DIRECTORIES>")
      target_compile_definitions(geo02_reference PRIVATE ${_geo02_defs})
      target_link_libraries(geo02_reference PRIVATE project_options project_fp_options project_warnings objexx bcrypt)
      target_compile_features(geo02_reference PRIVATE cxx_std_20)
      if(NOT DEFINED GEO02_SETUP_FRAGMENT OR NOT EXISTS "${GEO02_SETUP_FRAGMENT}")
        message(FATAL_ERROR "GEO-02 requires the verified verbatim source273-289 fragment")
      endif()
      add_executable(geo02_reference_helper "${_geo02_dir}/geo02_reference_helper.cpp")
      target_compile_definitions(geo02_reference_helper PRIVATE ${_geo02_defs} GEO02_SETUP_FRAGMENT="${GEO02_SETUP_FRAGMENT}")
      target_link_libraries(geo02_reference_helper PRIVATE energypluslib project_options project_fp_options project_warnings)
      target_compile_features(geo02_reference_helper PRIVATE cxx_std_20)
    endfunction()
    cmake_language(DEFER CALL geo02_add_original_reference)
  endif()
endif()
