# Test-only original-core dispatcher; preserve the existing CLK-01 registration.
include("${CMAKE_CURRENT_LIST_DIR}/clk01_reference.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/psy02_reachability.cmake")
if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
  get_property(_psy02_scheduled GLOBAL PROPERTY PSY02_REFERENCE_SCHEDULED)
  if(NOT _psy02_scheduled)
    set_property(GLOBAL PROPERTY PSY02_REFERENCE_SCHEDULED TRUE)
    set_property(GLOBAL PROPERTY PSY02_REFERENCE_SOURCE "${CMAKE_CURRENT_LIST_DIR}/psy02_reference.cpp")
    function(psy02_add_original_reference)
      if(NOT TARGET energypluslib)
        message(FATAL_ERROR "PSY-02 requires the unchanged original energypluslib")
      endif()
      get_property(_psy02_source GLOBAL PROPERTY PSY02_REFERENCE_SOURCE)
      # Original src/EnergyPlus directory definitions are not interface flags.
      # In particular header EP_psych_errors/statistics must match the linked core.
      get_target_property(_psy02_definitions energypluslib COMPILE_DEFINITIONS)
      get_directory_property(_psy02_directory_definitions
        DIRECTORY "${CMAKE_SOURCE_DIR}/src/EnergyPlus" COMPILE_DEFINITIONS)
      list(APPEND _psy02_definitions ${_psy02_directory_definitions})
      list(FILTER _psy02_definitions EXCLUDE REGEX "-NOTFOUND$")
      list(REMOVE_DUPLICATES _psy02_definitions)
      # Separate replay output preserves the archived original-first unit binary.
      foreach(_psy02_target IN ITEMS psy02_reference psy02_reference_replay)
        add_executable(${_psy02_target} "${_psy02_source}")
        target_link_libraries(${_psy02_target} PRIVATE energypluslib project_options project_fp_options project_warnings)
        if(_psy02_definitions)
          target_compile_definitions(${_psy02_target} PRIVATE ${_psy02_definitions})
        endif()
        target_compile_features(${_psy02_target} PRIVATE cxx_std_20)
      endforeach()
    endfunction()
    cmake_language(DEFER CALL psy02_add_original_reference)
  endif()
endif()
