"""Observe the pinned native EnergyPlus clock without supplying Rust operands.

The selected callback follows WeatherManager and precedes heat-balance/reporting.
Raw after-report clocks remain separate: API currentTime can reflect shortened
system steps, and CalendarYear can advance at year-end reporting. No Gregorian
oracle or expected clock values are generated by this observer.
"""

from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time
import traceback

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[2]
PLAN = ROOT / "energyplus_porting_plan"
EP_ROOT = ROOT / ".runtime/energyplus/26.1.0"
DLL_SHA256 = "bbe6f66240d108df9f51a03b9beb968808a2173234253574d27a31605aec2aa2"
PHASES = {
    "before_init_heat_balance": "callback_begin_zone_timestep_before_init_heat_balance",
    "after_zone_reporting": "callback_end_zone_timestep_after_zone_reporting",
    "warmup_complete": "callback_after_new_environment_warmup_complete",
}


def read(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def write(path: Path, value) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, allow_nan=False) + "\n",
                    encoding="utf-8", newline="\n")


def sha(path: Path) -> str:
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def ref(path: Path) -> dict:
    return {"path": path.resolve().relative_to(ROOT).as_posix(), "sha256": sha(path)}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def observe_case(case: dict, raw_root: Path, executed_source: Path, contracts: list[dict]) -> dict:
    directory = raw_root / case["id"]
    require(not directory.exists(), f"Fresh raw directory required: {directory}")
    for binding in (case["input"], case["weather"]):
        require(sha(ROOT / binding["path"]) == binding["sha256"], "Pinned input/weather changed")
    directory.mkdir(parents=True)
    sys.path.insert(0, str(EP_ROOT))
    dll_directory = os.add_dll_directory(str(EP_ROOT)) if os.name == "nt" else None
    from pyenergyplus.api import EnergyPlusAPI
    api = EnergyPlusAPI()
    state = api.state_manager.new_state()
    api.verify_api_version_match(state)
    exchange = api.exchange
    counts = Counter()
    rows, errors, phases, owners = [], [], [], []
    log_path = directory / "clock-callbacks.jsonl"
    log = log_path.open("w", encoding="utf-8", newline="\n")
    messages = (directory / "api-messages.log").open("wb")

    def frame(s) -> dict:
        return {
            "weather_record_year": exchange.year(s),
            "calendar_year": exchange.calendar_year(s),
            "month": exchange.month(s), "day_of_month": exchange.day_of_month(s),
            "day_of_week": exchange.day_of_week(s), "weather_day_of_year": exchange.day_of_year(s),
            "dst": exchange.daylight_savings_time_indicator(s),
            "raw_c_api_dst_indicator": exchange.api.daylightSavingsTimeIndicator(s),
            "holiday_index": exchange.holiday_index(s),
            "raw_c_api_holiday_index": exchange.api.holidayIndex(s),
            "hour_zero_based": exchange.hour(s),
            "zone_timestep": exchange.zone_time_step_number(s),
            "timesteps_per_hour": exchange.num_time_steps_in_hour(s),
            "zone_timestep_hours": exchange.zone_time_step(s),
            "system_timestep_hours": exchange.system_time_step(s),
            "raw_api_current_time_hours": exchange.current_time(s),
            "raw_api_minutes": exchange.minutes(s),
            "native_environment_number": exchange.current_environment_num(s),
            "kind_of_sim": exchange.kind_of_sim(s), "warmup": exchange.warmup_flag(s),
        }

    def callback_for(phase):
        def callback(s):
            try:
                observation = frame(s)
                counts[("warmup" if observation["warmup"] else "reporting") + ":" + phase] += 1
                if phase == "warmup_complete":
                    log.write(json.dumps({"phase": phase, **observation}, separators=(",", ":")) + "\n")
                    return
                if observation["warmup"]:
                    return
                rows.append({"sequence": len(rows) + 1, "phase": phase, **observation})
                phases.append(phase)
                log.write(json.dumps(rows[-1], separators=(",", ":"), allow_nan=False) + "\n")
            except Exception:
                errors.append(traceback.format_exc())
        return callback

    for phase, method in PHASES.items():
        callback = callback_for(phase)
        owners.append(callback)
        getattr(api.runtime, method)(state, callback)

    def message_callback(message):
        messages.write(message + b"\n")

    owners.append(message_callback)
    api.runtime.callback_message(state, message_callback)
    api.runtime.set_console_output_status(state, False)
    command = ["-w", str(ROOT / case["weather"]["path"]), "-d", str(directory),
               str(ROOT / case["input"]["path"])]
    started = time.perf_counter()
    try:
        exit_code = api.runtime.run_energyplus(state, command)
    except Exception:
        exit_code = -1
        errors.append(traceback.format_exc())
    finally:
        log.close()
        messages.close()
        api.state_manager.delete_state(state)
        if dll_directory is not None:
            dll_directory.close()
    before = [row for row in rows if row["phase"] == "before_init_heat_balance"]
    after = [row for row in rows if row["phase"] == "after_zone_reporting"]
    expected_count = case["expected_zone_steps_excluding_warmup"]
    if exit_code:
        errors.append(f"Native EnergyPlus exit code {exit_code}")
    if len(before) != expected_count or len(after) != expected_count:
        errors.append(f"Expected {expected_count} pre/report pairs; observed {len(before)}/{len(after)}")
    if phases != [phase for _ in range(expected_count)
                  for phase in ("before_init_heat_balance", "after_zone_reporting")]:
        errors.append("Selected callback order is incomplete or interleaved")
    if len({row["native_environment_number"] for row in before}) != 1:
        errors.append("Native rows do not identify one weather environment")
    if any(row["kind_of_sim"] != 3 for row in before):
        errors.append("Native observation escaped RunPeriodWeather kind=3")
    if counts["reporting:warmup_complete"] != 1:
        errors.append("Selected weather environment did not complete exactly one native warmup")
    err_path = directory / "eplusout.err"
    if err_path.exists():
        errors.extend(line for line in err_path.read_text(encoding="utf-8", errors="replace").splitlines()
                      if "** Severe" in line or "**  Fatal" in line)
    else:
        errors.append("Native error file missing")
    receipt = {
        "schema": "clk01-native-clock-observation.v1", "case_id": case["id"],
        "scope": case["scope"], "duration": case["duration"],
        "native_library": ref(EP_ROOT / "energyplusapi.dll"),
        "command": command, "exit_code": exit_code,
        "elapsed_seconds": round(time.perf_counter() - started, 3),
        "execution_repository_head": subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip(),
        "observer_source": ref(executed_source), "frozen_contracts": contracts,
        "python_api_sources": [ref(EP_ROOT / "pyenergyplus" / name)
                               for name in ["api.py", "datatransfer.py", "runtime.py", "state.py"]],
        "input": case["input"], "weather": case["weather"],
        "raw_callbacks": ref(log_path), "api_messages": ref(directory / "api-messages.log"),
        "native_outputs": [ref(directory / name) for name in
                           ["eplusout.eso", "eplusout.eio"] if (directory / name).is_file()],
        "native_error_file": ref(err_path) if err_path.exists() else None,
        "callback_counts": dict(counts), "before_report_count": len(before),
        "after_report_count": len(after), "paired_callback_order_valid": not errors,
        "observed_current_dates": len({(row["calendar_year"], row["month"], row["day_of_month"])
                                       for row in before}),
        "first_before_report": before[0] if before else None,
        "last_before_report": before[-1] if before else None,
        "last_after_report": after[-1] if after else None,
        "errors": errors, "observation_checks_passed": not errors,
        "calendar_comparison_status": "not_run",
        "rust_physics_comparison_status": "not_run",
        "automatic_gate_updates": False,
        "boundary": "Raw native C API only. No Python date arithmetic, private-state ABI access, Rust invocation, numerical injection, or completion claim.",
    }
    write(directory / "receipt.json", receipt)
    print(json.dumps({"case": case["id"], "before_report_rows": len(before),
                      "exit_code": exit_code, "errors": errors}), flush=True)
    return receipt


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case", action="append", required=True)
    parser.add_argument("--raw-root", type=Path, required=True)
    args = parser.parse_args()
    scope = read(PLAN / "contracts/scope.json")
    cases = {}
    for binding in scope["cases"]:
        metadata = ROOT / binding["metadata"]["path"]
        require(sha(metadata) == binding["metadata"]["sha256"], "Case metadata pin changed")
        case = read(metadata)
        require(all(case[key] == binding[key] for key in
                    ["id", "scope", "duration", "limit_variant", "input", "weather"]),
                "Case metadata differs from frozen scope binding")
        cases[case["id"]] = case
    require(len(args.case) == len(set(args.case)) and all(name in cases for name in args.case),
            "Case IDs must be unique fixed CON-01 cases")
    require(sha(EP_ROOT / "energyplusapi.dll") == DLL_SHA256, "Native EnergyPlus DLL pin changed")
    contracts = [ref(PLAN / "contracts" / name) for name in
                 ["CLK-01-source.json", "CLK-01-cases.json", "CLK-01-tolerances.json"]]
    raw_root = args.raw_root.resolve()
    require(raw_root.is_relative_to((ROOT / ".runtime/porting/CLK-01").resolve()),
            "Raw evidence must stay within .runtime/porting/CLK-01")
    source = raw_root / "source/trace_clk01_native.py"
    require(not source.exists(), "Fresh executed source archive required")
    source.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(Path(__file__), source)
    failed = False
    for name in args.case:
        receipt = observe_case(cases[name], raw_root, source, contracts)
        failed |= not receipt["observation_checks_passed"]
    return int(failed)


if __name__ == "__main__":
    raise SystemExit(main())
