[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$ScriptsRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
. (Join-Path $ScriptsRoot "lib\common.ps1")

$RepoRoot = Get-RepoRoot
Set-Location $RepoRoot

function Read-RepoText {
    param([Parameter(Mandatory = $true)][string]$Path)
    return Get-Content -Encoding UTF8 -Raw -LiteralPath $Path
}

function Assert-FileExists {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Description
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "$Description missing: $Path"
    }
}

function Assert-Contains {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Pattern,
        [Parameter(Mandatory = $true)][string]$Description
    )

    $text = Read-RepoText -Path $Path
    if ($text -notmatch $Pattern) {
        throw "$Description missing in $Path"
    }
}

function Assert-NotContains {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Pattern,
        [Parameter(Mandatory = $true)][string]$Description
    )

    $text = Read-RepoText -Path $Path
    if ($text -match $Pattern) {
        throw "$Description unexpectedly present in $Path"
    }
}

function Assert-LineLimit {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][int]$Limit,
        [Parameter(Mandatory = $true)][string]$Description
    )

    $lineCount = (Get-Content -Encoding UTF8 -LiteralPath $Path | Measure-Object -Line).Lines
    if ($lineCount -gt $Limit) {
        throw "$Description exceeds $Limit LOC: $Path has $lineCount LOC"
    }
}

$calcRoot = "crates\ep_runtime\src\ideal_loads\calc.rs"
$calcHumidity = "crates\ep_runtime\src\ideal_loads\calc\humidity.rs"
$calcLimits = "crates\ep_runtime\src\ideal_loads\calc\limits.rs"
$calcMassFlow = "crates\ep_runtime\src\ideal_loads\calc\mass_flow.rs"
$calcMoistureDemand = "crates\ep_runtime\src\ideal_loads\calc\moisture_demand.rs"
$calcMoistureDemandTests = "crates\ep_runtime\src\ideal_loads\calc\moisture_demand_tests.rs"
$noOaCalc = "crates\ep_runtime\src\ideal_loads\calc\no_oa.rs"
$calcPsychrometrics = "crates\ep_runtime\src\ideal_loads\calc\psychrometrics.rs"
$calcTypes = "crates\ep_runtime\src\ideal_loads\calc\types.rs"
$noOaTests = "crates\ep_runtime\src\ideal_loads\calc\no_oa_tests.rs"
$idealLoadsMod = "crates\ep_runtime\src\ideal_loads\mod.rs"
$idealLoadsHumidistat = "crates\ep_runtime\src\ideal_loads\humidistat.rs"
$idealLoadsHumidistatTests = "crates\ep_runtime\src\ideal_loads\humidistat_tests.rs"
$idealLoadsInit = "crates\ep_runtime\src\ideal_loads\init.rs"
$idealLoadsInput = "crates\ep_runtime\src\ideal_loads\input.rs"
$idealLoadsMeters = "crates\ep_runtime\src\ideal_loads\meters.rs"
$idealLoadsReport = "crates\ep_runtime\src\ideal_loads\report.rs"
$idealLoadsReportSemantics = "crates\ep_runtime\src\ideal_loads\report\semantics.rs"
$idealLoadsRuntime = "crates\ep_runtime\src\ideal_loads\runtime.rs"
$idealLoadsUpdate = "crates\ep_runtime\src\ideal_loads\update.rs"
$outdoorAir = "crates\ep_runtime\src\ideal_loads\outdoor_air.rs"
$outdoorAirTests = "crates\ep_runtime\src\ideal_loads\outdoor_air_tests.rs"
$outdoorAirDcvTests = "crates\ep_runtime\src\ideal_loads\outdoor_air_dcv_tests.rs"
$outdoorAirDesignFlow = "crates\ep_runtime\src\ideal_loads\outdoor_air\design_flow.rs"
$outdoorAirDcv = "crates\ep_runtime\src\ideal_loads\outdoor_air\dcv.rs"
$outdoorAirEconomizer = "crates\ep_runtime\src\ideal_loads\outdoor_air\economizer.rs"
$outdoorAirMixedAir = "crates\ep_runtime\src\ideal_loads\outdoor_air\mixed_air.rs"
$outdoorAirPsychrometrics = "crates\ep_runtime\src\ideal_loads\outdoor_air\psychrometrics.rs"
$outdoorAirSupply = "crates\ep_runtime\src\ideal_loads\outdoor_air\supply.rs"
$dispatch = "crates\ep_runtime\src\ideal_loads\dispatch.rs"
$idealLoadsCli = "crates\ep_cli\src\ideal_loads.rs"
$idealLoadsCliCaseAdapter = "crates\ep_cli\src\ideal_loads\case_adapter\mod.rs"
$idealLoadsCliTimeAxisAdapter = "crates\ep_cli\src\ideal_loads\case_adapter\time_axis.rs"
$idealLoadsCliTimeAxisAdapterTests = "crates\ep_cli\src\ideal_loads\case_adapter\time_axis_tests.rs"
$idealLoadsCliCommands = "crates\ep_cli\src\ideal_loads\commands\mod.rs"
$idealLoadsCliReports = "crates\ep_cli\src\ideal_loads\reports\mod.rs"
$idealLoadsCliOutdoorAirReports = "crates\ep_cli\src\ideal_loads\reports\outdoor_air\mod.rs"
$idealLoadsCliOutdoorAirMarkdown = "crates\ep_cli\src\ideal_loads\reports\outdoor_air\markdown.rs"
$idealLoadsCliOutdoorAirJson = "crates\ep_cli\src\ideal_loads\reports\outdoor_air\json.rs"
$idealLoadsCliOutdoorAirCsv = "crates\ep_cli\src\ideal_loads\reports\outdoor_air\csv.rs"
$outdoorAirSumCompare = "scripts\compare\compare-ideal-loads-outdoor-air-sum-conformance-candidate.ps1"
$outdoorAirMaximumCompare = "scripts\compare\compare-ideal-loads-outdoor-air-maximum-conformance-candidate.ps1"
$conformanceManifest = "crates\ep_conformance\src\conformance.rs"
$runtime = "crates\ep_runtime\src\runtime.rs"
$executionPlan = "crates\ep_runtime\src\execution_plan.rs"
$runSupport = "crates\ep_run\src\support.rs"
$runPipeline = "crates\ep_run\src\pipeline.rs"
$runRuntimeBoundaries = "crates\ep_run\src\support\runtime_boundaries.rs"
$runtimeOutputTests = "crates\ep_runtime\src\runtime\tests\part08.rs"
$lib = "crates\ep_runtime\src\lib.rs"
$output = "crates\ep_runtime\src\output.rs"
$resultStore = "crates\ep_runtime\src\output\result_store.rs"
$node = "crates\ep_runtime\src\node\mod.rs"
$nodeProjection = "crates\ep_runtime\src\node\projection.rs"
$nodeState = "crates\ep_runtime\src\node\state.rs"
$plant = "crates\ep_runtime\src\plant\mod.rs"
$plantState = "crates\ep_runtime\src\plant\state.rs"
$zoneEquipment = "crates\ep_runtime\src\zone_equipment\mod.rs"
$zoneEquipmentDemand = "crates\ep_runtime\src\zone_equipment\demand.rs"
$zoneEquipmentDispatch = "crates\ep_runtime\src\zone_equipment\dispatch.rs"
$zoneEquipmentTests = "crates\ep_runtime\src\zone_equipment\tests.rs"

Assert-FileExists -Path $calcRoot -Description "IdealLoads calc module root"
Assert-FileExists -Path $calcHumidity -Description "IdealLoads calc humidity module"
Assert-FileExists -Path $calcLimits -Description "IdealLoads calc limits module"
Assert-FileExists -Path $calcMassFlow -Description "IdealLoads calc mass-flow module"
Assert-FileExists -Path $calcMoistureDemand -Description "IdealLoads ThirdOrder moisture-demand module"
Assert-FileExists -Path $calcMoistureDemandTests -Description "IdealLoads ThirdOrder moisture-demand tests"
Assert-FileExists -Path $noOaCalc -Description "IdealLoads no-OA calc module"
Assert-FileExists -Path $calcPsychrometrics -Description "IdealLoads calc psychrometrics module"
Assert-FileExists -Path $calcTypes -Description "IdealLoads calc shared types module"
Assert-FileExists -Path $noOaTests -Description "IdealLoads no-OA calc tests"
Assert-FileExists -Path $idealLoadsMod -Description "IdealLoads module root"
Assert-FileExists -Path $idealLoadsHumidistat -Description "IdealLoads Humidistat closed-loop transition module"
Assert-FileExists -Path $idealLoadsHumidistatTests -Description "IdealLoads Humidistat closed-loop transition tests"
Assert-FileExists -Path $idealLoadsInit -Description "IdealLoads initialization module"
Assert-FileExists -Path $idealLoadsInput -Description "IdealLoads input boundary module"
Assert-FileExists -Path $idealLoadsMeters -Description "IdealLoads meter binding module"
Assert-FileExists -Path $idealLoadsReport -Description "IdealLoads report module"
Assert-FileExists -Path $idealLoadsReportSemantics -Description "IdealLoads report semantics module"
Assert-FileExists -Path $idealLoadsRuntime -Description "IdealLoads compatibility runtime"
Assert-FileExists -Path $idealLoadsUpdate -Description "IdealLoads node-update module"
Assert-FileExists -Path $outdoorAir -Description "IdealLoads outdoor-air module"
Assert-FileExists -Path $outdoorAirTests -Description "IdealLoads outdoor-air tests module"
Assert-FileExists -Path $outdoorAirDcvTests -Description "IdealLoads outdoor-air DCV tests module"
Assert-FileExists -Path $outdoorAirDesignFlow -Description "IdealLoads outdoor-air design-flow module"
Assert-FileExists -Path $outdoorAirDcv -Description "IdealLoads outdoor-air DCV module"
Assert-FileExists -Path $outdoorAirEconomizer -Description "IdealLoads outdoor-air economizer module"
Assert-FileExists -Path $outdoorAirMixedAir -Description "IdealLoads outdoor-air mixed-air module"
Assert-FileExists -Path $outdoorAirPsychrometrics -Description "IdealLoads outdoor-air psychrometrics module"
Assert-FileExists -Path $outdoorAirSupply -Description "IdealLoads outdoor-air supply module"
Assert-FileExists -Path $dispatch -Description "IdealLoads source-order dispatch module"
Assert-FileExists -Path $idealLoadsCli -Description "IdealLoads CLI report generator"
Assert-FileExists -Path $idealLoadsCliCaseAdapter -Description "IdealLoads CLI case-adapter module"
Assert-FileExists -Path $idealLoadsCliTimeAxisAdapter -Description "IdealLoads CLI time-axis adapter"
Assert-FileExists -Path $idealLoadsCliTimeAxisAdapterTests -Description "IdealLoads CLI time-axis adapter tests"
Assert-FileExists -Path $idealLoadsCliCommands -Description "IdealLoads CLI command entry points"
Assert-FileExists -Path $idealLoadsCliReports -Description "IdealLoads CLI report modules"
Assert-FileExists -Path $idealLoadsCliOutdoorAirReports -Description "IdealLoads CLI outdoor-air artifact writer"
Assert-FileExists -Path $idealLoadsCliOutdoorAirMarkdown -Description "IdealLoads CLI outdoor-air Markdown renderer"
Assert-FileExists -Path $idealLoadsCliOutdoorAirJson -Description "IdealLoads CLI outdoor-air JSON renderers"
Assert-FileExists -Path $idealLoadsCliOutdoorAirCsv -Description "IdealLoads CLI outdoor-air CSV renderers"
Assert-FileExists -Path $outdoorAirSumCompare -Description "IdealLoads outdoor-air Sum comparison script"
Assert-FileExists -Path $outdoorAirMaximumCompare -Description "IdealLoads outdoor-air Maximum comparison script"
Assert-FileExists -Path $conformanceManifest -Description "Conformance manifest schema"
Assert-FileExists -Path $runtime -Description "Runtime root"
Assert-FileExists -Path $executionPlan -Description "Runtime execution plan"
Assert-FileExists -Path $runSupport -Description "ep_run support assessment"
Assert-FileExists -Path $runPipeline -Description "ep_run pipeline"
Assert-FileExists -Path $runRuntimeBoundaries -Description "ep_run runtime boundary assessment"
Assert-FileExists -Path $runtimeOutputTests -Description "Runtime output registry tests"
Assert-FileExists -Path $lib -Description "Runtime crate facade"
Assert-FileExists -Path $output -Description "Runtime output registry"
Assert-FileExists -Path $resultStore -Description "Runtime result store"
Assert-FileExists -Path $node -Description "Node compatibility facade"
Assert-FileExists -Path $nodeProjection -Description "Node projection module"
Assert-FileExists -Path $nodeState -Description "Node state module"
Assert-FileExists -Path $plant -Description "Plant compatibility facade"
Assert-FileExists -Path $plantState -Description "Plant state module"
Assert-FileExists -Path $zoneEquipment -Description "Zone equipment compatibility facade"
Assert-FileExists -Path $zoneEquipmentDemand -Description "Zone equipment demand module"
Assert-FileExists -Path $zoneEquipmentDispatch -Description "Zone equipment dispatch module"
Assert-FileExists -Path $zoneEquipmentTests -Description "Zone equipment tests module"

Assert-LineLimit -Path $calcRoot -Limit 80 -Description "IdealLoads calc module root"
Assert-LineLimit -Path $calcHumidity -Limit 220 -Description "IdealLoads calc humidity module"
Assert-LineLimit -Path $calcLimits -Limit 180 -Description "IdealLoads calc limits module"
Assert-LineLimit -Path $calcMassFlow -Limit 150 -Description "IdealLoads calc mass-flow module"
Assert-LineLimit -Path $calcMoistureDemand -Limit 280 -Description "IdealLoads ThirdOrder moisture-demand module"
Assert-LineLimit -Path $calcMoistureDemandTests -Limit 240 -Description "IdealLoads ThirdOrder moisture-demand tests"
Assert-LineLimit -Path $noOaCalc -Limit 700 -Description "IdealLoads no-OA calc module"
Assert-LineLimit -Path $calcPsychrometrics -Limit 120 -Description "IdealLoads calc psychrometrics module"
Assert-LineLimit -Path $calcTypes -Limit 140 -Description "IdealLoads calc shared types module"
Assert-LineLimit -Path $noOaTests -Limit 650 -Description "IdealLoads no-OA calc tests"
Assert-LineLimit -Path $idealLoadsHumidistat -Limit 300 -Description "IdealLoads Humidistat closed-loop transition module"
Assert-LineLimit -Path $idealLoadsHumidistatTests -Limit 500 -Description "IdealLoads Humidistat closed-loop transition tests"
Assert-LineLimit -Path $idealLoadsInit -Limit 120 -Description "IdealLoads initialization module"
Assert-LineLimit -Path $idealLoadsInput -Limit 260 -Description "IdealLoads input boundary module"
Assert-LineLimit -Path $idealLoadsMeters -Limit 120 -Description "IdealLoads meter binding module"
Assert-LineLimit -Path $idealLoadsReportSemantics -Limit 80 -Description "IdealLoads report semantics module"
Assert-LineLimit -Path $idealLoadsUpdate -Limit 120 -Description "IdealLoads node-update module"
Assert-LineLimit -Path $outdoorAir -Limit 450 -Description "IdealLoads outdoor-air module"
Assert-LineLimit -Path $outdoorAirTests -Limit 450 -Description "IdealLoads outdoor-air tests module"
Assert-LineLimit -Path $outdoorAirDcvTests -Limit 240 -Description "IdealLoads outdoor-air DCV tests module"
Assert-LineLimit -Path $outdoorAirDesignFlow -Limit 220 -Description "IdealLoads outdoor-air design-flow module"
Assert-LineLimit -Path $outdoorAirDcv -Limit 120 -Description "IdealLoads outdoor-air DCV module"
Assert-LineLimit -Path $outdoorAirEconomizer -Limit 150 -Description "IdealLoads outdoor-air economizer module"
Assert-LineLimit -Path $outdoorAirMixedAir -Limit 260 -Description "IdealLoads outdoor-air mixed-air module"
Assert-LineLimit -Path $outdoorAirPsychrometrics -Limit 160 -Description "IdealLoads outdoor-air psychrometrics module"
Assert-LineLimit -Path $outdoorAirSupply -Limit 150 -Description "IdealLoads outdoor-air supply module"
Assert-LineLimit -Path $idealLoadsCliCaseAdapter -Limit 40 -Description "IdealLoads CLI case-adapter module"
Assert-LineLimit -Path $idealLoadsCliTimeAxisAdapter -Limit 160 -Description "IdealLoads CLI time-axis adapter"
Assert-LineLimit -Path $idealLoadsCliTimeAxisAdapterTests -Limit 160 -Description "IdealLoads CLI time-axis adapter tests"
Assert-LineLimit -Path $idealLoadsCliCommands -Limit 180 -Description "IdealLoads CLI command entry points"
Assert-LineLimit -Path $idealLoadsCliReports -Limit 40 -Description "IdealLoads CLI report module root"
Assert-LineLimit -Path $idealLoadsCliOutdoorAirReports -Limit 120 -Description "IdealLoads CLI outdoor-air artifact writer"
Assert-LineLimit -Path $idealLoadsCliOutdoorAirMarkdown -Limit 450 -Description "IdealLoads CLI outdoor-air Markdown renderer"
Assert-LineLimit -Path $idealLoadsCliOutdoorAirJson -Limit 1000 -Description "IdealLoads CLI outdoor-air JSON renderers"
Assert-LineLimit -Path $idealLoadsCliOutdoorAirCsv -Limit 120 -Description "IdealLoads CLI outdoor-air CSV renderers"
Assert-LineLimit -Path $nodeProjection -Limit 500 -Description "Node projection module"
Assert-LineLimit -Path $nodeState -Limit 220 -Description "Node state module"
Assert-LineLimit -Path $plantState -Limit 900 -Description "Plant state module"
Assert-LineLimit -Path $zoneEquipment -Limit 80 -Description "Zone equipment compatibility facade"
Assert-LineLimit -Path $zoneEquipmentDemand -Limit 120 -Description "Zone equipment demand module"
Assert-LineLimit -Path $zoneEquipmentDispatch -Limit 360 -Description "Zone equipment dispatch module"
Assert-LineLimit -Path $zoneEquipmentTests -Limit 320 -Description "Zone equipment tests module"
Assert-LineLimit -Path $resultStore -Limit 220 -Description "Runtime result store"

Assert-Contains -Path $calcRoot -Pattern 'mod humidity;' -Description "IdealLoads calc humidity submodule declaration"
Assert-Contains -Path $calcRoot -Pattern 'mod limits;' -Description "IdealLoads calc limits submodule declaration"
Assert-Contains -Path $calcRoot -Pattern 'mod mass_flow;' -Description "IdealLoads calc mass-flow submodule declaration"
Assert-Contains -Path $calcRoot -Pattern 'mod no_oa;' -Description "no-OA calc submodule declaration"
Assert-Contains -Path $calcRoot -Pattern 'mod psychrometrics;' -Description "IdealLoads calc psychrometrics submodule declaration"
Assert-Contains -Path $calcRoot -Pattern 'mod types;' -Description "IdealLoads calc shared types submodule declaration"
Assert-Contains -Path $calcRoot -Pattern 'pub use limits::IdealLoadsSensibleLimitContext;' -Description "IdealLoads calc limits public re-export"
Assert-Contains -Path $calcRoot -Pattern 'pub use no_oa::\*;' -Description "no-OA calc public re-export"
Assert-Contains -Path $calcRoot -Pattern 'pub use psychrometrics::' -Description "IdealLoads calc psychrometrics public re-export"
Assert-Contains -Path $calcRoot -Pattern 'pub use types::\*;' -Description "IdealLoads calc shared types public re-export"
Assert-Contains -Path $calcRoot -Pattern 'mod no_oa_tests;' -Description "no-OA calc test module declaration"
Assert-NotContains -Path $calcRoot -Pattern 'calc_no_oa_no_limit_sensible_compat\s*\(' -Description "branch formula in calc module root"
Assert-NotContains -Path $calcRoot -Pattern 'fn heating_result_with_limits\s*\(' -Description "heating branch helper in calc module root"
Assert-NotContains -Path $calcRoot -Pattern 'fn cooling_result_with_limits\s*\(' -Description "cooling branch helper in calc module root"

Assert-Contains -Path $idealLoadsMod -Pattern 'mod init;' -Description "IdealLoads init submodule declaration"
Assert-Contains -Path $idealLoadsMod -Pattern 'mod update;' -Description "IdealLoads update submodule declaration"
Assert-Contains -Path $idealLoadsMod -Pattern 'pub use init::\*;' -Description "IdealLoads init public re-export"
Assert-Contains -Path $idealLoadsMod -Pattern 'pub use update::\*;' -Description "IdealLoads update public re-export"

Assert-Contains -Path $noOaCalc -Pattern 'pub fn calc_no_oa_no_limit_sensible_compat\s*\(' -Description "no-OA/no-limit sensible calc"
Assert-Contains -Path $noOaCalc -Pattern 'pub fn calc_no_oa_sensible_with_limits_compat\s*\(' -Description "finite-limit sensible calc"
Assert-Contains -Path $noOaCalc -Pattern 'fn heating_result_with_limits\s*\(' -Description "heating branch helper"
Assert-Contains -Path $noOaCalc -Pattern 'fn cooling_result_with_limits\s*\(' -Description "cooling branch helper"
Assert-Contains -Path $calcHumidity -Pattern 'fn humidistat_dehumidification_mass_flow_rate_kg_per_s\s*\(' -Description "dehumidification diagnostic branch helper"
Assert-Contains -Path $calcHumidity -Pattern 'fn humidistat_humidification_mass_flow_rate_kg_per_s\s*\(' -Description "humidification diagnostic branch helper"
Assert-Contains -Path $calcHumidity -Pattern 'fn heating_supply_humidity_ratio\s*\(' -Description "heating supply humidity helper"
Assert-Contains -Path $calcHumidity -Pattern 'fn cooling_supply_humidity_ratio\s*\(' -Description "cooling supply humidity helper"
Assert-Contains -Path $calcLimits -Pattern 'pub struct IdealLoadsSensibleLimitContext' -Description "IdealLoads sensible limit context"
Assert-Contains -Path $calcLimits -Pattern 'fn flow_limit_kg_per_s\s*\(' -Description "IdealLoads flow limit helper"
Assert-Contains -Path $calcLimits -Pattern 'fn capacity_limit_w\s*\(' -Description "IdealLoads capacity limit helper"
Assert-Contains -Path $calcMassFlow -Pattern 'fn limited_heating_mass_flow_rate_kg_per_s\s*\(' -Description "IdealLoads limited heating mass-flow helper"
Assert-Contains -Path $calcMassFlow -Pattern 'fn limited_cooling_mass_flow_rate_kg_per_s\s*\(' -Description "IdealLoads limited cooling mass-flow helper"
Assert-Contains -Path $calcPsychrometrics -Pattern 'pub fn moist_air_enthalpy_j_per_kg\s*\(' -Description "IdealLoads moist-air enthalpy helper"
Assert-Contains -Path $calcPsychrometrics -Pattern 'pub fn energyplus_standard_air_density_kg_per_m3\s*\(' -Description "IdealLoads standard air density helper"
Assert-Contains -Path $calcPsychrometrics -Pattern 'fn humidity_ratio_from_enthalpy_and_dry_bulb\s*\(' -Description "IdealLoads humidity-from-enthalpy helper"
Assert-Contains -Path $calcTypes -Pattern 'pub enum IdealLoadsSensibleMode' -Description "IdealLoads sensible mode type"
Assert-Contains -Path $calcTypes -Pattern 'pub struct IdealLoadsZoneState' -Description "IdealLoads zone state type"
Assert-Contains -Path $calcTypes -Pattern 'pub struct IdealLoadsSensibleResult' -Description "IdealLoads sensible result type"
Assert-NotContains -Path $noOaCalc -Pattern '#\[test\]' -Description "unit tests in no-OA implementation module"
Assert-NotContains -Path $noOaCalc -Pattern 'pub fn moist_air_enthalpy_j_per_kg\s*\(' -Description "moist-air enthalpy helper in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'pub fn energyplus_standard_air_density_kg_per_m3\s*\(' -Description "standard air density helper in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'fn humidity_ratio_from_enthalpy_and_dry_bulb\s*\(' -Description "humidity-from-enthalpy helper in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'pub struct IdealLoadsSensibleLimitContext' -Description "limit context in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'pub enum IdealLoadsSensibleMode' -Description "sensible mode type in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'pub struct IdealLoadsZoneState' -Description "zone state type in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'pub struct IdealLoadsSensibleResult' -Description "sensible result type in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'fn humidistat_dehumidification_mass_flow_rate_kg_per_s\s*\(' -Description "dehumidification diagnostic helper in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'fn humidistat_humidification_mass_flow_rate_kg_per_s\s*\(' -Description "humidification diagnostic helper in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'fn heating_supply_humidity_ratio\s*\(' -Description "heating supply humidity helper in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'fn cooling_supply_humidity_ratio\s*\(' -Description "cooling supply humidity helper in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'fn limited_heating_mass_flow_rate_kg_per_s\s*\(' -Description "limited heating mass-flow helper in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'fn limited_cooling_mass_flow_rate_kg_per_s\s*\(' -Description "limited cooling mass-flow helper in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'fn flow_limit_kg_per_s\s*\(' -Description "flow limit helper in no-OA calc module"
Assert-NotContains -Path $noOaCalc -Pattern 'fn capacity_limit_w\s*\(' -Description "capacity limit helper in no-OA calc module"
Assert-Contains -Path $noOaTests -Pattern '#\[test\]' -Description "unit tests in no-OA test module"

Assert-Contains -Path $idealLoadsInit -Pattern 'pub struct IdealLoadsInitFlags' -Description "IdealLoads init flags type"
Assert-Contains -Path $idealLoadsInit -Pattern 'pub const fn source_order_candidate\s*\(' -Description "IdealLoads source-order init flags"
Assert-Contains -Path $idealLoadsUpdate -Pattern 'pub const fn supply_node_update_from_result\s*\(' -Description "IdealLoads supply-node update helper"

Assert-Contains -Path $idealLoadsInput -Pattern 'pub struct IdealLoadsFeatureFlags' -Description "IdealLoads compile feature flags"
Assert-Contains -Path $idealLoadsInput -Pattern 'pub fn from_system\s*\(' -Description "IdealLoads feature flag builder"
Assert-Contains -Path $idealLoadsInput -Pattern 'has_outdoor_air' -Description "IdealLoads outdoor-air feature flag"
Assert-Contains -Path $idealLoadsInput -Pattern 'has_economizer' -Description "IdealLoads economizer feature flag"
Assert-Contains -Path $idealLoadsInput -Pattern 'has_heat_recovery' -Description "IdealLoads heat-recovery feature flag"
Assert-Contains -Path $idealLoadsInput -Pattern 'has_dcv' -Description "IdealLoads DCV feature flag"
Assert-Contains -Path $idealLoadsInput -Pattern 'has_humidistat' -Description "IdealLoads humidistat feature flag"
Assert-Contains -Path $idealLoadsInput -Pattern 'has_constant_supply_humidity' -Description "IdealLoads constant supply humidity feature flag"
Assert-Contains -Path $idealLoadsInput -Pattern 'has_flow_limit' -Description "IdealLoads flow-limit feature flag"
Assert-Contains -Path $idealLoadsInput -Pattern 'has_capacity_limit' -Description "IdealLoads capacity-limit feature flag"
Assert-Contains -Path $idealLoadsInput -Pattern 'has_autosize' -Description "IdealLoads autosize feature flag"
Assert-Contains -Path $conformanceManifest -Pattern 'pub trace: Option<TraceContract>' -Description "case-level trace contract"
Assert-Contains -Path $conformanceManifest -Pattern 'pub struct TraceContract' -Description "trace contract schema type"
Assert-Contains -Path $conformanceManifest -Pattern 'require_non_empty\("trace\.level"' -Description "trace level validation"

Assert-Contains -Path $idealLoadsMod -Pattern 'mod meters;' -Description "IdealLoads meter submodule declaration"
Assert-Contains -Path $idealLoadsMod -Pattern 'pub use meters::\*;' -Description "IdealLoads meter public re-export"
Assert-Contains -Path $idealLoadsMeters -Pattern 'pub struct IdealLoadsFacilityMeterBinding' -Description "IdealLoads facility-meter binding type"
Assert-Contains -Path $idealLoadsMeters -Pattern 'pub const IDEAL_LOADS_METER_AGGREGATION_SOURCE' -Description "IdealLoads meter aggregation source label"
Assert-Contains -Path $idealLoadsMeters -Pattern 'pub fn ideal_loads_facility_meter_binding\s*\(' -Description "IdealLoads facility-meter binding helper"
Assert-Contains -Path $resultStore -Pattern 'pub struct ResultStore' -Description "runtime result store"
Assert-Contains -Path $resultStore -Pattern 'pub fn diagnostics\s*\(&self\)\s*->\s*RuntimeDiagnosticStore' -Description "ResultStore duplicate diagnostics"
Assert-Contains -Path $resultStore -Pattern 'pub fn profile\s*\(&self\)\s*->\s*ResultStoreProfile' -Description "ResultStore profile snapshot"
Assert-Contains -Path $resultStore -Pattern 'pub struct ResultStoreProfile' -Description "ResultStore profile type"
Assert-Contains -Path $resultStore -Pattern 'RuntimeDiagnosticCode::DuplicateOutputHandle' -Description "duplicate output handle diagnostic"
Assert-Contains -Path $resultStore -Pattern 'RuntimeDiagnosticCode::DuplicateOutputSeries' -Description "duplicate output series diagnostic"
Assert-Contains -Path $output -Pattern 'pub struct RuntimeOutputRegistry' -Description "runtime output registry"
Assert-Contains -Path $output -Pattern 'pub fn from_model\s*\(' -Description "runtime output registry model binding"
Assert-Contains -Path $output -Pattern 'pub fn resolve_output_requests\s*\(' -Description "runtime output request resolver"
Assert-Contains -Path $output -Pattern 'RuntimeDiagnosticCode::DuplicateOutputRequest' -Description "duplicate output request diagnostic"
Assert-Contains -Path $output -Pattern 'RuntimeDiagnosticCode::OutputVariableUnavailable' -Description "unavailable output variable diagnostic"
Assert-Contains -Path $runtimeOutputTests -Pattern 'runtime_output_registry_diagnoses_unavailable_system_node_output' -Description "system-node unavailable output registry test"
Assert-Contains -Path $runtimeOutputTests -Pattern 'result_store_diagnostics_report_duplicate_system_node_handles' -Description "system-node duplicate result-store handle test"
Assert-Contains -Path $output -Pattern 'ideal_loads_facility_meter_binding' -Description "Runtime meter registry uses IdealLoads meter binding helper"
Assert-NotContains -Path $output -Pattern 'pub struct IdealLoadsFacilityMeterBinding' -Description "IdealLoads facility-meter binding type in generic output registry"
Assert-NotContains -Path $output -Pattern 'pub fn ideal_loads_facility_meter_binding\s*\(' -Description "IdealLoads facility-meter binding helper in generic output registry"

Assert-Contains -Path $idealLoadsReport -Pattern 'mod semantics;' -Description "IdealLoads report semantics submodule declaration"
Assert-Contains -Path $idealLoadsReport -Pattern 'pub use semantics::\*;' -Description "IdealLoads report semantics public re-export"
Assert-Contains -Path $idealLoadsReportSemantics -Pattern 'pub const IDEAL_LOADS_RATE_OUTPUT_SOURCE' -Description "IdealLoads ReportPurchasedAir rate source metadata"
Assert-Contains -Path $idealLoadsReportSemantics -Pattern 'pub const IDEAL_LOADS_ENERGY_OUTPUT_TIMESTEP_SOURCE' -Description "IdealLoads report-energy timestep metadata"
Assert-Contains -Path $idealLoadsReportSemantics -Pattern 'pub const IDEAL_LOADS_FUEL_ENERGY_OUTPUT_LEVEL_POLICY' -Description "IdealLoads fuel-energy level policy metadata"
Assert-NotContains -Path $idealLoadsReport -Pattern 'pub const IDEAL_LOADS_RATE_OUTPUT_SOURCE' -Description "ReportPurchasedAir semantics in report module root"

Assert-Contains -Path $outdoorAir -Pattern 'mod dcv;' -Description "outdoor-air DCV submodule declaration"
Assert-Contains -Path $outdoorAir -Pattern 'mod design_flow;' -Description "outdoor-air design-flow submodule declaration"
Assert-Contains -Path $outdoorAir -Pattern 'mod economizer;' -Description "outdoor-air economizer submodule declaration"
Assert-Contains -Path $outdoorAir -Pattern 'mod mixed_air;' -Description "outdoor-air mixed-air submodule declaration"
Assert-Contains -Path $outdoorAir -Pattern 'mod psychrometrics;' -Description "outdoor-air psychrometrics submodule declaration"
Assert-Contains -Path $outdoorAir -Pattern 'mod supply;' -Description "outdoor-air supply submodule declaration"
Assert-Contains -Path $outdoorAir -Pattern '#\[path = "outdoor_air_tests\.rs"\]' -Description "outdoor-air test module path declaration"
Assert-Contains -Path $outdoorAir -Pattern 'pub use dcv::\*;' -Description "outdoor-air DCV public re-export"
Assert-Contains -Path $outdoorAir -Pattern 'pub use design_flow::\*;' -Description "outdoor-air design-flow public re-export"
Assert-Contains -Path $outdoorAirTests -Pattern '#\[test\]' -Description "outdoor-air root unit tests"
Assert-Contains -Path $outdoorAirDesignFlow -Pattern 'pub fn design_outdoor_air_volume_flow_components_m3_per_s\s*\(' -Description "outdoor-air design-flow component helper"
Assert-Contains -Path $outdoorAirDesignFlow -Pattern 'pub fn calc_scheduled_outdoor_air_mass_flow_rate_kg_per_s\s*\(' -Description "outdoor-air scheduled mass-flow helper"
Assert-Contains -Path $outdoorAirDesignFlow -Pattern 'fn nonnegative_product\s*\(' -Description "outdoor-air design-flow scalar helper"
Assert-Contains -Path $outdoorAirTests -Pattern 'fn sum_combines_supported_terms\s*\(' -Description "outdoor-air Sum runtime test"
Assert-Contains -Path $outdoorAirTests -Pattern 'fn maximum_selects_largest_supported_term\s*\(' -Description "outdoor-air Maximum runtime test"
Assert-Contains -Path $outdoorAirDcv -Pattern 'pub fn calc_occupancy_schedule_dcv_outdoor_air_mass_flow_rate_kg_per_s\s*\(' -Description "OccupancySchedule DCV helper"
Assert-Contains -Path $outdoorAirDcv -Pattern 'pub fn calc_co2_setpoint_dcv_outdoor_air_mass_flow_rate_kg_per_s\s*\(' -Description "CO2Setpoint DCV helper"
Assert-Contains -Path $outdoorAirDcvTests -Pattern 'fn co2_setpoint_dcv_selects_required_flow_above_minimum\s*\(' -Description "CO2Setpoint controlling-demand runtime test"
Assert-Contains -Path $outdoorAirDcvTests -Pattern 'fn co2_setpoint_dcv_preserves_minimum_for_noncontrolling_requirements\s*\(' -Description "CO2Setpoint minimum-flow runtime test"
Assert-Contains -Path $outdoorAirEconomizer -Pattern 'fn calc_economizer_adjusted_outdoor_air_mass_flow_rate_kg_per_s\s*\(' -Description "economizer OA flow helper"
Assert-Contains -Path $outdoorAirMixedAir -Pattern 'fn mixed_air_state\s*\(' -Description "mixed-air state helper"
Assert-Contains -Path $outdoorAirMixedAir -Pattern 'fn heat_recovery_allows_outdoor_air_tempering\s*\(' -Description "heat recovery activation helper"
Assert-Contains -Path $outdoorAirPsychrometrics -Pattern 'fn heat_recovery_saturation_adjusted_state\s*\(' -Description "heat recovery saturation helper"
Assert-Contains -Path $outdoorAirSupply -Pattern 'fn outdoor_air_supply_mass_flow_rate_kg_per_s\s*\(' -Description "outdoor-air supply mass-flow helper"
Assert-Contains -Path $outdoorAirSupply -Pattern 'fn supply_air_state\s*\(' -Description "outdoor-air supply state helper"
Assert-Contains -Path $outdoorAir -Pattern 'pub fn sim_purchased_air_outdoor_air_compat\s*\(' -Description "outdoor-air source-order wrapper"
Assert-NotContains -Path $outdoorAir -Pattern 'pub fn design_outdoor_air_volume_flow_components_m3_per_s\s*\(' -Description "outdoor-air design-flow component helper in outdoor-air root"
Assert-NotContains -Path $outdoorAir -Pattern 'pub fn calc_scheduled_outdoor_air_mass_flow_rate_kg_per_s\s*\(' -Description "outdoor-air scheduled mass-flow helper in outdoor-air root"
Assert-NotContains -Path $outdoorAir -Pattern 'fn nonnegative_product\s*\(' -Description "outdoor-air design-flow scalar helper in outdoor-air root"
Assert-NotContains -Path $outdoorAir -Pattern 'fn calc_occupancy_schedule_dcv_outdoor_air_mass_flow_rate_kg_per_s\s*\(' -Description "OccupancySchedule DCV helper in outdoor-air root"
Assert-NotContains -Path $outdoorAir -Pattern 'fn calc_co2_setpoint_dcv_outdoor_air_mass_flow_rate_kg_per_s\s*\(' -Description "CO2Setpoint DCV helper in outdoor-air root"
Assert-NotContains -Path $outdoorAir -Pattern 'fn calc_economizer_adjusted_outdoor_air_mass_flow_rate_kg_per_s\s*\(' -Description "economizer OA flow helper in outdoor-air root"
Assert-NotContains -Path $outdoorAir -Pattern 'fn mixed_air_state\s*\(' -Description "mixed-air state helper in outdoor-air root"
Assert-NotContains -Path $outdoorAir -Pattern 'fn heat_recovery_allows_outdoor_air_tempering\s*\(' -Description "heat recovery activation helper in outdoor-air root"
Assert-NotContains -Path $outdoorAir -Pattern 'fn heat_recovery_saturation_adjusted_state\s*\(' -Description "heat recovery saturation helper in outdoor-air root"
Assert-NotContains -Path $outdoorAir -Pattern 'fn outdoor_air_supply_mass_flow_rate_kg_per_s\s*\(' -Description "outdoor-air supply mass-flow helper in outdoor-air root"
Assert-NotContains -Path $outdoorAir -Pattern 'fn supply_air_state\s*\(' -Description "outdoor-air supply state helper in outdoor-air root"
Assert-NotContains -Path $outdoorAir -Pattern '#\[test\]' -Description "unit test body in outdoor-air root"
Assert-NotContains -Path $outdoorAir -Pattern 'energyplus_psychrometric_humidity_ratio_from_rh' -Description "psychrometric humidity-ratio helper import in outdoor-air root"
Assert-NotContains -Path $outdoorAirSumCompare -Pattern '\$summarySum\b|\$stageSum\b' -Description "script-owned outdoor-air Sum reconstruction"
Assert-NotContains -Path $outdoorAirMaximumCompare -Pattern '\$summaryMaximum\b|\$stageMaximum\b' -Description "script-owned outdoor-air Maximum reconstruction"

Assert-Contains -Path $dispatch -Pattern 'pub fn sim_purchased_air_compat\s*\(' -Description "SimPurchasedAir source-order wrapper"
Assert-Contains -Path $dispatch -Pattern 'pub struct IdealLoadsCompiledBranchFlags' -Description "IdealLoads cached branch flags"
Assert-Contains -Path $dispatch -Pattern 'pub fn sim_purchased_air_compat_with_branch_flags\s*\(' -Description "SimPurchasedAir wrapper accepts cached branch flags"
Assert-Contains -Path $dispatch -Pattern 'purchased_air_source_order_stages\s*\(' -Description "PurchasedAir source-order stage summary"
foreach ($routine in @(
        "GetPurchasedAir",
        "InitPurchasedAir",
        "CalcPurchAirLoads",
        "UpdatePurchasedAir",
        "ReportPurchasedAir"
    )) {
    Assert-Contains -Path $dispatch -Pattern "source_routine: `"$routine`"" -Description "PurchasedAirManager routine $routine"
}
Assert-Contains -Path $dispatch -Pattern 'pub const IDEAL_LOADS_RUNTIME_BINDING_SOURCE' -Description "IdealLoads runtime typed-ID binding metadata"
Assert-Contains -Path $dispatch -Pattern 'pub const IDEAL_LOADS_RUNTIME_STRING_LOOKUP_POLICY' -Description "IdealLoads runtime string lookup policy metadata"
Assert-Contains -Path $dispatch -Pattern 'pub const IDEAL_LOADS_SIZE_PURCHASED_AIR_POLICY' -Description "IdealLoads SizePurchasedAir autosize policy metadata"
Assert-Contains -Path $dispatch -Pattern 'SizePurchasedAir autosizing is blocked' -Description "IdealLoads SizePurchasedAir blocked autosizing policy"
Assert-Contains -Path $dispatch -Pattern 'IdealLoadsFeatureFlags::from_system' -Description "PurchasedAir branch dispatch uses compile feature flags"
Assert-Contains -Path $idealLoadsRuntime -Pattern 'IdealLoadsCompiledBranchFlags::from_system' -Description "IdealLoads runtime caches branch flags per system"
Assert-Contains -Path $idealLoadsRuntime -Pattern 'sim_purchased_air_compat_with_branch_flags' -Description "IdealLoads runtime uses cached branch flags"
Assert-Contains -Path $dispatch -Pattern 'calc_no_oa_sensible_with_limits_and_recirculation_compat\s*\(' -Description "finite-limit branch dispatch"
Assert-Contains -Path $dispatch -Pattern 'calc_no_oa_no_limit_sensible_with_recirculation_context_compat\s*\(' -Description "no-limit branch dispatch"
Assert-NotContains -Path $dispatch -Pattern 'calc_outdoor_air_sensible_report_rates_compat\s*\(' -Description "outdoor-air diagnostic calculation in source-order conformance wrapper"

$runtimeFormulaPatterns = @(
    'fn calc_no_oa_',
    'fn calc_outdoor_air_',
    'fn heating_result_with_limits\s*\(',
    'fn cooling_result_with_limits\s*\(',
    'fn calc_scheduled_outdoor_air_mass_flow_rate_kg_per_s\s*\('
)
foreach ($pattern in $runtimeFormulaPatterns) {
    Assert-NotContains -Path $runtime -Pattern $pattern -Description "IdealLoads branch formula in runtime root"
}

Assert-Contains -Path $node -Pattern 'mod state;' -Description "node state submodule declaration"
Assert-Contains -Path $node -Pattern 'pub use state::\*;' -Description "node state public re-export"
Assert-Contains -Path $node -Pattern 'mod projection;' -Description "node projection submodule declaration"
Assert-Contains -Path $node -Pattern 'pub use projection::\*;' -Description "node projection public re-export"
Assert-Contains -Path $node -Pattern 'pub struct IdealLoadsSupplyNodeUpdate' -Description "IdealLoads node update transfer struct"
Assert-Contains -Path $node -Pattern 'IDEAL_LOADS_NODE_OUTPUT_STORE_TYPE' -Description "IdealLoads node output store metadata"
Assert-Contains -Path $nodeProjection -Pattern 'pub struct NodeStateProjectionOptions' -Description "node projection options"
Assert-Contains -Path $nodeProjection -Pattern 'pub struct NodeStateProjectionEvidencePolicy' -Description "node projection evidence policy"
Assert-Contains -Path $nodeProjection -Pattern 'pub fn simulate_ideal_loads_node_state_projection\s*\(' -Description "node projection runtime function"
Assert-Contains -Path $nodeState -Pattern 'pub struct NodeStateStore' -Description "NodeStateStore implementation"
Assert-Contains -Path $nodeState -Pattern 'pub struct AirNodeState' -Description "AirNodeState implementation"
Assert-Contains -Path $nodeState -Pattern 'pub enum NodeStateRole' -Description "NodeStateRole implementation"
Assert-Contains -Path $nodeState -Pattern 'pub const NODE_STATE_SOURCE_MAP_PATH' -Description "node-state source-map metadata"
Assert-Contains -Path $nodeState -Pattern 'pub fn node_temperature_setpoint_from_energyplus\s*\(' -Description "EnergyPlus node setpoint sentinel adapter"
Assert-NotContains -Path $nodeState -Pattern 'IdealLoadsSupplyNodeUpdate' -Description "IdealLoads supply-node transfer struct in generic NodeStateStore"
Assert-NotContains -Path $nodeState -Pattern 'ideal_loads::' -Description "IdealLoads module dependency in generic NodeStateStore"
Assert-NotContains -Path $runtime -Pattern 'pub struct NodeStateProjectionOptions' -Description "node projection options in runtime root"
Assert-NotContains -Path $runtime -Pattern 'pub struct NodeStateProjectionEvidencePolicy' -Description "node projection evidence policy in runtime root"
Assert-NotContains -Path $runtime -Pattern 'pub fn simulate_ideal_loads_node_state_projection\s*\(' -Description "node projection runtime function in runtime root"
Assert-NotContains -Path $runtime -Pattern 'pub struct NodeStateStore' -Description "NodeStateStore implementation in runtime root"
Assert-NotContains -Path $runtime -Pattern 'pub struct AirNodeState' -Description "AirNodeState implementation in runtime root"
Assert-NotContains -Path $runtime -Pattern 'pub enum NodeStateRole' -Description "NodeStateRole implementation in runtime root"
Assert-NotContains -Path $runtime -Pattern 'pub const NODE_STATE_SOURCE_MAP_PATH' -Description "node-state source-map metadata in runtime root"

Assert-Contains -Path $lib -Pattern 'pub mod plant;' -Description "plant module public declaration"
Assert-Contains -Path $lib -Pattern 'pub use plant::\*;' -Description "plant module public re-export"
Assert-Contains -Path $plant -Pattern 'mod state;' -Description "plant state submodule declaration"
Assert-Contains -Path $plant -Pattern 'pub use state::\*;' -Description "plant state public re-export"
Assert-Contains -Path $plantState -Pattern 'pub struct PlantStateStore' -Description "PlantStateStore implementation"
Assert-Contains -Path $plantState -Pattern 'pub struct PlantStateProjectionEvidencePolicy' -Description "plant projection evidence policy"
Assert-Contains -Path $plantState -Pattern 'pub const PLANT_STATE_SOURCE_MAP_PATH' -Description "plant-state source-map metadata"
Assert-Contains -Path $plantState -Pattern 'pub fn simulate_plant_state_projection\s*\(' -Description "plant projection runtime function"
Assert-NotContains -Path $runtime -Pattern 'pub struct PlantStateStore' -Description "PlantStateStore implementation in runtime root"
Assert-NotContains -Path $runtime -Pattern 'pub struct PlantStateProjectionEvidencePolicy' -Description "plant projection evidence policy in runtime root"
Assert-NotContains -Path $runtime -Pattern 'pub const PLANT_STATE_SOURCE_MAP_PATH' -Description "plant-state source-map metadata in runtime root"
Assert-NotContains -Path $runtime -Pattern 'pub fn simulate_plant_state_projection\s*\(' -Description "plant projection runtime function in runtime root"

Assert-Contains -Path $zoneEquipment -Pattern 'mod demand;' -Description "zone equipment demand submodule declaration"
Assert-Contains -Path $zoneEquipment -Pattern 'pub use demand::\*;' -Description "zone equipment demand public re-export"
Assert-Contains -Path $zoneEquipment -Pattern 'mod dispatch;' -Description "zone equipment dispatch submodule declaration"
Assert-Contains -Path $zoneEquipment -Pattern 'pub use dispatch::\*;' -Description "zone equipment dispatch public re-export"
Assert-Contains -Path $zoneEquipment -Pattern '#\[path = "tests\.rs"\]' -Description "zone equipment test module path declaration"
Assert-Contains -Path $zoneEquipmentDemand -Pattern 'pub struct ZoneSysEnergyDemand' -Description "ZoneSysEnergyDemand source-order demand struct"
Assert-Contains -Path $zoneEquipmentDispatch -Pattern 'pub const fn ideal_loads_zone_equipment_stages\s*\(' -Description "Zone equipment compatibility stages"
Assert-Contains -Path $zoneEquipmentDispatch -Pattern 'pub fn validate_ideal_loads_zone_equipment_dispatch\s*\(' -Description "IdealLoads zone equipment dispatch validation"
Assert-Contains -Path $zoneEquipmentDispatch -Pattern 'SupplyNodeNotInZoneInletList' -Description "IdealLoads supply node inlet-list validation"
Assert-Contains -Path $zoneEquipmentDispatch -Pattern 'SequenceAmbiguity' -Description "IdealLoads sequence ambiguity validation"
Assert-Contains -Path $zoneEquipmentDispatch -Pattern 'MultipleZoneEquipmentDiagnosticOnly' -Description "IdealLoads multiple-equipment diagnostic boundary"
Assert-NotContains -Path $zoneEquipment -Pattern 'pub struct ZoneSysEnergyDemand' -Description "ZoneSysEnergyDemand implementation in zone equipment facade"
Assert-NotContains -Path $zoneEquipment -Pattern 'pub fn validate_ideal_loads_zone_equipment_dispatch\s*\(' -Description "dispatch validation implementation in zone equipment facade"
Assert-NotContains -Path $zoneEquipment -Pattern '#\[test\]' -Description "unit tests in zone equipment facade"
Assert-Contains -Path $executionPlan -Pattern 'ExecutionStep::ManageZoneEquipment' -Description "ZoneEquipmentManager stage in execution plan"
Assert-Contains -Path $executionPlan -Pattern 'ExecutionStep::SimZoneEquipment' -Description "SimZoneEquipment stage in execution plan"
Assert-Contains -Path $executionPlan -Pattern 'ExecutionStep::EvaluateIdealLoadsAirSystem' -Description "IdealLoads evaluation stage in execution plan"
Assert-Contains -Path $executionPlan -Pattern 'energyplus_ideal_loads_compatibility_stages' -Description "IdealLoads PurchasedAirManager source stage list"
Assert-Contains -Path $executionPlan -Pattern 'source_routine: "SimPurchasedAir"' -Description "SimPurchasedAir execution-plan source routine"
Assert-Contains -Path $executionPlan -Pattern 'source_routine: "GetPurchasedAir"' -Description "GetPurchasedAir execution-plan source routine"
Assert-Contains -Path $executionPlan -Pattern 'source_routine: "InitPurchasedAir"' -Description "InitPurchasedAir execution-plan source routine"
Assert-Contains -Path $executionPlan -Pattern 'source_routine: "CalcPurchAirLoads"' -Description "CalcPurchAirLoads execution-plan source routine"
Assert-Contains -Path $executionPlan -Pattern 'source_routine: "UpdatePurchasedAir"' -Description "UpdatePurchasedAir execution-plan source routine"
Assert-Contains -Path $executionPlan -Pattern 'source_routine: "ReportPurchasedAir"' -Description "ReportPurchasedAir execution-plan source routine"
Assert-Contains -Path $runSupport -Pattern 'active_ideal_loads_branches' -Description "run support active IdealLoads branch list"
Assert-Contains -Path $runSupport -Pattern 'inactive_ideal_loads_branches' -Description "run support inactive IdealLoads branch list"
Assert-Contains -Path $runPipeline -Pattern '"active_ideal_loads_branches"' -Description "run-summary active IdealLoads branch list"
Assert-Contains -Path $runPipeline -Pattern '"inactive_ideal_loads_branches"' -Description "run-summary inactive IdealLoads branch list"
Assert-Contains -Path $runRuntimeBoundaries -Pattern 'UnsupportedAlgorithm' -Description "unsupported active IdealLoads branch fails support assessment"
Assert-Contains -Path $runRuntimeBoundaries -Pattern 'unsupported_features_for_selected_branch' -Description "selected branch unsupported feature guard"
Assert-NotContains -Path $runtime -Pattern 'calc_no_oa_no_limit_sensible_compat\s*\(' -Description "IdealLoads no-limit branch formula call in runtime root"
Assert-NotContains -Path $runtime -Pattern 'calc_no_oa_sensible_with_limits_compat\s*\(' -Description "IdealLoads finite-limit branch formula call in runtime root"
Assert-NotContains -Path $runtime -Pattern 'calc_outdoor_air_sensible_report_rates_compat\s*\(' -Description "IdealLoads outdoor-air report calc call in runtime root"
Assert-NotContains -Path $runtime -Pattern 'sim_purchased_air_outdoor_air_compat\s*\(' -Description "IdealLoads outdoor-air diagnostic wrapper call in runtime root"
Assert-Contains -Path $idealLoadsMod -Pattern 'mod humidistat;' -Description "IdealLoads Humidistat transition module declaration"
Assert-Contains -Path $idealLoadsMod -Pattern 'pub use humidistat::\*;' -Description "IdealLoads Humidistat transition public re-export"
Assert-Contains -Path $idealLoadsHumidistat -Pattern 'pub struct NoOaHumidistatClosedLoopState' -Description "Humidistat closed-loop runtime state"
Assert-Contains -Path $idealLoadsHumidistat -Pattern 'pub struct NoOaHumidistatZoneTimestepInput' -Description "Humidistat closed-loop typed zone-timestep input"
Assert-Contains -Path $idealLoadsHumidistat -Pattern 'pub struct NoOaHumidistatZoneTimestepOutput' -Description "Humidistat closed-loop typed zone-timestep output"
Assert-Contains -Path $idealLoadsHumidistat -Pattern 'pub enum NoOaHumidistatZoneTimestepError' -Description "Humidistat closed-loop typed zone-timestep error"
Assert-Contains -Path $idealLoadsHumidistat -Pattern 'pub fn advance_no_oa_humidistat_zone_timestep_compat\s*\(' -Description "Humidistat closed-loop runtime zone-timestep transition"
Assert-Contains -Path $idealLoadsHumidistatTests -Pattern 'fn no_oa_humidistat_closed_loop_advances_corrected_humidity_histories\s*\(' -Description "Humidistat history transition runtime test"
Assert-Contains -Path $idealLoadsHumidistatTests -Pattern 'fn no_oa_humidistat_closed_loop_reuses_committed_history_on_next_step\s*\(' -Description "Humidistat committed-history runtime test"
Assert-Contains -Path $idealLoadsHumidistatTests -Pattern 'fn no_oa_humidistat_closed_loop_divides_supply_flow_by_zone_multiplier_before_correction\s*\(' -Description "Humidistat zone-multiplier runtime test"
Assert-Contains -Path $idealLoadsHumidistatTests -Pattern 'fn no_oa_humidistat_closed_loop_preserves_state_when_predictor_rejects_input\s*\(' -Description "Humidistat atomic predictor-error runtime test"
Assert-Contains -Path $idealLoadsHumidistatTests -Pattern 'fn no_oa_humidistat_closed_loop_rejects_non_humidistat_branch_without_advancing_state\s*\(' -Description "Humidistat branch-ownership runtime test"
Assert-Contains -Path $idealLoadsHumidistatTests -Pattern 'fn no_oa_humidistat_closed_loop_preserves_state_when_purchased_air_rejects_input\s*\(' -Description "Humidistat atomic PurchasedAir-error runtime test"
Assert-Contains -Path $idealLoadsHumidistatTests -Pattern 'fn no_oa_humidistat_closed_loop_preserves_state_when_corrector_rejects_input\s*\(' -Description "Humidistat atomic corrector-error runtime test"
Assert-NotContains -Path $idealLoadsHumidistat -Pattern 'ep_compare|ep_conformance|IdealLoadsInputTrace|LoadedSeries|std::path::Path' -Description "case/report adaptation in Humidistat runtime transition"
Assert-NotContains -Path $idealLoadsHumidistat -Pattern '#\[test\]' -Description "inline tests in Humidistat runtime transition"
Assert-NotContains -Path $idealLoadsHumidistat -Pattern 'pub timestep_seconds:' -Description "ambiguous Humidistat system-substep input"
Assert-Contains -Path $idealLoadsCli -Pattern 'mod case_adapter;' -Description "IdealLoads CLI case-adapter module declaration"
Assert-Contains -Path $idealLoadsCliCaseAdapter -Pattern 'mod time_axis;' -Description "IdealLoads CLI time-axis adapter module declaration"
Assert-Contains -Path $idealLoadsCliTimeAxisAdapter -Pattern 'time_axis_timestep_profile\s*\(' -Description "IdealLoads adapter uses runtime TimeAxis timestep profile"
Assert-Contains -Path $idealLoadsCliTimeAxisAdapter -Pattern 'pub\(in crate::ideal_loads\) fn ideal_loads_timestep_context\s*\(' -Description "IdealLoads nominal timestep adapter"
Assert-Contains -Path $idealLoadsCliTimeAxisAdapter -Pattern 'pub\(in crate::ideal_loads\) fn ideal_loads_sample_timestep_seconds\s*\(' -Description "IdealLoads exact sample-seconds adapter"
Assert-Contains -Path $idealLoadsCliTimeAxisAdapter -Pattern 'pub\(in crate::ideal_loads\) fn ideal_loads_sample_timestep_hours\s*\(' -Description "IdealLoads exact sample-hours adapter"
Assert-Contains -Path $idealLoadsCliTimeAxisAdapterTests -Pattern 'fn ideal_loads_timestep_context_uses_runtime_time_axis_nominal_values\s*\(' -Description "IdealLoads TimeAxis nominal metadata test"
Assert-Contains -Path $idealLoadsCliTimeAxisAdapterTests -Pattern 'fn ideal_loads_timestep_context_does_not_validate_unrelated_run_period_dates\s*\(' -Description "IdealLoads timestep-only adapter run-period decoupling test"
Assert-Contains -Path $idealLoadsCliTimeAxisAdapterTests -Pattern 'fn ideal_loads_sample_timestep_uses_valid_duration_and_timestamp_precision_normalization\s*\(' -Description "IdealLoads sample duration and timestamp-precision test"
Assert-Contains -Path $idealLoadsCliTimeAxisAdapterTests -Pattern 'fn ideal_loads_sample_timestep_falls_back_for_missing_or_invalid_timestamp\s*\(' -Description "IdealLoads nominal timestamp fallback test"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_sample_timestep_seconds\s*\(' -Description "IdealLoads report-energy uses exact sample duration adapter"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_sample_timestep_hours\s*\(' -Description "IdealLoads outdoor-air active time uses exact sample duration adapter"
Assert-Contains -Path $idealLoadsCli -Pattern 'timestep_source: \{\}' -Description "IdealLoads report exposes TimeAxis source"
Assert-Contains -Path $idealLoadsCli -Pattern 'adaptive_system_timestep_claim' -Description "IdealLoads report preserves adaptive timestep non-claim"
Assert-NotContains -Path $idealLoadsCli -Pattern 'IDEAL_LOADS_(NO_OA_ENERGY|OUTDOOR_AIR)_SYSTEM_SUBSTEPS' -Description "fixed IdealLoads system-substep constant"
Assert-NotContains -Path $idealLoadsCli -Pattern 'fn ideal_loads_(system_timestep_seconds|energy_report_interval_seconds|outdoor_air_sample_timestep_hours)\s*\(' -Description "legacy IdealLoads fixed-timestep helper"
Assert-NotContains -Path $idealLoadsCli -Pattern 'fn energy_report_seconds_from_timestamp\s*\(' -Description "duplicate IdealLoads report-energy timestamp heuristic"
Assert-NotContains -Path $idealLoadsCli -Pattern 'fixed_system_substeps|fixed 8-substep fixture branch' -Description "fixed IdealLoads substep report metadata"
Assert-NotContains -Path $idealLoadsCli -Pattern '(?<!nominal_)system_timestep_substeps|(?<!nominal_)system_timestep_seconds|energy_report_interval_seconds' -Description "ambiguous legacy IdealLoads timestep JSON key"
Assert-NotContains -Path $idealLoadsCliOutdoorAirJson -Pattern '(?<!nominal_)system_timestep_substeps|(?<!nominal_)system_timestep_seconds|energy_report_interval_seconds|fixed 8-substep' -Description "legacy IdealLoads outdoor-air timestep metadata"
Assert-NotContains -Path $idealLoadsCliOutdoorAirMarkdown -Pattern 'fixed_system_substeps|fixed 8-substep|112\.5' -Description "fixed IdealLoads outdoor-air timestep claim"
Assert-Contains -Path $outdoorAirSumCompare -Pattern 'timestep_source -ne "ep_runtime::TimeAxis"' -Description "outdoor-air TimeAxis report assertion"
Assert-Contains -Path $outdoorAirSumCompare -Pattern 'adaptive_system_timestep_claim -ne \$false' -Description "outdoor-air adaptive timestep non-claim assertion"
Assert-Contains -Path $outdoorAirSumCompare -Pattern 'sample_timestep_source -ne "ESO timestamp duration with ep_runtime::TimeAxis integer-substep normalization and nominal fallback"' -Description "outdoor-air sample timestep source assertion"
Assert-Contains -Path $idealLoadsCli -Pattern 'mod commands;' -Description "IdealLoads CLI commands module declaration"
Assert-Contains -Path $idealLoadsCli -Pattern 'pub\(crate\) use commands::' -Description "IdealLoads CLI command facade re-export"
Assert-Contains -Path $idealLoadsCli -Pattern 'mod reports;' -Description "IdealLoads CLI reports module declaration"
Assert-Contains -Path $idealLoadsCliReports -Pattern 'mod outdoor_air;' -Description "IdealLoads CLI outdoor-air reports module declaration"
Assert-Contains -Path $idealLoadsCliReports -Pattern 'pub\(super\) use outdoor_air::write_outdoor_air_artifacts;' -Description "IdealLoads CLI outdoor-air writer facade"
Assert-Contains -Path $idealLoadsCliOutdoorAirReports -Pattern 'mod csv;' -Description "IdealLoads CLI outdoor-air CSV module declaration"
Assert-Contains -Path $idealLoadsCliOutdoorAirReports -Pattern 'mod json;' -Description "IdealLoads CLI outdoor-air JSON module declaration"
Assert-Contains -Path $idealLoadsCliOutdoorAirReports -Pattern 'mod markdown;' -Description "IdealLoads CLI outdoor-air Markdown module declaration"
Assert-Contains -Path $idealLoadsCliOutdoorAirReports -Pattern 'pub\(in crate::ideal_loads\) fn write_outdoor_air_artifacts\s*\(' -Description "IdealLoads CLI outdoor-air artifact writer ownership"
Assert-Contains -Path $idealLoadsCliOutdoorAirMarkdown -Pattern 'pub\(super\) fn render_outdoor_air_markdown\s*\(' -Description "IdealLoads CLI outdoor-air Markdown renderer ownership"
Assert-Contains -Path $idealLoadsCliOutdoorAirJson -Pattern 'pub\(super\) fn render_outdoor_air_summary_json\s*\(' -Description "IdealLoads CLI outdoor-air summary JSON renderer ownership"
Assert-Contains -Path $idealLoadsCliOutdoorAirJson -Pattern 'pub\(super\) fn render_outdoor_air_selected_outputs_json\s*\(' -Description "IdealLoads CLI outdoor-air selected-outputs JSON renderer ownership"
Assert-Contains -Path $idealLoadsCliOutdoorAirJson -Pattern 'pub\(super\) fn render_outdoor_air_result_store_json\s*\(' -Description "IdealLoads CLI outdoor-air result-store JSON renderer ownership"
Assert-Contains -Path $idealLoadsCliOutdoorAirJson -Pattern 'pub\(super\) fn render_outdoor_air_stage_summary_json\s*\(' -Description "IdealLoads CLI outdoor-air stage-summary JSON renderer ownership"
Assert-Contains -Path $idealLoadsCliOutdoorAirCsv -Pattern 'pub\(super\) fn render_outdoor_air_variable_deltas_csv\s*\(' -Description "IdealLoads CLI outdoor-air variable-deltas CSV renderer ownership"
Assert-Contains -Path $idealLoadsCliOutdoorAirCsv -Pattern 'pub\(super\) fn render_outdoor_air_first_divergence_csv\s*\(' -Description "IdealLoads CLI outdoor-air first-divergence CSV renderer ownership"
Assert-Contains -Path $idealLoadsCliOutdoorAirCsv -Pattern 'pub\(super\) fn render_outdoor_air_tolerance_failures_csv\s*\(' -Description "IdealLoads CLI outdoor-air tolerance-failures CSV renderer ownership"
Assert-NotContains -Path $idealLoadsCli -Pattern 'fn (write_outdoor_air_artifacts|render_outdoor_air_(markdown|summary_json|selected_outputs_json|result_store_json|variable_deltas_csv|first_divergence_csv|tolerance_failures_csv|stage_summary_json))\s*\(' -Description "IdealLoads outdoor-air report renderer implementation in facade"
Assert-Contains -Path $idealLoadsCliCommands -Pattern 'pub\(crate\) struct IdealLoadsDiagnosticReportSummary' -Description "IdealLoads CLI command artifact summary"
Assert-Contains -Path $idealLoadsCliCommands -Pattern 'pub\(crate\) fn generate_ideal_loads_no_oa_sensible_report\s*\(' -Description "IdealLoads no-OA command entry point"
Assert-Contains -Path $idealLoadsCliCommands -Pattern 'pub\(crate\) fn generate_ideal_loads_outdoor_air_design_flow_report\s*\(' -Description "IdealLoads outdoor-air command entry point"
Assert-NotContains -Path $idealLoadsCli -Pattern 'pub\(crate\) struct IdealLoadsDiagnosticReportSummary' -Description "IdealLoads CLI command artifact summary in facade"
Assert-NotContains -Path $idealLoadsCli -Pattern 'pub\(crate\) fn generate_ideal_loads_(no_oa_sensible|outdoor_air_design_flow)_report\s*\(' -Description "IdealLoads command implementation in facade"
Assert-Contains -Path $idealLoadsCli -Pattern 'zone_equipment_dispatch_path' -Description "IdealLoads report zone-equipment dispatch path metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_invocation_path' -Description "IdealLoads report source-order invocation path metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'direct_calc_helper_invocation' -Description "IdealLoads report direct-helper invocation metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'zone_equipment_dispatch_execution_boundary' -Description "IdealLoads report zone-equipment execution boundary metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_trace_level\s*\(' -Description "IdealLoads report manifest trace-level helper"
Assert-Contains -Path $idealLoadsCli -Pattern 'trace_level_source' -Description "IdealLoads report trace-level source metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'trace_result_invariance_policy' -Description "IdealLoads report trace-result invariance metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'trace_overhead_accounting' -Description "IdealLoads report trace overhead accounting metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'zone_equipment_dispatch_validation' -Description "IdealLoads report zone-equipment dispatch validation metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'zone_equipment_conformance_candidate' -Description "IdealLoads report zone-equipment conformance-candidate metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_feature_flags' -Description "IdealLoads report feature flag metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_feature_dispatch_policy' -Description "IdealLoads report feature-dispatch policy metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_prebound_id_contract' -Description "IdealLoads report prebound-ID contract metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_psychrometric_evaluation_policy' -Description "IdealLoads report psychrometric evaluation policy metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_psychrometric_cache_policy' -Description "IdealLoads report psychrometric cache policy metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'resolve_ideal_loads_output_handles' -Description "IdealLoads setup-time output handle resolver"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_output_handle_registration_policy' -Description "IdealLoads report output handle registration policy metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_output_handle_write_policy' -Description "IdealLoads report output handle write policy metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_diagnostic_output_request_policy' -Description "IdealLoads report diagnostic output request policy metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_report_export_order_policy' -Description "IdealLoads report export order policy metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_detailed_output_lookup_policy' -Description "IdealLoads report Detailed output lookup policy metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_duplicate_output_handle_policy' -Description "IdealLoads report duplicate output handle policy metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'ideal_loads_runtime_binding_source' -Description "IdealLoads report typed-ID binding metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'purchased_air_name_lookup_policy' -Description "IdealLoads report string lookup policy metadata"
Assert-Contains -Path $idealLoadsCli -Pattern 'sim_purchased_air_compat' -Description "IdealLoads no-OA report generator uses source-order wrapper"
Assert-Contains -Path $idealLoadsCli -Pattern 'sim_purchased_air_outdoor_air_compat' -Description "IdealLoads outdoor-air report generator uses source-order wrapper"
Assert-Contains -Path $idealLoadsCli -Pattern 'calc_co2_setpoint_dcv_outdoor_air_mass_flow_rate_kg_per_s' -Description "IdealLoads CO2Setpoint reporter uses runtime helper"
Assert-Contains -Path $idealLoadsCli -Pattern 'meter_rate_to_energy_j\s*\(' -Description "IdealLoads report energy uses runtime rate-to-energy helper"
Assert-Contains -Path $calcMoistureDemand -Pattern 'pub fn third_order_humidity_history_term\s*\(' -Description "ThirdOrder humidity history runtime helper"
Assert-Contains -Path $calcMoistureDemandTests -Pattern 'fn third_order_humidity_history_term_matches_energyplus_coefficients\s*\(' -Description "ThirdOrder humidity history runtime test"
Assert-Contains -Path $idealLoadsCli -Pattern 'third_order_humidity_history_term\s*\(' -Description "IdealLoads residual diagnostic uses runtime ThirdOrder helper"
Assert-Contains -Path $idealLoadsCli -Pattern 'advance_no_oa_humidistat_zone_timestep_compat\s*\(' -Description "IdealLoads CLI uses runtime Humidistat zone-timestep state transition"
Assert-NotContains -Path $idealLoadsCli -Pattern 'outdoor_air_design_mass_flow_rate_kg_per_s\s*\.max\s*\(' -Description "CO2Setpoint DCV physics in CLI reporter"
Assert-NotContains -Path $idealLoadsCli -Pattern 'rate\([^\r\n]*\)\s*\*\s*interval_seconds' -Description "IdealLoads rate-to-energy physics in CLI reporter"
Assert-NotContains -Path $idealLoadsCli -Pattern 'fn third_order_humidity_history_term\s*\(' -Description "ThirdOrder humidity history helper in CLI reporter"
Assert-NotContains -Path $idealLoadsCli -Pattern '3\.0\s*\*\s*history\[0\].*1\.5\s*\*\s*history\[1\]' -Description "raw ThirdOrder humidity history coefficients in CLI reporter"
Assert-NotContains -Path $idealLoadsCli -Pattern 'NoOaThirdOrderHumidityCorrectorInput|correct_no_oa_third_order_humidity_ratio_compat' -Description "Humidistat corrector physics in CLI reporter"
Assert-NotContains -Path $idealLoadsCli -Pattern 'zone_(air|mean)_humidity_history\s*=\s*\[' -Description "Humidistat history mutation in CLI reporter"
Assert-NotContains -Path $idealLoadsCli -Pattern 'remaining_output_req_to_humid_sp_kg_per_s\s*=\s*predicted' -Description "Humidistat predicted-demand injection in CLI reporter"
Assert-NotContains -Path $idealLoadsCli -Pattern 'remaining_output_req_to_dehumid_sp_kg_per_s\s*=\s*predicted' -Description "Humidistat predicted-demand injection in CLI reporter"
Assert-NotContains -Path $idealLoadsCli -Pattern 'calc_no_oa_no_limit_sensible_compat' -Description "direct no-limit no-OA calc helper call in report generator"
Assert-NotContains -Path $idealLoadsCli -Pattern 'calc_no_oa_sensible_with_limits_compat' -Description "direct finite-limit no-OA calc helper call in report generator"
Assert-NotContains -Path $idealLoadsCli -Pattern 'calc_outdoor_air_sensible_report_rates_compat' -Description "direct outdoor-air calc helper call in report generator"

Write-Host "IdealLoads structure audit complete."
