//! Lossless JSON serialization for one CP413 saturation-guard snapshot.

use ep_model::DehumidificationControlType;
use ep_runtime::PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationSupplyHumidityRatioSaturationGuardSnapshot;
use serde_json::{Value, json};

pub(super) fn snapshot_json(
    snapshot: PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationSupplyHumidityRatioSaturationGuardSnapshot,
) -> Value {
    json!({
        "source": snapshot.source,
        "first_excluded_source": snapshot.first_excluded_source,
        "source_order": snapshot.source_order,
        "system": snapshot.system.0,
        "parent_call_ordinal": snapshot.parent_call_ordinal,
        "controlled_zone": snapshot.controlled_zone.0,
        "unit_off_skipped": snapshot.unit_off_skipped,
        "non_cooling_skipped": snapshot.non_cooling_skipped,
        "positive_guard_false_fallthrough_skipped": snapshot.positive_guard_false_fallthrough_skipped,
        "heating_availability_guard_false_fallthrough": snapshot.heating_availability_guard_false_fallthrough,
        "humidification_control_guard_false_fallthrough": snapshot.humidification_control_guard_false_fallthrough,
        "dehumidification_control_humidistat_maximum_assignment_executed": snapshot.dehumidification_control_humidistat_maximum_assignment_executed,
        "dehumidification_control_none_maximum_assignment_executed": snapshot.dehumidification_control_none_maximum_assignment_executed,
        "dehumidification_control_guard_false_fallthrough": snapshot.dehumidification_control_guard_false_fallthrough,
        "predecessor_capacity_limit_guard_evaluated": snapshot.predecessor_capacity_limit_guard_evaluated,
        "predecessor_capacity_limit_body_entered": snapshot.predecessor_capacity_limit_body_entered,
        "predecessor_active_capacity_limit_guard_false_fallthrough": snapshot.predecessor_active_capacity_limit_guard_false_fallthrough,
        "predecessor_dehumidification_guard_evaluated": snapshot.predecessor_dehumidification_guard_evaluated,
        "predecessor_dehumidification_body_entered": snapshot.predecessor_dehumidification_body_entered,
        "predecessor_dehumidification_guard_false_fallthrough": snapshot.predecessor_dehumidification_guard_false_fallthrough,
        "predecessor_dehumidification_total_output_assignment_executed": snapshot.predecessor_dehumidification_total_output_assignment_executed,
        "predecessor_dehumidification_total_output_capacity_guard_evaluated": snapshot.predecessor_dehumidification_total_output_capacity_guard_evaluated,
        "predecessor_dehumidification_total_output_capacity_adjustment_body_entered": snapshot.predecessor_dehumidification_total_output_capacity_adjustment_body_entered,
        "predecessor_dehumidification_total_output_capacity_guard_false_fallthrough": snapshot.predecessor_dehumidification_total_output_capacity_guard_false_fallthrough,
        "dehumidification_total_output_capacity_guard_false_fallthrough": snapshot.dehumidification_total_output_capacity_guard_false_fallthrough,
        "dehumidification_total_output_maximum_capacity_assignment_executed": snapshot.dehumidification_total_output_maximum_capacity_assignment_executed,
        "predecessor_supply_enthalpy_assignment_executed": snapshot.predecessor_supply_enthalpy_assignment_executed,
        "predecessor_dehumidification_control_type_read": snapshot.predecessor_dehumidification_control_type_read,
        "predecessor_dehumidification_control_type": snapshot.predecessor_dehumidification_control_type.map(control_type_name),
        "predecessor_dehumidification_control_switch_dispatched": snapshot.predecessor_dehumidification_control_switch_dispatched,
        "predecessor_dehumidification_control_constant_sensible_heat_ratio_case_entered": snapshot.predecessor_dehumidification_control_constant_sensible_heat_ratio_case_entered,
        "predecessor_dehumidification_control_constant_sensible_heat_ratio_case_exited_via_break": snapshot.predecessor_dehumidification_control_constant_sensible_heat_ratio_case_exited_via_break,
        "predecessor_dehumidification_control_humidistat_case_entered": snapshot.predecessor_dehumidification_control_humidistat_case_entered,
        "predecessor_dehumidification_control_humidistat_supply_humidity_ratio_assignment_executed": snapshot.predecessor_dehumidification_control_humidistat_supply_humidity_ratio_assignment_executed,
        "predecessor_dehumidification_control_humidistat_case_exited_via_break": snapshot.predecessor_dehumidification_control_humidistat_case_exited_via_break,
        "predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_shared_case_entered": snapshot.predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_shared_case_entered,
        "predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_capacity_guard_false_fallthrough": snapshot.predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_capacity_guard_false_fallthrough,
        "predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_maximum_capacity_assignment_executed": snapshot.predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_maximum_capacity_assignment_executed,
        "predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_shared_case_exited_via_break": snapshot.predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_shared_case_exited_via_break,
        "predecessor_cp409_resulting_supply_humidity_ratio": json_number(snapshot.predecessor_cp409_resulting_supply_humidity_ratio),
        "predecessor_cp409_resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp409_resulting_supply_humidity_ratio),
        "predecessor_cp409_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp409_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp409_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp409_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp409_resulting_supply_temperature_c": json_number(snapshot.predecessor_cp409_resulting_supply_temperature_c),
        "predecessor_cp409_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp409_resulting_supply_temperature_c),
        "predecessor_dehumidification_control_default_case_exited_via_break": snapshot.predecessor_dehumidification_control_default_case_exited_via_break,
        "predecessor_cp410_resulting_supply_humidity_ratio": json_number(snapshot.predecessor_cp410_resulting_supply_humidity_ratio),
        "predecessor_cp410_resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp410_resulting_supply_humidity_ratio),
        "predecessor_cp410_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp410_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp410_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp410_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp410_resulting_supply_temperature_c": json_number(snapshot.predecessor_cp410_resulting_supply_temperature_c),
        "predecessor_cp410_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp410_resulting_supply_temperature_c),
        "post_saturation_capacity_limit_dehumidification_supply_humidity_ratio_pre_saturation_original_assignment_executed": snapshot.post_saturation_capacity_limit_dehumidification_supply_humidity_ratio_pre_saturation_original_assignment_executed,
        "cp410_retained_supply_humidity_ratio_state_owned": snapshot.cp410_retained_supply_humidity_ratio_state_owned,
        "cp410_retained_supply_enthalpy_state_owned": snapshot.cp410_retained_supply_enthalpy_state_owned,
        "cp410_retained_supply_temperature_state_owned": snapshot.cp410_retained_supply_temperature_state_owned,
        "cp410_retained_supply_humidity_ratio_owned_read": snapshot.cp410_retained_supply_humidity_ratio_owned_read,
        "purchased_air_supply_humidity_ratio_read": snapshot.purchased_air_supply_humidity_ratio_read,
        "purchased_air_supply_humidity_ratio_before_saturation_check": json_number(snapshot.purchased_air_supply_humidity_ratio_before_saturation_check),
        "purchased_air_supply_humidity_ratio_before_saturation_check_ieee_bits": ieee_bits(snapshot.purchased_air_supply_humidity_ratio_before_saturation_check),
        "local_supply_humidity_ratio_original_assignment_performed": snapshot.local_supply_humidity_ratio_original_assignment_performed,
        "assigned_supply_humidity_ratio_original": json_number(snapshot.assigned_supply_humidity_ratio_original),
        "assigned_supply_humidity_ratio_original_ieee_bits": ieee_bits(snapshot.assigned_supply_humidity_ratio_original),
        "resulting_supply_humidity_ratio_original": json_number(snapshot.resulting_supply_humidity_ratio_original),
        "resulting_supply_humidity_ratio_original_ieee_bits": ieee_bits(snapshot.resulting_supply_humidity_ratio_original),
        "predecessor_cp411_resulting_supply_humidity_ratio": json_number(snapshot.predecessor_cp411_resulting_supply_humidity_ratio),
        "predecessor_cp411_resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp411_resulting_supply_humidity_ratio),
        "predecessor_cp411_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp411_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp411_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp411_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp411_resulting_supply_temperature_c": json_number(snapshot.predecessor_cp411_resulting_supply_temperature_c),
        "predecessor_cp411_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp411_resulting_supply_temperature_c),
        "post_saturation_capacity_limit_dehumidification_supply_humidity_ratio_saturation_assignment_executed": snapshot.post_saturation_capacity_limit_dehumidification_supply_humidity_ratio_saturation_assignment_executed,
        "cp411_retained_supply_humidity_ratio_state_owned": snapshot.cp411_retained_supply_humidity_ratio_state_owned,
        "cp411_retained_supply_enthalpy_state_owned": snapshot.cp411_retained_supply_enthalpy_state_owned,
        "cp411_retained_supply_temperature_state_owned": snapshot.cp411_retained_supply_temperature_state_owned,
        "cp411_retained_supply_temperature_owned_read": snapshot.cp411_retained_supply_temperature_owned_read,
        "purchased_air_supply_temperature_for_saturation_humidity_ratio_read": snapshot.purchased_air_supply_temperature_for_saturation_humidity_ratio_read,
        "supply_temperature_for_saturation_humidity_ratio_c": json_number(snapshot.supply_temperature_for_saturation_humidity_ratio_c),
        "supply_temperature_for_saturation_humidity_ratio_c_ieee_bits": ieee_bits(snapshot.supply_temperature_for_saturation_humidity_ratio_c),
        "environment_outdoor_barometric_pressure_owned_read": snapshot.environment_outdoor_barometric_pressure_owned_read,
        "environment_outdoor_barometric_pressure_for_saturation_humidity_ratio_read": snapshot.environment_outdoor_barometric_pressure_for_saturation_humidity_ratio_read,
        "outdoor_barometric_pressure_pa": json_number(snapshot.outdoor_barometric_pressure_pa),
        "outdoor_barometric_pressure_pa_ieee_bits": ieee_bits(snapshot.outdoor_barometric_pressure_pa),
        "psy_w_fn_tdb_rh_pb_at_unity_relative_humidity_evaluated": snapshot.psy_w_fn_tdb_rh_pb_at_unity_relative_humidity_evaluated,
        "saturation_supply_humidity_ratio": json_number(snapshot.saturation_supply_humidity_ratio),
        "saturation_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.saturation_supply_humidity_ratio),
        "local_saturation_supply_humidity_ratio_assignment_performed": snapshot.local_saturation_supply_humidity_ratio_assignment_performed,
        "assigned_saturation_supply_humidity_ratio": json_number(snapshot.assigned_saturation_supply_humidity_ratio),
        "assigned_saturation_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.assigned_saturation_supply_humidity_ratio),
        "resulting_saturation_supply_humidity_ratio": json_number(snapshot.resulting_saturation_supply_humidity_ratio),
        "resulting_saturation_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.resulting_saturation_supply_humidity_ratio),
        "predecessor_cp412_resulting_supply_humidity_ratio": json_number(snapshot.predecessor_cp412_resulting_supply_humidity_ratio),
        "predecessor_cp412_resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp412_resulting_supply_humidity_ratio),
        "predecessor_cp412_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp412_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp412_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp412_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp412_resulting_supply_temperature_c": json_number(snapshot.predecessor_cp412_resulting_supply_temperature_c),
        "predecessor_cp412_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp412_resulting_supply_temperature_c),
        "post_saturation_capacity_limit_dehumidification_supply_humidity_ratio_saturation_guard_evaluated": snapshot.post_saturation_capacity_limit_dehumidification_supply_humidity_ratio_saturation_guard_evaluated,
        "cp412_saturation_supply_humidity_ratio_owned_read": snapshot.cp412_saturation_supply_humidity_ratio_owned_read,
        "saturation_supply_humidity_ratio_for_guard_read": snapshot.saturation_supply_humidity_ratio_for_guard_read,
        "saturation_supply_humidity_ratio_for_guard": json_number(snapshot.saturation_supply_humidity_ratio_for_guard),
        "saturation_supply_humidity_ratio_for_guard_ieee_bits": ieee_bits(snapshot.saturation_supply_humidity_ratio_for_guard),
        "cp411_original_supply_humidity_ratio_owned_read": snapshot.cp411_original_supply_humidity_ratio_owned_read,
        "cp412_same_call_original_supply_humidity_ratio_bit_corroborated": snapshot.cp412_same_call_original_supply_humidity_ratio_bit_corroborated,
        "original_supply_humidity_ratio_for_guard_read": snapshot.original_supply_humidity_ratio_for_guard_read,
        "original_supply_humidity_ratio_for_guard": json_number(snapshot.original_supply_humidity_ratio_for_guard),
        "original_supply_humidity_ratio_for_guard_ieee_bits": ieee_bits(snapshot.original_supply_humidity_ratio_for_guard),
        "saturation_original_supply_humidity_ratio_comparison_evaluated": snapshot.saturation_original_supply_humidity_ratio_comparison_evaluated,
        "saturation_supply_humidity_ratio_strictly_less_than_original_supply_humidity_ratio": snapshot.saturation_supply_humidity_ratio_strictly_less_than_original_supply_humidity_ratio,
        "saturation_supply_humidity_ratio_guard_body_entered": snapshot.saturation_supply_humidity_ratio_guard_body_entered,
        "saturation_supply_humidity_ratio_guard_false_fallthrough": snapshot.saturation_supply_humidity_ratio_guard_false_fallthrough,
        "cp412_retained_supply_humidity_ratio_state_owned": snapshot.cp412_retained_supply_humidity_ratio_state_owned,
        "cp412_retained_supply_enthalpy_state_owned": snapshot.cp412_retained_supply_enthalpy_state_owned,
        "cp412_retained_supply_temperature_state_owned": snapshot.cp412_retained_supply_temperature_state_owned,
        "resulting_supply_humidity_ratio": json_number(snapshot.resulting_supply_humidity_ratio),
        "resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.resulting_supply_humidity_ratio),
        "resulting_supply_enthalpy_j_per_kg": json_number(snapshot.resulting_supply_enthalpy_j_per_kg),
        "resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.resulting_supply_enthalpy_j_per_kg),
        "resulting_supply_temperature_c": json_number(snapshot.resulting_supply_temperature_c),
        "resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.resulting_supply_temperature_c),
    })
}

fn control_type_name(control: DehumidificationControlType) -> &'static str {
    match control {
        DehumidificationControlType::None => "None",
        DehumidificationControlType::ConstantSensibleHeatRatio => "ConstantSensibleHeatRatio",
        DehumidificationControlType::Humidistat => "Humidistat",
        DehumidificationControlType::ConstantSupplyHumidityRatio => "ConstantSupplyHumidityRatio",
    }
}

fn json_number(value: Option<f64>) -> Value {
    value
        .filter(|value| value.is_finite())
        .map_or(Value::Null, |value| json!(value))
}

fn ieee_bits(value: Option<f64>) -> Option<String> {
    value.map(|value| format!("0x{:016x}", value.to_bits()))
}

#[cfg(test)]
mod tests;
