//! Heat-balance simulation summary value types.

use crate::ResultStore;
use crate::heat_balance::state::{
    HeatBalanceCtfHistorySlotFirstSample, HeatBalanceCtfHistorySlotHourlySample,
    HeatBalanceCtfHistorySlotSample, HeatBalanceCtfInitialHistoryPolicy, HeatBalanceState,
    HeatBalanceSurfaceFirstSampleTrace, HeatBalanceSurfaceIterationFirstSampleTrace,
    HeatBalanceSurfaceIterationSampleTrace, HeatBalanceSurfaceLoopZoneAirCorrection,
    HeatBalanceWarmupDayEndZoneAirStateSample, HeatBalanceZoneAirFirstSampleTrace,
    HeatBalanceZoneAirReportSampling, HeatBalanceZoneAirStateSample,
    HeatBalanceZoneConductionReportSource,
};
/// Summary of the executed heat-balance warmup loop.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct HeatBalanceWarmupSummary {
    /// Whether warmup was requested.
    pub enabled: bool,
    /// Minimum repeated warmup days requested by the Building object or diagnostic override.
    pub minimum_days: u32,
    /// Maximum repeated warmup days requested by the Building object after minimum-day clamping.
    pub maximum_days: u32,
    /// Zone end-state temperature convergence tolerance in delta C.
    pub temperature_convergence_tolerance_delta_c: f64,
    /// Zone load convergence tolerance in W from the Building object.
    pub loads_convergence_tolerance_w: f64,
    /// Number of warmup days actually executed.
    pub day_count: u32,
    /// Number of timesteps executed during warmup.
    pub timestep_count: usize,
    /// Number of weather hours repeated for one warmup day.
    pub hours_per_day: usize,
    /// Whether the repeated-day end state converged before max days.
    pub converged: bool,
    /// Final max delta between repeated-day zone air temperature extrema.
    pub final_max_zone_temperature_delta_c: f64,
}

impl HeatBalanceWarmupSummary {
    /// Creates a disabled warmup summary.
    #[must_use]
    pub const fn disabled() -> Self {
        Self {
            enabled: false,
            minimum_days: 0,
            maximum_days: 0,
            temperature_convergence_tolerance_delta_c: 0.0,
            loads_convergence_tolerance_w: 0.0,
            day_count: 0,
            timestep_count: 0,
            hours_per_day: 0,
            converged: false,
            final_max_zone_temperature_delta_c: 0.0,
        }
    }
}

/// Summary for the heat-balance zone-air diagnostic trace.
#[derive(Clone, Debug, PartialEq)]
pub struct HeatBalanceSimulationSummary {
    /// Hourly output sample count.
    pub samples: usize,
    /// Number of executed zone timesteps.
    pub timestep_count: usize,
    /// Number of reported run-period zone timesteps.
    pub run_period_timestep_count: usize,
    /// Shared time-axis source used by weather, schedules, outputs, and reports.
    pub time_axis_source: &'static str,
    /// Number of zone timesteps in each weather/output hour.
    pub zone_timesteps_per_hour: u32,
    /// Zone timestep duration in seconds.
    pub zone_timestep_seconds: f64,
    /// Nominal system timestep duration before adaptive shortening.
    pub system_timestep_nominal_seconds: f64,
    /// Explicit placeholder for later variable system timestep support.
    pub variable_system_timestep_support: &'static str,
    /// Whether `ShortenTimeStepSys` is represented in runtime state.
    pub shorten_timestep_sys_state: bool,
    /// Whether `UseZoneTimeStepHistory` is represented in runtime state.
    pub use_zone_timestep_history_state: bool,
    /// Runtime HVAC iteration count state.
    pub hvac_iteration_count: u32,
    /// Runtime plant iteration count state.
    pub plant_iteration_count: u32,
    /// Warmup samples included in the reported output sample axis.
    pub warmup_reported_samples: usize,
    /// Run-period samples included in the reported output sample axis.
    pub run_period_reported_samples: usize,
    /// Design-day samples included in the reported output sample axis.
    pub design_day_reported_samples: usize,
    /// Warmup execution summary.
    pub warmup: HeatBalanceWarmupSummary,
    /// Number of zones represented in the state.
    pub zone_count: usize,
    /// Number of surfaces represented in the state.
    pub surface_count: usize,
    /// Construction coefficient cache hash used for this simulation.
    pub construction_cache_hash: u64,
    /// Construction coefficient cache build time in seconds.
    pub construction_cache_build_wall_seconds: f64,
    /// Number of construction cache entries.
    pub construction_cache_entry_count: usize,
    /// Number of no-mass construction cache entries.
    pub construction_cache_no_mass_count: usize,
    /// Number of massive CTF construction cache entries.
    pub construction_cache_massive_ctf_count: usize,
    /// Number of construction cache entries seeded from EnergyPlus EIO CTF rows.
    pub construction_cache_eio_seeded_count: usize,
    /// Number of construction cache entries generated by Rust steady fallback.
    pub construction_cache_rust_generated_count: usize,
    /// Number of surface-balance passes used per zone timestep.
    pub surface_iteration_count: u32,
    /// Optional frozen inside-convection coefficient re-evaluation interval.
    pub inside_hconv_reevaluation_interval: Option<u32>,
    /// Initial CTF temperature/flux history seeding policy.
    pub ctf_initial_history_policy: HeatBalanceCtfInitialHistoryPolicy,
    /// Source used for zone opaque conduction report variables.
    pub zone_conduction_report_source: HeatBalanceZoneConductionReportSource,
    /// Sampling mode used for zone air heat-balance report variables.
    pub zone_air_report_sampling: HeatBalanceZoneAirReportSampling,
    /// Timing for zone-air correction during interleaved surface-balance probes.
    pub surface_loop_zone_air_correction: HeatBalanceSurfaceLoopZoneAirCorrection,
    /// Per-zone zone-air state after warmup and before the run period starts.
    pub run_period_initial_zone_air_states: Vec<HeatBalanceZoneAirStateSample>,
    /// Per-zone day-end state captured during run-period warmup.
    pub warmup_day_end_zone_air_states: Vec<HeatBalanceWarmupDayEndZoneAirStateSample>,
    /// Per-slot CTF history terms after optional warmup, before the run period starts.
    pub run_period_initial_ctf_history_slots: Vec<HeatBalanceCtfHistorySlotSample>,
    /// Per-slot CTF history terms averaged over the first reported hourly sample.
    pub first_sample_ctf_history_slots: Vec<HeatBalanceCtfHistorySlotFirstSample>,
    /// Per-slot CTF history terms averaged for each reported hourly sample before history advance.
    pub hourly_ctf_history_slots: Vec<HeatBalanceCtfHistorySlotHourlySample>,
    /// Per-slot CTF history terms averaged for each reported hourly sample after history advance.
    pub hourly_ctf_history_slots_after_advance: Vec<HeatBalanceCtfHistorySlotHourlySample>,
    /// Per-surface timestep states captured across the first reported hourly sample.
    pub surface_first_sample_trace: Vec<HeatBalanceSurfaceFirstSampleTrace>,
    /// Per-zone timestep states captured across the first reported hourly sample.
    pub zone_air_first_sample_trace: Vec<HeatBalanceZoneAirFirstSampleTrace>,
    /// Per-timestep inside-surface iteration summary for the first reported hourly sample.
    pub surface_iteration_first_sample_trace: Vec<HeatBalanceSurfaceIterationFirstSampleTrace>,
    /// Per-timestep inside-surface iteration summary for every reported hourly sample.
    pub surface_iteration_sample_trace: Vec<HeatBalanceSurfaceIterationSampleTrace>,
}

/// Result of the heat-balance zone-air diagnostic trace.
#[derive(Clone, Debug, PartialEq)]
pub struct HeatBalanceSimulation {
    /// Final heat-balance state.
    pub state: HeatBalanceState,
    /// Native output results.
    pub results: ResultStore,
    /// Trace summary.
    pub summary: HeatBalanceSimulationSummary,
}
