//! HeatBalanceSurfaceManager source-order stage contract.

use crate::RuntimeError;
use crate::execution_plan::{EnergyPlusCompatibilityStage, ExecutionStageKind};
use crate::heat_balance::ctf::ConstructionCtfCoefficientOverride;
use ep_model::{
    Construction, ConstructionId, Material, MaterialId, MaterialSurfaceRoughness, Surface,
    TypedModel,
};
use std::collections::BTreeMap;
use std::hash::{Hash, Hasher};
use std::time::Instant;

const SOURCE_FILE: &str = "src/EnergyPlus/HeatBalanceSurfaceManager.cc";
const DEFAULT_MATERIAL_THERMAL_ABSORPTANCE: f64 = 0.9;
const DEFAULT_MATERIAL_SOLAR_ABSORPTANCE: f64 = 0.7;

/// Source of CTF coefficients held by one construction thermal cache entry.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ConstructionCtfCoefficientSource {
    /// Coefficients were generated by the Rust steady no-mass fallback.
    RustGeneratedSteady,
    /// Coefficients were seeded from EnergyPlus EIO rows.
    EnergyPlusEioSeeded,
}

impl ConstructionCtfCoefficientSource {
    /// Stable identifier used in reports.
    #[must_use]
    pub const fn id(self) -> &'static str {
        match self {
            Self::RustGeneratedSteady => "rust-generated-steady",
            Self::EnergyPlusEioSeeded => "energyplus-eio-seeded",
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub(crate) struct ConstructionThermalData {
    pub(crate) cache_index: usize,
    pub(crate) construction_id: ConstructionId,
    pub(crate) construction_name: String,
    pub(crate) material_layer_stack: Vec<MaterialId>,
    pub(crate) outside_layer_material_id: MaterialId,
    pub(crate) outside_layer_material_name: String,
    pub(crate) outside_layer_roughness: MaterialSurfaceRoughness,
    pub(crate) thermal_resistance_m2_k_per_w: f64,
    pub(crate) heat_capacity_j_per_m2_k: Option<f64>,
    pub(crate) thermal_absorptance: f64,
    pub(crate) inside_thermal_absorptance: f64,
    pub(crate) solar_absorptance: f64,
    pub(crate) ctf_coefficient_source: ConstructionCtfCoefficientSource,
    pub(crate) ctf_coefficients: Vec<ConstructionCtfCoefficientOverride>,
}

#[derive(Clone, Debug, PartialEq)]
pub(crate) struct ConstructionThermalDataCache {
    entries: Vec<ConstructionThermalData>,
    pub(crate) no_mass_construction_ids: Vec<ConstructionId>,
    pub(crate) massive_ctf_construction_ids: Vec<ConstructionId>,
    pub(crate) coefficient_cache_hash: u64,
    pub(crate) build_wall_seconds: f64,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct ConstructionCacheInvalidationToken {
    pub(crate) coefficient_cache_hash: u64,
}

impl ConstructionCacheInvalidationToken {
    pub(crate) const fn from_coefficient_cache_hash(coefficient_cache_hash: u64) -> Self {
        Self {
            coefficient_cache_hash,
        }
    }
}

impl ConstructionThermalDataCache {
    pub(crate) fn build(
        model: &TypedModel,
        ctf_coefficients_by_construction: &BTreeMap<
            String,
            Vec<&ConstructionCtfCoefficientOverride>,
        >,
    ) -> Result<Self, RuntimeError> {
        let build_start = Instant::now();
        let mut entries = Vec::with_capacity(model.constructions.len());
        let mut no_mass_construction_ids = Vec::new();
        let mut massive_ctf_construction_ids = Vec::new();

        for construction in &model.constructions {
            let entry = construction_thermal_data(
                model,
                construction,
                entries.len(),
                ctf_coefficients_by_construction,
            )?;
            if entry.heat_capacity_j_per_m2_k.is_some() {
                massive_ctf_construction_ids.push(entry.construction_id);
            } else {
                no_mass_construction_ids.push(entry.construction_id);
            }
            entries.push(entry);
        }

        let coefficient_cache_hash = construction_cache_hash(&entries);
        Ok(Self {
            entries,
            no_mass_construction_ids,
            massive_ctf_construction_ids,
            coefficient_cache_hash,
            build_wall_seconds: build_start.elapsed().as_secs_f64(),
        })
    }

    pub(crate) fn len(&self) -> usize {
        self.entries.len()
    }

    pub(crate) fn invalidation_token(&self) -> ConstructionCacheInvalidationToken {
        ConstructionCacheInvalidationToken::from_coefficient_cache_hash(self.coefficient_cache_hash)
    }

    pub(crate) fn is_invalidated_by(&self, token: ConstructionCacheInvalidationToken) -> bool {
        self.coefficient_cache_hash != token.coefficient_cache_hash
    }

    pub(crate) fn eio_seeded_count(&self) -> usize {
        self.entries
            .iter()
            .filter(|entry| {
                entry.ctf_coefficient_source
                    == ConstructionCtfCoefficientSource::EnergyPlusEioSeeded
            })
            .count()
    }

    pub(crate) fn rust_generated_count(&self) -> usize {
        self.entries.len() - self.eio_seeded_count()
    }

    pub(crate) fn data_for_surface(
        &self,
        surface: &Surface,
    ) -> Result<&ConstructionThermalData, RuntimeError> {
        self.entries
            .iter()
            .find(|entry| entry.construction_id == surface.construction)
            .ok_or_else(|| RuntimeError::MissingConstruction {
                surface_name: surface.name.0.clone(),
            })
    }
}

pub(crate) fn surface_thermal_properties(
    model: &TypedModel,
    surface: &Surface,
) -> Result<ConstructionThermalData, RuntimeError> {
    let cache = ConstructionThermalDataCache::build(model, &BTreeMap::new())?;
    Ok(cache.data_for_surface(surface)?.clone())
}

fn construction_thermal_data(
    model: &TypedModel,
    construction: &Construction,
    cache_index: usize,
    ctf_coefficients_by_construction: &BTreeMap<String, Vec<&ConstructionCtfCoefficientOverride>>,
) -> Result<ConstructionThermalData, RuntimeError> {
    let layer_ids = construction_layer_stack(construction);
    let layer_materials = layer_materials(model, construction, &layer_ids)?;
    let outside_material =
        layer_materials
            .first()
            .ok_or_else(|| RuntimeError::MissingMaterial {
                construction_name: construction.name.0.clone(),
            })?;
    let inside_material = layer_materials
        .last()
        .ok_or_else(|| RuntimeError::MissingMaterial {
            construction_name: construction.name.0.clone(),
        })?;
    let thermal_resistance_m2_k_per_w =
        material_thermal_resistance_sum(&layer_materials, construction)?;
    let heat_capacity_j_per_m2_k = material_heat_capacity_per_area_sum(&layer_materials);
    let ctf_coefficients = ctf_coefficients_by_construction
        .get(&construction.name.0)
        .map(|rows| rows.iter().copied().cloned().collect::<Vec<_>>())
        .unwrap_or_default();
    let ctf_coefficient_source = if ctf_coefficients.is_empty() {
        ConstructionCtfCoefficientSource::RustGeneratedSteady
    } else {
        ConstructionCtfCoefficientSource::EnergyPlusEioSeeded
    };

    Ok(ConstructionThermalData {
        cache_index,
        construction_id: construction.id,
        construction_name: construction.name.0.clone(),
        material_layer_stack: layer_ids,
        outside_layer_material_id: outside_material.id,
        outside_layer_material_name: outside_material.name.0.clone(),
        outside_layer_roughness: outside_material
            .roughness
            .unwrap_or(MaterialSurfaceRoughness::MediumRough),
        thermal_resistance_m2_k_per_w,
        heat_capacity_j_per_m2_k,
        thermal_absorptance: outside_material
            .thermal_absorptance
            .unwrap_or(DEFAULT_MATERIAL_THERMAL_ABSORPTANCE),
        inside_thermal_absorptance: inside_material
            .thermal_absorptance
            .unwrap_or(DEFAULT_MATERIAL_THERMAL_ABSORPTANCE),
        solar_absorptance: outside_material
            .solar_absorptance
            .unwrap_or(DEFAULT_MATERIAL_SOLAR_ABSORPTANCE),
        ctf_coefficient_source,
        ctf_coefficients,
    })
}

fn construction_layer_stack(construction: &Construction) -> Vec<MaterialId> {
    if construction.layers.is_empty() {
        vec![construction.outside_layer]
    } else {
        construction.layers.clone()
    }
}

fn layer_materials<'a>(
    model: &'a TypedModel,
    construction: &Construction,
    layer_ids: &[MaterialId],
) -> Result<Vec<&'a Material>, RuntimeError> {
    let mut layer_materials = Vec::with_capacity(layer_ids.len());
    for layer_id in layer_ids {
        let material = model
            .materials
            .iter()
            .find(|material| material.id == *layer_id)
            .ok_or_else(|| RuntimeError::MissingMaterial {
                construction_name: construction.name.0.clone(),
            })?;
        layer_materials.push(material);
    }
    Ok(layer_materials)
}

fn material_thermal_resistance_sum(
    layer_materials: &[&Material],
    construction: &Construction,
) -> Result<f64, RuntimeError> {
    let mut thermal_resistance_m2_k_per_w = 0.0;
    for material in layer_materials {
        thermal_resistance_m2_k_per_w += material.thermal_resistance().ok_or_else(|| {
            RuntimeError::MissingThermalResistance {
                material_name: material.name.0.clone(),
            }
        })?;
    }
    if thermal_resistance_m2_k_per_w > 0.0 {
        Ok(thermal_resistance_m2_k_per_w)
    } else {
        Err(RuntimeError::MissingThermalResistance {
            material_name: construction.name.0.clone(),
        })
    }
}

fn material_heat_capacity_per_area_sum(layer_materials: &[&Material]) -> Option<f64> {
    let heat_capacity_j_per_m2_k = layer_materials
        .iter()
        .filter_map(|material| material.heat_capacity_per_area())
        .sum::<f64>();
    if heat_capacity_j_per_m2_k > 0.0 {
        Some(heat_capacity_j_per_m2_k)
    } else {
        None
    }
}

fn construction_cache_hash(entries: &[ConstructionThermalData]) -> u64 {
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    for entry in entries {
        entry.construction_id.hash(&mut hasher);
        entry.material_layer_stack.hash(&mut hasher);
        entry
            .thermal_resistance_m2_k_per_w
            .to_bits()
            .hash(&mut hasher);
        entry
            .heat_capacity_j_per_m2_k
            .map(f64::to_bits)
            .hash(&mut hasher);
        entry.ctf_coefficient_source.id().hash(&mut hasher);
        for coefficient in &entry.ctf_coefficients {
            coefficient.time_index.hash(&mut hasher);
            coefficient.outside_w_per_m2_k.to_bits().hash(&mut hasher);
            coefficient.cross_w_per_m2_k.to_bits().hash(&mut hasher);
            coefficient.inside_w_per_m2_k.to_bits().hash(&mut hasher);
            coefficient.flux.map(f64::to_bits).hash(&mut hasher);
        }
    }
    hasher.finish()
}

const fn stage(
    kind: ExecutionStageKind,
    stage_name: &'static str,
    source_routine: &'static str,
) -> EnergyPlusCompatibilityStage {
    EnergyPlusCompatibilityStage {
        kind,
        stage_name,
        source_file: SOURCE_FILE,
        source_routine,
    }
}

/// EnergyPlus `HeatBalanceSurfaceManager::ManageSurfaceHeatBalance`.
#[must_use]
pub const fn manage_surface_heat_balance_stage() -> EnergyPlusCompatibilityStage {
    stage(
        ExecutionStageKind::ManageSurfaceHeatBalance,
        "manage-surface-heat-balance",
        "ManageSurfaceHeatBalance",
    )
}

/// EnergyPlus `HeatBalanceSurfaceManager::ManageSurfaceHeatBalance` source-order wrapper.
pub(crate) fn manage_surface_heat_balance_source_order_path<T>(execute: impl FnOnce() -> T) -> T {
    execute()
}

/// EnergyPlus `HeatBalanceSurfaceManager::InitSurfaceHeatBalance`.
#[must_use]
pub const fn init_surface_heat_balance_stage() -> EnergyPlusCompatibilityStage {
    stage(
        ExecutionStageKind::InitSurfaceHeatBalance,
        "init-surface-heat-balance",
        "InitSurfaceHeatBalance",
    )
}

/// EnergyPlus `HeatBalanceSurfaceManager::InitSurfaceHeatBalance` source-order wrapper.
pub(crate) fn init_surface_heat_balance_source_order_path<T>(execute: impl FnOnce() -> T) -> T {
    execute()
}

/// EnergyPlus `HeatBalanceSurfaceManager::CalcHeatBalanceOutsideSurf`.
#[must_use]
pub const fn calc_heat_balance_outside_surf_stage() -> EnergyPlusCompatibilityStage {
    stage(
        ExecutionStageKind::CalcHeatBalanceOutsideSurf,
        "calc-heat-balance-outside-surf",
        "CalcHeatBalanceOutsideSurf",
    )
}

/// EnergyPlus `HeatBalanceSurfaceManager::CalcHeatBalanceOutsideSurf` source-order wrapper.
pub(crate) fn calc_heat_balance_outside_surf_source_order_path<T>(
    execute: impl FnOnce() -> T,
) -> T {
    execute()
}

/// EnergyPlus `HeatBalanceSurfaceManager::CalcHeatBalanceInsideSurf`.
#[must_use]
pub const fn calc_heat_balance_inside_surf_stage() -> EnergyPlusCompatibilityStage {
    stage(
        ExecutionStageKind::CalcHeatBalanceInsideSurf,
        "calc-heat-balance-inside-surf",
        "CalcHeatBalanceInsideSurf",
    )
}

/// EnergyPlus `HeatBalanceSurfaceManager::CalcHeatBalanceInsideSurf` source-order wrapper.
pub(crate) fn calc_heat_balance_inside_surf_source_order_path<T>(execute: impl FnOnce() -> T) -> T {
    execute()
}

/// EnergyPlus `HeatBalanceSurfaceManager::UpdateFinalSurfaceHeatBalance`.
#[must_use]
pub const fn update_final_surface_heat_balance_stage() -> EnergyPlusCompatibilityStage {
    stage(
        ExecutionStageKind::UpdateFinalSurfaceHeatBalance,
        "update-final-surface-heat-balance",
        "UpdateFinalSurfaceHeatBalance",
    )
}

/// EnergyPlus `HeatBalanceSurfaceManager::UpdateFinalSurfaceHeatBalance` source-order wrapper.
pub(crate) fn update_final_surface_heat_balance_source_order_path<T>(
    execute: impl FnOnce() -> T,
) -> T {
    execute()
}

/// EnergyPlus `HeatBalanceSurfaceManager::UpdateThermalHistories`.
#[must_use]
pub const fn update_thermal_histories_stage() -> EnergyPlusCompatibilityStage {
    stage(
        ExecutionStageKind::UpdateThermalHistories,
        "update-thermal-histories",
        "UpdateThermalHistories",
    )
}

/// EnergyPlus `HeatBalanceSurfaceManager::UpdateThermalHistories` source-order wrapper.
pub(crate) fn update_thermal_histories_source_order_path<T>(execute: impl FnOnce() -> T) -> T {
    execute()
}

/// EnergyPlus `HeatBalanceSurfaceManager::ReportSurfaceHeatBalance`.
#[must_use]
pub const fn report_surface_heat_balance_stage() -> EnergyPlusCompatibilityStage {
    stage(
        ExecutionStageKind::ReportSurfaceHeatBalance,
        "report-surface-heat-balance",
        "ReportSurfaceHeatBalance",
    )
}

/// EnergyPlus `HeatBalanceSurfaceManager::ReportSurfaceHeatBalance` source-order wrapper.
pub(crate) fn report_surface_heat_balance_source_order_path<T>(execute: impl FnOnce() -> T) -> T {
    execute()
}
