//! Lossless JSON serialization for one CP405 latent-output maximum assignment snapshot.

use ep_model::DehumidificationControlType;
use ep_runtime::PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationControlConstantSupplyHumidityRatioLatentOutputMaximumCapacityAssignmentSnapshot;
use serde_json::{Value, json};

pub(super) fn snapshot_json(
    snapshot: PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationControlConstantSupplyHumidityRatioLatentOutputMaximumCapacityAssignmentSnapshot,
) -> Value {
    json!({
        "source": snapshot.source,
        "first_excluded_source": snapshot.first_excluded_source,
        "source_order": snapshot.source_order,
        "system": snapshot.system.0,
        "parent_call_ordinal": snapshot.parent_call_ordinal,
        "controlled_zone": snapshot.controlled_zone.0,
        "unit_off_skipped": snapshot.unit_off_skipped,
        "non_cooling_skipped": snapshot.non_cooling_skipped,
        "positive_guard_false_fallthrough_skipped": snapshot.positive_guard_false_fallthrough_skipped,
        "heating_availability_guard_false_fallthrough": snapshot.heating_availability_guard_false_fallthrough,
        "humidification_control_guard_false_fallthrough": snapshot.humidification_control_guard_false_fallthrough,
        "dehumidification_control_humidistat_maximum_assignment_executed": snapshot.dehumidification_control_humidistat_maximum_assignment_executed,
        "dehumidification_control_none_maximum_assignment_executed": snapshot.dehumidification_control_none_maximum_assignment_executed,
        "dehumidification_control_guard_false_fallthrough": snapshot.dehumidification_control_guard_false_fallthrough,
        "predecessor_capacity_limit_guard_evaluated": snapshot.predecessor_capacity_limit_guard_evaluated,
        "predecessor_capacity_limit_body_entered": snapshot.predecessor_capacity_limit_body_entered,
        "predecessor_active_capacity_limit_guard_false_fallthrough": snapshot.predecessor_active_capacity_limit_guard_false_fallthrough,
        "predecessor_dehumidification_guard_evaluated": snapshot.predecessor_dehumidification_guard_evaluated,
        "predecessor_dehumidification_body_entered": snapshot.predecessor_dehumidification_body_entered,
        "predecessor_dehumidification_guard_false_fallthrough": snapshot.predecessor_dehumidification_guard_false_fallthrough,
        "predecessor_dehumidification_total_output_assignment_executed": snapshot.predecessor_dehumidification_total_output_assignment_executed,
        "predecessor_dehumidification_total_output_capacity_guard_evaluated": snapshot.predecessor_dehumidification_total_output_capacity_guard_evaluated,
        "predecessor_dehumidification_total_output_capacity_adjustment_body_entered": snapshot.predecessor_dehumidification_total_output_capacity_adjustment_body_entered,
        "predecessor_dehumidification_total_output_capacity_guard_false_fallthrough": snapshot.predecessor_dehumidification_total_output_capacity_guard_false_fallthrough,
        "dehumidification_total_output_capacity_guard_false_fallthrough": snapshot.dehumidification_total_output_capacity_guard_false_fallthrough,
        "dehumidification_total_output_maximum_capacity_assignment_executed": snapshot.dehumidification_total_output_maximum_capacity_assignment_executed,
        "predecessor_supply_enthalpy_assignment_executed": snapshot.predecessor_supply_enthalpy_assignment_executed,
        "predecessor_dehumidification_control_type_read": snapshot.predecessor_dehumidification_control_type_read,
        "predecessor_dehumidification_control_type": snapshot.predecessor_dehumidification_control_type.map(control_type_name),
        "predecessor_dehumidification_control_switch_dispatched": snapshot.predecessor_dehumidification_control_switch_dispatched,
        "predecessor_dehumidification_control_constant_sensible_heat_ratio_case_entered": snapshot.predecessor_dehumidification_control_constant_sensible_heat_ratio_case_entered,
        "predecessor_dehumidification_control_constant_sensible_heat_ratio_case_exited_via_break": snapshot.predecessor_dehumidification_control_constant_sensible_heat_ratio_case_exited_via_break,
        "predecessor_dehumidification_control_humidistat_case_entered": snapshot.predecessor_dehumidification_control_humidistat_case_entered,
        "predecessor_dehumidification_control_humidistat_supply_humidity_ratio_assignment_executed": snapshot.predecessor_dehumidification_control_humidistat_supply_humidity_ratio_assignment_executed,
        "predecessor_dehumidification_control_humidistat_case_exited_via_break": snapshot.predecessor_dehumidification_control_humidistat_case_exited_via_break,
        "predecessor_cp397_resulting_supply_humidity_ratio": json_number(snapshot.predecessor_cp397_resulting_supply_humidity_ratio),
        "predecessor_cp397_resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp397_resulting_supply_humidity_ratio),
        "predecessor_cp397_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp397_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp397_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp397_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp397_resulting_supply_temperature_c": json_number(snapshot.predecessor_cp397_resulting_supply_temperature_c),
        "predecessor_cp397_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp397_resulting_supply_temperature_c),
        "predecessor_dehumidification_control_none_case_entered": snapshot.predecessor_dehumidification_control_none_case_entered,
        "predecessor_cp398_resulting_supply_humidity_ratio": json_number(snapshot.predecessor_cp398_resulting_supply_humidity_ratio),
        "predecessor_cp398_resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp398_resulting_supply_humidity_ratio),
        "predecessor_cp398_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp398_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp398_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp398_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp398_resulting_supply_temperature_c": json_number(snapshot.predecessor_cp398_resulting_supply_temperature_c),
        "predecessor_cp398_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp398_resulting_supply_temperature_c),
        "predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_shared_case_entered": snapshot.predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_shared_case_entered,
        "predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_cp_air_assignment_executed": snapshot.predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_cp_air_assignment_executed,
        "predecessor_mixed_air_humidity_ratio_read": snapshot.predecessor_mixed_air_humidity_ratio_read,
        "predecessor_mixed_air_humidity_ratio": json_number(snapshot.predecessor_mixed_air_humidity_ratio),
        "predecessor_mixed_air_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_mixed_air_humidity_ratio),
        "predecessor_psychrometric_cp_air_evaluated": snapshot.predecessor_psychrometric_cp_air_evaluated,
        "predecessor_psychrometric_cp_air_result_j_per_kg_k": json_number(snapshot.predecessor_psychrometric_cp_air_result_j_per_kg_k),
        "predecessor_psychrometric_cp_air_result_j_per_kg_k_ieee_bits": ieee_bits(snapshot.predecessor_psychrometric_cp_air_result_j_per_kg_k),
        "predecessor_cp_air_assigned": snapshot.predecessor_cp_air_assigned,
        "predecessor_cp_air_j_per_kg_k": json_number(snapshot.predecessor_cp_air_j_per_kg_k),
        "predecessor_cp_air_j_per_kg_k_ieee_bits": ieee_bits(snapshot.predecessor_cp_air_j_per_kg_k),
        "predecessor_cp399_resulting_supply_humidity_ratio": json_number(snapshot.predecessor_cp399_resulting_supply_humidity_ratio),
        "predecessor_cp399_resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp399_resulting_supply_humidity_ratio),
        "predecessor_cp399_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp399_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp399_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp399_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp399_resulting_supply_temperature_c": json_number(snapshot.predecessor_cp399_resulting_supply_temperature_c),
        "predecessor_cp399_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp399_resulting_supply_temperature_c),
        "predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_sensible_output_assignment_executed": snapshot.predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_sensible_output_assignment_executed,
        "predecessor_cp399_retained_supply_humidity_ratio_state_owned": snapshot.predecessor_cp399_retained_supply_humidity_ratio_state_owned,
        "predecessor_cp399_retained_supply_enthalpy_state_owned": snapshot.predecessor_cp399_retained_supply_enthalpy_state_owned,
        "predecessor_cp399_retained_supply_temperature_state_owned": snapshot.predecessor_cp399_retained_supply_temperature_state_owned,
        "predecessor_cp330_retained_supply_mass_flow_rate_owned_read": snapshot.predecessor_cp330_retained_supply_mass_flow_rate_owned_read,
        "predecessor_cp329_supply_mass_flow_rate_bit_corroborated": snapshot.predecessor_cp329_supply_mass_flow_rate_bit_corroborated,
        "predecessor_supply_mass_flow_rate_read": snapshot.predecessor_supply_mass_flow_rate_read,
        "predecessor_supply_mass_flow_rate_kg_per_s": json_number(snapshot.predecessor_supply_mass_flow_rate_kg_per_s),
        "predecessor_supply_mass_flow_rate_kg_per_s_ieee_bits": ieee_bits(snapshot.predecessor_supply_mass_flow_rate_kg_per_s),
        "predecessor_cp399_retained_cp_air_owned_read": snapshot.predecessor_cp399_retained_cp_air_owned_read,
        "predecessor_cp_air_read": snapshot.predecessor_cp_air_read,
        "predecessor_cp400_cp_air_j_per_kg_k": json_number(snapshot.predecessor_cp400_cp_air_j_per_kg_k),
        "predecessor_cp400_cp_air_j_per_kg_k_ieee_bits": ieee_bits(snapshot.predecessor_cp400_cp_air_j_per_kg_k),
        "predecessor_supply_mass_flow_rate_times_cp_air_calculated": snapshot.predecessor_supply_mass_flow_rate_times_cp_air_calculated,
        "predecessor_supply_mass_flow_rate_times_cp_air_w_per_k": json_number(snapshot.predecessor_supply_mass_flow_rate_times_cp_air_w_per_k),
        "predecessor_supply_mass_flow_rate_times_cp_air_w_per_k_ieee_bits": ieee_bits(snapshot.predecessor_supply_mass_flow_rate_times_cp_air_w_per_k),
        "predecessor_cp329_retained_mixed_air_temperature_owned_read": snapshot.predecessor_cp329_retained_mixed_air_temperature_owned_read,
        "predecessor_mixed_air_temperature_read": snapshot.predecessor_mixed_air_temperature_read,
        "predecessor_mixed_air_temperature_c": json_number(snapshot.predecessor_mixed_air_temperature_c),
        "predecessor_mixed_air_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_mixed_air_temperature_c),
        "predecessor_cp399_retained_supply_temperature_owned_read": snapshot.predecessor_cp399_retained_supply_temperature_owned_read,
        "predecessor_supply_temperature_read": snapshot.predecessor_supply_temperature_read,
        "predecessor_supply_temperature_c": json_number(snapshot.predecessor_supply_temperature_c),
        "predecessor_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_supply_temperature_c),
        "predecessor_mixed_air_minus_supply_temperature_calculated": snapshot.predecessor_mixed_air_minus_supply_temperature_calculated,
        "predecessor_mixed_air_minus_supply_temperature_k": json_number(snapshot.predecessor_mixed_air_minus_supply_temperature_k),
        "predecessor_mixed_air_minus_supply_temperature_k_ieee_bits": ieee_bits(snapshot.predecessor_mixed_air_minus_supply_temperature_k),
        "predecessor_cooling_sensible_output_calculated": snapshot.predecessor_cooling_sensible_output_calculated,
        "predecessor_calculated_cooling_sensible_output_w": json_number(snapshot.predecessor_calculated_cooling_sensible_output_w),
        "predecessor_calculated_cooling_sensible_output_w_ieee_bits": ieee_bits(snapshot.predecessor_calculated_cooling_sensible_output_w),
        "predecessor_cooling_sensible_output_assigned": snapshot.predecessor_cooling_sensible_output_assigned,
        "predecessor_cooling_sensible_output_w": json_number(snapshot.predecessor_cooling_sensible_output_w),
        "predecessor_cooling_sensible_output_w_ieee_bits": ieee_bits(snapshot.predecessor_cooling_sensible_output_w),
        "predecessor_cp400_resulting_supply_humidity_ratio": json_number(snapshot.predecessor_cp400_resulting_supply_humidity_ratio),
        "predecessor_cp400_resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp400_resulting_supply_humidity_ratio),
        "predecessor_cp400_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp400_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp400_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp400_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp400_resulting_supply_temperature_c": json_number(snapshot.predecessor_cp400_resulting_supply_temperature_c),
        "predecessor_cp400_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp400_resulting_supply_temperature_c),
        "predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_assignment_executed": snapshot.predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_assignment_executed,
        "predecessor_cp400_retained_supply_humidity_ratio_state_owned": snapshot.predecessor_cp400_retained_supply_humidity_ratio_state_owned,
        "predecessor_cp400_retained_supply_enthalpy_state_owned": snapshot.predecessor_cp400_retained_supply_enthalpy_state_owned,
        "predecessor_cp400_retained_supply_temperature_state_owned": snapshot.predecessor_cp400_retained_supply_temperature_state_owned,
        "predecessor_cp384_retained_cooling_total_output_owned_read": snapshot.predecessor_cp384_retained_cooling_total_output_owned_read,
        "predecessor_cp385_cooling_total_output_bit_corroborated": snapshot.predecessor_cp385_cooling_total_output_bit_corroborated,
        "predecessor_cooling_total_output_read": snapshot.predecessor_cooling_total_output_read,
        "predecessor_cooling_total_output_w": json_number(snapshot.predecessor_cooling_total_output_w),
        "predecessor_cooling_total_output_w_ieee_bits": ieee_bits(snapshot.predecessor_cooling_total_output_w),
        "predecessor_cp400_retained_cooling_sensible_output_owned_read": snapshot.predecessor_cp400_retained_cooling_sensible_output_owned_read,
        "predecessor_cp401_cooling_sensible_output_read": snapshot.predecessor_cp401_cooling_sensible_output_read,
        "predecessor_cp401_cooling_sensible_output_w": json_number(snapshot.predecessor_cp401_cooling_sensible_output_w),
        "predecessor_cp401_cooling_sensible_output_w_ieee_bits": ieee_bits(snapshot.predecessor_cp401_cooling_sensible_output_w),
        "predecessor_cooling_latent_output_calculated": snapshot.predecessor_cooling_latent_output_calculated,
        "predecessor_calculated_cooling_latent_output_w": json_number(snapshot.predecessor_calculated_cooling_latent_output_w),
        "predecessor_calculated_cooling_latent_output_w_ieee_bits": ieee_bits(snapshot.predecessor_calculated_cooling_latent_output_w),
        "predecessor_cooling_latent_output_assigned": snapshot.predecessor_cooling_latent_output_assigned,
        "predecessor_cooling_latent_output_w": json_number(snapshot.predecessor_cooling_latent_output_w),
        "predecessor_cooling_latent_output_w_ieee_bits": ieee_bits(snapshot.predecessor_cooling_latent_output_w),
        "predecessor_cp401_resulting_supply_humidity_ratio": json_number(snapshot.predecessor_cp401_resulting_supply_humidity_ratio),
        "predecessor_cp401_resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp401_resulting_supply_humidity_ratio),
        "predecessor_cp401_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp401_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp401_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp401_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp401_resulting_supply_temperature_c": json_number(snapshot.predecessor_cp401_resulting_supply_temperature_c),
        "predecessor_cp401_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp401_resulting_supply_temperature_c),
        "predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_capacity_guard_evaluated": snapshot.predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_capacity_guard_evaluated,
        "predecessor_cp401_retained_cooling_latent_output_owned_read": snapshot.predecessor_cp401_retained_cooling_latent_output_owned_read,
        "predecessor_cooling_latent_output_read": snapshot.predecessor_cooling_latent_output_read,
        "predecessor_cp402_cooling_latent_output_w": json_number(snapshot.predecessor_cp402_cooling_latent_output_w),
        "predecessor_cp402_cooling_latent_output_w_ieee_bits": ieee_bits(snapshot.predecessor_cp402_cooling_latent_output_w),
        "predecessor_cp321_maximum_total_cooling_capacity_owned_read": snapshot.predecessor_cp321_maximum_total_cooling_capacity_owned_read,
        "predecessor_cp340_same_call_maximum_total_cooling_capacity_bit_corroborated": snapshot.predecessor_cp340_same_call_maximum_total_cooling_capacity_bit_corroborated,
        "predecessor_maximum_total_cooling_capacity_read": snapshot.predecessor_maximum_total_cooling_capacity_read,
        "predecessor_maximum_total_cooling_capacity_w": json_number(snapshot.predecessor_maximum_total_cooling_capacity_w),
        "predecessor_maximum_total_cooling_capacity_w_ieee_bits": ieee_bits(snapshot.predecessor_maximum_total_cooling_capacity_w),
        "predecessor_cooling_latent_output_maximum_total_cooling_capacity_comparison_evaluated": snapshot.predecessor_cooling_latent_output_maximum_total_cooling_capacity_comparison_evaluated,
        "predecessor_cooling_latent_output_greater_than_or_equal_to_maximum_total_cooling_capacity": snapshot.predecessor_cooling_latent_output_greater_than_or_equal_to_maximum_total_cooling_capacity,
        "predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_capacity_adjustment_body_entered": snapshot.predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_capacity_adjustment_body_entered,
        "predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_capacity_guard_false_fallthrough": snapshot.predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_capacity_guard_false_fallthrough,
        "predecessor_cp401_retained_supply_humidity_ratio_state_owned": snapshot.predecessor_cp401_retained_supply_humidity_ratio_state_owned,
        "predecessor_cp401_retained_supply_enthalpy_state_owned": snapshot.predecessor_cp401_retained_supply_enthalpy_state_owned,
        "predecessor_cp401_retained_supply_temperature_state_owned": snapshot.predecessor_cp401_retained_supply_temperature_state_owned,
        "predecessor_cp402_resulting_supply_humidity_ratio": json_number(snapshot.predecessor_cp402_resulting_supply_humidity_ratio),
        "predecessor_cp402_resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp402_resulting_supply_humidity_ratio),
        "predecessor_cp402_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp402_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp402_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp402_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp402_resulting_supply_temperature_c": json_number(snapshot.predecessor_cp402_resulting_supply_temperature_c),
        "predecessor_cp402_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp402_resulting_supply_temperature_c),
        "predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_capacity_adjustment_supply_temperature_mixed_air_assignment_executed": snapshot.predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_capacity_adjustment_supply_temperature_mixed_air_assignment_executed,
        "predecessor_cp403_cp329_retained_mixed_air_temperature_owned_read": snapshot.predecessor_cp403_cp329_retained_mixed_air_temperature_owned_read,
        "predecessor_cp402_same_call_mixed_air_temperature_bit_corroborated": snapshot.predecessor_cp402_same_call_mixed_air_temperature_bit_corroborated,
        "predecessor_cp403_mixed_air_temperature_read": snapshot.predecessor_cp403_mixed_air_temperature_read,
        "predecessor_cp403_mixed_air_temperature_c": json_number(snapshot.predecessor_cp403_mixed_air_temperature_c),
        "predecessor_cp403_mixed_air_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp403_mixed_air_temperature_c),
        "predecessor_supply_temperature_assigned": snapshot.predecessor_supply_temperature_assigned,
        "predecessor_cp403_assigned_supply_temperature_c": json_number(snapshot.predecessor_cp403_assigned_supply_temperature_c),
        "predecessor_cp403_assigned_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp403_assigned_supply_temperature_c),
        "predecessor_cp402_retained_supply_humidity_ratio_state_owned": snapshot.predecessor_cp402_retained_supply_humidity_ratio_state_owned,
        "predecessor_cp402_retained_supply_enthalpy_state_owned": snapshot.predecessor_cp402_retained_supply_enthalpy_state_owned,
        "predecessor_cp402_retained_supply_temperature_state_owned": snapshot.predecessor_cp402_retained_supply_temperature_state_owned,
        "predecessor_cp403_resulting_supply_humidity_ratio": json_number(snapshot.predecessor_cp403_resulting_supply_humidity_ratio),
        "predecessor_cp403_resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp403_resulting_supply_humidity_ratio),
        "predecessor_cp403_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp403_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp403_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp403_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp403_resulting_supply_temperature_c": json_number(snapshot.predecessor_cp403_resulting_supply_temperature_c),
        "predecessor_cp403_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp403_resulting_supply_temperature_c),
        "predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_capacity_adjustment_supply_humidity_ratio_assignment_executed": snapshot.predecessor_dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_capacity_adjustment_supply_humidity_ratio_assignment_executed,
        "predecessor_cp403_retained_supply_humidity_ratio_state_owned": snapshot.predecessor_cp403_retained_supply_humidity_ratio_state_owned,
        "predecessor_cp403_retained_supply_temperature_state_owned": snapshot.predecessor_cp403_retained_supply_temperature_state_owned,
        "predecessor_cp403_retained_supply_enthalpy_state_owned": snapshot.predecessor_cp403_retained_supply_enthalpy_state_owned,
        "predecessor_cp404_cp403_retained_supply_temperature_owned_read": snapshot.predecessor_cp404_cp403_retained_supply_temperature_owned_read,
        "predecessor_supply_temperature_for_humidity_ratio_inversion_read": snapshot.predecessor_supply_temperature_for_humidity_ratio_inversion_read,
        "predecessor_cp404_supply_temperature_c": json_number(snapshot.predecessor_cp404_supply_temperature_c),
        "predecessor_cp404_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp404_supply_temperature_c),
        "predecessor_cp404_cp403_retained_supply_enthalpy_owned_read": snapshot.predecessor_cp404_cp403_retained_supply_enthalpy_owned_read,
        "predecessor_supply_enthalpy_for_humidity_ratio_inversion_read": snapshot.predecessor_supply_enthalpy_for_humidity_ratio_inversion_read,
        "predecessor_cp404_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp404_supply_enthalpy_j_per_kg),
        "predecessor_cp404_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp404_supply_enthalpy_j_per_kg),
        "predecessor_psychrometric_supply_humidity_ratio_evaluated": snapshot.predecessor_psychrometric_supply_humidity_ratio_evaluated,
        "predecessor_cp404_psychrometric_supply_humidity_ratio": json_number(snapshot.predecessor_cp404_psychrometric_supply_humidity_ratio),
        "predecessor_cp404_psychrometric_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp404_psychrometric_supply_humidity_ratio),
        "predecessor_supply_humidity_ratio_assignment_performed": snapshot.predecessor_supply_humidity_ratio_assignment_performed,
        "predecessor_cp404_assigned_supply_humidity_ratio": json_number(snapshot.predecessor_cp404_assigned_supply_humidity_ratio),
        "predecessor_cp404_assigned_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp404_assigned_supply_humidity_ratio),
        "predecessor_cp404_resulting_supply_humidity_ratio": json_number(snapshot.predecessor_cp404_resulting_supply_humidity_ratio),
        "predecessor_cp404_resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cp404_resulting_supply_humidity_ratio),
        "predecessor_cp404_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp404_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp404_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp404_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp404_resulting_supply_temperature_c": json_number(snapshot.predecessor_cp404_resulting_supply_temperature_c),
        "predecessor_cp404_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp404_resulting_supply_temperature_c),
        "dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_maximum_capacity_assignment_executed": snapshot.dehumidification_control_none_or_constant_supply_humidity_ratio_latent_output_maximum_capacity_assignment_executed,
        "cp404_retained_supply_humidity_ratio_state_owned": snapshot.cp404_retained_supply_humidity_ratio_state_owned,
        "cp404_retained_supply_temperature_state_owned": snapshot.cp404_retained_supply_temperature_state_owned,
        "cp404_retained_supply_enthalpy_state_owned": snapshot.cp404_retained_supply_enthalpy_state_owned,
        "preexisting_cooling_latent_output_w": json_number(snapshot.preexisting_cooling_latent_output_w),
        "preexisting_cooling_latent_output_w_ieee_bits": ieee_bits(snapshot.preexisting_cooling_latent_output_w),
        "cp404_retained_maximum_total_cooling_capacity_owned_read": snapshot.cp404_retained_maximum_total_cooling_capacity_owned_read,
        "maximum_total_cooling_capacity_read": snapshot.maximum_total_cooling_capacity_read,
        "maximum_total_cooling_capacity_w": json_number(snapshot.maximum_total_cooling_capacity_w),
        "maximum_total_cooling_capacity_w_ieee_bits": ieee_bits(snapshot.maximum_total_cooling_capacity_w),
        "cooling_latent_output_assigned": snapshot.cooling_latent_output_assigned,
        "assigned_cooling_latent_output_w": json_number(snapshot.assigned_cooling_latent_output_w),
        "assigned_cooling_latent_output_w_ieee_bits": ieee_bits(snapshot.assigned_cooling_latent_output_w),
        "resulting_cooling_latent_output_w": json_number(snapshot.resulting_cooling_latent_output_w),
        "resulting_cooling_latent_output_w_ieee_bits": ieee_bits(snapshot.resulting_cooling_latent_output_w),
        "resulting_supply_humidity_ratio": json_number(snapshot.resulting_supply_humidity_ratio),
        "resulting_supply_humidity_ratio_ieee_bits": ieee_bits(snapshot.resulting_supply_humidity_ratio),
        "resulting_supply_enthalpy_j_per_kg": json_number(snapshot.resulting_supply_enthalpy_j_per_kg),
        "resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.resulting_supply_enthalpy_j_per_kg),
        "resulting_supply_temperature_c": json_number(snapshot.resulting_supply_temperature_c),
        "resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.resulting_supply_temperature_c),
    })
}

fn control_type_name(control: DehumidificationControlType) -> &'static str {
    match control {
        DehumidificationControlType::None => "None",
        DehumidificationControlType::ConstantSensibleHeatRatio => "ConstantSensibleHeatRatio",
        DehumidificationControlType::Humidistat => "Humidistat",
        DehumidificationControlType::ConstantSupplyHumidityRatio => "ConstantSupplyHumidityRatio",
    }
}

fn json_number(value: Option<f64>) -> Value {
    value
        .filter(|value| value.is_finite())
        .map_or(Value::Null, |value| json!(value))
}

fn ieee_bits(value: Option<f64>) -> Option<String> {
    value.map(|value| format!("0x{:016x}", value.to_bits()))
}

#[cfg(test)]
mod tests;
