//! Persistent CP383 total-output capacity-guard state.

use ep_model::IdealLoadsAirSystemId;

use super::PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputGuardSnapshot;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(in crate::ideal_loads::calc) enum PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputGuardRetainedRoute
{
    UnitOff,
    NonCooling,
    PositiveGuardFalseFallthrough,
    HeatingAvailabilityGuardFalseFallthroughCapacityLimitGuardFalseFallthrough,
    HeatingAvailabilityGuardFalseFallthroughDehumidificationGuardFalseFallthrough,
    HeatingAvailabilityGuardFalseFallthroughDehumidificationTotalOutputCapacityGuardFalseFallthrough,
    HeatingAvailabilityGuardFalseFallthroughDehumidificationTotalOutputCapacityAdjustmentBodyEntered,
    HumidificationControlGuardFalseFallthroughCapacityLimitGuardFalseFallthrough,
    HumidificationControlGuardFalseFallthroughDehumidificationGuardFalseFallthrough,
    HumidificationControlGuardFalseFallthroughDehumidificationTotalOutputCapacityGuardFalseFallthrough,
    HumidificationControlGuardFalseFallthroughDehumidificationTotalOutputCapacityAdjustmentBodyEntered,
    DehumidificationControlHumidistatMaximumAssignmentExecutedCapacityLimitGuardFalseFallthrough,
    DehumidificationControlHumidistatMaximumAssignmentExecutedDehumidificationGuardFalseFallthrough,
    DehumidificationControlHumidistatMaximumAssignmentExecutedDehumidificationTotalOutputCapacityGuardFalseFallthrough,
    DehumidificationControlHumidistatMaximumAssignmentExecutedDehumidificationTotalOutputCapacityAdjustmentBodyEntered,
    DehumidificationControlNoneMaximumAssignmentExecutedCapacityLimitGuardFalseFallthrough,
    DehumidificationControlNoneMaximumAssignmentExecutedDehumidificationGuardFalseFallthrough,
    DehumidificationControlNoneMaximumAssignmentExecutedDehumidificationTotalOutputCapacityGuardFalseFallthrough,
    DehumidificationControlNoneMaximumAssignmentExecutedDehumidificationTotalOutputCapacityAdjustmentBodyEntered,
    DehumidificationControlGuardFalseFallthroughCapacityLimitGuardFalseFallthrough,
    DehumidificationControlGuardFalseFallthroughDehumidificationGuardFalseFallthrough,
    DehumidificationControlGuardFalseFallthroughDehumidificationTotalOutputCapacityGuardFalseFallthrough,
    DehumidificationControlGuardFalseFallthroughDehumidificationTotalOutputCapacityAdjustmentBodyEntered,
}

/// Persistent bounded state and exact source/lineage counters for one system.
#[allow(missing_docs)]
#[derive(Clone, Debug, PartialEq)]
pub struct PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputGuardRuntimeState
{
    pub system: IdealLoadsAirSystemId,
    pub transition_count: usize,
    pub unit_off_skip_count: usize,
    pub non_cooling_skip_count: usize,
    pub positive_guard_false_fallthrough_skip_count: usize,
    pub heating_availability_guard_false_fallthrough_count: usize,
    pub humidification_control_guard_false_fallthrough_count: usize,
    pub dehumidification_control_humidistat_supply_humidity_ratio_maximum_assignment_count: usize,
    pub dehumidification_control_none_supply_humidity_ratio_maximum_assignment_count: usize,
    pub dehumidification_control_guard_false_fallthrough_count: usize,
    pub heating_availability_guard_false_fallthrough_capacity_guard_false_count: usize,
    pub heating_availability_guard_false_fallthrough_dehumidification_guard_false_count: usize,
    pub heating_availability_guard_false_fallthrough_dehumidification_total_output_assignment_count: usize,
    pub humidification_control_guard_false_fallthrough_capacity_guard_false_count: usize,
    pub humidification_control_guard_false_fallthrough_dehumidification_guard_false_count: usize,
    pub humidification_control_guard_false_fallthrough_dehumidification_total_output_assignment_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_capacity_guard_false_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_dehumidification_guard_false_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_assignment_count: usize,
    pub dehumidification_control_none_maximum_assignment_capacity_guard_false_count: usize,
    pub dehumidification_control_none_maximum_assignment_dehumidification_guard_false_count: usize,
    pub dehumidification_control_none_maximum_assignment_dehumidification_total_output_assignment_count: usize,
    pub dehumidification_control_guard_false_fallthrough_capacity_guard_false_count: usize,
    pub dehumidification_control_guard_false_fallthrough_dehumidification_guard_false_count: usize,
    pub dehumidification_control_guard_false_fallthrough_dehumidification_total_output_assignment_count: usize,
    pub heating_availability_guard_false_fallthrough_dehumidification_total_output_capacity_adjustment_body_entry_count: usize,
    pub heating_availability_guard_false_fallthrough_dehumidification_total_output_capacity_guard_false_fallthrough_count: usize,
    pub humidification_control_guard_false_fallthrough_dehumidification_total_output_capacity_adjustment_body_entry_count: usize,
    pub humidification_control_guard_false_fallthrough_dehumidification_total_output_capacity_guard_false_fallthrough_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_capacity_adjustment_body_entry_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_capacity_guard_false_fallthrough_count: usize,
    pub dehumidification_control_none_maximum_assignment_dehumidification_total_output_capacity_adjustment_body_entry_count: usize,
    pub dehumidification_control_none_maximum_assignment_dehumidification_total_output_capacity_guard_false_fallthrough_count: usize,
    pub dehumidification_control_guard_false_fallthrough_dehumidification_total_output_capacity_adjustment_body_entry_count: usize,
    pub dehumidification_control_guard_false_fallthrough_dehumidification_total_output_capacity_guard_false_fallthrough_count: usize,
    pub dehumidification_total_output_capacity_guard_evaluation_count: usize,
    pub source_site_execution_count: usize,
    pub cp382_cooling_total_output_owned_read_count: usize,
    pub cooling_total_output_read_count: usize,
    pub cp321_maximum_total_cooling_capacity_owned_read_count: usize,
    pub cp340_same_call_maximum_total_cooling_capacity_bit_corroboration_count: usize,
    pub maximum_total_cooling_capacity_read_count: usize,
    pub cooling_total_output_maximum_total_cooling_capacity_comparison_count: usize,
    pub cooling_total_output_strictly_greater_than_maximum_total_cooling_capacity_count: usize,
    pub dehumidification_total_output_capacity_adjustment_body_entry_count: usize,
    pub dehumidification_total_output_capacity_guard_false_fallthrough_count: usize,
    pub latest:
        Option<PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputGuardSnapshot>,
    pub(super) latest_route: Option<
        PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputGuardRetainedRoute,
    >,
    pub(super) latest_transition_ordinal: Option<usize>,
}

impl PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputGuardRuntimeState {
    /// Creates zeroed CP383 state for one system.
    #[must_use]
    pub const fn new(system: IdealLoadsAirSystemId) -> Self {
        Self {
            system,
            transition_count: 0,
            unit_off_skip_count: 0,
            non_cooling_skip_count: 0,
            positive_guard_false_fallthrough_skip_count: 0,
            heating_availability_guard_false_fallthrough_count: 0,
            humidification_control_guard_false_fallthrough_count: 0,
            dehumidification_control_humidistat_supply_humidity_ratio_maximum_assignment_count: 0,
            dehumidification_control_none_supply_humidity_ratio_maximum_assignment_count: 0,
            dehumidification_control_guard_false_fallthrough_count: 0,
            heating_availability_guard_false_fallthrough_capacity_guard_false_count: 0,
            heating_availability_guard_false_fallthrough_dehumidification_guard_false_count: 0,
            heating_availability_guard_false_fallthrough_dehumidification_total_output_assignment_count: 0,
            humidification_control_guard_false_fallthrough_capacity_guard_false_count: 0,
            humidification_control_guard_false_fallthrough_dehumidification_guard_false_count: 0,
            humidification_control_guard_false_fallthrough_dehumidification_total_output_assignment_count: 0,
            dehumidification_control_humidistat_maximum_assignment_capacity_guard_false_count: 0,
            dehumidification_control_humidistat_maximum_assignment_dehumidification_guard_false_count: 0,
            dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_assignment_count: 0,
            dehumidification_control_none_maximum_assignment_capacity_guard_false_count: 0,
            dehumidification_control_none_maximum_assignment_dehumidification_guard_false_count: 0,
            dehumidification_control_none_maximum_assignment_dehumidification_total_output_assignment_count: 0,
            dehumidification_control_guard_false_fallthrough_capacity_guard_false_count: 0,
            dehumidification_control_guard_false_fallthrough_dehumidification_guard_false_count: 0,
            dehumidification_control_guard_false_fallthrough_dehumidification_total_output_assignment_count: 0,
            heating_availability_guard_false_fallthrough_dehumidification_total_output_capacity_adjustment_body_entry_count: 0,
            heating_availability_guard_false_fallthrough_dehumidification_total_output_capacity_guard_false_fallthrough_count: 0,
            humidification_control_guard_false_fallthrough_dehumidification_total_output_capacity_adjustment_body_entry_count: 0,
            humidification_control_guard_false_fallthrough_dehumidification_total_output_capacity_guard_false_fallthrough_count: 0,
            dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_capacity_adjustment_body_entry_count: 0,
            dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_capacity_guard_false_fallthrough_count: 0,
            dehumidification_control_none_maximum_assignment_dehumidification_total_output_capacity_adjustment_body_entry_count: 0,
            dehumidification_control_none_maximum_assignment_dehumidification_total_output_capacity_guard_false_fallthrough_count: 0,
            dehumidification_control_guard_false_fallthrough_dehumidification_total_output_capacity_adjustment_body_entry_count: 0,
            dehumidification_control_guard_false_fallthrough_dehumidification_total_output_capacity_guard_false_fallthrough_count: 0,
            dehumidification_total_output_capacity_guard_evaluation_count: 0,
            source_site_execution_count: 0,
            cp382_cooling_total_output_owned_read_count: 0,
            cooling_total_output_read_count: 0,
            cp321_maximum_total_cooling_capacity_owned_read_count: 0,
            cp340_same_call_maximum_total_cooling_capacity_bit_corroboration_count: 0,
            maximum_total_cooling_capacity_read_count: 0,
            cooling_total_output_maximum_total_cooling_capacity_comparison_count: 0,
            cooling_total_output_strictly_greater_than_maximum_total_cooling_capacity_count: 0,
            dehumidification_total_output_capacity_adjustment_body_entry_count: 0,
            dehumidification_total_output_capacity_guard_false_fallthrough_count: 0,
            latest: None,
            latest_route: None,
            latest_transition_ordinal: None,
        }
    }
}
