# CP438 maps PurchasedAirManager.cc physical executable line 2365's heating outdoor-air maximum-flow first-warning counter increment.
& {
function Get-Cp438Sha([byte[]]$Bytes) {
    $sha = [Security.Cryptography.SHA256]::Create()
    try { return ([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-', '') } finally { $sha.Dispose() }
}
function Get-Cp438SnapshotBlock([string]$Text, [string]$Type, [string]$EndMarker) {
    $start = $Text.IndexOf("pub struct $Type")
    $end = $Text.IndexOf($EndMarker, $start)
    if ($start -lt 0 -or $end -le $start) { throw "CP438 snapshot block drift: $Type" }
    return $Text.Substring($start, $end - $start)
}
$stem = 'heating_outdoor_air_maximum_flow_first_warning_counter_increment'
$predecessorStem = 'heating_outdoor_air_maximum_flow_first_warning_guard'
$typeStem = 'PurchasedAirCalcHeatingOutdoorAirMaximumFlowFirstWarningCounterIncrement'
$source = '.reference\energyplus-src\26.1.0\src\EnergyPlus\PurchasedAirManager.cc'
$module = "crates\ep_runtime\src\ideal_loads\calc\$stem.rs"; $predecessorModule = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem.rs"
$root = "crates\ep_runtime\src\ideal_loads\calc\$stem"; $predecessorRoot = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem"
$release = "$root\release.rs"; $prefix = "$root\release\prefix.rs"; $runtimeValidation = "$root\release\runtime_validation.rs"; $snapshotValidation = "$root\release\snapshot_validation.rs"; $state = "$root\state.rs"; $transition = "$root\transition.rs"; $accounting = "$root\transition\accounting.rs"; $snapshot = "$root\transition\snapshot.rs"; $tests = "$root\tests.rs"; $schemaTests = "$root\tests\schema_prefix.rs"
$predecessorCommitted = "$predecessorRoot\release\committed.rs"; $predecessorCommittedTests = "$predecessorRoot\tests\committed_seal.rs"
$binding = 'crates\ep_runtime\src\ideal_loads\binding.rs'; $scheduled = 'crates\ep_runtime\src\ideal_loads\binding\scheduled_output.rs'; $adapter = "crates\ep_runtime\src\ideal_loads\binding\$stem.rs"; $adapterTests = "crates\ep_runtime\src\ideal_loads\binding\$($stem)_tests.rs"
$coupled = "crates\ep_runtime\src\ideal_loads\coupled_runtime\$($stem)_validation.rs"; $coupledTests = 'crates\ep_runtime\src\ideal_loads\test_coupled_runtime_cp438.rs'; $coupledOutput = "crates\ep_runtime\src\ideal_loads\coupled_output_tests\$($stem)_fixture.rs"
$pipelineRoot = 'crates\ep_run\src\pipeline.rs'; $pipeline = "crates\ep_run\src\pipeline\purchased_air_$stem"; $pipelineModule = "$pipeline.rs"; $serialization = "$pipeline\serialization.rs"; $serializationSnapshot = "$pipeline\serialization\snapshot.rs"; $pipelineValidation = "$pipeline\validation.rs"; $pipelineLineage = "$pipeline\validation\lineage.rs"
$arbitrary = 'crates\ep_run\tests\arbitrary_run_ideal_loads\cp438_assertions.rs'; $audit = "scripts\quality\ideal-loads-structure-audit\cp438-$($stem -replace '_','-').ps1"
foreach ($file in @($source,$module,$predecessorModule,$release,$prefix,$runtimeValidation,$snapshotValidation,$state,$transition,$accounting,$snapshot,$tests,$schemaTests,$predecessorCommitted,$predecessorCommittedTests,$binding,$scheduled,$adapter,$adapterTests,$coupled,$coupledTests,$coupledOutput,$pipelineRoot,$pipelineModule,$serialization,$serializationSnapshot,$pipelineValidation,$pipelineLineage,$arbitrary,$audit)) { Assert-FileExists -Path $file -Description 'CP438 implementation/audit file' }
$bounded = @($audit,$module,$pipelineModule) + @((Get-ChildItem $root -Recurse -File -Filter '*.rs').FullName) + @((Get-ChildItem $pipeline -Recurse -File -Filter '*.rs').FullName)
foreach ($file in $bounded) { Assert-LineLimit -Path $file -Limit 500 -Description 'bounded CP438 file' }
$sourceBytes = [IO.File]::ReadAllBytes($source)
if ((Get-Cp438Sha $sourceBytes) -cne '54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005') { throw 'CP438 pinned PurchasedAirManager.cc hash drift' }
$sourceLines = Get-Content -LiteralPath $source
if ($sourceLines[2364].Trim() -cne '++PurchAir.OAFlowMaxHeatOutputError;' -or $sourceLines[2365].Trim() -cne 'ShowWarningError(state,') { throw 'CP438 physical 2365-2366 boundary drift' }
$sites = @('increment-state-owned-outdoor-air-flow-maximum-heating-output-error-count')
Assert-ExactStringArray -Path $module -Name 'PURCHASED_AIR_CALC_HEATING_OUTDOOR_AIR_MAXIMUM_FLOW_FIRST_WARNING_COUNTER_INCREMENT_SOURCE_ORDER' -Expected $sites -Description 'one CP438 textual source site'
foreach ($pattern in @('EnergyPlus 26\.1 PurchasedAirManager\.cc:2365','EnergyPlus 26\.1 PurchasedAirManager\.cc:2366','PurchasedAirCalcHeatingOutdoorAirMaximumFlowFirstWarningCounterIncrementSnapshot')) { Assert-Contains -Path $module -Pattern $pattern -Description 'CP438 boundary/type contract' }
$core = @(Get-ChildItem -LiteralPath $root -Recurse -File -Filter '*.rs'); $predecessorCore = @(Get-ChildItem -LiteralPath $predecessorRoot -Recurse -File -Filter '*.rs')
if ($core.Count -ne 11 -or @(Get-ChildItem "$root\tests" -File -Filter '*.rs').Count -ne 1) { throw 'CP438 exact eleven-subtree-file/one-test topology drift' }
if ($predecessorCore.Count -ne 13 -or @(Get-ChildItem "$predecessorRoot\tests" -File -Filter '*.rs').Count -ne 2) { throw 'CP438 exact sealed CP437 thirteen-subtree-file/two-test topology drift' }
$stateText = Read-RepoText -Path $state
$arrays = @([regex]::Matches($stateText, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*route_counts)\s*:\s*\[usize;\s*36\]') | ForEach-Object { $_.Groups['name'].Value })
$expectedArrays = @('predecessor_route_counts','predecessor_guard_false_fallthrough_route_counts','predecessor_guard_body_entry_route_counts','predecessor_volume_flow_assignment_route_counts','predecessor_first_warning_guard_false_fallthrough_route_counts','predecessor_first_warning_branch_entry_route_counts','heating_outdoor_air_maximum_flow_first_warning_counter_increment_route_counts')
if ($arrays.Count -ne 7 -or ($arrays -join '|') -cne ($expectedArrays -join '|')) { throw 'CP438 exact seven width-36 arrays drift' }
foreach ($pattern in @('outdoor_air_flow_maximum_heating_output_error_count_increment_count','cp437_outdoor_air_flow_maximum_heating_output_error_count_state_owner_count','outdoor_air_flow_maximum_heating_output_error_count_increment_write_count')) { Assert-Contains -Path $state -Pattern $pattern -Description 'CP438 retained-counter accounting state' }
foreach ($pattern in @('counter_increment_executed:\s*predecessor_route\.first_warning_branch_entered','counter_owner\s*\.outdoor_air_flow_maximum_heating_output_error_count\s*\.checked_add\(1\)','assigned_counter\s*!=\s*Some\(1\)','counter_owner\.outdoor_air_flow_maximum_heating_output_error_count\s*=\s*assigned')) { Assert-Contains -Path $transition -Pattern $pattern -Description 'CP438 exact transactional zero-to-one mutation' }
foreach ($pattern in @('source_site_execution_count\s*\+=\s*1','increment\s*==\s*route\.predecessor_first_warning_branch_entered','outdoor_air_flow_maximum_heating_output_error_count_increment_count\s*\+=\s*1')) { Assert-Contains -Path $accounting -Pattern $pattern -Description 'CP438 transactional single-site accounting' }
foreach ($pattern in @('heating_outdoor_air_maximum_flow_first_warning_guard_committed_latest_route_and_outdoor_air_flow_maximum_heating_output_error_count\(','state\.latest_route','snapshots_match_bit_exact','state_counts_are_consistent','predecessor_counts_match')) { Assert-Contains -Path $predecessorCommitted -Pattern $pattern -Description 'CP437 committed route/counter-owner seal' }
foreach ($pattern in @('cp437_committed_seal_is_retained_constant_time_counter_exact_and_owner_lazy','cp437_committed_seal_rejects_latest_witness_route_accounting_and_counter_forgeries','private_characterization','DirectZonePurchasedAirCouplingInput')) { Assert-Contains -Path $predecessorCommittedTests -Pattern $pattern -Description 'CP437 committed-seal regression' }
foreach ($pattern in @('heating_outdoor_air_maximum_flow_first_warning_guard_committed_latest_route_and_outdoor_air_flow_maximum_heating_output_error_count\(','ExactReleaseReductionViolated','let\s+mut\s+next_state\s*=','let\s+mut\s+next_counter_owner\s*=','counter_increment_executed')) { Assert-Contains -Path $release -Pattern $pattern -Description 'CP438 committed-predecessor/public/private release contract' }
foreach ($pattern in @('exhaustive_67_routes_preserve_20_47_visibility_and_increment_three_private_alternatives','\(public,\s*67\s*-\s*public\),\s*\(20,\s*47\)','\(public_increments,\s*private_increments\),\s*\(0,\s*3\)','transition_count,\s*67','inactive_transition_count,\s*64','outdoor_air_flow_maximum_heating_output_error_count_increment_count,\s*3','source_site_execution_count,\s*3','cp437_supply_humidity_ratio_state_owner_count','cp437_supply_enthalpy_state_owner_count','cp437_supply_temperature_state_owner_count','\(37,\s*42,\s*57\)','active_increment_is_exactly_zero_to_one_and_persists_into_the_next_guard','cp438_new_state_has_seven_zeroed_width_36_arrays','public_release_uses_cp437_committed_counter_seal_before_transactional_clones','cp438_subtree_is_twelve_files_and_every_file_is_bounded')) { Assert-Contains -Path $tests -Pattern $pattern -Description 'CP438 exhaustive/counter/topology regression' }
$moduleText = Read-RepoText -Path $module; $predecessorText = Read-RepoText -Path $predecessorModule
$snapshotBlock = Get-Cp438SnapshotBlock $moduleText "$($typeStem)Snapshot" '/// Final selected-unit CP438'
$predecessorBlock = Get-Cp438SnapshotBlock $predecessorText 'PurchasedAirCalcHeatingOutdoorAirMaximumFlowFirstWarningGuardSnapshot' '/// Final selected-unit CP437'
$fields = @([regex]::Matches($snapshotBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value }); $predecessorFields = @([regex]::Matches($predecessorBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value })
if ($predecessorFields.Count -ne 416 -or $fields.Count -ne 426 -or @($fields | Select-Object -Unique).Count -ne 426 -or ($fields[0..412] -join '|') -cne ($predecessorFields[0..412] -join '|')) { throw 'CP438 exact unique 426-field/CP437-first-413 schema drift' }
$tail = @('predecessor_cp437_resulting_supply_humidity_ratio','predecessor_cp437_resulting_supply_enthalpy_j_per_kg','predecessor_cp437_resulting_supply_temperature_c','heating_outdoor_air_maximum_flow_first_warning_counter_increment_executed','cp437_retained_supply_humidity_ratio_state_owned','cp437_retained_supply_enthalpy_state_owned','cp437_retained_supply_temperature_state_owned','cp437_retained_outdoor_air_flow_maximum_heating_output_error_count_state_owned','outdoor_air_flow_maximum_heating_output_error_count_increment_performed','assigned_outdoor_air_flow_maximum_heating_output_error_count','resulting_supply_humidity_ratio','resulting_supply_enthalpy_j_per_kg','resulting_supply_temperature_c')
if (($fields[413..425] -join '|') -cne ($tail -join '|') -or [regex]::Matches($snapshotBlock,'Option<f64>').Count -ne 146 -or [regex]::Matches($snapshotBlock,'Option<bool>').Count -ne 9 -or [regex]::Matches($snapshotBlock,'Option<usize>').Count -ne 2 -or ([regex]::Matches($snapshotBlock,'Option<').Count - 146 - 9 - 2) -ne 6) { throw 'CP438 locked 426/146/9/6/2 schema/tail drift' }
foreach ($pattern in @('cp438_schema_is_exact_426_146_9_6_2_with_cp437_first_413_and_locked_tail','assert_eq!\(&cp438\[\.\.413\],\s*&cp437\[\.\.413\]\)','predecessors\.len\(\),\s*67')) { Assert-Contains -Path $schemaTests -Pattern $pattern -Description 'CP438 schema/prefix regression' }
foreach ($pattern in @('assigned_outdoor_air_flow_maximum_heating_output_error_count:\s*assigned_counter','cp437_retained_outdoor_air_flow_maximum_heating_output_error_count_state_owned:\s*route\.counter_increment_executed','resulting_supply_temperature_c:\s*predecessor\.resulting_supply_temperature_c')) { Assert-Contains -Path $snapshot -Pattern $pattern -Description 'CP438 retained-counter/unchanged-output semantics' }
foreach ($pattern in @('\[67usize,\s*64,\s*3,\s*3\]','20usize\s*\+\s*47','\(public_active,\s*private_active\)\s*=\s*\(0usize,\s*3usize\)','public_active\s*\+\s*private_active','426','146','Option<bool>"\)\.count\(\),\s*9','Option<usize>"\)\.count\(\),\s*2','fields\.len\(\),\s*129','cp438_new_state_has_seven_zeroed_lossless_route_partitions','cp438_is_ordered_after_cp437_and_does_not_feed_numerics')) { Assert-Contains -Path $coupledTests -Pattern $pattern -Description 'CP438 route/schema/binding/no-feed regression' }
foreach ($pattern in @('serializer_source_preserves_cp437_prefix_and_extends_exact_19_key_tail','cp437_snapshot_json\(predecessor\)','keys\.len\(\),\s*19','keys\[18\],\s*"resulting_supply_temperature_c_ieee_bits"')) { Assert-Contains -Path $serializationSnapshot -Pattern $pattern -Description 'CP438 CP437-prefix/19-key serializer contract' }
foreach ($pattern in @('actual\.len\(\),\s*572','ends_with\("_ieee_bits"\)\)\s*\.count\(\),\s*146','fields\.len\(\),\s*426','snapshot\.matches\("Option<f64>"\)\.count\(\),\s*146','snapshot\.matches\("Option<bool>"\)\.count\(\),\s*9','snapshot\.matches\("Option<usize>"\)\.count\(\),\s*2','fields\.len\(\),\s*129','fields\[127\][\s\S]*heating_outdoor_air_maximum_flow_first_warning_guard','fields\[128\][\s\S]*heating_outdoor_air_maximum_flow_first_warning_counter_increment')) { Assert-Contains -Path $arbitrary -Pattern $pattern -Description 'actual CP438 JSON/IEEE/schema/binding contract' }
Assert-PatternsInOrder -Path $binding -Patterns @("let\s+calculation_$predecessorStem\s*=","let\s+calculation_$stem\s*=",'let\s+unit_available\s*=','let\s+coupling\s*=') -Description 'CP437-to-CP438-to-numerical order'
Assert-PatternsInOrder -Path $scheduled -Patterns @("pub\s+calculation_$predecessorStem\s*:","pub\s+calculation_$stem\s*:",'pub\s+coupling\s*:') -Description 'scheduled CP437-to-CP438 order'
$scheduledFields = @([regex]::Matches((Read-RepoText -Path $scheduled), '(?m)^\s*pub\s+(?<name>calculation_[A-Za-z0-9_]+)\s*:') | ForEach-Object { $_.Groups['name'].Value })
if ($scheduledFields.Count -ne 129 -or $scheduledFields[127] -cne 'calculation_heating_outdoor_air_maximum_flow_first_warning_guard' -or $scheduledFields[128] -cne 'calculation_heating_outdoor_air_maximum_flow_first_warning_counter_increment') { throw 'CP438 exact binding index 127/128/current 129 drift' }
foreach ($test in @('scheduled_binding_advances_cp438_after_cp437_before_unchanged_coupling','cp438_adapter_accepts_only_the_cp437_snapshot_and_no_scalar_input','cp438_extends_current_scheduled_binding_from_128_to_129_snapshots')) { Assert-Contains -Path $adapterTests -Pattern $test -Description 'CP438 adapter/current-binding regression' }
foreach ($pattern in @('predecessor_first_warning_guard_false_fallthrough_route_counts','predecessor_first_warning_branch_entry_route_counts','heating_outdoor_air_maximum_flow_first_warning_counter_increment_route_counts','public_counter_increment_count','warning_counter_increment_write_count','local_public_skip_matches')) { Assert-Contains -Path $coupled -Pattern $pattern -Description 'CP438 public exact-release/no-increment validation' }
foreach ($pattern in @('validate_direct_lifecycle','validate_public_route_contract','public_counter_increment_count"\s*,\s*0\s*,\s*increments','source_site_execution_count','lineage_is_exact')) { Assert-Contains -Path $pipelineValidation -Pattern $pattern -Description 'CP438 pipeline structural/no-feed seal' }
foreach ($pattern in @('lineage_is_exact','!predecessor\.heating_outdoor_air_maximum_flow_first_warning_branch_entered','!snapshot\.heating_outdoor_air_maximum_flow_first_warning_counter_increment_executed','assigned_outdoor_air_flow_maximum_heating_output_error_count[\s\S]*\.is_none\(\)')) { Assert-Contains -Path $pipelineLineage -Pattern $pattern -Description 'CP438 exact increment/skip lineage seal' }
Assert-Contains -Path $pipelineRoot -Pattern 'non_direct_runtime_rejects_cp316_through_cp438_lifecycle_evidence' -Description 'CP438 non-direct firewall'
Assert-Contains -Path $pipelineRoot -Pattern 'purchased_air_calc_heating_outdoor_air_maximum_flow_first_warning_counter_increment_lifecycle' -Description 'CP438 lifecycle JSON field'
$ledger = Read-RepoText -Path 'specs\algorithm_ledger.toml'; $capabilities = Read-RepoText -Path 'specs\capabilities.toml'
if ([regex]::Matches($ledger,[regex]::Escape('CP438 supersedes only CP437')).Count -ne 1 -or [regex]::Matches($capabilities,[regex]::Escape('CP438 additionally requires')).Count -ne 1) { throw 'CP438 bounded spec addendum drift' }
foreach ($text in @($ledger,$capabilities)) { foreach ($claim in @('54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005','physical-line-2365','first 413 nonterminal fields','first 553 nonterminal keys','426','572','146','376 total','240 public','136 internal')) { if (-not $text.Contains($claim)) { throw "CP438 spec claim missing $claim" } }; foreach ($site in $sites) { if (-not $text.Contains($site)) { throw "CP438 spec source site missing $site" } } }
if ([regex]::Matches($ledger,'(?m)^\[\[algorithm\]\]\r?$').Count -ne 32 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"state_mapped"\r?$').Count -ne 58 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"source_mapped"\r?$').Count -ne 235 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.required_for_full_domain\s*=\s*true\r?$').Count -ne 170) { throw 'CP438 unchanged algorithm/routine count drift' }
Assert-NotContains -Path 'docs\src\current\roadmap.md' -Pattern '(?m)^## CP438\b' -Description 'Roadmap non-promotion'; Assert-NotContains -Path 'docs\src\porting-map\psychrometrics-source-map.md' -Pattern '(?m)^## CP438\b' -Description 'psychrometrics non-promotion'
$auditRoot = 'scripts\quality\ideal-loads-structure-audit'; $audits = @(Get-ChildItem $auditRoot -Filter 'cp*.ps1' -File)
$historical = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -eq 326) -or ([int]$Matches.n -ge 329 -and [int]$Matches.n -le 437)) })
if ($historical.Count -ne 110 -or @($historical | Where-Object { $_.BaseName -match '^cp(?:327|328)-' }).Count) { throw 'CP438 exact 110 historical leaf set drift' }
$firewall = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 334 -and [int]$Matches.n -le 438 }); $script = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 337 -and [int]$Matches.n -le 438 }); $internal = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 367 -and [int]$Matches.n -le 438 }); $generated = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 335 -and [int]$Matches.n -le 438 })
if ($firewall.Count -ne 105 -or $script.Count -ne 102 -or $internal.Count -ne 72 -or $generated.Count -ne 104) { throw 'CP438 propagation range cardinality drift' }
foreach ($file in $firewall) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('non_direct_runtime_rejects_cp316_through_cp438_lifecycle_evidence')) { throw "CP438 firewall propagation drift $($file.Name)" } }
foreach ($file in $script) { if (-not (Read-RepoText -Path $file.FullName).Contains('script_count = 376')) { throw "CP438 inventory-total propagation drift $($file.Name)" } }
$internalClassification = '\[regex\]::Matches\(\s*\$[A-Za-z_][A-Za-z0-9_]*\s*,\s*''\(\?m\)\^classification\s*\=\s*"internal"(?:\\r\?)?\$''\s*\)\s*\.Count\s*-ne\s*(?<count>\d+)'
foreach ($file in $internal) { $matches = [regex]::Matches((Read-RepoText -Path $file.FullName),$internalClassification); if ($matches.Count -ne 1 -or $matches[0].Groups['count'].Value -cne '136') { throw "CP438 internal propagation drift $($file.Name)" } }
foreach ($file in $generated) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('\| 376 \|') -or -not $text.Contains('\| 136 \|')) { throw "CP438 generated propagation drift $($file.Name)" } }
$helpers = @((Get-ChildItem $auditRoot -Filter 'cp326-*.ps1' -File); Get-ChildItem $auditRoot -Filter 'cp3*.ps1' -File | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 329 -and [int]$Matches.n -le 344 })
if ($helpers.Count -ne 17) { throw 'CP438 helper set drift' }
foreach ($file in $helpers) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains("calculation_$stem") -or -not $text.Contains("advance_$stem") -or -not $text.Contains('CP340 through CP438')) { throw "CP438 helper strip/whitelist drift $($file.Name)" } }
$terminal = @((Get-ChildItem $auditRoot -Filter 'cp345-*.ps1' -File); $audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -ge 377 -and [int]$Matches.n -le 392) -or ([int]$Matches.n -ge 394 -and [int]$Matches.n -le 437)) })
if ($terminal.Count -ne 61) { throw 'CP438 terminal set drift' }
foreach ($file in $terminal) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('$cp438Call') -or -not $text.Contains('CP437-to-CP438') -or -not $text.Contains("-Pattern ('Assert-Contains[^\r\n]+CP437-to-' + 'numerical')")) { throw "CP438 terminal propagation drift $($file.Name)" } }
$live = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 421 -and [int]$Matches.n -le 437 })
if ($live.Count -ne 17) { throw 'CP438 live binding set drift' }
foreach ($file in $live) { $text = Read-RepoText -Path $file.FullName; if ($text -notmatch 'current_129_snapshot_binding|binding_is_129|Count-ne129|,\s*\\s\*129') { throw "CP438 current-129 propagation drift $($file.Name)" }; if ($text -notmatch 'Count\s*-(?:gt|ne)\s*4201') { throw "CP438 master-cap propagation drift $($file.Name)" } }
$recent = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 425 -and [int]$Matches.n -le 437 }); if ($recent.Count -ne 13) { throw 'CP438 recent binding set drift' }
foreach ($file in $recent) { Assert-Contains -Path $file.FullName -Pattern "calculation_$stem" -Description 'CP438 recent binding propagation' }
$cp424 = Get-ChildItem $auditRoot -Filter 'cp424-*.ps1' -File; Assert-NotContains -Path $cp424.FullName -Pattern "calculation_$stem" -Description 'CP424 excludes CP438 registration'
$manualShape = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 424 -and [int]$Matches.n -le 437 }); if ($manualShape.Count -ne 14) { throw 'CP438 manual-shape propagation set drift' }; foreach ($file in $manualShape) { if ((Read-RepoText -Path $file.FullName) -notmatch '3458\s*\+\s*3655') { throw "CP438 manual-shape propagation drift $($file.Name)" } }
$manuals = @([PSCustomObject]@{Path='docs\src\current\current-status.md';Length=496927;Hash='669940CD322B17B28200D42A1FB2AA3A299553988BE92E0582FC599294CDE688'},[PSCustomObject]@{Path='docs\src\current\project-contract.md';Length=1448375;Hash='32E1F708766F17BF230BDD56A11645D2A089A7AED3BD5E8429DBFD88ACE19F99'},[PSCustomObject]@{Path='docs\src\porting-map\heat-balance-source-map.md';Length=3913161;Hash='0843513D95924B57FA7F2317BA2F0E7E7840ACE3A57C8F722C3E4E6A0C8A843C'},[PSCustomObject]@{Path='docs\src\porting-map\ideal-loads-source-map.md';Length=1452502;Hash='6464C1A943796FD4EAA6E25F5FC0A807AC4CB1E28A3570A96EC41E51DAEE25E3'},[PSCustomObject]@{Path='docs\src\porting-map\zone-air-update-map.md';Length=1651940;Hash='FF7B38DB29CF305CB9CA98B1F7DE8206E1F41EEE75CEDC4EC85BF8A22E669F8B'})
$canonical = $null
foreach ($manual in $manuals) { $bytes = [IO.File]::ReadAllBytes($manual.Path); if ($bytes.Length -ne $manual.Length + 3655 -or [Array]::IndexOf($bytes,[byte]13) -ne -1 -or $bytes[-1] -ne 10) { throw "CP438 manual byte shape drift $($manual.Path)" }; $head = New-Object byte[] $manual.Length; [Array]::Copy($bytes,$head,$manual.Length); if ((Get-Cp438Sha $head) -cne $manual.Hash) { throw "CP438 manual prefix drift $($manual.Path)" }; $suffix = New-Object byte[] 3655; [Array]::Copy($bytes,$manual.Length,$suffix,0,3655); if ((Get-Cp438Sha $suffix) -cne '433049BC7D606D748380B746460D01058F607CD4376C4C338D12EC18170AA13F') { throw "CP438 manual suffix drift $($manual.Path)" }; $text = [Text.UTF8Encoding]::new($false,$true).GetString($suffix); if ($null -eq $canonical) { $canonical = $text } elseif ($text -cne $canonical) { throw "CP438 canonical manual drift $($manual.Path)" } }
foreach ($pattern in @('(?m)^## CP438 heating outdoor-air maximum-flow first-warning counter increment$','physical-line-2365','line\s+2366','exactly one textual source site','T438=67','Z438=64','I438=3','S438=3','20/47','active\s+public/private 0/3','seven width-36','first 413 nonterminal fields','426 unique Rust fields','146 `Option<f64>`','nine\s+`Option<bool>`','six optional enums','two\s+`Option<usize>`','572 unique keys','146\s+adjacent\s+IEEE sidecars','37/42/57','index 128','current\s+count 129','zero public increment','376 total','240\s+public','136\s+internal')) { if ($canonical -notmatch "(?is)$pattern") { throw "CP438 documentation claim missing $pattern" } }
$master = Read-RepoText -Path 'scripts\quality\ideal-loads-structure-audit.ps1'; $leaf = Split-Path -Leaf $audit; $previous = $master.IndexOf('cp437-heating-outdoor-air-maximum-flow-first-warning-guard.ps1'); $current = $master.IndexOf($leaf); $done = $master.IndexOf('Write-Host "IdealLoads structure audit complete."')
if ($previous -lt 0 -or $current -le $previous -or $done -le $current -or [regex]::Matches($master,[regex]::Escape($leaf)).Count -ne 1) { throw 'CP438 master order/uniqueness drift' }
if ((Get-Content 'scripts\quality\ideal-loads-structure-audit.ps1').Count -ne 4201 -or (Get-Content 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1').Count -ne 1200 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\calc.rs').Count -ne 99 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\init\state\witnesses.rs').Count -ne 275 -or @(Get-Content 'crates\ep_runtime\src\ideal_loads\init\state.rs' | Where-Object { $_ -match '\S' }).Count -ne 380 -or (Get-Content $scheduled).Count -gt 500) { throw 'CP438 fixed cap drift' }
$inventory = Read-RepoText -Path 'specs\script_inventory.toml'; foreach ($pattern in @('script_count = 376','dev_command_count = 238','unused_script_count = 0','unreachable_count = 0')) { if ($inventory -notmatch $pattern) { throw "CP438 inventory missing $pattern" } }
if ([regex]::Matches($inventory,'(?m)^classification = "public"$').Count -ne 240 -or [regex]::Matches($inventory,'(?m)^classification = "internal"$').Count -ne 136) { throw 'CP438 inventory classification drift' }
Assert-Contains -Path 'specs\script_inventory.toml' -Pattern 'cp438-heating-outdoor-air-maximum-flow-first-warning-counter-increment\.ps1' -Description 'CP438 inventory record'; Assert-Contains -Path 'docs\src\generated\algorithm-ledger.md' -Pattern 'CP438 supersedes only CP437' -Description 'generated algorithm'; Assert-Contains -Path 'docs\src\generated\capability-index.md' -Pattern 'CP438 additionally requires' -Description 'generated capability'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 376 \|' -Description 'generated total'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 136 \|' -Description 'generated internal'
Write-Host 'CP438 heating outdoor-air maximum-flow first-warning counter increment structure audit passed.'
}
