# CP435 maps PurchasedAirManager.cc physical executable lines 2361-2362's heating outdoor-air maximum-flow guard.
& {
function Get-Cp435Sha([byte[]]$Bytes) {
    $sha = [Security.Cryptography.SHA256]::Create()
    try { return ([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-', '') } finally { $sha.Dispose() }
}
function Get-Cp435SnapshotBlock([string]$Text, [string]$Type, [string]$EndMarker) {
    $start = $Text.IndexOf("pub struct $Type")
    $end = $Text.IndexOf($EndMarker, $start)
    if ($start -lt 0 -or $end -le $start) { throw "CP435 snapshot block drift: $Type" }
    return $Text.Substring($start, $end - $start)
}
$stem = 'heating_outdoor_air_maximum_flow_guard'
$predecessorStem = 'heating_operating_mode_deadband_assignment'
$typeStem = 'PurchasedAirCalcHeatingOutdoorAirMaximumFlowGuard'
$source = '.reference\energyplus-src\26.1.0\src\EnergyPlus\PurchasedAirManager.cc'
$module = "crates\ep_runtime\src\ideal_loads\calc\$stem.rs"; $predecessorModule = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem.rs"
$root = "crates\ep_runtime\src\ideal_loads\calc\$stem"; $predecessorRoot = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem"
$release = "$root\release.rs"; $state = "$root\state.rs"; $transition = "$root\transition.rs"; $accounting = "$root\transition\accounting.rs"; $snapshot = "$root\transition\snapshot.rs"; $tests = "$root\tests.rs"; $schemaTests = "$root\tests\schema_prefix.rs"
$binding = 'crates\ep_runtime\src\ideal_loads\binding.rs'; $scheduled = 'crates\ep_runtime\src\ideal_loads\binding\scheduled_output.rs'; $adapter = "crates\ep_runtime\src\ideal_loads\binding\$stem.rs"; $adapterTests = "crates\ep_runtime\src\ideal_loads\binding\$($stem)_tests.rs"
$coupled = "crates\ep_runtime\src\ideal_loads\coupled_runtime\$($stem)_validation.rs"; $coupledTests = 'crates\ep_runtime\src\ideal_loads\test_coupled_runtime_cp435.rs'; $coupledOutput = "crates\ep_runtime\src\ideal_loads\coupled_output_tests\$($stem)_fixture.rs"
$pipelineRoot = 'crates\ep_run\src\pipeline.rs'; $pipeline = "crates\ep_run\src\pipeline\purchased_air_$stem"; $pipelineModule = "$pipeline.rs"; $serialization = "$pipeline\serialization.rs"; $serializationSnapshot = "$pipeline\serialization\snapshot.rs"; $pipelineValidation = "$pipeline\validation.rs"; $pipelineLineage = "$pipeline\validation\lineage.rs"
$arbitrary = 'crates\ep_run\tests\arbitrary_run_ideal_loads\cp435_assertions.rs'; $audit = "scripts\quality\ideal-loads-structure-audit\cp435-$($stem -replace '_','-').ps1"
foreach ($file in @($source,$module,$predecessorModule,$release,$state,$transition,$accounting,$snapshot,$tests,$schemaTests,$binding,$scheduled,$adapter,$adapterTests,$coupled,$coupledTests,$coupledOutput,$pipelineRoot,$pipelineModule,$serialization,$serializationSnapshot,$pipelineValidation,$pipelineLineage,$arbitrary,$audit)) { Assert-FileExists -Path $file -Description 'CP435 implementation/audit file' }
$bounded = @($audit,$module,$pipelineModule) + @((Get-ChildItem $root -Recurse -File -Filter '*.rs').FullName) + @((Get-ChildItem $pipeline -Recurse -File -Filter '*.rs').FullName)
foreach ($file in $bounded) { Assert-LineLimit -Path $file -Limit 500 -Description 'bounded CP435 file' }
$sourceBytes = [IO.File]::ReadAllBytes($source)
if ((Get-Cp435Sha $sourceBytes) -cne '54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005') { throw 'CP435 pinned PurchasedAirManager.cc hash drift' }
$sourceLines = Get-Content -LiteralPath $source
if ($sourceLines[2360].Trim() -cne 'if (((PurchAir.HeatingLimit == LimitType::FlowRate) || (PurchAir.HeatingLimit == LimitType::FlowRateAndCapacity)) &&' -or $sourceLines[2361].Trim() -cne '(OAMassFlowRate > PurchAir.MaxHeatMassFlowRate)) {' -or $sourceLines[2362].Trim() -cne 'OAVolFlowRate = OAMassFlowRate / state.dataEnvrn->StdRhoAir;') { throw 'CP435 physical 2361-2363 boundary drift' }
$sites = @('compare-heating-limit-to-flow-rate','compare-heating-limit-to-flow-rate-and-capacity-after-short-circuit','read-outdoor-air-mass-flow-after-limit-short-circuit','read-maximum-heating-air-mass-flow-after-limit-short-circuit','compare-strict-outdoor-air-above-maximum-heating-flow','enter-maximum-heating-flow-body-if-satisfied')
Assert-ExactStringArray -Path $module -Name 'PURCHASED_AIR_CALC_HEATING_OUTDOOR_AIR_MAXIMUM_FLOW_GUARD_SOURCE_ORDER' -Expected $sites -Description 'six CP435 textual source sites'
foreach ($pattern in @('EnergyPlus 26\.1 PurchasedAirManager\.cc:2361-2362','EnergyPlus 26\.1 PurchasedAirManager\.cc:2363','PurchasedAirCalcHeatingOutdoorAirMaximumFlowGuardSnapshot')) { Assert-Contains -Path $module -Pattern $pattern -Description 'CP435 boundary/type contract' }
$core = @(Get-ChildItem -LiteralPath $root -Recurse -File -Filter '*.rs'); $predecessorCore = @(Get-ChildItem -LiteralPath $predecessorRoot -Recurse -File -Filter '*.rs')
if ($core.Count -ne 13 -or @(Get-ChildItem "$root\tests" -File -Filter '*.rs').Count -ne 2) { throw 'CP435 exact sealed thirteen-file/two-test topology drift' }
if ($predecessorCore.Count -ne 13 -or @(Get-ChildItem "$predecessorRoot\tests" -File -Filter '*.rs').Count -ne 2) { throw 'CP435 exact sealed CP434 thirteen-file/two-test topology drift' }
$stateText = Read-RepoText -Path $state
$arrays = @([regex]::Matches($stateText, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*route_counts)\s*:\s*\[usize;\s*36\]') | ForEach-Object { $_.Groups['name'].Value })
if ($arrays.Count -ne 3 -or ($arrays -join '|') -cne 'predecessor_route_counts|heating_outdoor_air_maximum_flow_guard_false_fallthrough_route_counts|maximum_heating_flow_body_entry_route_counts') { throw 'CP435 exact three width-36 arrays drift' }
foreach ($pattern in @('heating_outdoor_air_maximum_flow_guard_evaluation_count','heating_limit_flow_rate_comparison_count','heating_limit_flow_rate_match_count','heating_limit_flow_rate_and_capacity_comparison_count','heating_limit_flow_rate_and_capacity_match_count','outdoor_air_mass_flow_rate_read_after_heating_limit_short_circuit_count','maximum_heating_air_mass_flow_rate_read_after_heating_limit_short_circuit_count','outdoor_air_mass_flow_rate_maximum_heating_air_mass_flow_rate_comparison_count','maximum_heating_flow_body_entry_count','heating_outdoor_air_maximum_flow_guard_false_fallthrough_count')) { Assert-Contains -Path $state -Pattern $pattern -Description 'CP435 state accounting' }
foreach ($pattern in @('let\s+first\s*=\s*active\s*&&\s*heating_limit\s*==\s*IdealLoadsLimit::LimitFlowRate','let\s+second_evaluated\s*=\s*active\s*&&\s*!first','IdealLoadsLimit::LimitFlowRateAndCapacity','outdoor_air_mass_flow_rate_kg_per_s\s*>\s*maximum_heating_air_mass_flow_rate_kg_per_s','false_fallthrough:\s*active\s*&&\s*!body')) { Assert-Contains -Path $transition -Pattern $pattern -Description 'CP435 short-circuit/strict guard semantics' }
foreach ($pattern in @('usize::from\(route\.guard_evaluated\)','usize::from\(route\.heating_limit_flow_rate_and_capacity_comparison_evaluated\)','3\s*\*\s*usize::from\(route\.strict_mass_flow_comparison_evaluated\)','usize::from\(route\.body_entered\)','heating_limit_flow_rate_match_count\s*\+=','heating_limit_flow_rate_and_capacity_match_count\s*\+=')) { Assert-Contains -Path $accounting -Pattern $pattern -Description 'CP435 six-site accounting formula' }
foreach ($pattern in @('if\s+flow_limit_active\s*\{\s*let\s+minimum_oa','minimum_oa_is_sealed_same_call_no_oa','outdoor\.to_bits\(\)\s*!=\s*0\.0f64\.to_bits\(\)','maximum_heating_cache_is_bit_exact','if\s+route\.body_entered','predecessor_cp434\.parent_call_ordinal\s*!=\s*unit\.init_call_count','snapshot\.parent_call_ordinal\s*==\s*predecessor\.parent_call_ordinal','unit\.calc_entry\.call_count\s*==\s*unit\.init_call_count','has_positive_zero\(snapshot\.working_outdoor_air_mass_flow_rate_kg_per_s\)','density\.is_finite\(\)','volume\s*>=\s*0\.0','maximum_heating_air_mass_flow_rate_kg_per_s\.to_bits\(\)\s*==\s*expected\.to_bits\(\)')) { Assert-Contains -Path $release -Pattern $pattern -Description 'CP435 exact +0/same-call/cache/body public-release seal' }
foreach ($pattern in @('exhaustive_61_predecessors_refine_to_64_successors_with_exact_guard_partition_and_accounting','cases\.len\(\),\s*64','\(public,\s*private\),\s*\(20,\s*44\)','transition_count,\s*64','inactive_transition_count,\s*58','heating_outdoor_air_maximum_flow_guard_evaluation_count,\s*6','heating_limit_flow_rate_match_count,\s*0','heating_limit_flow_rate_and_capacity_comparison_count,\s*6','heating_limit_flow_rate_and_capacity_match_count,\s*6','heating_flow_limit_selector_rejection_count,\s*0','outdoor_air_mass_flow_rate_read_after_heating_limit_short_circuit_count,\s*6','maximum_heating_air_mass_flow_rate_read_after_heating_limit_short_circuit_count,\s*6','maximum_heating_flow_body_entry_count,\s*3','heating_outdoor_air_maximum_flow_guard_false_fallthrough_count,\s*3','source_site_execution_count,\s*33','cp434_supply_humidity_ratio_state_owner_count,\s*37','cp434_supply_enthalpy_state_owner_count,\s*42','cp434_supply_temperature_state_owner_count,\s*57','strict_comparison_and_selector_short_circuits_have_exact_local_shape','heating_flow_limit_selector_rejected','!rejected\.outdoor_air_mass_flow_rate_read_after_heating_limit_short_circuit','cp435_public_release_seals_cp311_cache_and_rejects_body_before_mutation','outdoor\.to_bits\(\)\s*!=\s*0\.0f64\.to_bits\(\)','cp435_topology_includes_successor_seal_and_every_file_is_bounded')) { Assert-Contains -Path $tests -Pattern $pattern -Description 'CP435 exhaustive/rejection/+0/cache/topology regression' }
$moduleText = Read-RepoText -Path $module; $predecessorText = Read-RepoText -Path $predecessorModule
$snapshotBlock = Get-Cp435SnapshotBlock $moduleText "$($typeStem)Snapshot" '/// Final selected-unit CP435'
$predecessorBlock = Get-Cp435SnapshotBlock $predecessorText 'PurchasedAirCalcHeatingOperatingModeDeadbandAssignmentSnapshot' '/// Final selected-unit CP434'
$fields = @([regex]::Matches($snapshotBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value }); $predecessorFields = @([regex]::Matches($predecessorBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value })
if ($predecessorFields.Count -ne 361 -or $fields.Count -ne 385 -or @($fields | Select-Object -Unique).Count -ne 385 -or ($fields[0..357] -join '|') -cne ($predecessorFields[0..357] -join '|')) { throw 'CP435 exact unique 385-field/CP434-first-358 schema drift' }
$tail = @('predecessor_cp434_resulting_supply_humidity_ratio','predecessor_cp434_resulting_supply_enthalpy_j_per_kg','predecessor_cp434_resulting_supply_temperature_c','heating_outdoor_air_maximum_flow_guard_evaluated','heating_limit_flow_rate_comparison_evaluated','heating_limit_flow_rate_value','heating_limit_flow_rate_comparison_satisfied','heating_limit_flow_rate_and_capacity_comparison_evaluated','heating_limit_flow_rate_and_capacity_value','heating_limit_flow_rate_and_capacity_comparison_satisfied','heating_flow_limit_active','heating_flow_limit_selector_rejected','cp311_same_call_outdoor_air_mass_flow_rate_bit_corroborated','outdoor_air_mass_flow_rate_read_after_heating_limit_short_circuit','outdoor_air_mass_flow_rate_for_heating_maximum_flow_guard_kg_per_s','maximum_heating_air_mass_flow_rate_read_after_heating_limit_short_circuit','maximum_heating_air_mass_flow_rate_for_guard_kg_per_s','outdoor_air_mass_flow_rate_maximum_heating_air_mass_flow_rate_comparison_evaluated','outdoor_air_mass_flow_rate_strictly_greater_than_maximum_heating_air_mass_flow_rate','maximum_heating_flow_body_entered','heating_outdoor_air_maximum_flow_guard_false_fallthrough','cp434_retained_supply_humidity_ratio_state_owned','cp434_retained_supply_enthalpy_state_owned','cp434_retained_supply_temperature_state_owned','resulting_supply_humidity_ratio','resulting_supply_enthalpy_j_per_kg','resulting_supply_temperature_c')
if (($fields[358..384] -join '|') -cne ($tail -join '|') -or [regex]::Matches($snapshotBlock,'Option<f64>').Count -ne 133 -or [regex]::Matches($snapshotBlock,'Option<bool>').Count -ne 8 -or ([regex]::Matches($snapshotBlock,'Option<').Count - 133 - 8) -ne 6) { throw 'CP435 locked 385/133/8/6 schema/tail drift' }
foreach ($pattern in @('heating_limit_flow_rate_comparison_satisfied:\s*route','heating_limit_flow_rate_and_capacity_comparison_satisfied:\s*route','heating_flow_limit_active:\s*route','then_some\(route\.body_entered\)','maximum_heating_flow_body_entered:\s*route\.body_entered','heating_outdoor_air_maximum_flow_guard_false_fallthrough:\s*route\.false_fallthrough')) { Assert-Contains -Path $snapshot -Pattern $pattern -Description 'CP435 optional-bool/outcome snapshot semantics' }
foreach ($pattern in @('\[64usize,\s*58,\s*6,\s*3,\s*3\]','20usize\s*\+\s*44','385','133','Option<bool>"\)\.count\(\),\s*8','\.matches\("    pub calculation_"\)\s*\.count\(\),\s*129','cp435_new_state_has_three_zeroed_lossless_route_partitions','cp435_is_ordered_after_cp434_and_does_not_feed_numerics')) { Assert-Contains -Path $coupledTests -Pattern $pattern -Description 'CP435 route/schema/binding/no-feed regression' }
foreach ($pattern in @('serializer_source_preserves_cp434_prefix_and_extends_exact_35_key_tail','cp434_snapshot_json\(predecessor\)','keys\.len\(\),\s*35','keys\[34\],\s*"resulting_supply_temperature_c_ieee_bits"')) { Assert-Contains -Path $serializationSnapshot -Pattern $pattern -Description 'CP435 CP434-prefix/35-key serializer contract' }
foreach ($pattern in @('latest\.len\(\),\s*518','actual\.len\(\),\s*518','ends_with\("_ieee_bits"\)\)\s*\.count\(\),\s*133','fields\.len\(\),\s*385','snapshot\.matches\("Option<f64>"\)\.count\(\),\s*133','snapshot\.matches\("Option<bool>"\)\.count\(\),\s*8','fields\.len\(\),\s*129','fields\[124\].*heating_operating_mode_deadband_assignment','fields\[125\].*heating_outdoor_air_maximum_flow_guard')) { Assert-Contains -Path $arbitrary -Pattern $pattern -Description 'actual CP435 JSON/IEEE/schema/binding contract' }
Assert-PatternsInOrder -Path $binding -Patterns @("let\s+calculation_$predecessorStem\s*=","let\s+calculation_$stem\s*=",'let\s+unit_available\s*=','let\s+coupling\s*=') -Description 'CP434-to-CP435-to-numerical order'
Assert-PatternsInOrder -Path $scheduled -Patterns @("pub\s+calculation_$predecessorStem\s*:","pub\s+calculation_$stem\s*:",'pub\s+coupling\s*:') -Description 'scheduled CP434-to-CP435 order'
$scheduledFields = @([regex]::Matches((Read-RepoText -Path $scheduled), '(?m)^\s*pub\s+(?<name>calculation_[A-Za-z0-9_]+)\s*:') | ForEach-Object { $_.Groups['name'].Value })
if ($scheduledFields.Count -ne 129 -or $scheduledFields[124] -cne 'calculation_heating_operating_mode_deadband_assignment' -or $scheduledFields[125] -cne 'calculation_heating_outdoor_air_maximum_flow_guard') { throw 'CP435 exact binding index 124/125/current 129 drift' }
foreach ($test in @('scheduled_binding_advances_cp435_after_cp434_before_unchanged_coupling','cp435_adapter_accepts_only_the_cp434_snapshot_and_no_scalar_input','cp435_remains_index_125_in_current_129_snapshot_binding')) { Assert-Contains -Path $adapterTests -Pattern $test -Description 'CP435 adapter/current-binding regression' }
foreach ($pattern in @('cp311_same_call_outdoor_air_mass_flow_rate_bit_corroborated','maximum_heating_air_mass_flow_rate_kg_per_s','parent_call_ordinal\s*==\s*call_ordinal','let\s+evaluations\s*=\s*checked_add\(false_fallthroughs,\s*body_entries','let\s+flow_limit_active\s*=\s*checked_add','evaluations\.checked_sub\(flow_limit_active\)','outdoor_air_read_count",\s*flow_limit_active','source_site_execution_count",\s*expected_sites','value\.to_bits\(\)\s*==\s*0\.0f64\.to_bits\(\)','"public_body_entry_count",\s*0,\s*body_entries','&&\s*!body')) { Assert-Contains -Path $coupled -Pattern $pattern -Description 'CP435 public exact-release/no-body validation' }
foreach ($pattern in @('validate_direct_lifecycle','validate_public_route_contract','maximum_heating_flow_body_entry_route_counts','let\s+expected_evaluated\s*=\s*if\s+index\s*==\s*1\s*\{\s*predecessor_count\s*\}\s*else\s*\{\s*0\s*\}','evaluated\s*!=\s*expected_evaluated','let\s+evaluations\s*=\s*checked_add\(false_fallthroughs,\s*body_entries','let\s+selected_flow\s*=\s*checked_add','evaluations\s*\.checked_sub\(selected_flow\)','selected_flow\.checked_mul\(3\)','body_count\s*!=\s*0','validator_is_structural_public_only_and_has_no_numerical_or_dto_feed')) { Assert-Contains -Path $pipelineValidation -Pattern $pattern -Description 'CP435 pipeline structural/no-feed seal' }
foreach ($pattern in @('provenance_is_exact','guard_shape_is_exact','option_has_bits','0\.0','Some\(false\)','!snapshot\.maximum_heating_flow_body_entered')) { Assert-Contains -Path $pipelineLineage -Pattern $pattern -Description 'CP435 owned-read/strict-false lineage seal' }
Assert-Contains -Path $pipelineRoot -Pattern 'non_direct_runtime_rejects_cp316_through_cp438_lifecycle_evidence' -Description 'CP435 non-direct firewall'
Assert-Contains -Path $pipelineRoot -Pattern 'purchased_air_calc_heating_outdoor_air_maximum_flow_guard_lifecycle' -Description 'CP435 lifecycle JSON field'
$ledger = Read-RepoText -Path 'specs\algorithm_ledger.toml'; $capabilities = Read-RepoText -Path 'specs\capabilities.toml'
if ([regex]::Matches($ledger,[regex]::Escape('CP435 supersedes only CP434')).Count -ne 1 -or [regex]::Matches($capabilities,[regex]::Escape('CP435 additionally requires')).Count -ne 1) { throw 'CP435 bounded spec addendum drift' }
foreach ($text in @($ledger,$capabilities)) { foreach ($claim in @('54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005','physical-line-2361','first 358 nonterminal fields','first 483 nonterminal keys','385','518','133','373 total','240 public','133 internal')) { if (-not $text.Contains($claim)) { throw "CP435 spec claim missing $claim" } }; foreach ($site in $sites) { if (-not $text.Contains($site)) { throw "CP435 spec source site missing $site" } } }
if ([regex]::Matches($ledger,'(?m)^\[\[algorithm\]\]\r?$').Count -ne 32 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"state_mapped"\r?$').Count -ne 58 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"source_mapped"\r?$').Count -ne 235 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.required_for_full_domain\s*=\s*true\r?$').Count -ne 170) { throw 'CP435 unchanged algorithm/routine count drift' }
Assert-NotContains -Path 'docs\src\current\roadmap.md' -Pattern '(?m)^## CP435\b' -Description 'Roadmap non-promotion'; Assert-NotContains -Path 'docs\src\porting-map\psychrometrics-source-map.md' -Pattern '(?m)^## CP435\b' -Description 'psychrometrics non-promotion'
$auditRoot = 'scripts\quality\ideal-loads-structure-audit'; $audits = @(Get-ChildItem $auditRoot -Filter 'cp*.ps1' -File)
$historical = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -eq 326) -or ([int]$Matches.n -ge 329 -and [int]$Matches.n -le 434)) })
if ($historical.Count -ne 107 -or @($historical | Where-Object { $_.BaseName -match '^cp(?:327|328)-' }).Count) { throw 'CP435 exact 107 historical leaf set drift' }
$firewall = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 334 -and [int]$Matches.n -le 435 }); $script = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 337 -and [int]$Matches.n -le 435 }); $internal = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 367 -and [int]$Matches.n -le 435 }); $generated = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 335 -and [int]$Matches.n -le 435 })
if ($firewall.Count -ne 102 -or $script.Count -ne 99 -or $internal.Count -ne 69 -or $generated.Count -ne 101) { throw 'CP435 propagation range cardinality drift' }
$staleFirewall = 'non_direct_runtime_rejects_cp316_through_cp43' + '4_lifecycle_evidence'; $staleScript = 'script_count = 37' + '2'; $staleGeneratedTotal = '\| 37' + '2 \|'; $staleGeneratedInternal = '\| 13' + '2 \|'
foreach ($file in $firewall) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('non_direct_runtime_rejects_cp316_through_cp438_lifecycle_evidence') -or $text.Contains($staleFirewall)) { throw "CP435 firewall propagation drift $($file.Name)" } }
foreach ($file in $script) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('script_count = 376') -or $text.Contains($staleScript)) { throw "CP435 inventory-total propagation drift $($file.Name)" } }
$internalClassification = '\[regex\]::Matches\(\s*\$[A-Za-z_][A-Za-z0-9_]*\s*,\s*''\(\?m\)\^classification\s*\=\s*"internal"(?:\\r\?)?\$''\s*\)\s*\.Count\s*-ne\s*(?<count>\d+)'
foreach ($file in $internal) { $text = Read-RepoText -Path $file.FullName; $matches = [regex]::Matches($text,$internalClassification); if ($matches.Count -ne 1 -or $matches[0].Groups['count'].Value -cne '136') { throw "CP435 internal propagation drift $($file.Name)" } }
foreach ($file in $generated) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('\| 376 \|') -or -not $text.Contains('\| 136 \|') -or $text.Contains($staleGeneratedTotal) -or $text.Contains($staleGeneratedInternal)) { throw "CP435 generated propagation drift $($file.Name)" } }
$helpers = @((Get-ChildItem $auditRoot -Filter 'cp326-*.ps1' -File); Get-ChildItem $auditRoot -Filter 'cp3*.ps1' -File | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 329 -and [int]$Matches.n -le 344 })
if ($helpers.Count -ne 17) { throw 'CP435 helper set drift' }
foreach ($file in $helpers) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains("calculation_$stem") -or -not $text.Contains("advance_$stem") -or -not $text.Contains('CP340 through CP438')) { throw "CP435 helper strip/whitelist drift $($file.Name)" } }
$terminal = @((Get-ChildItem $auditRoot -Filter 'cp345-*.ps1' -File); $audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -ge 377 -and [int]$Matches.n -le 392) -or ([int]$Matches.n -ge 394 -and [int]$Matches.n -le 434)) })
if ($terminal.Count -ne 58) { throw 'CP435 terminal set drift' }
foreach ($file in $terminal) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('$cp435Call') -or -not $text.Contains('CP434-to-CP435') -or -not $text.Contains('CP438-to-numerical') -or -not $text.Contains("-Pattern ('Assert-Contains[^\r\n]+CP434-to-' + 'numerical')")) { throw "CP435 terminal propagation drift $($file.Name)" } }; Assert-Contains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern '\$cp436Call' -Description 'CP436 terminal capture'; Assert-Contains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern 'CP435-to-CP436' -Description 'CP435-to-CP436 terminal interval'; Assert-NotContains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern ('Assert-Contains[^\r\n]+CP435-to-' + 'numerical') -Description 'stale CP435 numerical interval'
$live = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 421 -and [int]$Matches.n -le 434 })
if ($live.Count -ne 14) { throw 'CP435 live binding set drift' }
$staleLiveBinding = 'current_12' + '6_snapshot_binding|binding_is_12' + '6|(?:binding|calculation_fields|scheduledFields|scheduled|pub calculation_)[^\r\n]{0,240}(?:Count-ne12' + '6|,\s*\\s\*12' + '6)'
foreach ($file in $live) { $text = Read-RepoText -Path $file.FullName; if ($text -notmatch 'current_129_snapshot_binding|binding_is_129|Count-ne129|,\s*\\s\*129' -or $text -match $staleLiveBinding) { throw "CP435 current-129 propagation drift $($file.Name)" } }
$recent = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 425 -and [int]$Matches.n -le 434 }); if ($recent.Count -ne 10) { throw 'CP435 recent binding set drift' }
foreach ($file in $recent) { Assert-Contains -Path $file.FullName -Pattern "calculation_$stem" -Description 'CP435 recent binding propagation' }
$cp424 = Get-ChildItem $auditRoot -Filter 'cp424-*.ps1' -File; Assert-Contains -Path $cp424.FullName -Pattern 'calculation_heating_mode_guard_else_branch_entry' -Description 'CP424 retains CP433 registration'; Assert-NotContains -Path $cp424.FullName -Pattern "calculation_$stem" -Description 'CP424 excludes CP435 registration'
$manualAudits = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 424 -and [int]$Matches.n -le 434 }); if ($manualAudits.Count -ne 11) { throw 'CP435 manual cumulative audit set drift' }
foreach ($file in $manualAudits) { if (-not (Read-RepoText -Path $file.FullName).Contains('+3638+3009+3458')) { throw "CP435 manual cumulative propagation drift $($file.Name)" } }
$manuals = @([PSCustomObject]@{Path='docs\src\current\current-status.md';Length=486822;Hash='052C78C418678E512911B940B6C9977858D9756E616F9A167F09429E04D3F598'},[PSCustomObject]@{Path='docs\src\current\project-contract.md';Length=1438270;Hash='DE7384F45415ABCA7D28D00E1C4EB1BB0E146FB75ADB47EAE5D077E93C90DB49'},[PSCustomObject]@{Path='docs\src\porting-map\heat-balance-source-map.md';Length=3903056;Hash='7C5A037574E73B1ABBF57DABA7FEA3C5B3184F2F8D6F9CB455FDF984B089A1E0'},[PSCustomObject]@{Path='docs\src\porting-map\ideal-loads-source-map.md';Length=1442397;Hash='AA42FCB0EA5F9304FB4BF66CE654977B5C601F121A814CBCF6DED580489C60D7'},[PSCustomObject]@{Path='docs\src\porting-map\zone-air-update-map.md';Length=1641835;Hash='BAFC9047554D228DAEA8971854D1FC15505EBF2DE4E2BEDA09D722CEB8861D52'})
$canonical = $null
foreach ($manual in $manuals) { $bytes = [IO.File]::ReadAllBytes($manual.Path); if ($bytes.Length -ne $manual.Length + 3638 + 3009 + 3458 + 3655 -or [Array]::IndexOf($bytes,[byte]13) -ne -1 -or $bytes[-1] -ne 10) { throw "CP435 manual byte shape drift $($manual.Path)" }; $prefix = New-Object byte[] $manual.Length; [Array]::Copy($bytes,$prefix,$manual.Length); if ((Get-Cp435Sha $prefix) -cne $manual.Hash) { throw "CP435 manual prefix drift $($manual.Path)" }; $suffix = New-Object byte[] 3638; [Array]::Copy($bytes,$manual.Length,$suffix,0,3638); if ((Get-Cp435Sha $suffix) -cne '954C04C36CF7BB4B178387D9E7BC6D0F232A522EA5901BD4F27FCE1962705F62') { throw "CP435 manual suffix drift $($manual.Path)" }; $text = [Text.UTF8Encoding]::new($false,$true).GetString($suffix); if ($null -eq $canonical) { $canonical = $text } elseif ($text -cne $canonical) { throw "CP435 canonical manual drift $($manual.Path)" } }
foreach ($pattern in @('(?m)^## CP435 heating outdoor-air maximum-flow guard$','source lines 2361-2362','line 2363.*first excluded lexical and executable','six textual sites','no C\+\+ operand-evaluation-order claim','T435=64','Z435=58','G435=6','F435=3','B435=3','S435=33','20/44','active public/private 2/4','three width-36','FlowRateAndCapacity','first selector comparison false','reach and satisfy the second selector comparison','first 358 nonterminal fields','385 unique Rust fields','133 `Option<f64>`','eight optional comparison bools','six optional enums','518 unique keys','133 adjacent IEEE sidecars','37/42/57','index 125','current count 126','does not consume, reconcile with, feed','373 total','240 public','133 internal')) { if ($canonical -notmatch "(?is)$pattern") { throw "CP435 documentation claim missing $pattern" } }
$master = Read-RepoText -Path 'scripts\quality\ideal-loads-structure-audit.ps1'; $leaf = Split-Path -Leaf $audit; $previous = $master.IndexOf('cp434-heating-operating-mode-deadband-assignment.ps1'); $current = $master.IndexOf($leaf); $done = $master.IndexOf('Write-Host "IdealLoads structure audit complete."')
if ($previous -lt 0 -or $current -le $previous -or $done -le $current -or [regex]::Matches($master,[regex]::Escape($leaf)).Count -ne 1) { throw 'CP435 master order/uniqueness drift' }
if ((Get-Content 'scripts\quality\ideal-loads-structure-audit.ps1').Count -ne 4201 -or (Get-Content 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1').Count -ne 1200 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\calc.rs').Count -ne 99 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\init\state\witnesses.rs').Count -ne 275 -or @(Get-Content 'crates\ep_runtime\src\ideal_loads\init\state.rs' | Where-Object { $_ -match '\S' }).Count -ne 380 -or (Get-Content $scheduled).Count -gt 500) { throw 'CP435 fixed cap drift' }
$inventory = Read-RepoText -Path 'specs\script_inventory.toml'; foreach ($pattern in @('script_count = 376','dev_command_count = 238','unused_script_count = 0','unreachable_count = 0')) { if ($inventory -notmatch $pattern) { throw "CP435 inventory missing $pattern" } }
if ([regex]::Matches($inventory,'(?m)^classification = "public"$').Count -ne 240 -or [regex]::Matches($inventory,'(?m)^classification = "internal"$').Count -ne 136) { throw 'CP435 inventory classification drift' }
Assert-Contains -Path 'specs\script_inventory.toml' -Pattern 'cp435-heating-outdoor-air-maximum-flow-guard\.ps1' -Description 'CP435 inventory record'; Assert-Contains -Path 'docs\src\generated\algorithm-ledger.md' -Pattern 'CP435 supersedes only CP434' -Description 'generated algorithm'; Assert-Contains -Path 'docs\src\generated\capability-index.md' -Pattern 'CP435 additionally requires' -Description 'generated capability'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 376 \|' -Description 'generated total'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 136 \|' -Description 'generated internal'
Write-Host 'CP435 heating outdoor-air maximum-flow guard structure audit passed.'
}
Assert-Contains -Path 'crates\ep_runtime\src\ideal_loads\binding.rs' -Pattern 'calculation_heating_outdoor_air_maximum_flow_body_volume_flow_assignment' -Description 'CP436 recent binding propagation'; Assert-Contains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern '\$cp437Call' -Description 'CP437 terminal capture'; Assert-Contains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern 'CP436-to-CP437' -Description 'CP436-to-CP437 terminal interval'; Assert-NotContains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern ('Assert-Contains[^\r\n]+CP436-to-' + 'numerical') -Description 'stale CP436 numerical interval'; Assert-Contains -Path 'crates\ep_runtime\src\ideal_loads\binding.rs' -Pattern 'calculation_heating_outdoor_air_maximum_flow_first_warning_guard' -Description 'CP437 recent binding propagation'; Assert-Contains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern '\$cp438Call' -Description 'CP438 terminal capture'; Assert-Contains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern 'CP437-to-CP438' -Description 'CP437-to-CP438 terminal interval'; Assert-NotContains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern ('Assert-Contains[^\r\n]+CP437-to-' + 'numerical') -Description 'stale CP437 numerical interval'; Assert-Contains -Path 'crates\ep_runtime\src\ideal_loads\binding.rs' -Pattern 'calculation_heating_outdoor_air_maximum_flow_first_warning_counter_increment' -Description 'CP438 recent binding propagation'
