# CP437 maps PurchasedAirManager.cc physical executable line 2364's heating outdoor-air maximum-flow first-warning guard.
& {
function Get-Cp437Sha([byte[]]$Bytes) {
    $sha = [Security.Cryptography.SHA256]::Create()
    try { return ([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-', '') } finally { $sha.Dispose() }
}
function Get-Cp437SnapshotBlock([string]$Text, [string]$Type, [string]$EndMarker) {
    $start = $Text.IndexOf("pub struct $Type")
    $end = $Text.IndexOf($EndMarker, $start)
    if ($start -lt 0 -or $end -le $start) { throw "CP437 snapshot block drift: $Type" }
    return $Text.Substring($start, $end - $start)
}
$stem = 'heating_outdoor_air_maximum_flow_first_warning_guard'
$predecessorStem = 'heating_outdoor_air_maximum_flow_body_volume_flow_assignment'
$typeStem = 'PurchasedAirCalcHeatingOutdoorAirMaximumFlowFirstWarningGuard'
$source = '.reference\energyplus-src\26.1.0\src\EnergyPlus\PurchasedAirManager.cc'
$module = "crates\ep_runtime\src\ideal_loads\calc\$stem.rs"; $predecessorModule = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem.rs"
$root = "crates\ep_runtime\src\ideal_loads\calc\$stem"; $predecessorRoot = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem"
$release = "$root\release.rs"; $prefix = "$root\release\prefix.rs"; $runtimeValidation = "$root\release\runtime_validation.rs"; $snapshotValidation = "$root\release\snapshot_validation.rs"; $state = "$root\state.rs"; $transition = "$root\transition.rs"; $accounting = "$root\transition\accounting.rs"; $snapshot = "$root\transition\snapshot.rs"; $tests = "$root\tests.rs"; $schemaTests = "$root\tests\schema_prefix.rs"
$predecessorCommitted = "$predecessorRoot\release\committed.rs"; $predecessorCommittedTests = "$predecessorRoot\tests\committed_seal.rs"
$binding = 'crates\ep_runtime\src\ideal_loads\binding.rs'; $scheduled = 'crates\ep_runtime\src\ideal_loads\binding\scheduled_output.rs'; $adapter = "crates\ep_runtime\src\ideal_loads\binding\$stem.rs"; $adapterTests = "crates\ep_runtime\src\ideal_loads\binding\$($stem)_tests.rs"
$coupled = "crates\ep_runtime\src\ideal_loads\coupled_runtime\$($stem)_validation.rs"; $coupledTests = 'crates\ep_runtime\src\ideal_loads\test_coupled_runtime_cp437.rs'; $coupledOutput = "crates\ep_runtime\src\ideal_loads\coupled_output_tests\$($stem)_fixture.rs"
$pipelineRoot = 'crates\ep_run\src\pipeline.rs'; $pipeline = "crates\ep_run\src\pipeline\purchased_air_$stem"; $pipelineModule = "$pipeline.rs"; $serialization = "$pipeline\serialization.rs"; $serializationSnapshot = "$pipeline\serialization\snapshot.rs"; $pipelineValidation = "$pipeline\validation.rs"; $pipelineLineage = "$pipeline\validation\lineage.rs"
$arbitrary = 'crates\ep_run\tests\arbitrary_run_ideal_loads\cp437_assertions.rs'; $audit = "scripts\quality\ideal-loads-structure-audit\cp437-$($stem -replace '_','-').ps1"
foreach ($file in @($source,$module,$predecessorModule,$release,$prefix,$runtimeValidation,$snapshotValidation,$state,$transition,$accounting,$snapshot,$tests,$schemaTests,$predecessorCommitted,$predecessorCommittedTests,$binding,$scheduled,$adapter,$adapterTests,$coupled,$coupledTests,$coupledOutput,$pipelineRoot,$pipelineModule,$serialization,$serializationSnapshot,$pipelineValidation,$pipelineLineage,$arbitrary,$audit)) { Assert-FileExists -Path $file -Description 'CP437 implementation/audit file' }
$bounded = @($audit,$module,$pipelineModule) + @((Get-ChildItem $root -Recurse -File -Filter '*.rs').FullName) + @((Get-ChildItem $pipeline -Recurse -File -Filter '*.rs').FullName)
foreach ($file in $bounded) { Assert-LineLimit -Path $file -Limit 500 -Description 'bounded CP437 file' }
$sourceBytes = [IO.File]::ReadAllBytes($source)
if ((Get-Cp437Sha $sourceBytes) -cne '54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005') { throw 'CP437 pinned PurchasedAirManager.cc hash drift' }
$sourceLines = Get-Content -LiteralPath $source
if ($sourceLines[2363].Trim() -cne 'if (PurchAir.OAFlowMaxHeatOutputError < 1) {' -or $sourceLines[2364].Trim() -cne '++PurchAir.OAFlowMaxHeatOutputError;') { throw 'CP437 physical 2364-2365 boundary drift' }
$sites = @('read-state-owned-outdoor-air-flow-maximum-heating-output-error-count','compare-outdoor-air-flow-maximum-heating-output-error-count-less-than-one','enter-heating-outdoor-air-maximum-flow-first-warning-branch-if-satisfied')
Assert-ExactStringArray -Path $module -Name 'PURCHASED_AIR_CALC_HEATING_OUTDOOR_AIR_MAXIMUM_FLOW_FIRST_WARNING_GUARD_SOURCE_ORDER' -Expected $sites -Description 'three CP437 textual source sites'
foreach ($pattern in @('EnergyPlus 26\.1 PurchasedAirManager\.cc:2364','EnergyPlus 26\.1 PurchasedAirManager\.cc:2365','PurchasedAirCalcHeatingOutdoorAirMaximumFlowFirstWarningGuardSnapshot')) { Assert-Contains -Path $module -Pattern $pattern -Description 'CP437 boundary/type contract' }
$core = @(Get-ChildItem -LiteralPath $root -Recurse -File -Filter '*.rs'); $predecessorCore = @(Get-ChildItem -LiteralPath $predecessorRoot -Recurse -File -Filter '*.rs')
if ($core.Count -ne 11 -or @(Get-ChildItem "$root\tests" -File -Filter '*.rs').Count -ne 1) { throw 'CP437 exact eleven-subtree-file/one-test topology drift' }
if ($predecessorCore.Count -ne 13 -or @(Get-ChildItem "$predecessorRoot\tests" -File -Filter '*.rs').Count -ne 2) { throw 'CP437 exact sealed CP436 thirteen-subtree-file/two-test topology drift' }
$stateText = Read-RepoText -Path $state
$arrays = @([regex]::Matches($stateText, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*route_counts)\s*:\s*\[usize;\s*36\]') | ForEach-Object { $_.Groups['name'].Value })
$expectedArrays = @('predecessor_route_counts','predecessor_guard_false_fallthrough_route_counts','predecessor_guard_body_entry_route_counts','predecessor_volume_flow_assignment_route_counts','heating_outdoor_air_maximum_flow_first_warning_guard_false_fallthrough_route_counts','heating_outdoor_air_maximum_flow_first_warning_branch_entry_route_counts')
if ($arrays.Count -ne 6 -or ($arrays -join '|') -cne ($expectedArrays -join '|')) { throw 'CP437 exact six width-36 arrays drift' }
foreach ($pattern in @('outdoor_air_flow_maximum_heating_output_error_count:\s*usize','outdoor_air_flow_maximum_heating_output_error_count_state_owner_count','outdoor_air_flow_maximum_heating_output_error_count_read_count','outdoor_air_flow_maximum_heating_output_error_count_less_than_one_comparison_count','first_warning_branch_entry_count','guard_false_fallthrough_count')) { Assert-Contains -Path $state -Pattern $pattern -Description 'CP437 owned counter/accounting state' }
foreach ($pattern in @('let\s+guard_evaluated\s*=\s*predecessor_route\.assignment_executed','guard_evaluated\s*&&\s*outdoor_air_flow_maximum_heating_output_error_count\s*<\s*1','guard_evaluated\s*&&\s*!first_warning_branch_entered','then_some\(state\.outdoor_air_flow_maximum_heating_output_error_count\)')) { Assert-Contains -Path $transition -Pattern $pattern -Description 'CP437 exact integer guard semantics' }
foreach ($pattern in @('usize::from\(route\.guard_evaluated\)\s*\*\s*2\s*\+\s*usize::from\(route\.first_warning_branch_entered\)','source_site_execution_count\s*\+=\s*2','source_site_execution_count\s*\+=\s*1','route\.predecessor_assignment_executed\s*==\s*route\.guard_evaluated')) { Assert-Contains -Path $accounting -Pattern $pattern -Description 'CP437 transactional three-site accounting' }
foreach ($pattern in @('heating_outdoor_air_maximum_flow_body_volume_flow_assignment_committed_latest_route\(','state\.latest_route','snapshots_match_bit_exact','state_counts_are_consistent','predecessor_counts_match')) { Assert-Contains -Path $predecessorCommitted -Pattern $pattern -Description 'CP436 committed retained-route seal' }
foreach ($pattern in @('cp436_committed_seal_is_retained_constant_time_and_owner_lazy','cp436_committed_seal_rejects_latest_witness_route_and_accounting_forgeries','private_characterization','DirectZonePurchasedAirCouplingInput')) { Assert-Contains -Path $predecessorCommittedTests -Pattern $pattern -Description 'CP436 committed-seal regression' }
foreach ($pattern in @('heating_outdoor_air_maximum_flow_body_volume_flow_assignment_committed_latest_route\(','if\s+route\.guard_evaluated','ExactReleaseReductionViolated','let\s+mut\s+next_state\s*=','outdoor_air_flow_maximum_heating_output_error_count:\s*usize')) { Assert-Contains -Path $release -Pattern $pattern -Description 'CP437 committed-predecessor/public/private release contract' }
foreach ($pattern in @('exhaustive_67_routes_preserve_20_47_visibility_and_split_six_private_evaluations','\(public,\s*67\s*-\s*public\),\s*\(20,\s*47\)','\(public_evaluations,\s*private_evaluations\),\s*\(0,\s*6\)','transition_count,\s*67','inactive_transition_count,\s*61','guard_evaluation_count,\s*6','first_warning_branch_entry_count,\s*3','guard_false_fallthrough_count,\s*3','source_site_execution_count,\s*15','cp436_supply_humidity_ratio_state_owner_count,\s*37','cp436_supply_enthalpy_state_owner_count,\s*42','cp436_supply_temperature_state_owner_count,\s*57','inactive_routes_do_not_read_or_expose_the_state_owned_counter','guard_reads_and_compares_without_incrementing_the_persistent_counter','cp437_new_state_has_six_zeroed_width_36_arrays','public_release_uses_cp436_committed_seal_and_rejects_private_guard_evaluation','cp437_subtree_is_twelve_files_and_every_file_is_bounded')) { Assert-Contains -Path $tests -Pattern $pattern -Description 'CP437 exhaustive/counter/topology regression' }
$moduleText = Read-RepoText -Path $module; $predecessorText = Read-RepoText -Path $predecessorModule
$snapshotBlock = Get-Cp437SnapshotBlock $moduleText "$($typeStem)Snapshot" '/// Final selected-unit CP437'
$predecessorBlock = Get-Cp437SnapshotBlock $predecessorText 'PurchasedAirCalcHeatingOutdoorAirMaximumFlowBodyVolumeFlowAssignmentSnapshot' '/// Final selected-unit CP436'
$fields = @([regex]::Matches($snapshotBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value }); $predecessorFields = @([regex]::Matches($predecessorBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value })
if ($predecessorFields.Count -ne 402 -or $fields.Count -ne 416 -or @($fields | Select-Object -Unique).Count -ne 416 -or ($fields[0..398] -join '|') -cne ($predecessorFields[0..398] -join '|')) { throw 'CP437 exact unique 416-field/CP436-first-399 schema drift' }
$tail = @('predecessor_cp436_resulting_supply_humidity_ratio','predecessor_cp436_resulting_supply_enthalpy_j_per_kg','predecessor_cp436_resulting_supply_temperature_c','heating_outdoor_air_maximum_flow_first_warning_guard_evaluated','cp436_retained_supply_humidity_ratio_state_owned','cp436_retained_supply_enthalpy_state_owned','cp436_retained_supply_temperature_state_owned','outdoor_air_flow_maximum_heating_output_error_count_state_owned','outdoor_air_flow_maximum_heating_output_error_count_read','outdoor_air_flow_maximum_heating_output_error_count_before','outdoor_air_flow_maximum_heating_output_error_count_less_than_one_comparison_evaluated','outdoor_air_flow_maximum_heating_output_error_count_less_than_one','heating_outdoor_air_maximum_flow_first_warning_branch_entered','heating_outdoor_air_maximum_flow_first_warning_guard_false_fallthrough','resulting_supply_humidity_ratio','resulting_supply_enthalpy_j_per_kg','resulting_supply_temperature_c')
if (($fields[399..415] -join '|') -cne ($tail -join '|') -or [regex]::Matches($snapshotBlock,'Option<f64>').Count -ne 143 -or [regex]::Matches($snapshotBlock,'Option<bool>').Count -ne 9 -or [regex]::Matches($snapshotBlock,'Option<usize>').Count -ne 1 -or ([regex]::Matches($snapshotBlock,'Option<').Count - 143 - 9 - 1) -ne 6) { throw 'CP437 locked 416/143/9/6/1 schema/tail drift' }
foreach ($pattern in @('cp437_schema_is_exact_416_143_9_6_1_with_cp436_first_399_and_locked_tail','assert_eq!\(&cp437\[\.\.399\],\s*&cp436\[\.\.399\]\)','outcomes,\s*67')) { Assert-Contains -Path $schemaTests -Pattern $pattern -Description 'CP437 schema/prefix regression' }
foreach ($pattern in @('outdoor_air_flow_maximum_heating_output_error_count_before:\s*warning_counter_before','outdoor_air_flow_maximum_heating_output_error_count_less_than_one:\s*warning_counter_before\.map\(\|counter\|\s*counter\s*<\s*1\)','resulting_supply_temperature_c:\s*predecessor\.resulting_supply_temperature_c')) { Assert-Contains -Path $snapshot -Pattern $pattern -Description 'CP437 snapshot guard/unchanged-output semantics' }
foreach ($pattern in @('\[67usize,\s*61,\s*6\]','20usize\s*\+\s*47','\(public_active,\s*private_active\)\s*=\s*\(0usize,\s*6usize\)','416','143','Option<bool>"\)\.count\(\),\s*9','Option<usize>"\)\.count\(\),\s*1','fields\.len\(\),\s*128','cp437_new_state_has_six_zeroed_lossless_route_partitions_and_owned_counter','cp437_is_ordered_after_cp436_and_does_not_feed_numerics')) { Assert-Contains -Path $coupledTests -Pattern $pattern -Description 'CP437 route/schema/binding/no-feed regression' }
foreach ($pattern in @('serializer_source_preserves_cp436_prefix_and_extends_exact_23_key_tail','cp436_snapshot_json\(predecessor\)','keys\.len\(\),\s*23','keys\[22\],\s*"resulting_supply_temperature_c_ieee_bits"')) { Assert-Contains -Path $serializationSnapshot -Pattern $pattern -Description 'CP437 CP436-prefix/23-key serializer contract' }
foreach ($pattern in @('latest\.len\(\),\s*559','actual\.len\(\),\s*559','ends_with\("_ieee_bits"\)\)\s*\.count\(\),\s*143','fields\.len\(\),\s*416','snapshot\.matches\("Option<f64>"\)\.count\(\),\s*143','snapshot\.matches\("Option<bool>"\)\.count\(\),\s*9','snapshot\.matches\("Option<usize>"\)\.count\(\),\s*1','fields\.len\(\),\s*128','fields\[126\][\s\S]*heating_outdoor_air_maximum_flow_body_volume_flow_assignment','fields\[127\][\s\S]*heating_outdoor_air_maximum_flow_first_warning_guard')) { Assert-Contains -Path $arbitrary -Pattern $pattern -Description 'actual CP437 JSON/IEEE/schema/binding contract' }
Assert-PatternsInOrder -Path $binding -Patterns @("let\s+calculation_$predecessorStem\s*=","let\s+calculation_$stem\s*=",'let\s+unit_available\s*=','let\s+coupling\s*=') -Description 'CP436-to-CP437-to-numerical order'
Assert-PatternsInOrder -Path $scheduled -Patterns @("pub\s+calculation_$predecessorStem\s*:","pub\s+calculation_$stem\s*:",'pub\s+coupling\s*:') -Description 'scheduled CP436-to-CP437 order'
$scheduledFields = @([regex]::Matches((Read-RepoText -Path $scheduled), '(?m)^\s*pub\s+(?<name>calculation_[A-Za-z0-9_]+)\s*:') | ForEach-Object { $_.Groups['name'].Value })
if ($scheduledFields.Count -ne 128 -or $scheduledFields[126] -cne 'calculation_heating_outdoor_air_maximum_flow_body_volume_flow_assignment' -or $scheduledFields[127] -cne 'calculation_heating_outdoor_air_maximum_flow_first_warning_guard') { throw 'CP437 exact binding index 126/127/current 128 drift' }
foreach ($test in @('scheduled_binding_advances_cp437_after_cp436_before_unchanged_coupling','cp437_adapter_accepts_only_the_cp436_snapshot_and_no_scalar_input','cp437_extends_current_scheduled_binding_from_127_to_128_snapshots')) { Assert-Contains -Path $adapterTests -Pattern $test -Description 'CP437 adapter/current-binding regression' }
foreach ($pattern in @('predecessor_volume_flow_assignment_route_counts','heating_outdoor_air_maximum_flow_first_warning_guard_false_fallthrough_route_counts','heating_outdoor_air_maximum_flow_first_warning_branch_entry_route_counts','public_guard_evaluation_count','warning_counter_state_owner_count','warning_counter_read_count','warning_counter_comparison_count','warning_counter_unchanged')) { Assert-Contains -Path $coupled -Pattern $pattern -Description 'CP437 public exact-release/no-counter-read validation' }
foreach ($pattern in @('validate_direct_lifecycle','validate_public_route_contract','assignment_count\s*!=\s*0','guard_evaluation_count','source_site_execution_count','lineage_is_exact')) { Assert-Contains -Path $pipelineValidation -Pattern $pattern -Description 'CP437 pipeline structural/no-feed seal' }
foreach ($pattern in @('guard_shape_is_exact','count\|\s*count\s*<\s*1','outdoor_air_flow_maximum_heating_output_error_count_before','heating_outdoor_air_maximum_flow_first_warning_guard_false_fallthrough','lineage_is_exact')) { Assert-Contains -Path $pipelineLineage -Pattern $pattern -Description 'CP437 exact guard/skip lineage seal' }
Assert-Contains -Path $pipelineRoot -Pattern 'non_direct_runtime_rejects_cp316_through_cp437_lifecycle_evidence' -Description 'CP437 non-direct firewall'
Assert-Contains -Path $pipelineRoot -Pattern 'purchased_air_calc_heating_outdoor_air_maximum_flow_first_warning_guard_lifecycle' -Description 'CP437 lifecycle JSON field'
$ledger = Read-RepoText -Path 'specs\algorithm_ledger.toml'; $capabilities = Read-RepoText -Path 'specs\capabilities.toml'
if ([regex]::Matches($ledger,[regex]::Escape('CP437 supersedes only CP436')).Count -ne 1 -or [regex]::Matches($capabilities,[regex]::Escape('CP437 additionally requires')).Count -ne 1) { throw 'CP437 bounded spec addendum drift' }
foreach ($text in @($ledger,$capabilities)) { foreach ($claim in @('54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005','physical-line-2364','first 399 nonterminal fields','first 536 nonterminal keys','416','559','143','375 total','240 public','135 internal')) { if (-not $text.Contains($claim)) { throw "CP437 spec claim missing $claim" } }; foreach ($site in $sites) { if (-not $text.Contains($site)) { throw "CP437 spec source site missing $site" } } }
if ([regex]::Matches($ledger,'(?m)^\[\[algorithm\]\]\r?$').Count -ne 32 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"state_mapped"\r?$').Count -ne 58 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"source_mapped"\r?$').Count -ne 235 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.required_for_full_domain\s*=\s*true\r?$').Count -ne 170) { throw 'CP437 unchanged algorithm/routine count drift' }
Assert-NotContains -Path 'docs\src\current\roadmap.md' -Pattern '(?m)^## CP437\b' -Description 'Roadmap non-promotion'; Assert-NotContains -Path 'docs\src\porting-map\psychrometrics-source-map.md' -Pattern '(?m)^## CP437\b' -Description 'psychrometrics non-promotion'
$auditRoot = 'scripts\quality\ideal-loads-structure-audit'; $audits = @(Get-ChildItem $auditRoot -Filter 'cp*.ps1' -File)
$historical = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -eq 326) -or ([int]$Matches.n -ge 329 -and [int]$Matches.n -le 436)) })
if ($historical.Count -ne 109 -or @($historical | Where-Object { $_.BaseName -match '^cp(?:327|328)-' }).Count) { throw 'CP437 exact 109 historical leaf set drift' }
$firewall = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 334 -and [int]$Matches.n -le 437 }); $script = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 337 -and [int]$Matches.n -le 437 }); $internal = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 367 -and [int]$Matches.n -le 437 }); $generated = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 335 -and [int]$Matches.n -le 437 })
if ($firewall.Count -ne 104 -or $script.Count -ne 101 -or $internal.Count -ne 71 -or $generated.Count -ne 103) { throw 'CP437 propagation range cardinality drift' }
foreach ($file in $firewall) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('non_direct_runtime_rejects_cp316_through_cp437_lifecycle_evidence')) { throw "CP437 firewall propagation drift $($file.Name)" } }
foreach ($file in $script) { if (-not (Read-RepoText -Path $file.FullName).Contains('script_count = 375')) { throw "CP437 inventory-total propagation drift $($file.Name)" } }
$internalClassification = '\[regex\]::Matches\(\s*\$[A-Za-z_][A-Za-z0-9_]*\s*,\s*''\(\?m\)\^classification\s*\=\s*"internal"(?:\\r\?)?\$''\s*\)\s*\.Count\s*-ne\s*(?<count>\d+)'
foreach ($file in $internal) { $matches = [regex]::Matches((Read-RepoText -Path $file.FullName),$internalClassification); if ($matches.Count -ne 1 -or $matches[0].Groups['count'].Value -cne '135') { throw "CP437 internal propagation drift $($file.Name)" } }
foreach ($file in $generated) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('\| 375 \|') -or -not $text.Contains('\| 135 \|')) { throw "CP437 generated propagation drift $($file.Name)" } }
$helpers = @((Get-ChildItem $auditRoot -Filter 'cp326-*.ps1' -File); Get-ChildItem $auditRoot -Filter 'cp3*.ps1' -File | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 329 -and [int]$Matches.n -le 344 })
if ($helpers.Count -ne 17) { throw 'CP437 helper set drift' }
foreach ($file in $helpers) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains("calculation_$stem") -or -not $text.Contains("advance_$stem") -or -not $text.Contains('CP340 through CP437')) { throw "CP437 helper strip/whitelist drift $($file.Name)" } }
$terminal = @((Get-ChildItem $auditRoot -Filter 'cp345-*.ps1' -File); $audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -ge 377 -and [int]$Matches.n -le 392) -or ([int]$Matches.n -ge 394 -and [int]$Matches.n -le 436)) })
if ($terminal.Count -ne 60) { throw 'CP437 terminal set drift' }
foreach ($file in $terminal) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('$cp437Call') -or -not $text.Contains('CP436-to-CP437') -or -not $text.Contains("-Pattern ('Assert-Contains[^\r\n]+CP436-to-' + 'numerical')")) { throw "CP437 terminal propagation drift $($file.Name)" } }
$live = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 421 -and [int]$Matches.n -le 436 })
if ($live.Count -ne 16) { throw 'CP437 live binding set drift' }
foreach ($file in $live) { $text = Read-RepoText -Path $file.FullName; if ($text -notmatch 'current_128_snapshot_binding|binding_is_128|Count-ne128|,\s*\\s\*128') { throw "CP437 current-128 propagation drift $($file.Name)" } }
$recent = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 425 -and [int]$Matches.n -le 436 }); if ($recent.Count -ne 12) { throw 'CP437 recent binding set drift' }
foreach ($file in $recent) { Assert-Contains -Path $file.FullName -Pattern "calculation_$stem" -Description 'CP437 recent binding propagation' }
$cp424 = Get-ChildItem $auditRoot -Filter 'cp424-*.ps1' -File; Assert-NotContains -Path $cp424.FullName -Pattern "calculation_$stem" -Description 'CP424 excludes CP437 registration'
$manuals = @([PSCustomObject]@{Path='docs\src\current\current-status.md';Length=493469;Hash='459FF472AF078A9D21EEEEF16C7C30694871A461A6DA13A66AF4C45DD26C7A2F'},[PSCustomObject]@{Path='docs\src\current\project-contract.md';Length=1444917;Hash='D202B8E99B724A336C6C18A7CCD62F528D997A9C9D636A087DDE5DC860BA3FDC'},[PSCustomObject]@{Path='docs\src\porting-map\heat-balance-source-map.md';Length=3909703;Hash='4B7070C25006E26BD5E291D72575287298FE1A69A8168535297AD1954DCBF9FE'},[PSCustomObject]@{Path='docs\src\porting-map\ideal-loads-source-map.md';Length=1449044;Hash='F8D37E076F5FFCA8888E3CB5B43375694C26CC86DBFE5D6F9D4A03B0A96EAB43'},[PSCustomObject]@{Path='docs\src\porting-map\zone-air-update-map.md';Length=1648482;Hash='94DFA0FD678419A44C3E968BF1A60A7FDD8F1709B60ADAAB15A99030B282501C'})
$canonical = $null
foreach ($manual in $manuals) { $bytes = [IO.File]::ReadAllBytes($manual.Path); if ($bytes.Length -ne $manual.Length + 3458 -or [Array]::IndexOf($bytes,[byte]13) -ne -1 -or $bytes[-1] -ne 10) { throw "CP437 manual byte shape drift $($manual.Path)" }; $head = New-Object byte[] $manual.Length; [Array]::Copy($bytes,$head,$manual.Length); if ((Get-Cp437Sha $head) -cne $manual.Hash) { throw "CP437 manual prefix drift $($manual.Path)" }; $suffix = New-Object byte[] 3458; [Array]::Copy($bytes,$manual.Length,$suffix,0,3458); if ((Get-Cp437Sha $suffix) -cne '70516D057817CE10184EF81134DB9C29D1AE461E924B1593D8EB3D9ED2857EF2') { throw "CP437 manual suffix drift $($manual.Path)" }; $text = [Text.UTF8Encoding]::new($false,$true).GetString($suffix); if ($null -eq $canonical) { $canonical = $text } elseif ($text -cne $canonical) { throw "CP437 canonical manual drift $($manual.Path)" } }
foreach ($pattern in @('(?m)^## CP437 heating outdoor-air maximum-flow first-warning guard$','physical-line-2364','line\s+2365.*first excluded\s+executable','three dependency-ordered textual','T437=67','Z437=61','G437=6','B437=3','F437=3','S437=15','20/47','active public/private 0/6','six width-36','first 399 nonterminal fields','416 unique Rust fields','143 `Option<f64>`','nine `Option<bool>`','six optional enums','one\s+`Option<usize>`','559 unique keys','143\s+adjacent\s+IEEE sidecars','37/42/57','index 127','current\s+count 128','zero public guard evaluations','375 total','240 public','135 internal')) { if ($canonical -notmatch "(?is)$pattern") { throw "CP437 documentation claim missing $pattern" } }
$master = Read-RepoText -Path 'scripts\quality\ideal-loads-structure-audit.ps1'; $leaf = Split-Path -Leaf $audit; $previous = $master.IndexOf('cp436-heating-outdoor-air-maximum-flow-body-volume-flow-assignment.ps1'); $current = $master.IndexOf($leaf); $done = $master.IndexOf('Write-Host "IdealLoads structure audit complete."')
if ($previous -lt 0 -or $current -le $previous -or $done -le $current -or [regex]::Matches($master,[regex]::Escape($leaf)).Count -ne 1) { throw 'CP437 master order/uniqueness drift' }
if ((Get-Content 'scripts\quality\ideal-loads-structure-audit.ps1').Count -ne 4200 -or (Get-Content 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1').Count -ne 1200 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\calc.rs').Count -ne 99 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\init\state\witnesses.rs').Count -ne 274 -or @(Get-Content 'crates\ep_runtime\src\ideal_loads\init\state.rs' | Where-Object { $_ -match '\S' }).Count -ne 380 -or (Get-Content $scheduled).Count -gt 500) { throw 'CP437 fixed cap drift' }
$inventory = Read-RepoText -Path 'specs\script_inventory.toml'; foreach ($pattern in @('script_count = 375','dev_command_count = 238','unused_script_count = 0','unreachable_count = 0')) { if ($inventory -notmatch $pattern) { throw "CP437 inventory missing $pattern" } }
if ([regex]::Matches($inventory,'(?m)^classification = "public"$').Count -ne 240 -or [regex]::Matches($inventory,'(?m)^classification = "internal"$').Count -ne 135) { throw 'CP437 inventory classification drift' }
Assert-Contains -Path 'specs\script_inventory.toml' -Pattern 'cp437-heating-outdoor-air-maximum-flow-first-warning-guard\.ps1' -Description 'CP437 inventory record'; Assert-Contains -Path 'docs\src\generated\algorithm-ledger.md' -Pattern 'CP437 supersedes only CP436' -Description 'generated algorithm'; Assert-Contains -Path 'docs\src\generated\capability-index.md' -Pattern 'CP437 additionally requires' -Description 'generated capability'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 375 \|' -Description 'generated total'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 135 \|' -Description 'generated internal'
Write-Host 'CP437 heating outdoor-air maximum-flow first-warning guard structure audit passed.'
}
