# CP436 maps PurchasedAirManager.cc physical executable line 2363's heating outdoor-air volume-flow assignment.
& {
function Get-Cp436Sha([byte[]]$Bytes) {
    $sha = [Security.Cryptography.SHA256]::Create()
    try { return ([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-', '') } finally { $sha.Dispose() }
}
function Get-Cp436SnapshotBlock([string]$Text, [string]$Type, [string]$EndMarker) {
    $start = $Text.IndexOf("pub struct $Type")
    $end = $Text.IndexOf($EndMarker, $start)
    if ($start -lt 0 -or $end -le $start) { throw "CP436 snapshot block drift: $Type" }
    return $Text.Substring($start, $end - $start)
}
$stem = 'heating_outdoor_air_maximum_flow_body_volume_flow_assignment'
$predecessorStem = 'heating_outdoor_air_maximum_flow_guard'
$typeStem = 'PurchasedAirCalcHeatingOutdoorAirMaximumFlowBodyVolumeFlowAssignment'
$source = '.reference\energyplus-src\26.1.0\src\EnergyPlus\PurchasedAirManager.cc'
$module = "crates\ep_runtime\src\ideal_loads\calc\$stem.rs"; $predecessorModule = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem.rs"
$root = "crates\ep_runtime\src\ideal_loads\calc\$stem"; $predecessorRoot = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem"
$release = "$root\release.rs"; $prefix = "$root\release\prefix.rs"; $snapshotValidation = "$root\release\snapshot_validation.rs"; $state = "$root\state.rs"; $transition = "$root\transition.rs"; $accounting = "$root\transition\accounting.rs"; $snapshot = "$root\transition\snapshot.rs"; $tests = "$root\tests.rs"; $schemaTests = "$root\tests\schema_prefix.rs"
$binding = 'crates\ep_runtime\src\ideal_loads\binding.rs'; $scheduled = 'crates\ep_runtime\src\ideal_loads\binding\scheduled_output.rs'; $adapter = "crates\ep_runtime\src\ideal_loads\binding\$stem.rs"; $adapterTests = "crates\ep_runtime\src\ideal_loads\binding\$($stem)_tests.rs"
$coupled = "crates\ep_runtime\src\ideal_loads\coupled_runtime\$($stem)_validation.rs"; $coupledTests = 'crates\ep_runtime\src\ideal_loads\test_coupled_runtime_cp436.rs'; $coupledOutput = "crates\ep_runtime\src\ideal_loads\coupled_output_tests\$($stem)_fixture.rs"
$pipelineRoot = 'crates\ep_run\src\pipeline.rs'; $pipeline = "crates\ep_run\src\pipeline\purchased_air_$stem"; $pipelineModule = "$pipeline.rs"; $serialization = "$pipeline\serialization.rs"; $serializationSnapshot = "$pipeline\serialization\snapshot.rs"; $pipelineValidation = "$pipeline\validation.rs"; $pipelineLineage = "$pipeline\validation\lineage.rs"
$arbitrary = 'crates\ep_run\tests\arbitrary_run_ideal_loads\cp436_assertions.rs'; $audit = "scripts\quality\ideal-loads-structure-audit\cp436-$($stem -replace '_','-').ps1"
foreach ($file in @($source,$module,$predecessorModule,$release,$prefix,$snapshotValidation,$state,$transition,$accounting,$snapshot,$tests,$schemaTests,$binding,$scheduled,$adapter,$adapterTests,$coupled,$coupledTests,$coupledOutput,$pipelineRoot,$pipelineModule,$serialization,$serializationSnapshot,$pipelineValidation,$pipelineLineage,$arbitrary,$audit)) { Assert-FileExists -Path $file -Description 'CP436 implementation/audit file' }
$bounded = @($audit,$module,$pipelineModule) + @((Get-ChildItem $root -Recurse -File -Filter '*.rs').FullName) + @((Get-ChildItem $pipeline -Recurse -File -Filter '*.rs').FullName)
foreach ($file in $bounded) { Assert-LineLimit -Path $file -Limit 500 -Description 'bounded CP436 file' }
$sourceBytes = [IO.File]::ReadAllBytes($source)
if ((Get-Cp436Sha $sourceBytes) -cne '54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005') { throw 'CP436 pinned PurchasedAirManager.cc hash drift' }
$sourceLines = Get-Content -LiteralPath $source
if ($sourceLines[2362].Trim() -cne 'OAVolFlowRate = OAMassFlowRate / state.dataEnvrn->StdRhoAir;' -or $sourceLines[2363].Trim() -cne 'if (PurchAir.OAFlowMaxHeatOutputError < 1) {') { throw 'CP436 physical 2363-2364 boundary drift' }
$sites = @('read-cp435-retained-outdoor-air-mass-flow-for-outdoor-air-volume-flow-division','read-environment-standard-air-density-for-outdoor-air-volume-flow-division','calculate-outdoor-air-mass-flow-divided-by-standard-air-density','assign-local-outdoor-air-volume-flow-rate')
Assert-ExactStringArray -Path $module -Name 'PURCHASED_AIR_CALC_HEATING_OUTDOOR_AIR_MAXIMUM_FLOW_BODY_VOLUME_FLOW_ASSIGNMENT_SOURCE_ORDER' -Expected $sites -Description 'four CP436 textual source sites'
foreach ($pattern in @('EnergyPlus 26\.1 PurchasedAirManager\.cc:2363','EnergyPlus 26\.1 PurchasedAirManager\.cc:2364','PurchasedAirCalcHeatingOutdoorAirMaximumFlowBodyVolumeFlowAssignmentSnapshot')) { Assert-Contains -Path $module -Pattern $pattern -Description 'CP436 boundary/type contract' }
$core = @(Get-ChildItem -LiteralPath $root -Recurse -File -Filter '*.rs'); $predecessorCore = @(Get-ChildItem -LiteralPath $predecessorRoot -Recurse -File -Filter '*.rs')
if ($core.Count -ne 13 -or @(Get-ChildItem "$root\tests" -File -Filter '*.rs').Count -ne 2) { throw 'CP436 exact successor-sealed thirteen-subtree-file/two-test topology drift' }
if ($predecessorCore.Count -ne 13 -or @(Get-ChildItem "$predecessorRoot\tests" -File -Filter '*.rs').Count -ne 2) { throw 'CP436 exact sealed CP435 thirteen-file/two-test topology drift' }
$stateText = Read-RepoText -Path $state
$arrays = @([regex]::Matches($stateText, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*route_counts)\s*:\s*\[usize;\s*36\]') | ForEach-Object { $_.Groups['name'].Value })
if ($arrays.Count -ne 4 -or ($arrays -join '|') -cne 'predecessor_route_counts|predecessor_guard_false_fallthrough_route_counts|predecessor_guard_body_entry_route_counts|heating_outdoor_air_volume_flow_assignment_route_counts') { throw 'CP436 exact four width-36 arrays drift' }
foreach ($pattern in @('outdoor_air_volume_flow_assignment_count','cp435_outdoor_air_mass_flow_rate_owned_read_count','outdoor_air_mass_flow_rate_for_volume_flow_division_read_count','begin_environment_standard_air_density_owner_count','standard_air_density_for_volume_flow_division_read_count','outdoor_air_mass_flow_rate_standard_air_density_division_count','local_outdoor_air_volume_flow_rate_assignment_write_count')) { Assert-Contains -Path $state -Pattern $pattern -Description 'CP436 state accounting' }
foreach ($pattern in @('route\.assignment_executed\s*&&\s*\(!standard_air_density_kg_per_m3\.is_finite\(\)','standard_air_density_kg_per_m3\s*<=\s*0\.0','outdoor_air_mass_flow_rate_kg_per_s\s*/\s*standard_air_density_kg_per_m3','then\(\|\|\s*outdoor_air_mass_flow_rate_kg_per_s')) { Assert-Contains -Path $transition -Pattern $pattern -Description 'CP436 exact division/density semantics' }
foreach ($pattern in @('fits\(count,\s*route\.assignment_executed\)','source_site_execution_count\s*\.checked_add\(if\s+route\.assignment_executed\s*\{\s*4','state\.heating_outdoor_air_volume_flow_assignment_route_counts\[index\]\s*\+=\s*1','state\.source_site_execution_count\s*\+=\s*4')) { Assert-Contains -Path $accounting -Pattern $pattern -Description 'CP436 transactional four-site accounting' }
foreach ($pattern in @('PURCHASED_AIR_CALC_HEATING_OUTDOOR_AIR_MAXIMUM_FLOW_GUARD_SOURCE','PURCHASED_AIR_CALC_HEATING_OUTDOOR_AIR_MAXIMUM_FLOW_GUARD_FIRST_EXCLUDED_SOURCE','PURCHASED_AIR_CALC_HEATING_OUTDOOR_AIR_MAXIMUM_FLOW_GUARD_SOURCE_ORDER')) { Assert-Contains -Path $prefix -Pattern $pattern -Description 'CP436 exact CP435 metadata reconstruction' }
foreach ($pattern in @('begin_environment_standard_air_density_is_bit_exact','density\.is_finite\(\)','density\s*>\s*0\.0','maximum_heating_air_mass_flow_rate_kg_per_s\.to_bits\(\)','expected_maximum_mass_flow\.to_bits\(\)','if\s+route\.assignment_executed','ExactReleaseReductionViolated','predecessor_cp435\.parent_call_ordinal\s*!=\s*unit\.init_call_count')) { Assert-Contains -Path $release -Pattern $pattern -Description 'CP436 BeginEnvironment/public-release seal' }
foreach ($pattern in @('exhaustive_64_routes_preserve_20_44_visibility_and_assign_only_three_private_bodies','predecessors\.len\(\),\s*64','\(public,\s*64\s*-\s*public\),\s*\(20,\s*44\)','\(public_assignments,\s*private_assignments\),\s*\(0,\s*3\)','transition_count,\s*64','inactive_transition_count,\s*61','outdoor_air_volume_flow_assignment_count,\s*3','source_site_execution_count,\s*12','expected\[0\]\[1\],\s*6','expected\[1\]\[1\],\s*3','expected\[2\]\[1\],\s*3','expected\[3\]\[1\],\s*3','cp435_supply_humidity_ratio_state_owner_count,\s*37','cp435_supply_enthalpy_state_owner_count,\s*42','cp435_supply_temperature_state_owner_count,\s*57','active_routes_reject_every_nonpositive_or_nonfinite_density_transactionally','inactive_routes_do_not_read_or_validate_density','cp436_subtree_is_twelve_files_and_every_file_is_bounded')) { Assert-Contains -Path $tests -Pattern $pattern -Description 'CP436 exhaustive/density/topology regression' }
$moduleText = Read-RepoText -Path $module; $predecessorText = Read-RepoText -Path $predecessorModule
$snapshotBlock = Get-Cp436SnapshotBlock $moduleText "$($typeStem)Snapshot" '/// Final selected-unit CP436'
$predecessorBlock = Get-Cp436SnapshotBlock $predecessorText 'PurchasedAirCalcHeatingOutdoorAirMaximumFlowGuardSnapshot' '/// Final selected-unit CP435'
$fields = @([regex]::Matches($snapshotBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value }); $predecessorFields = @([regex]::Matches($predecessorBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value })
if ($predecessorFields.Count -ne 385 -or $fields.Count -ne 402 -or @($fields | Select-Object -Unique).Count -ne 402 -or ($fields[0..381] -join '|') -cne ($predecessorFields[0..381] -join '|')) { throw 'CP436 exact unique 402-field/CP435-first-382 schema drift' }
$tail = @('predecessor_cp435_resulting_supply_humidity_ratio','predecessor_cp435_resulting_supply_enthalpy_j_per_kg','predecessor_cp435_resulting_supply_temperature_c','heating_outdoor_air_maximum_flow_body_volume_flow_assignment_executed','cp435_retained_supply_humidity_ratio_state_owned','cp435_retained_supply_enthalpy_state_owned','cp435_retained_supply_temperature_state_owned','cp435_retained_outdoor_air_mass_flow_rate_owned_read','outdoor_air_mass_flow_rate_for_outdoor_air_volume_flow_division_read','outdoor_air_mass_flow_rate_for_outdoor_air_volume_flow_division_kg_per_s','begin_environment_standard_air_density_owned_read','standard_air_density_for_outdoor_air_volume_flow_division_read','standard_air_density_for_outdoor_air_volume_flow_division_kg_per_m3','outdoor_air_mass_flow_rate_standard_air_density_division_evaluated','calculated_outdoor_air_volume_flow_rate_m3_per_s','local_outdoor_air_volume_flow_rate_assignment_performed','assigned_outdoor_air_volume_flow_rate_m3_per_s','resulting_supply_humidity_ratio','resulting_supply_enthalpy_j_per_kg','resulting_supply_temperature_c')
if (($fields[382..401] -join '|') -cne ($tail -join '|') -or [regex]::Matches($snapshotBlock,'Option<f64>').Count -ne 140 -or [regex]::Matches($snapshotBlock,'Option<bool>').Count -ne 8 -or ([regex]::Matches($snapshotBlock,'Option<').Count - 140 - 8) -ne 6) { throw 'CP436 locked 402/140/8/6 schema/tail drift' }
foreach ($pattern in @('standard_air_density_for_outdoor_air_volume_flow_division_kg_per_m3:\s*route\.assignment_executed\.then_some','calculated_outdoor_air_volume_flow_rate_m3_per_s,','assigned_outdoor_air_volume_flow_rate_m3_per_s:\s*calculated_outdoor_air_volume_flow_rate_m3_per_s')) { Assert-Contains -Path $snapshot -Pattern $pattern -Description 'CP436 local read/division/assignment snapshot semantics' }
foreach ($pattern in @('\[64usize,\s*61,\s*3\]','20usize\s*\+\s*44','\(public_active,\s*private_active\)\s*=\s*\(0usize,\s*3usize\)','402','140','Option<bool>"\)\.count\(\),\s*8','fields\.len\(\),\s*129','cp436_new_state_has_four_zeroed_lossless_route_partitions','cp436_is_ordered_after_cp435_and_does_not_feed_numerics')) { Assert-Contains -Path $coupledTests -Pattern $pattern -Description 'CP436 route/schema/binding/no-feed regression' }
foreach ($pattern in @('serializer_source_preserves_cp435_prefix_and_extends_exact_30_key_tail','cp435_snapshot_json\(predecessor\)','keys\.len\(\),\s*30','keys\[29\],\s*"resulting_supply_temperature_c_ieee_bits"')) { Assert-Contains -Path $serializationSnapshot -Pattern $pattern -Description 'CP436 CP435-prefix/30-key serializer contract' }
foreach ($pattern in @('latest\.len\(\),\s*542','actual\.len\(\),\s*542','ends_with\("_ieee_bits"\)\)\s*\.count\(\),\s*140','fields\.len\(\),\s*402','snapshot\.matches\("Option<f64>"\)\.count\(\),\s*140','snapshot\.matches\("Option<bool>"\)\.count\(\),\s*8','fields\.len\(\),\s*129','fields\[125\].*heating_outdoor_air_maximum_flow_guard','fields\[126\][\s\S]*heating_outdoor_air_maximum_flow_body_volume_flow_assignment')) { Assert-Contains -Path $arbitrary -Pattern $pattern -Description 'actual CP436 JSON/IEEE/schema/binding contract' }
Assert-PatternsInOrder -Path $binding -Patterns @("let\s+calculation_$predecessorStem\s*=","let\s+calculation_$stem\s*=",'let\s+unit_available\s*=','let\s+coupling\s*=') -Description 'CP435-to-CP438-to-numerical order'
Assert-PatternsInOrder -Path $scheduled -Patterns @("pub\s+calculation_$predecessorStem\s*:","pub\s+calculation_$stem\s*:",'pub\s+coupling\s*:') -Description 'scheduled CP435-to-CP436 order'
$scheduledFields = @([regex]::Matches((Read-RepoText -Path $scheduled), '(?m)^\s*pub\s+(?<name>calculation_[A-Za-z0-9_]+)\s*:') | ForEach-Object { $_.Groups['name'].Value })
if ($scheduledFields.Count -ne 129 -or $scheduledFields[125] -cne 'calculation_heating_outdoor_air_maximum_flow_guard' -or $scheduledFields[126] -cne 'calculation_heating_outdoor_air_maximum_flow_body_volume_flow_assignment') { throw 'CP436 exact binding index 125/126/current 129 drift' }
foreach ($test in @('scheduled_binding_advances_cp436_after_cp435_before_unchanged_coupling','cp436_adapter_accepts_only_the_cp435_snapshot_and_no_scalar_input','cp436_remains_index_126_in_current_129_snapshot_binding')) { Assert-Contains -Path $adapterTests -Pattern $test -Description 'CP436 adapter/current-binding regression' }
foreach ($pattern in @('predecessor_guard_false_fallthrough_route_counts','predecessor_guard_body_entry_route_counts','heating_outdoor_air_volume_flow_assignment_route_counts','assignments\s*\.checked_mul\(4\)','public_assignment_count",\s*0,\s*assignments','local_public_skip_matches','!snapshot\.begin_environment_standard_air_density_owned_read')) { Assert-Contains -Path $coupled -Pattern $pattern -Description 'CP436 public exact-release/no-body validation' }
foreach ($pattern in @('validate_direct_lifecycle','validate_public_route_contract','body_count\s*!=\s*0','assignment_count','source_site_execution_count','standard density is invalid','lineage_is_exact')) { Assert-Contains -Path $pipelineValidation -Pattern $pattern -Description 'CP436 pipeline structural/no-feed seal' }
foreach ($pattern in @('assignment_shape_is_exact','mass_flow\s*/\s*standard_air_density_kg_per_m3','option_has_bits','!snapshot\.begin_environment_standard_air_density_owned_read','assigned_outdoor_air_volume_flow_rate_m3_per_s')) { Assert-Contains -Path $pipelineLineage -Pattern $pattern -Description 'CP436 exact division/skip lineage seal' }
Assert-Contains -Path $pipelineRoot -Pattern 'non_direct_runtime_rejects_cp316_through_cp438_lifecycle_evidence' -Description 'CP436 non-direct firewall'
Assert-Contains -Path $pipelineRoot -Pattern 'purchased_air_calc_heating_outdoor_air_maximum_flow_body_volume_flow_assignment_lifecycle' -Description 'CP436 lifecycle JSON field'
$ledger = Read-RepoText -Path 'specs\algorithm_ledger.toml'; $capabilities = Read-RepoText -Path 'specs\capabilities.toml'
if ([regex]::Matches($ledger,[regex]::Escape('CP436 supersedes only CP435')).Count -ne 1 -or [regex]::Matches($capabilities,[regex]::Escape('CP436 additionally requires')).Count -ne 1) { throw 'CP436 bounded spec addendum drift' }
foreach ($text in @($ledger,$capabilities)) { foreach ($claim in @('54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005','physical-line-2363','first 382 nonterminal fields','first 512 nonterminal keys','402','542','140','374 total','240 public','134 internal')) { if (-not $text.Contains($claim)) { throw "CP436 spec claim missing $claim" } }; foreach ($site in $sites) { if (-not $text.Contains($site)) { throw "CP436 spec source site missing $site" } } }
if ([regex]::Matches($ledger,'(?m)^\[\[algorithm\]\]\r?$').Count -ne 32 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"state_mapped"\r?$').Count -ne 58 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"source_mapped"\r?$').Count -ne 235 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.required_for_full_domain\s*=\s*true\r?$').Count -ne 170) { throw 'CP436 unchanged algorithm/routine count drift' }
Assert-NotContains -Path 'docs\src\current\roadmap.md' -Pattern '(?m)^## CP436\b' -Description 'Roadmap non-promotion'; Assert-NotContains -Path 'docs\src\porting-map\psychrometrics-source-map.md' -Pattern '(?m)^## CP436\b' -Description 'psychrometrics non-promotion'
$auditRoot = 'scripts\quality\ideal-loads-structure-audit'; $audits = @(Get-ChildItem $auditRoot -Filter 'cp*.ps1' -File)
$historical = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -eq 326) -or ([int]$Matches.n -ge 329 -and [int]$Matches.n -le 435)) })
if ($historical.Count -ne 108 -or @($historical | Where-Object { $_.BaseName -match '^cp(?:327|328)-' }).Count) { throw 'CP436 exact 108 historical leaf set drift' }
$firewall = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 334 -and [int]$Matches.n -le 436 }); $script = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 337 -and [int]$Matches.n -le 436 }); $internal = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 367 -and [int]$Matches.n -le 436 }); $generated = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 335 -and [int]$Matches.n -le 436 })
if ($firewall.Count -ne 103 -or $script.Count -ne 100 -or $internal.Count -ne 70 -or $generated.Count -ne 102) { throw 'CP436 propagation range cardinality drift' }
foreach ($file in $firewall) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('non_direct_runtime_rejects_cp316_through_cp438_lifecycle_evidence')) { throw "CP436 firewall propagation drift $($file.Name)" } }
foreach ($file in $script) { if (-not (Read-RepoText -Path $file.FullName).Contains('script_count = 376')) { throw "CP436 inventory-total propagation drift $($file.Name)" } }
$internalClassification = '\[regex\]::Matches\(\s*\$[A-Za-z_][A-Za-z0-9_]*\s*,\s*''\(\?m\)\^classification\s*\=\s*"internal"(?:\\r\?)?\$''\s*\)\s*\.Count\s*-ne\s*(?<count>\d+)'
foreach ($file in $internal) { $matches = [regex]::Matches((Read-RepoText -Path $file.FullName),$internalClassification); if ($matches.Count -ne 1 -or $matches[0].Groups['count'].Value -cne '136') { throw "CP436 internal propagation drift $($file.Name)" } }
foreach ($file in $generated) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('\| 376 \|') -or -not $text.Contains('\| 136 \|')) { throw "CP436 generated propagation drift $($file.Name)" } }
$helpers = @((Get-ChildItem $auditRoot -Filter 'cp326-*.ps1' -File); Get-ChildItem $auditRoot -Filter 'cp3*.ps1' -File | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 329 -and [int]$Matches.n -le 344 })
if ($helpers.Count -ne 17) { throw 'CP436 helper set drift' }
foreach ($file in $helpers) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains("calculation_$stem") -or -not $text.Contains("advance_$stem") -or -not $text.Contains('CP340 through CP438')) { throw "CP436 helper strip/whitelist drift $($file.Name)" } }
$terminal = @((Get-ChildItem $auditRoot -Filter 'cp345-*.ps1' -File); $audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -ge 377 -and [int]$Matches.n -le 392) -or ([int]$Matches.n -ge 394 -and [int]$Matches.n -le 435)) })
if ($terminal.Count -ne 59) { throw 'CP436 terminal set drift' }
foreach ($file in $terminal) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('$cp436Call') -or -not $text.Contains('CP435-to-CP436') -or -not $text.Contains('CP438-to-numerical') -or -not $text.Contains("-Pattern ('Assert-Contains[^\r\n]+CP435-to-' + 'numerical')")) { throw "CP436 terminal propagation drift $($file.Name)" } }
$live = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 421 -and [int]$Matches.n -le 435 })
if ($live.Count -ne 15) { throw 'CP436 live binding set drift' }
foreach ($file in $live) { $text = Read-RepoText -Path $file.FullName; if ($text -notmatch 'current_129_snapshot_binding|binding_is_129|Count-ne129|,\s*\\s\*129') { throw "CP436 current-129 propagation drift $($file.Name)" } }
$recent = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 425 -and [int]$Matches.n -le 435 }); if ($recent.Count -ne 11) { throw 'CP436 recent binding set drift' }
foreach ($file in $recent) { Assert-Contains -Path $file.FullName -Pattern "calculation_$stem" -Description 'CP436 recent binding propagation' }
$cp424 = Get-ChildItem $auditRoot -Filter 'cp424-*.ps1' -File; Assert-NotContains -Path $cp424.FullName -Pattern "calculation_$stem" -Description 'CP424 excludes CP436 registration'
$manuals = @([PSCustomObject]@{Path='docs\src\current\current-status.md';Length=490460;Hash='C7F25398A460DDA864879C30F8AFCA2BAE505D072DA1DE07F7BC04402F0801D5'},[PSCustomObject]@{Path='docs\src\current\project-contract.md';Length=1441908;Hash='246A0153CA8598C99B79E4991939ECE15EAFED405B1014FFAF8A8E57B731EA92'},[PSCustomObject]@{Path='docs\src\porting-map\heat-balance-source-map.md';Length=3906694;Hash='B1CBF09330D5859927C8D56930AFBCC810696CB29B69CEFB43E91F50E0108D3C'},[PSCustomObject]@{Path='docs\src\porting-map\ideal-loads-source-map.md';Length=1446035;Hash='2D9960135A13F146CDF311E1A63C4526E382746B31D9EDA5E688F5E16728E61F'},[PSCustomObject]@{Path='docs\src\porting-map\zone-air-update-map.md';Length=1645473;Hash='D83BDC214EB613275C5749C834822026000E1412B13665E1E62B21F7D95A809A'})
$canonical = $null
foreach ($manual in $manuals) { $bytes = [IO.File]::ReadAllBytes($manual.Path); if ($bytes.Length -ne $manual.Length + 3009 + 3458 + 3655 -or [Array]::IndexOf($bytes,[byte]13) -ne -1 -or $bytes[-1] -ne 10) { throw "CP436 manual byte shape drift $($manual.Path)" }; $head = New-Object byte[] $manual.Length; [Array]::Copy($bytes,$head,$manual.Length); if ((Get-Cp436Sha $head) -cne $manual.Hash) { throw "CP436 manual prefix drift $($manual.Path)" }; $suffix = New-Object byte[] 3009; [Array]::Copy($bytes,$manual.Length,$suffix,0,3009); if ((Get-Cp436Sha $suffix) -cne '6D45554A68B7D23E0CCF22B7BAFF5CE58D502E8FD3CF52CAAA5EE3F06F5CA3C4') { throw "CP436 manual suffix drift $($manual.Path)" }; $text = [Text.UTF8Encoding]::new($false,$true).GetString($suffix); if ($null -eq $canonical) { $canonical = $text } elseif ($text -cne $canonical) { throw "CP436 canonical manual drift $($manual.Path)" } }
foreach ($pattern in @('(?m)^## CP436 heating outdoor-air maximum-flow body volume-flow assignment$','physical-line-2363','line 2364.*first excluded lexical and executable','four textual sites','T436=64','Z436=61','A436=3','S436=12','20/44','active public/private is 0/3','four width-36','first 382 nonterminal fields','402 unique Rust fields','140 `Option<f64>`','eight optional comparison bools','six optional enums','542 unique keys','140 adjacent IEEE sidecars','37/42/57','index 126','current count 127','zero public assignments and density reads','374 total','240 public','134 internal')) { if ($canonical -notmatch "(?is)$pattern") { throw "CP436 documentation claim missing $pattern" } }
$master = Read-RepoText -Path 'scripts\quality\ideal-loads-structure-audit.ps1'; $leaf = Split-Path -Leaf $audit; $previous = $master.IndexOf('cp435-heating-outdoor-air-maximum-flow-guard.ps1'); $current = $master.IndexOf($leaf); $done = $master.IndexOf('Write-Host "IdealLoads structure audit complete."')
if ($previous -lt 0 -or $current -le $previous -or $done -le $current -or [regex]::Matches($master,[regex]::Escape($leaf)).Count -ne 1) { throw 'CP436 master order/uniqueness drift' }
if ((Get-Content 'scripts\quality\ideal-loads-structure-audit.ps1').Count -ne 4201 -or (Get-Content 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1').Count -ne 1200 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\calc.rs').Count -ne 99 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\init\state\witnesses.rs').Count -ne 275 -or @(Get-Content 'crates\ep_runtime\src\ideal_loads\init\state.rs' | Where-Object { $_ -match '\S' }).Count -ne 380 -or (Get-Content $scheduled).Count -gt 500) { throw 'CP436 fixed cap drift' }
$inventory = Read-RepoText -Path 'specs\script_inventory.toml'; foreach ($pattern in @('script_count = 376','dev_command_count = 238','unused_script_count = 0','unreachable_count = 0')) { if ($inventory -notmatch $pattern) { throw "CP436 inventory missing $pattern" } }
if ([regex]::Matches($inventory,'(?m)^classification = "public"$').Count -ne 240 -or [regex]::Matches($inventory,'(?m)^classification = "internal"$').Count -ne 136) { throw 'CP436 inventory classification drift' }
Assert-Contains -Path 'specs\script_inventory.toml' -Pattern 'cp436-heating-outdoor-air-maximum-flow-body-volume-flow-assignment\.ps1' -Description 'CP436 inventory record'; Assert-Contains -Path 'docs\src\generated\algorithm-ledger.md' -Pattern 'CP436 supersedes only CP435' -Description 'generated algorithm'; Assert-Contains -Path 'docs\src\generated\capability-index.md' -Pattern 'CP436 additionally requires' -Description 'generated capability'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 376 \|' -Description 'generated total'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 136 \|' -Description 'generated internal'
Write-Host 'CP436 heating outdoor-air maximum-flow body volume-flow assignment structure audit passed.'
}; Assert-Contains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern '\$cp437Call' -Description 'CP437 terminal capture'; Assert-Contains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern 'CP436-to-CP437' -Description 'CP436-to-CP437 terminal interval'; Assert-NotContains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern ('Assert-Contains[^\r\n]+CP436-to-' + 'numerical') -Description 'stale CP436 numerical interval'; Assert-Contains -Path 'crates\ep_runtime\src\ideal_loads\binding.rs' -Pattern 'calculation_heating_outdoor_air_maximum_flow_first_warning_guard' -Description 'CP437 recent binding propagation'; Assert-Contains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern '\$cp438Call' -Description 'CP438 terminal capture'; Assert-Contains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern 'CP437-to-CP438' -Description 'CP437-to-CP438 terminal interval'; Assert-NotContains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern ('Assert-Contains[^\r\n]+CP437-to-' + 'numerical') -Description 'stale CP437 numerical interval'; Assert-Contains -Path 'crates\ep_runtime\src\ideal_loads\binding.rs' -Pattern 'calculation_heating_outdoor_air_maximum_flow_first_warning_counter_increment' -Description 'CP438 recent binding propagation'
