# CP439 maps PurchasedAirManager.cc physical executable lines 2366-2370's complete first-warning call.
& {
function Get-Cp439Sha([byte[]]$Bytes) { $sha = [Security.Cryptography.SHA256]::Create(); try { return ([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-', '') } finally { $sha.Dispose() } }
function Get-Cp439SnapshotBlock([string]$Text, [string]$Type, [string]$EndMarker) { $start = $Text.IndexOf("pub struct $Type"); $end = $Text.IndexOf($EndMarker, $start); if ($start -lt 0 -or $end -le $start) { throw "CP439 snapshot block drift: $Type" }; return $Text.Substring($start, $end - $start) }
$stem = 'heating_outdoor_air_maximum_flow_first_warning_call'; $predecessorStem = 'heating_outdoor_air_maximum_flow_first_warning_counter_increment'; $typeStem = 'PurchasedAirCalcHeatingOutdoorAirMaximumFlowFirstWarningCall'
$source = '.reference\energyplus-src\26.1.0\src\EnergyPlus\PurchasedAirManager.cc'; $module = "crates\ep_runtime\src\ideal_loads\calc\$stem.rs"; $predecessorModule = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem.rs"
$root = "crates\ep_runtime\src\ideal_loads\calc\$stem"; $predecessorRoot = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem"; $release = "$root\release.rs"; $prefix = "$root\release\prefix.rs"; $runtimeValidation = "$root\release\runtime_validation.rs"; $snapshotValidation = "$root\release\snapshot_validation.rs"; $state = "$root\state.rs"; $transition = "$root\transition.rs"; $accounting = "$root\transition\accounting.rs"; $snapshot = "$root\transition\snapshot.rs"; $tests = "$root\tests.rs"; $schemaTests = "$root\tests\schema_prefix.rs"
$predecessorCommitted = "$predecessorRoot\release\committed.rs"; $predecessorCommittedTests = "$predecessorRoot\tests\committed_seal.rs"
$binding = 'crates\ep_runtime\src\ideal_loads\binding.rs'; $scheduled = 'crates\ep_runtime\src\ideal_loads\binding\scheduled_output.rs'; $adapter = "crates\ep_runtime\src\ideal_loads\binding\$stem.rs"; $adapterTests = "crates\ep_runtime\src\ideal_loads\binding\$($stem)_tests.rs"
$coupled = "crates\ep_runtime\src\ideal_loads\coupled_runtime\$($stem)_validation.rs"; $coupledTests = 'crates\ep_runtime\src\ideal_loads\test_coupled_runtime_cp439.rs'; $coupledOutput = "crates\ep_runtime\src\ideal_loads\coupled_output_tests\$($stem)_fixture.rs"
$pipelineRoot = 'crates\ep_run\src\pipeline.rs'; $pipeline = "crates\ep_run\src\pipeline\purchased_air_$stem"; $pipelineModule = "$pipeline.rs"; $serialization = "$pipeline\serialization.rs"; $serializationSnapshot = "$pipeline\serialization\snapshot.rs"; $pipelineValidation = "$pipeline\validation.rs"; $pipelineLineage = "$pipeline\validation\lineage.rs"; $arbitrary = 'crates\ep_run\tests\arbitrary_run_ideal_loads\cp439_assertions.rs'; $audit = "scripts\quality\ideal-loads-structure-audit\cp439-$($stem -replace '_','-').ps1"
$witness = "crates\ep_runtime\src\ideal_loads\init\state\witnesses\$stem.rs"
foreach ($file in @($source,$module,$predecessorModule,$release,$prefix,$runtimeValidation,$snapshotValidation,$state,$transition,$accounting,$snapshot,$tests,$schemaTests,$predecessorCommitted,$predecessorCommittedTests,$binding,$scheduled,$adapter,$adapterTests,$coupled,$coupledTests,$coupledOutput,$pipelineRoot,$pipelineModule,$serialization,$serializationSnapshot,$pipelineValidation,$pipelineLineage,$arbitrary,$witness,$audit)) { Assert-FileExists -Path $file -Description 'CP439 implementation/audit file' }
$bounded = @($audit,$module,$pipelineModule) + @((Get-ChildItem $root -Recurse -File -Filter '*.rs').FullName) + @((Get-ChildItem $pipeline -Recurse -File -Filter '*.rs').FullName); foreach ($file in $bounded) { Assert-LineLimit -Path $file -Limit 500 -Description 'bounded CP439 file' }
$sourceBytes = [IO.File]::ReadAllBytes($source); if ((Get-Cp439Sha $sourceBytes) -cne '54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005') { throw 'CP439 pinned PurchasedAirManager.cc hash drift' }
$sourceLines = Get-Content -LiteralPath $source
$expectedSource = @('ShowWarningError(state,','EnergyPlus::format("{} \"{}\" Requested outdoor air flow rate = {:.5T} [m3/s] exceeds limit.",','PurchAir.cObjectName,','PurchAir.Name,','OAVolFlowRate));'); for ($i = 0; $i -lt 5; $i++) { if ($sourceLines[2365 + $i].Trim() -cne $expectedSource[$i]) { throw "CP439 physical line $($i + 2366) drift" } }; if ($sourceLines[2370].Trim() -cne 'ShowContinueError(') { throw 'CP439 physical line 2371 exclusion drift' }
$sites = @('reach-heating-outdoor-air-maximum-flow-first-warning-call-site'); Assert-ExactStringArray -Path $module -Name 'PURCHASED_AIR_CALC_HEATING_OUTDOOR_AIR_MAXIMUM_FLOW_FIRST_WARNING_CALL_SOURCE_ORDER' -Expected $sites -Description 'one CP439 textual source site'
foreach ($pattern in @('EnergyPlus 26\.1 PurchasedAirManager\.cc:2366-2370','EnergyPlus 26\.1 PurchasedAirManager\.cc:2371','PurchasedAirCalcHeatingOutdoorAirMaximumFlowFirstWarningCallSnapshot')) { Assert-Contains -Path $module -Pattern $pattern -Description 'CP439 boundary/type contract' }
$core = @(Get-ChildItem -LiteralPath $root -Recurse -File -Filter '*.rs'); $predecessorCore = @(Get-ChildItem -LiteralPath $predecessorRoot -Recurse -File -Filter '*.rs'); if ($core.Count -ne 13 -or @(Get-ChildItem "$root\tests" -File -Filter '*.rs').Count -ne 2) { throw 'CP439 exact sealed thirteen-subtree-file/two-test topology drift' }; if ($predecessorCore.Count -ne 13 -or @(Get-ChildItem "$predecessorRoot\tests" -File -Filter '*.rs').Count -ne 2) { throw 'CP439 exact sealed CP438 thirteen-subtree-file/two-test topology drift' }
$stateText = Read-RepoText -Path $state; $arrays = @([regex]::Matches($stateText, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*route_counts)\s*:\s*\[usize;\s*36\]') | ForEach-Object { $_.Groups['name'].Value }); $expectedArrays = @('predecessor_route_counts','predecessor_guard_false_fallthrough_route_counts','predecessor_guard_body_entry_route_counts','predecessor_volume_flow_assignment_route_counts','predecessor_first_warning_guard_false_fallthrough_route_counts','predecessor_first_warning_branch_entry_route_counts','predecessor_first_warning_counter_increment_route_counts','heating_outdoor_air_maximum_flow_first_warning_call_route_counts'); if (($arrays -join '|') -cne ($expectedArrays -join '|')) { throw 'CP439 exact eight width-36 route arrays drift' }
foreach ($pattern in @('heating_outdoor_air_maximum_flow_first_warning_counter_increment_committed_latest_route_and_outdoor_air_flow_maximum_heating_output_error_count','outdoor_air_flow_maximum_heating_output_error_count')) { Assert-Contains -Path $predecessorCommitted -Pattern $pattern -Description 'CP438 committed counter seal' }; Assert-Contains -Path "$predecessorRoot\release.rs" -Pattern 'ExactReleaseReductionViolated' -Description 'CP438 exact-release reduction seal'; foreach ($pattern in @('cp438_committed_seal_is_retained_constant_time_and_active_counter_exact','cp438_committed_seal_rejects_witness_route_accounting_and_counter_forgeries','private_characterization','DirectZonePurchasedAirCouplingInput')) { Assert-Contains -Path $predecessorCommittedTests -Pattern $pattern -Description 'CP438 committed-seal regression' }
foreach ($pattern in @('cp439_boundary_maps_complete_warning_call_and_excludes_continue_call','exhaustive_67_routes_preserve_20_47_visibility_and_reach_three_private_calls','active_call_requires_cp438_increment_and_sealed_counter_one_without_mutation','cp439_new_state_has_eight_zeroed_width_36_arrays_and_no_service_state','cp439_transition_contains_no_sink_format_service_or_counter_mutation','cp439_sealed_subtree_is_fourteen_files_and_every_file_is_bounded','state\.transition_count,\s*67','state\.inactive_transition_count,\s*64','state\.source_site_execution_count,\s*3','\(public_calls,\s*private_calls\),\s*\(0,\s*3\)')) { Assert-Contains -Path $tests -Pattern $pattern -Description 'CP439 exhaustive/call/topology regression' }
$moduleText = Read-RepoText -Path $module; $predecessorText = Read-RepoText -Path $predecessorModule; $snapshotBlock = Get-Cp439SnapshotBlock $moduleText "$($typeStem)Snapshot" '/// Final selected-unit CP439'; $predecessorBlock = Get-Cp439SnapshotBlock $predecessorText 'PurchasedAirCalcHeatingOutdoorAirMaximumFlowFirstWarningCounterIncrementSnapshot' '/// Final selected-unit CP438'
$fields = @([regex]::Matches($snapshotBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value }); $predecessorFields = @([regex]::Matches($predecessorBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value }); if ($predecessorFields.Count -ne 426 -or $fields.Count -ne 427 -or @($fields | Select-Object -Unique).Count -ne 427 -or ($fields[0..425] -join '|') -cne ($predecessorFields -join '|') -or $fields[426] -cne 'heating_outdoor_air_maximum_flow_first_warning_call_site_reached') { throw 'CP439 exact unique 427-field/all-426-prefix/one-marker schema drift' }; if ([regex]::Matches($snapshotBlock,'Option<f64>').Count -ne 146 -or [regex]::Matches($snapshotBlock,'Option<bool>').Count -ne 9 -or [regex]::Matches($snapshotBlock,'Option<usize>').Count -ne 2 -or ([regex]::Matches($snapshotBlock,'Option<').Count - 146 - 9 - 2) -ne 6) { throw 'CP439 locked 427/146/9/6/2 schema drift' }
foreach ($pattern in @('cp439_schema_is_exact_427_with_cp438_first_426_and_one_marker','cp439_preserves_cp438_optional_type_counts','assert_eq!\(&cp439\[\.\.426\],\s*&cp438\[\.\.\]\)','predecessors\.len\(\),\s*67')) { Assert-Contains -Path $schemaTests -Pattern $pattern -Description 'CP439 schema/prefix regression' }
foreach ($pattern in @('heating_outdoor_air_maximum_flow_first_warning_call_site_reached:\s*route\.first_warning_call_site_reached','predecessor\.assigned_outdoor_air_flow_maximum_heating_output_error_count')) { Assert-Contains -Path $snapshot -Pattern $pattern -Description 'CP439 marker/counter preservation' }
foreach ($pattern in @('\[67usize,\s*64,\s*3,\s*3\]','20usize\s*\+\s*47','\[0usize,\s*3\]\.into_iter\(\)\.sum::<usize>\(\)','427','146','Option<bool>"\)\.count\(\),\s*9','Option<usize>"\)\.count\(\),\s*2','fields\.len\(\),\s*131','fields\[128\][\s\S]*?first_warning_counter_increment','fields\[129\][\s\S]*?first_warning_call','cp439_new_state_has_eight_zeroed_lossless_route_partitions','cp439_is_ordered_after_cp438_and_does_not_feed_numerics_or_services')) { Assert-Contains -Path $coupledTests -Pattern $pattern -Description 'CP439 route/schema/binding/no-feed regression' }
foreach ($pattern in @('serializer_source_preserves_cp438_json_and_appends_only_the_call_marker','cp438_snapshot_json\(predecessor\)','heating_outdoor_air_maximum_flow_first_warning_call_site_reached')) { Assert-Contains -Path $serializationSnapshot -Pattern $pattern -Description 'CP439 CP438-prefix/marker serializer contract' }
$serializationSnapshotText = Read-RepoText -Path $serializationSnapshot; $productionSerialization = ($serializationSnapshotText -split '#\[cfg\(test\)\]', 2)[0]; $targetInsertPattern = [regex]::Escape(('tar' + 'get' + '.insert')) + '\s*\('; if ([regex]::Matches($productionSerialization, $targetInsertPattern).Count -ne 4) { throw 'CP439 exact four serializer insertions drift' }
foreach ($pattern in @('actual\.len\(\),\s*573','ends_with\("_ieee_bits"\)\)\s*\.count\(\),\s*146','fields\.len\(\),\s*427','snapshot\.matches\("Option<f64>"\)\.count\(\),\s*146','snapshot\.matches\("Option<bool>"\)\.count\(\),\s*9','snapshot\.matches\("Option<usize>"\)\.count\(\),\s*2','fields\.len\(\),\s*131','fields\[128\][\s\S]*?first_warning_counter_increment','fields\[129\][\s\S]*?first_warning_call')) { Assert-Contains -Path $arbitrary -Pattern $pattern -Description 'actual CP439 JSON/IEEE/schema/binding contract' }
Assert-PatternsInOrder -Path $binding -Patterns @("let\s+calculation_$predecessorStem\s*=","let\s+calculation_$stem\s*=",'let\s+unit_available\s*=','let\s+coupling\s*=') -Description 'CP438-to-CP440-to-numerical order'; Assert-PatternsInOrder -Path $scheduled -Patterns @("pub\s+calculation_$predecessorStem\s*:","pub\s+calculation_$stem\s*:",'pub\s+coupling\s*:') -Description 'scheduled CP438-to-CP439 order'
$scheduledFields = @([regex]::Matches((Read-RepoText -Path $scheduled), '(?m)^\s*pub\s+(?<name>calculation_[A-Za-z0-9_]+)\s*:') | ForEach-Object { $_.Groups['name'].Value }); if ($scheduledFields.Count -ne 131 -or $scheduledFields[128] -cne 'calculation_heating_outdoor_air_maximum_flow_first_warning_counter_increment' -or $scheduledFields[129] -cne 'calculation_heating_outdoor_air_maximum_flow_first_warning_call') { throw 'CP439 exact binding index 128/129/current 131 drift' }
foreach ($test in @('scheduled_binding_advances_cp439_after_cp438_before_unchanged_coupling','cp439_adapter_accepts_only_the_cp438_snapshot_and_no_scalar_input','cp439_extends_current_scheduled_binding_from_129_to_130_snapshots')) { Assert-Contains -Path $adapterTests -Pattern $test -Description 'CP439 adapter/current-binding regression' }
foreach ($pattern in @('predecessor_first_warning_counter_increment_route_counts','heating_outdoor_air_maximum_flow_first_warning_call_route_counts','public_first_warning_call_count','warning_counter_owner_count','warning_counter_preservation_count','source_site_execution_count','local_public_skip_matches')) { Assert-Contains -Path $coupled -Pattern $pattern -Description 'CP439 public exact-release/no-call validation' }
foreach ($pattern in @('validate_direct_lifecycle','public_first_warning_call_count','source_site_execution_count','warning_counter_owner_count','warning_counter_preservation_count','lineage_is_exact')) { Assert-Contains -Path $pipelineValidation -Pattern $pattern -Description 'CP439 pipeline structural/no-feed seal' }; foreach ($pattern in @('lineage_is_exact','!predecessor\.heating_outdoor_air_maximum_flow_first_warning_counter_increment_executed','!snapshot\.heating_outdoor_air_maximum_flow_first_warning_call_site_reached','cp438_snapshot_json')) { Assert-Contains -Path $pipelineLineage -Pattern $pattern -Description 'CP439 exact call/skip lineage seal' }
Assert-Contains -Path $pipelineRoot -Pattern 'non_direct_runtime_rejects_cp316_through_cp440_lifecycle_evidence' -Description 'CP439 non-direct firewall'; Assert-Contains -Path $pipelineRoot -Pattern 'purchased_air_calc_heating_outdoor_air_maximum_flow_first_warning_call_lifecycle' -Description 'CP439 lifecycle JSON field'
$ledger = Read-RepoText -Path 'specs\algorithm_ledger.toml'; $capabilities = Read-RepoText -Path 'specs\capabilities.toml'; if ([regex]::Matches($ledger,[regex]::Escape('CP439 supersedes only CP438')).Count -ne 1 -or [regex]::Matches($capabilities,[regex]::Escape('CP439 additionally requires')).Count -ne 1) { throw 'CP439 bounded spec addendum drift' }; foreach ($text in @($ledger,$capabilities)) { foreach ($claim in @('54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005','physical-lines-2366-through-2370','reach-heating-outdoor-air-maximum-flow-first-warning-call-site','all 426 CP438 fields','427','573','146','377 total','240 public','137 internal')) { if (-not $text.Contains($claim)) { throw "CP439 spec claim missing $claim" } } }
if ([regex]::Matches($ledger,'(?m)^\[\[algorithm\]\]\r?$').Count -ne 32 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"state_mapped"\r?$').Count -ne 58 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"source_mapped"\r?$').Count -ne 235 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.required_for_full_domain\s*=\s*true\r?$').Count -ne 170) { throw 'CP439 unchanged algorithm/routine count drift' }; Assert-NotContains -Path 'docs\src\current\roadmap.md' -Pattern '(?m)^## CP439\b' -Description 'Roadmap non-promotion'; Assert-NotContains -Path 'docs\src\porting-map\psychrometrics-source-map.md' -Pattern '(?m)^## CP439\b' -Description 'psychrometrics non-promotion'
$auditRoot = 'scripts\quality\ideal-loads-structure-audit'; $audits = @(Get-ChildItem $auditRoot -Filter 'cp*.ps1' -File); $historical = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -eq 326) -or ([int]$Matches.n -ge 329 -and [int]$Matches.n -le 438)) }); if ($historical.Count -ne 111 -or @($historical | Where-Object { $_.BaseName -match '^cp(?:327|328)-' }).Count) { throw 'CP439 exact 111 historical leaf set drift' }
$firewall = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 334 -and [int]$Matches.n -le 439 }); $script = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 337 -and [int]$Matches.n -le 439 }); $internal = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 367 -and [int]$Matches.n -le 439 }); $generated = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 335 -and [int]$Matches.n -le 439 }); if ($firewall.Count -ne 106 -or $script.Count -ne 103 -or $internal.Count -ne 73 -or $generated.Count -ne 105) { throw 'CP439 propagation range cardinality drift' }
foreach ($file in $firewall) { if (-not (Read-RepoText -Path $file.FullName).Contains('non_direct_runtime_rejects_cp316_through_cp440_lifecycle_evidence')) { throw "CP439 firewall propagation drift $($file.Name)" } }; foreach ($file in $script) { if (-not (Read-RepoText -Path $file.FullName).Contains('script_count = 378')) { throw "CP439 inventory-total propagation drift $($file.Name)" } }
$internalClassification = '\[regex\]::Matches\(\s*\$[A-Za-z_][A-Za-z0-9_]*\s*,\s*''\(\?m\)\^classification\s*\=\s*"internal"(?:\\r\?)?\$''\s*\)\s*\.Count\s*-ne\s*(?<count>\d+)'; foreach ($file in $internal) { $matches = [regex]::Matches((Read-RepoText -Path $file.FullName),$internalClassification); if ($matches.Count -ne 1 -or $matches[0].Groups['count'].Value -cne '138') { throw "CP439 internal propagation drift $($file.Name)" } }; foreach ($file in $generated) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('\| 378 \|') -or -not $text.Contains('\| 138 \|')) { throw "CP439 generated propagation drift $($file.Name)" } }
$helpers = @((Get-ChildItem $auditRoot -Filter 'cp326-*.ps1' -File); Get-ChildItem $auditRoot -Filter 'cp3*.ps1' -File | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 329 -and [int]$Matches.n -le 344 }); if ($helpers.Count -ne 17) { throw 'CP439 helper set drift' }; foreach ($file in $helpers) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains("calculation_$stem") -or -not $text.Contains("advance_$stem") -or -not $text.Contains('CP340 through CP440')) { throw "CP439 helper strip/whitelist drift $($file.Name)" } }
$terminal = @((Get-ChildItem $auditRoot -Filter 'cp345-*.ps1' -File); $audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -ge 377 -and [int]$Matches.n -le 392) -or ([int]$Matches.n -ge 394 -and [int]$Matches.n -le 438)) }); if ($terminal.Count -ne 62) { throw 'CP439 terminal set drift' }; foreach ($file in $terminal) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('$cp439Call') -or -not $text.Contains('CP438-to-CP439') -or -not $text.Contains("-Pattern ('Assert-Contains[^\r\n]+CP438-to-' + 'numerical')")) { throw "CP439 terminal propagation drift $($file.Name)" } }
$live = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 421 -and [int]$Matches.n -le 438 }); if ($live.Count -ne 18) { throw 'CP439 live binding set drift' }; foreach ($file in $live) { $text = Read-RepoText -Path $file.FullName; if ($text -notmatch 'current_131_snapshot_binding|binding_is_131|Count-ne131|,\s*\\s\*131') { throw "CP439 current-131 propagation drift $($file.Name)" }; if ($text -notmatch 'Count\s*-(?:gt|ne)\s*4203') { throw "CP439 master-cap propagation drift $($file.Name)" } }
$recent = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 425 -and [int]$Matches.n -le 438 }); if ($recent.Count -ne 14) { throw 'CP439 recent binding set drift' }; foreach ($file in $recent) { Assert-Contains -Path $file.FullName -Pattern "calculation_$stem" -Description 'CP439 recent binding propagation' }; $cp424 = Get-ChildItem $auditRoot -Filter 'cp424-*.ps1' -File; Assert-NotContains -Path $cp424.FullName -Pattern "calculation_$stem" -Description 'CP424 excludes CP439 registration'
$manualShape = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 424 -and [int]$Matches.n -le 438 }); if ($manualShape.Count -ne 15) { throw 'CP439 manual-shape propagation set drift' }; foreach ($file in $manualShape) { $matches = [regex]::Matches((Read-RepoText -Path $file.FullName), '3632\s*\+\s*3653\s*-or'); if ($matches.Count -ne 1) { throw "CP439 manual-shape propagation drift $($file.Name)" } }
$manuals = @([PSCustomObject]@{Path='docs\src\current\current-status.md';Length=500582;Hash='64799CB6B561CB6D27F2FD7FC00D3C998E9ED95943426B5D19A6A69722393085'},[PSCustomObject]@{Path='docs\src\current\project-contract.md';Length=1452030;Hash='78DEA86934F2B1951B5CDEF96C43C08A7E20D550A76C5DA4FC451C9D4F1F7E8C'},[PSCustomObject]@{Path='docs\src\porting-map\heat-balance-source-map.md';Length=3916816;Hash='7006ADB83D6B1D229B8DA0024584B8AA8242A13E95C7D26355B99BBC3F68F02F'},[PSCustomObject]@{Path='docs\src\porting-map\ideal-loads-source-map.md';Length=1456157;Hash='6E7E067373EAA396DBC188E7F6F19562A1632C9292D23E0A8FD45652B135257B'},[PSCustomObject]@{Path='docs\src\porting-map\zone-air-update-map.md';Length=1655595;Hash='C53100A70969A7D050148056BFE8F5139A007E41AD845299791DD39A3A53B9C7'}); $canonical = $null; foreach ($manual in $manuals) { $bytes = [IO.File]::ReadAllBytes($manual.Path); if ($bytes.Length -ne $manual.Length + 3632 + 3653 -or [Array]::IndexOf($bytes,[byte]13) -ne -1 -or $bytes[-1] -ne 10) { throw "CP439 manual byte shape drift $($manual.Path)" }; $head = New-Object byte[] $manual.Length; [Array]::Copy($bytes,$head,$manual.Length); if ((Get-Cp439Sha $head) -cne $manual.Hash) { throw "CP439 manual prefix drift $($manual.Path)" }; $suffix = New-Object byte[] 3632; [Array]::Copy($bytes,$manual.Length,$suffix,0,3632); if ((Get-Cp439Sha $suffix) -cne '90D850093D7467D405B08407BA9C2EB88E56E288579633A9A9218355A76C233B') { throw "CP439 manual suffix drift $($manual.Path)" }; $text = [Text.UTF8Encoding]::new($false,$true).GetString($suffix); if ($null -eq $canonical) { $canonical = $text } elseif ($text -cne $canonical) { throw "CP439 canonical manual drift $($manual.Path)" } }
foreach ($pattern in @('(?m)^## CP439 heating outdoor-air maximum-flow first-warning call$','physical-lines-2366-through-2370','line 2371','exactly one textual\s+source site','T439=67','Z439=64','C439=3','S439=3','20/47','active public/private 0/3','eight width-36','all 426 CP438 fields verbatim','427 unique Rust fields','146 `Option<f64>`','nine `Option<bool>`','six optional enums','two `Option<usize>`','573 unique\s+keys','146 adjacent IEEE sidecars','37/42/57','index 129','current\s+count 130','zero public call sites','377\s+total','240 public','137 internal')) { if ($canonical -notmatch "(?is)$pattern") { throw "CP439 documentation claim missing $pattern" } }
$master = Read-RepoText -Path 'scripts\quality\ideal-loads-structure-audit.ps1'; $leaf = Split-Path -Leaf $audit; $previous = $master.IndexOf('cp438-heating-outdoor-air-maximum-flow-first-warning-counter-increment.ps1'); $current = $master.IndexOf($leaf); $done = $master.IndexOf('Write-Host "IdealLoads structure audit complete."'); if ($previous -lt 0 -or $current -le $previous -or $done -le $current -or [regex]::Matches($master,[regex]::Escape($leaf)).Count -ne 1) { throw 'CP439 master order/uniqueness drift' }
if ((Get-Content 'scripts\quality\ideal-loads-structure-audit.ps1').Count -ne 4203 -or (Get-Content 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1').Count -ne 1200 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\calc.rs').Count -ne 99 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\init\state\witnesses.rs').Count -ne 277 -or @(Get-Content 'crates\ep_runtime\src\ideal_loads\init\state.rs' | Where-Object { $_ -match '\S' }).Count -ne 380 -or (Get-Content $scheduled).Count -gt 500) { throw 'CP439 fixed cap drift' }
$inventory = Read-RepoText -Path 'specs\script_inventory.toml'; foreach ($pattern in @('script_count = 378','dev_command_count = 238','unused_script_count = 0','unreachable_count = 0')) { if ($inventory -notmatch $pattern) { throw "CP439 inventory missing $pattern" } }; if ([regex]::Matches($inventory,'(?m)^classification = "public"$').Count -ne 240 -or [regex]::Matches($inventory,'(?m)^classification = "internal"$').Count -ne 138) { throw 'CP439 inventory classification drift' }
Assert-Contains -Path 'specs\script_inventory.toml' -Pattern 'cp439-heating-outdoor-air-maximum-flow-first-warning-call\.ps1' -Description 'CP439 inventory record'; Assert-Contains -Path 'docs\src\generated\algorithm-ledger.md' -Pattern 'CP439 supersedes only CP438' -Description 'generated algorithm'; Assert-Contains -Path 'docs\src\generated\capability-index.md' -Pattern 'CP439 additionally requires' -Description 'generated capability'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 378 \|' -Description 'generated total'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 138 \|' -Description 'generated internal'
Write-Host 'CP439 heating outdoor-air maximum-flow first-warning call structure audit passed.'
}; Assert-Contains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern '\$cp440Call' -Description 'CP440 terminal capture'; Assert-Contains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern 'CP439-to-CP440' -Description 'CP439-to-CP440 terminal interval'; Assert-NotContains -Path 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1' -Pattern ('Assert-Contains[^\r\n]+CP439-to-' + 'numerical') -Description 'stale CP439 numerical interval'; Assert-Contains -Path 'crates\ep_runtime\src\ideal_loads\binding.rs' -Pattern 'calculation_heating_outdoor_air_maximum_flow_continue_warning_call' -Description 'CP440 recent binding propagation'
