# CP441 maps PurchasedAirManager.cc physical executable line 2374's complete continue-warning timestamp call.
& {
function Get-Cp441Sha([byte[]]$Bytes) { $sha = [Security.Cryptography.SHA256]::Create(); try { return ([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-', '') } finally { $sha.Dispose() } }
function Get-Cp441SnapshotBlock([string]$Text, [string]$Type, [string]$EndMarker) { $start = $Text.IndexOf("pub struct $Type"); $end = $Text.IndexOf($EndMarker, $start); if ($start -lt 0 -or $end -le $start) { throw "CP441 snapshot block drift: $Type" }; return $Text.Substring($start, $end - $start) }
$stem = 'heating_outdoor_air_maximum_flow_continue_warning_timestamp_call'; $predecessorStem = 'heating_outdoor_air_maximum_flow_continue_warning_call'; $typeStem = 'PurchasedAirCalcHeatingOutdoorAirMaximumFlowContinueWarningTimestampCall'
$source = '.reference\energyplus-src\26.1.0\src\EnergyPlus\PurchasedAirManager.cc'; $module = "crates\ep_runtime\src\ideal_loads\calc\$stem.rs"; $predecessorModule = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem.rs"
$root = "crates\ep_runtime\src\ideal_loads\calc\$stem"; $predecessorRoot = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem"; $release = "$root\release.rs"; $prefix = "$root\release\prefix.rs"; $runtimeValidation = "$root\release\runtime_validation.rs"; $snapshotValidation = "$root\release\snapshot_validation.rs"; $state = "$root\state.rs"; $transition = "$root\transition.rs"; $accounting = "$root\transition\accounting.rs"; $snapshot = "$root\transition\snapshot.rs"; $tests = "$root\tests.rs"; $schemaTests = "$root\tests\schema_prefix.rs"
$predecessorCommitted = "$predecessorRoot\release\committed.rs"; $predecessorCommittedTests = "$predecessorRoot\tests\committed_seal.rs"
$binding = 'crates\ep_runtime\src\ideal_loads\binding.rs'; $scheduled = 'crates\ep_runtime\src\ideal_loads\binding\scheduled_output.rs'; $adapter = "crates\ep_runtime\src\ideal_loads\binding\$stem.rs"; $adapterTests = "crates\ep_runtime\src\ideal_loads\binding\$($stem)_tests.rs"
$coupled = "crates\ep_runtime\src\ideal_loads\coupled_runtime\$($stem)_validation.rs"; $coupledTests = 'crates\ep_runtime\src\ideal_loads\test_coupled_runtime_cp441.rs'; $coupledOutput = "crates\ep_runtime\src\ideal_loads\coupled_output_tests\$($stem)_fixture.rs"
$pipelineRoot = 'crates\ep_run\src\pipeline.rs'; $pipeline = "crates\ep_run\src\pipeline\purchased_air_$stem"; $pipelineModule = "$pipeline.rs"; $serialization = "$pipeline\serialization.rs"; $serializationSnapshot = "$pipeline\serialization\snapshot.rs"; $pipelineValidation = "$pipeline\validation.rs"; $pipelineLineage = "$pipeline\validation\lineage.rs"; $arbitrary = 'crates\ep_run\tests\arbitrary_run_ideal_loads\cp441_assertions.rs'; $audit = "scripts\quality\ideal-loads-structure-audit\cp441-$($stem -replace '_','-').ps1"
$witness = "crates\ep_runtime\src\ideal_loads\init\state\witnesses\$stem.rs"
foreach ($file in @($source,$module,$predecessorModule,$release,$prefix,$runtimeValidation,$snapshotValidation,$state,$transition,$accounting,$snapshot,$tests,$schemaTests,$predecessorCommitted,$predecessorCommittedTests,$binding,$scheduled,$adapter,$adapterTests,$coupled,$coupledTests,$coupledOutput,$pipelineRoot,$pipelineModule,$serialization,$serializationSnapshot,$pipelineValidation,$pipelineLineage,$arbitrary,$witness,$audit)) { Assert-FileExists -Path $file -Description 'CP441 implementation/audit file' }
$bounded = @($audit,$module,$pipelineModule) + @((Get-ChildItem $root -Recurse -File -Filter '*.rs').FullName) + @((Get-ChildItem $pipeline -Recurse -File -Filter '*.rs').FullName); foreach ($file in $bounded) { Assert-LineLimit -Path $file -Limit 500 -Description 'bounded CP441 file' }
$sourceBytes = [IO.File]::ReadAllBytes($source); if ((Get-Cp441Sha $sourceBytes) -cne '54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005') { throw 'CP441 pinned PurchasedAirManager.cc hash drift' }
$sourceLines = Get-Content -LiteralPath $source
$expectedSource = 'ShowContinueErrorTimeStamp(state, "");'; if ($sourceLines[2373].Trim() -cne $expectedSource) { throw 'CP441 physical line 2374 drift' }; if ($sourceLines[2374].Trim() -cne '} else {') { throw 'CP441 physical line 2375 control exclusion drift' }; if ($sourceLines[2375].Trim() -notmatch '^ShowRecurringWarningErrorAtEnd\(') { throw 'CP441 physical line 2376 executable exclusion drift' }
$sites = @('reach-heating-outdoor-air-maximum-flow-continue-warning-timestamp-call-site'); Assert-ExactStringArray -Path $module -Name 'PURCHASED_AIR_CALC_HEATING_OUTDOOR_AIR_MAXIMUM_FLOW_CONTINUE_WARNING_TIMESTAMP_CALL_SOURCE_ORDER' -Expected $sites -Description 'one CP441 textual source site'
foreach ($pattern in @('EnergyPlus 26\.1 PurchasedAirManager\.cc:2374','Physical line 2375 is the excluded structural sibling-`else` boundary','EnergyPlus 26\.1 PurchasedAirManager\.cc:2376','PurchasedAirCalcHeatingOutdoorAirMaximumFlowContinueWarningTimestampCallSnapshot')) { Assert-Contains -Path $module -Pattern $pattern -Description 'CP441 boundary/type contract' }
$core = @(Get-ChildItem -LiteralPath $root -Recurse -File -Filter '*.rs'); $predecessorCore = @(Get-ChildItem -LiteralPath $predecessorRoot -Recurse -File -Filter '*.rs'); if ($core.Count -ne 11 -or @(Get-ChildItem "$root\tests" -File -Filter '*.rs').Count -ne 1) { throw 'CP441 exact eleven-subtree-file/one-test topology drift' }; if ($predecessorCore.Count -ne 13 -or @(Get-ChildItem "$predecessorRoot\tests" -File -Filter '*.rs').Count -ne 2) { throw 'CP441 exact sealed CP440 thirteen-subtree-file/two-test topology drift' }
$stateText = Read-RepoText -Path $state; $arrays = @([regex]::Matches($stateText, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*route_counts)\s*:\s*\[usize;\s*36\]') | ForEach-Object { $_.Groups['name'].Value }); $expectedArrays = @('predecessor_route_counts','predecessor_guard_false_fallthrough_route_counts','predecessor_guard_body_entry_route_counts','predecessor_volume_flow_assignment_route_counts','predecessor_first_warning_guard_false_fallthrough_route_counts','predecessor_first_warning_branch_entry_route_counts','predecessor_first_warning_counter_increment_route_counts','predecessor_first_warning_call_route_counts','predecessor_continue_warning_call_route_counts','heating_outdoor_air_maximum_flow_continue_warning_timestamp_call_route_counts'); if (($arrays -join '|') -cne ($expectedArrays -join '|')) { throw 'CP441 exact ten width-36 route arrays drift' }
foreach ($pattern in @('heating_outdoor_air_maximum_flow_continue_warning_call_committed_latest_route','heating_outdoor_air_maximum_flow_first_warning_call_committed_latest_route')) { Assert-Contains -Path $predecessorCommitted -Pattern $pattern -Description 'CP440 committed call seal' }; Assert-Contains -Path 'crates\ep_runtime\src\ideal_loads\calc\heating_outdoor_air_maximum_flow_first_warning_call\release\committed.rs' -Pattern 'heating_outdoor_air_maximum_flow_first_warning_counter_increment_committed_latest_route_and_outdoor_air_flow_maximum_heating_output_error_count' -Description 'retained committed warning-counter seal'; Assert-Contains -Path "$predecessorRoot\release.rs" -Pattern 'ExactReleaseReductionViolated' -Description 'CP440 exact-release reduction seal'; foreach ($pattern in @('cp440_committed_seal_is_retained_constant_time_and_active_call_exact','cp440_committed_seal_rejects_witness_route_and_accounting_forgeries','private_characterization','ShowContinueError')) { Assert-Contains -Path $predecessorCommittedTests -Pattern $pattern -Description 'CP440 committed-seal regression' }
foreach ($pattern in @('cp441_boundary_maps_timestamp_call_and_excludes_structural_else_and_recurring_call','exhaustive_67_routes_preserve_20_47_visibility_and_reach_three_private_calls','active_call_aliases_cp440_continue_warning_call_and_preserves_sealed_counter','cp441_new_state_has_ten_zeroed_width_36_arrays_and_no_service_state','cp441_transition_contains_no_sink_format_service_or_counter_mutation','cp441_subtree_is_twelve_files_and_every_file_is_bounded','state\.transition_count,\s*67','state\.inactive_transition_count,\s*64','state\.source_site_execution_count,\s*3','\(public_calls,\s*private_calls\),\s*\(0,\s*3\)')) { Assert-Contains -Path $tests -Pattern $pattern -Description 'CP441 exhaustive/call/topology regression' }
$moduleText = Read-RepoText -Path $module; $predecessorText = Read-RepoText -Path $predecessorModule; $snapshotBlock = Get-Cp441SnapshotBlock $moduleText "$($typeStem)Snapshot" '/// Final selected-unit CP441'; $predecessorBlock = Get-Cp441SnapshotBlock $predecessorText 'PurchasedAirCalcHeatingOutdoorAirMaximumFlowContinueWarningCallSnapshot' '/// Final selected-unit CP440'
$fields = @([regex]::Matches($snapshotBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value }); $predecessorFields = @([regex]::Matches($predecessorBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value }); if ($predecessorFields.Count -ne 428 -or $fields.Count -ne 429 -or @($fields | Select-Object -Unique).Count -ne 429 -or ($fields[0..427] -join '|') -cne ($predecessorFields -join '|') -or $fields[428] -cne 'heating_outdoor_air_maximum_flow_continue_warning_timestamp_call_site_reached') { throw 'CP441 exact unique 429-field/all-428-prefix/one-marker schema drift' }; if ([regex]::Matches($snapshotBlock,'Option<f64>').Count -ne 146 -or [regex]::Matches($snapshotBlock,'Option<bool>').Count -ne 9 -or [regex]::Matches($snapshotBlock,'Option<usize>').Count -ne 2 -or ([regex]::Matches($snapshotBlock,'Option<').Count - 146 - 9 - 2) -ne 6) { throw 'CP441 locked 429/146/9/6/2 schema drift' }
foreach ($pattern in @('cp441_schema_is_exact_429_with_cp440_first_428_and_one_marker','cp441_preserves_cp440_optional_type_counts','assert_eq!\(&cp441\[\.\.428\],\s*&cp440\[\.\.\]\)','predecessors\.len\(\),\s*67')) { Assert-Contains -Path $schemaTests -Pattern $pattern -Description 'CP441 schema/prefix regression' }
foreach ($pattern in @('heating_outdoor_air_maximum_flow_continue_warning_timestamp_call_site_reached:\s*route\.continue_warning_timestamp_call_site_reached','assigned_outdoor_air_flow_maximum_heating_output_error_count:\s*predecessor\.assigned_outdoor_air_flow_maximum_heating_output_error_count')) { Assert-Contains -Path $snapshot -Pattern $pattern -Description 'CP441 marker/counter preservation' }
foreach ($pattern in @('\[67usize,\s*64,\s*3,\s*3\]','20usize\s*\+\s*47','\[0usize,\s*3\]\.into_iter\(\)\.sum::<usize>\(\)','429','146','Option<bool>"\)\.count\(\),\s*9','Option<usize>"\)\.count\(\),\s*2','fields\.len\(\),\s*132','fields\[130\][\s\S]*?continue_warning_call','fields\[131\][\s\S]*?continue_warning_timestamp_call','cp441_new_state_has_ten_zeroed_lossless_route_partitions','cp441_is_ordered_after_cp440_and_does_not_feed_numerics_or_services')) { Assert-Contains -Path $coupledTests -Pattern $pattern -Description 'CP441 route/schema/binding/no-feed regression' }
foreach ($pattern in @('serializer_source_preserves_cp440_json_and_appends_only_the_call_marker','cp440_snapshot_json\(predecessor\)','heating_outdoor_air_maximum_flow_continue_warning_timestamp_call_site_reached')) { Assert-Contains -Path $serializationSnapshot -Pattern $pattern -Description 'CP441 CP440-prefix/marker serializer contract' }
$serializationSnapshotText = Read-RepoText -Path $serializationSnapshot; $productionSerialization = ($serializationSnapshotText -split '#\[cfg\(test\)\]', 2)[0]; $targetInsertPattern = [regex]::Escape(('tar' + 'get' + '.insert')) + '\s*\('; if ([regex]::Matches($productionSerialization, $targetInsertPattern).Count -ne 4) { throw 'CP441 exact four serializer insertions drift' }
foreach ($pattern in @('actual\.len\(\),\s*575','ends_with\("_ieee_bits"\)\)\s*\.count\(\),\s*146','fields\.len\(\),\s*429','snapshot\.matches\("Option<f64>"\)\.count\(\),\s*146','snapshot\.matches\("Option<bool>"\)\.count\(\),\s*9','snapshot\.matches\("Option<usize>"\)\.count\(\),\s*2','fields\.len\(\),\s*132','fields\[130\][\s\S]*?continue_warning_call','fields\[131\][\s\S]*?continue_warning_timestamp_call')) { Assert-Contains -Path $arbitrary -Pattern $pattern -Description 'actual CP441 JSON/IEEE/schema/binding contract' }
Assert-PatternsInOrder -Path $binding -Patterns @("let\s+calculation_$predecessorStem\s*=","let\s+calculation_$stem\s*=",'let\s+unit_available\s*=','let\s+coupling\s*=') -Description 'CP440-to-CP441-to-numerical order'; Assert-PatternsInOrder -Path $scheduled -Patterns @("pub\s+calculation_$predecessorStem\s*:","pub\s+calculation_$stem\s*:",'pub\s+coupling\s*:') -Description 'scheduled CP440-to-CP441 order'
$scheduledFields = @([regex]::Matches((Read-RepoText -Path $scheduled), '(?m)^\s*pub\s+(?<name>calculation_[A-Za-z0-9_]+)\s*:') | ForEach-Object { $_.Groups['name'].Value }); if ($scheduledFields.Count -ne 132 -or $scheduledFields[130] -cne 'calculation_heating_outdoor_air_maximum_flow_continue_warning_call' -or $scheduledFields[131] -cne 'calculation_heating_outdoor_air_maximum_flow_continue_warning_timestamp_call') { throw 'CP441 exact binding index 130/131/current 132 drift' }
foreach ($test in @('scheduled_binding_advances_cp441_after_cp440_before_unchanged_coupling','cp441_adapter_accepts_only_the_cp440_snapshot_and_no_scalar_input','cp441_extends_current_scheduled_binding_from_131_to_132_snapshots')) { Assert-Contains -Path $adapterTests -Pattern $test -Description 'CP441 adapter/current-binding regression' }
foreach ($pattern in @('predecessor_continue_warning_call_route_counts','heating_outdoor_air_maximum_flow_continue_warning_timestamp_call_route_counts','public_continue_warning_timestamp_call_count','warning_counter_owner_count','warning_counter_preservation_count','source_site_execution_count','local_public_skip_matches')) { Assert-Contains -Path $coupled -Pattern $pattern -Description 'CP441 public exact-release/no-call validation' }
foreach ($pattern in @('validate_direct_lifecycle','public_continue_warning_timestamp_call_count','source_site_execution_count','warning_counter_owner_count','warning_counter_preservation_count','lineage_is_exact')) { Assert-Contains -Path $pipelineValidation -Pattern $pattern -Description 'CP441 pipeline structural/no-feed seal' }; foreach ($pattern in @('lineage_is_exact','!predecessor\.heating_outdoor_air_maximum_flow_continue_warning_call_site_reached','!snapshot\.heating_outdoor_air_maximum_flow_continue_warning_timestamp_call_site_reached','cp440_snapshot_json')) { Assert-Contains -Path $pipelineLineage -Pattern $pattern -Description 'CP441 exact call/skip lineage seal' }
Assert-Contains -Path $pipelineRoot -Pattern 'non_direct_runtime_rejects_cp316_through_cp441_lifecycle_evidence' -Description 'CP441 non-direct firewall'; Assert-Contains -Path $pipelineRoot -Pattern 'purchased_air_calc_heating_outdoor_air_maximum_flow_continue_warning_timestamp_call_lifecycle' -Description 'CP441 lifecycle JSON field'
$ledger = Read-RepoText -Path 'specs\algorithm_ledger.toml'; $capabilities = Read-RepoText -Path 'specs\capabilities.toml'; if ([regex]::Matches($ledger,[regex]::Escape('CP441 supersedes only CP440')).Count -ne 1 -or [regex]::Matches($capabilities,[regex]::Escape('CP441 additionally requires')).Count -ne 1) { throw 'CP441 bounded spec addendum drift' }; foreach ($text in @($ledger,$capabilities)) { foreach ($claim in @('54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005','physical-line-2374','reach-heating-outdoor-air-maximum-flow-continue-warning-timestamp-call-site','all 428 CP440 fields','429','575','146','379 total','240 public','139 internal')) { if (-not $text.Contains($claim)) { throw "CP441 spec claim missing $claim" } } }
if ([regex]::Matches($ledger,'(?m)^\[\[algorithm\]\]\r?$').Count -ne 32 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"state_mapped"\r?$').Count -ne 58 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"source_mapped"\r?$').Count -ne 235 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.required_for_full_domain\s*=\s*true\r?$').Count -ne 170) { throw 'CP441 unchanged algorithm/routine count drift' }; Assert-NotContains -Path 'docs\src\current\roadmap.md' -Pattern '(?m)^## CP441\b' -Description 'Roadmap non-promotion'; Assert-NotContains -Path 'docs\src\porting-map\psychrometrics-source-map.md' -Pattern '(?m)^## CP441\b' -Description 'psychrometrics non-promotion'
$auditRoot = 'scripts\quality\ideal-loads-structure-audit'; $audits = @(Get-ChildItem $auditRoot -Filter 'cp*.ps1' -File); $historical = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -eq 326) -or ([int]$Matches.n -ge 329 -and [int]$Matches.n -le 440)) }); if ($historical.Count -ne 113 -or @($historical | Where-Object { $_.BaseName -match '^cp(?:327|328)-' }).Count) { throw 'CP441 exact 113 historical leaf set drift' }
$firewall = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 334 -and [int]$Matches.n -le 441 }); $script = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 337 -and [int]$Matches.n -le 441 }); $internal = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 367 -and [int]$Matches.n -le 441 }); $generated = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 335 -and [int]$Matches.n -le 441 }); if ($firewall.Count -ne 108 -or $script.Count -ne 105 -or $internal.Count -ne 75 -or $generated.Count -ne 107) { throw 'CP441 propagation range cardinality drift' }
foreach ($file in $firewall) { if (-not (Read-RepoText -Path $file.FullName).Contains('non_direct_runtime_rejects_cp316_through_cp441_lifecycle_evidence')) { throw "CP441 firewall propagation drift $($file.Name)" } }; foreach ($file in $script) { if (-not (Read-RepoText -Path $file.FullName).Contains('script_count = 379')) { throw "CP441 inventory-total propagation drift $($file.Name)" } }
$internalClassification = '\[regex\]::Matches\(\s*\$[A-Za-z_][A-Za-z0-9_]*\s*,\s*''\(\?m\)\^classification\s*\=\s*"internal"(?:\\r\?)?\$''\s*\)\s*\.Count\s*-ne\s*(?<count>\d+)'; foreach ($file in $internal) { $matches = [regex]::Matches((Read-RepoText -Path $file.FullName),$internalClassification); if ($matches.Count -ne 1 -or $matches[0].Groups['count'].Value -cne '139') { throw "CP441 internal propagation drift $($file.Name)" } }; foreach ($file in $generated) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('\| 379 \|') -or -not $text.Contains('\| 139 \|')) { throw "CP441 generated propagation drift $($file.Name)" } }
$helpers = @((Get-ChildItem $auditRoot -Filter 'cp326-*.ps1' -File); Get-ChildItem $auditRoot -Filter 'cp3*.ps1' -File | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 329 -and [int]$Matches.n -le 344 }); if ($helpers.Count -ne 17) { throw 'CP441 helper set drift' }; foreach ($file in $helpers) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains("calculation_$stem") -or -not $text.Contains("advance_$stem") -or -not $text.Contains('CP340 through CP441')) { throw "CP441 helper strip/whitelist drift $($file.Name)" } }
$terminal = @((Get-ChildItem $auditRoot -Filter 'cp345-*.ps1' -File); $audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -ge 377 -and [int]$Matches.n -le 392) -or ([int]$Matches.n -ge 394 -and [int]$Matches.n -le 440)) }); if ($terminal.Count -ne 64) { throw 'CP441 terminal set drift' }; foreach ($file in $terminal) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('$cp441Call') -or -not $text.Contains('CP440-to-CP441') -or -not $text.Contains("-Pattern ('Assert-Contains[^\r\n]+CP440-to-' + 'numerical')")) { throw "CP441 terminal propagation drift $($file.Name)" } }
$live = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 421 -and [int]$Matches.n -le 440 }); if ($live.Count -ne 20) { throw 'CP441 live binding set drift' }; foreach ($file in $live) { $text = Read-RepoText -Path $file.FullName; if ($text -notmatch 'current_132_snapshot_binding|binding_is_132|Count-ne132|,\s*\\s\*132') { throw "CP441 current-132 propagation drift $($file.Name)" }; if ($text -notmatch 'Count\s*-(?:gt|ne)\s*4204') { throw "CP441 master-cap propagation drift $($file.Name)" } }
$recent = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 425 -and [int]$Matches.n -le 440 }); if ($recent.Count -ne 16) { throw 'CP441 recent binding set drift' }; foreach ($file in $recent) { Assert-Contains -Path $file.FullName -Pattern "calculation_$stem" -Description 'CP441 recent binding propagation' }; $cp424 = Get-ChildItem $auditRoot -Filter 'cp424-*.ps1' -File; Assert-NotContains -Path $cp424.FullName -Pattern "calculation_$stem" -Description 'CP424 excludes CP441 registration'
$manualShape = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 424 -and [int]$Matches.n -le 440 }); if ($manualShape.Count -ne 17) { throw 'CP441 manual-shape propagation set drift' }; foreach ($file in $manualShape) { $matches = [regex]::Matches((Read-RepoText -Path $file.FullName), '3653\s*\+\s*3850\s*-or'); if ($matches.Count -ne 1) { throw "CP441 manual-shape propagation drift $($file.Name)" } }
$manuals = @([PSCustomObject]@{Path='docs\src\current\current-status.md';Length=507867;Hash='67E556437F767EE781CE77C87DBE2171DFF1E1B94FC190939FD173AD568B50B8'},[PSCustomObject]@{Path='docs\src\current\project-contract.md';Length=1459315;Hash='21F5F5FCF1B32F750C0D979DF42FF1A93E3166E6364AB020CAB1F4CB69043847'},[PSCustomObject]@{Path='docs\src\porting-map\heat-balance-source-map.md';Length=3924101;Hash='71643C9532D194D81450685C93227A0357771520C025701E5B4B45B67EC5B2CB'},[PSCustomObject]@{Path='docs\src\porting-map\ideal-loads-source-map.md';Length=1463442;Hash='232F23D6EC6AEBFC6AB40A41B463593C2CC15A1DE2A0335E2DDE36137B834BF9'},[PSCustomObject]@{Path='docs\src\porting-map\zone-air-update-map.md';Length=1662880;Hash='E3E5D6B57E01C906066425E18FD23B76EA6FE3E7CC879BB38276588EB8E9335E'}); $canonical = $null; foreach ($manual in $manuals) { $bytes = [IO.File]::ReadAllBytes($manual.Path); if ($bytes.Length -ne $manual.Length + 3850 -or [Array]::IndexOf($bytes,[byte]13) -ne -1 -or $bytes[-1] -ne 10) { throw "CP441 manual byte shape drift $($manual.Path)" }; $head = New-Object byte[] $manual.Length; [Array]::Copy($bytes,$head,$manual.Length); if ((Get-Cp441Sha $head) -cne $manual.Hash) { throw "CP441 manual prefix drift $($manual.Path)" }; $suffix = New-Object byte[] 3850; [Array]::Copy($bytes,$manual.Length,$suffix,0,3850); if ((Get-Cp441Sha $suffix) -cne 'DAA6FDA7E5D852F0E6B2F3126A8ACE04D19754E16E29DE0143F0F58395FA97FF') { throw "CP441 manual suffix drift $($manual.Path)" }; $text = [Text.UTF8Encoding]::new($false,$true).GetString($suffix); if ($null -eq $canonical) { $canonical = $text } elseif ($text -cne $canonical) { throw "CP441 canonical manual drift $($manual.Path)" } }
foreach ($pattern in @('(?m)^## CP441 heating outdoor-air maximum-flow continue-warning timestamp call$','physical-line-2374','line 2375','executable lines 2376','exactly one textual\s+source site','T441=67','Z441=64','C441=3','S441=3','20/47','active public/private\s+0/3','ten width-36','all 428 CP440 fields verbatim','429 unique Rust fields','146\s+`Option<f64>`','nine `Option<bool>`','six optional enums','two `Option<usize>`','575\s+unique keys','146\s+adjacent\s+IEEE sidecars','37/42/57','index 131','current\s+count 132','zero public timestamp call','379\s+total','240 public','139 internal')) { if ($canonical -notmatch "(?is)$pattern") { throw "CP441 documentation claim missing $pattern" } }
$master = Read-RepoText -Path 'scripts\quality\ideal-loads-structure-audit.ps1'; $leaf = Split-Path -Leaf $audit; $previous = $master.IndexOf('cp440-heating-outdoor-air-maximum-flow-continue-warning-call.ps1'); $current = $master.IndexOf($leaf); $done = $master.IndexOf('Write-Host "IdealLoads structure audit complete."'); if ($previous -lt 0 -or $current -le $previous -or $done -le $current -or [regex]::Matches($master,[regex]::Escape($leaf)).Count -ne 1) { throw 'CP441 master order/uniqueness drift' }
if ((Get-Content 'scripts\quality\ideal-loads-structure-audit.ps1').Count -ne 4204 -or (Get-Content 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1').Count -ne 1200 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\calc.rs').Count -ne 99 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\init\state\witnesses.rs').Count -ne 278 -or @(Get-Content 'crates\ep_runtime\src\ideal_loads\init\state.rs' | Where-Object { $_ -match '\S' }).Count -ne 380 -or (Get-Content $scheduled).Count -gt 500) { throw 'CP441 fixed cap drift' }
$inventory = Read-RepoText -Path 'specs\script_inventory.toml'; foreach ($pattern in @('script_count = 379','dev_command_count = 238','unused_script_count = 0','unreachable_count = 0')) { if ($inventory -notmatch $pattern) { throw "CP441 inventory missing $pattern" } }; if ([regex]::Matches($inventory,'(?m)^classification = "public"$').Count -ne 240 -or [regex]::Matches($inventory,'(?m)^classification = "internal"$').Count -ne 139) { throw 'CP441 inventory classification drift' }
Assert-Contains -Path 'specs\script_inventory.toml' -Pattern 'cp441-heating-outdoor-air-maximum-flow-continue-warning-timestamp-call\.ps1' -Description 'CP441 inventory record'; Assert-Contains -Path 'docs\src\generated\algorithm-ledger.md' -Pattern 'CP441 supersedes only CP440' -Description 'generated algorithm'; Assert-Contains -Path 'docs\src\generated\capability-index.md' -Pattern 'CP441 additionally requires' -Description 'generated capability'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 379 \|' -Description 'generated total'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 139 \|' -Description 'generated internal'
Write-Host 'CP441 heating outdoor-air maximum-flow continue-warning timestamp call structure audit passed.'
}
