# CP442 maps PurchasedAirManager.cc physical control line 2375's first-warning guard sibling else entry.
& {
function Get-Cp442Sha([byte[]]$Bytes) { $sha = [Security.Cryptography.SHA256]::Create(); try { return ([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-', '') } finally { $sha.Dispose() } }
function Get-Cp442SnapshotBlock([string]$Text, [string]$Type, [string]$EndMarker) { $start = $Text.IndexOf("pub struct $Type"); $end = $Text.IndexOf($EndMarker, $start); if ($start -lt 0 -or $end -le $start) { throw "CP442 snapshot block drift: $Type" }; return $Text.Substring($start, $end - $start) }
$stem = 'heating_outdoor_air_maximum_flow_first_warning_guard_else_branch_entry'
$predecessorStem = 'heating_outdoor_air_maximum_flow_continue_warning_timestamp_call'
$typeStem = 'PurchasedAirCalcHeatingOutdoorAirMaximumFlowFirstWarningGuardElseBranchEntry'
$predecessorTypeStem = 'PurchasedAirCalcHeatingOutdoorAirMaximumFlowContinueWarningTimestampCall'
$source = '.reference\energyplus-src\26.1.0\src\EnergyPlus\PurchasedAirManager.cc'
$module = "crates\ep_runtime\src\ideal_loads\calc\$stem.rs"; $predecessorModule = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem.rs"
$root = "crates\ep_runtime\src\ideal_loads\calc\$stem"; $predecessorRoot = "crates\ep_runtime\src\ideal_loads\calc\$predecessorStem"
$release = "$root\release.rs"; $releaseError = "$root\release\error.rs"; $prefix = "$root\release\prefix.rs"; $runtimeValidation = "$root\release\runtime_validation.rs"; $snapshotValidation = "$root\release\snapshot_validation.rs"
$state = "$root\state.rs"; $transition = "$root\transition.rs"; $accounting = "$root\transition\accounting.rs"; $snapshot = "$root\transition\snapshot.rs"; $tests = "$root\tests.rs"; $schemaTests = "$root\tests\schema_prefix.rs"
$predecessorCommitted = "$predecessorRoot\release\committed.rs"; $predecessorCommittedTests = "$predecessorRoot\tests\committed_seal.rs"
$binding = 'crates\ep_runtime\src\ideal_loads\binding.rs'; $scheduled = 'crates\ep_runtime\src\ideal_loads\binding\scheduled_output.rs'; $adapter = "crates\ep_runtime\src\ideal_loads\binding\$stem.rs"; $adapterTests = "crates\ep_runtime\src\ideal_loads\binding\$($stem)_tests.rs"
$coupled = "crates\ep_runtime\src\ideal_loads\coupled_runtime\$($stem)_validation.rs"; $coupledTests = 'crates\ep_runtime\src\ideal_loads\test_coupled_runtime_cp442.rs'; $coupledOutput = 'crates\ep_runtime\src\ideal_loads\coupled_output_tests.rs'; $fixture = "crates\ep_runtime\src\ideal_loads\coupled_output_tests\$($stem)_fixture.rs"
$pipelineRoot = 'crates\ep_run\src\pipeline.rs'; $pipelineStem = "purchased_air_$stem"; $pipelineModule = "crates\ep_run\src\pipeline\$pipelineStem.rs"; $pipeline = "crates\ep_run\src\pipeline\$pipelineStem"; $serializationRoot = "$pipeline\serialization.rs"; $serializationSnapshot = "$pipeline\serialization\snapshot.rs"; $pipelineValidation = "$pipeline\validation.rs"; $pipelineLineage = "$pipeline\validation\lineage.rs"
$arbitrary = 'crates\ep_run\tests\arbitrary_run_ideal_loads\cp442_assertions.rs'; $arbitraryPredecessor = 'crates\ep_run\tests\arbitrary_run_ideal_loads\cp441_assertions.rs'; $witness = "crates\ep_runtime\src\ideal_loads\init\state\witnesses\$stem.rs"; $audit = "scripts\quality\ideal-loads-structure-audit\cp442-$($stem -replace '_','-').ps1"
$required = @($source,$audit,$module,$predecessorModule,$release,$releaseError,$prefix,$runtimeValidation,$snapshotValidation,$state,$transition,$accounting,$snapshot,$tests,$schemaTests,$predecessorCommitted,$predecessorCommittedTests,$binding,$scheduled,$adapter,$adapterTests,$coupled,$coupledTests,$coupledOutput,$fixture,$pipelineRoot,$pipelineModule,$serializationRoot,$serializationSnapshot,$pipelineValidation,$pipelineLineage,$arbitrary,$arbitraryPredecessor,$witness)
foreach ($file in $required) { Assert-FileExists -Path $file -Description 'CP442 implementation/audit file' }
$bounded = @($audit,$module,$adapter,$adapterTests,$coupled,$coupledTests,$fixture,$pipelineModule,$serializationRoot,$serializationSnapshot,$pipelineValidation,$pipelineLineage,$arbitrary,$witness) + @((Get-ChildItem $root -Recurse -File -Filter '*.rs').FullName) + @((Get-ChildItem $pipeline -Recurse -File -Filter '*.rs').FullName)
foreach ($file in $bounded) { Assert-LineLimit -Path $file -Limit 500 -Description 'bounded CP442 file' }
$core = @(Get-ChildItem -LiteralPath $root -Recurse -File -Filter '*.rs'); $predecessorCore = @(Get-ChildItem -LiteralPath $predecessorRoot -Recurse -File -Filter '*.rs')
if ($core.Count -ne 11 -or @(Get-ChildItem "$root\tests" -File -Filter '*.rs').Count -ne 1 -or (Test-Path "$root\release\committed.rs") -or (Test-Path "$root\tests\committed_seal.rs")) { throw 'CP442 exact current eleven-core-file/one-split-test/no-self-seal topology drift' }
if ($predecessorCore.Count -ne 13 -or @(Get-ChildItem "$predecessorRoot\tests" -File -Filter '*.rs').Count -ne 2) { throw 'CP442 exact sealed CP441 thirteen-core-file/two-split-test topology drift' }
$registrations = @(
    [PSCustomObject]@{Path='crates\ep_runtime\src\ideal_loads\calc.rs';Pattern="mod\s+$stem;"},
    [PSCustomObject]@{Path='crates\ep_runtime\src\ideal_loads\init\state.rs';Pattern="calc_$stem\s*:"},
    [PSCustomObject]@{Path='crates\ep_runtime\src\ideal_loads\init\state\unit.rs';Pattern="calc_$stem\s*:"},
    [PSCustomObject]@{Path='crates\ep_runtime\src\ideal_loads\init\state\witnesses.rs';Pattern=$stem},
    [PSCustomObject]@{Path=$binding;Pattern="mod\s+$stem;"},
    [PSCustomObject]@{Path='crates\ep_runtime\src\ideal_loads\binding_tests.rs';Pattern="$($stem)_tests"},
    [PSCustomObject]@{Path='crates\ep_runtime\src\ideal_loads\coupled_runtime.rs';Pattern="$($stem)_validation"},
    [PSCustomObject]@{Path='crates\ep_runtime\src\ideal_loads\coupled_runtime_tests.rs';Pattern='test_coupled_runtime_cp442\.rs'},
    [PSCustomObject]@{Path=$coupledOutput;Pattern="$($stem)_fixture\.rs"},
    [PSCustomObject]@{Path=$pipelineRoot;Pattern="mod\s+$pipelineStem;"})
foreach ($registration in $registrations) { Assert-Contains -Path $registration.Path -Pattern $registration.Pattern -Description 'CP442 registration' }
if ((Get-Cp442Sha ([IO.File]::ReadAllBytes($source))) -cne '54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005') { throw 'CP442 pinned PurchasedAirManager.cc hash drift' }
$sourceLines = Get-Content -LiteralPath $source
if ($sourceLines[2373].Trim() -cne 'ShowContinueErrorTimeStamp(state, "");' -or $sourceLines[2374].Trim() -cne '} else {' -or $sourceLines[2375].Trim() -cne 'ShowRecurringWarningErrorAtEnd(' -or $sourceLines[2380].Trim() -cne 'OAVolFlowRate);' -or $sourceLines[2381].Trim() -cne '}' -or $sourceLines[2382].Trim() -cne 'OAMassFlowRate = PurchAir.MaxHeatMassFlowRate;') { throw 'CP442 physical predecessor/control/recurring-call/clamp boundary drift' }
$site = 'enter-heating-outdoor-air-maximum-flow-first-warning-guard-else-branch-after-guard-false-fallthrough'
Assert-ExactStringArray -Path $module -Name 'PURCHASED_AIR_CALC_HEATING_OUTDOOR_AIR_MAXIMUM_FLOW_FIRST_WARNING_GUARD_ELSE_BRANCH_ENTRY_SOURCE_ORDER' -Expected @($site) -Description 'sole CP442 structural else-entry site'
foreach ($pattern in @('EnergyPlus 26\.1 PurchasedAirManager\.cc:2375','EnergyPlus 26\.1 PurchasedAirManager\.cc:2376','PurchasedAirCalcHeatingOutdoorAirMaximumFlowFirstWarningGuardElseBranchEntrySnapshot')) { Assert-Contains -Path $module -Pattern $pattern -Description 'CP442 boundary/type contract' }
$moduleText = Read-RepoText -Path $module; $predecessorText = Read-RepoText -Path $predecessorModule
$snapshotBlock = Get-Cp442SnapshotBlock $moduleText "$($typeStem)Snapshot" '/// Final selected-unit CP442'; $predecessorBlock = Get-Cp442SnapshotBlock $predecessorText "$($predecessorTypeStem)Snapshot" '/// Final selected-unit CP441'
$fields = @([regex]::Matches($snapshotBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value }); $predecessorFields = @([regex]::Matches($predecessorBlock, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value })
if ($predecessorFields.Count -ne 429 -or $fields.Count -ne 430 -or @($fields | Select-Object -Unique).Count -ne 430 -or ($fields[0..428] -join '|') -cne ($predecessorFields -join '|') -or $fields[429] -cne 'heating_outdoor_air_maximum_flow_first_warning_guard_else_branch_entered') { throw 'CP442 exact unique 430-field/all-429-prefix/one-marker schema drift' }
if ([regex]::Matches($snapshotBlock,'Option<f64>').Count -ne 146 -or [regex]::Matches($snapshotBlock,'Option<bool>').Count -ne 9 -or [regex]::Matches($snapshotBlock,'Option<usize>').Count -ne 2 -or ([regex]::Matches($snapshotBlock,'Option<').Count - 146 - 9 - 2) -ne 6) { throw 'CP442 locked 430/146/9/6/2 schema drift' }
$stateText = Read-RepoText -Path $state; $arrays = @([regex]::Matches($stateText, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:\s*\[usize;\s*36\]') | ForEach-Object { $_.Groups['name'].Value })
$expectedArrays = @('predecessor_route_counts','heating_outdoor_air_maximum_flow_first_warning_guard_else_branch_entry_route_counts'); if (($arrays -join '|') -cne ($expectedArrays -join '|')) { throw 'CP442 exact two width-36 predecessor/local-entry route arrays drift' }
foreach ($pattern in @('cp441_supply_humidity_ratio_state_owner_count','unchanged_supply_humidity_ratio_preservation_count','cp441_supply_enthalpy_state_owner_count','unchanged_supply_enthalpy_preservation_count','cp441_supply_temperature_state_owner_count','unchanged_supply_temperature_preservation_count')) { Assert-Contains -Path $state -Pattern $pattern -Description 'CP442 retained W/H/T owner/preservation accounting' }
$ownerFields = [regex]::Matches($stateText, '(?m)^\s*pub\s+[A-Za-z_][A-Za-z0-9_]*_state_owner_count\s*:\s*usize\s*,'); $preservationFields = [regex]::Matches($stateText, '(?m)^\s*pub\s+unchanged_[A-Za-z_][A-Za-z0-9_]*_preservation_count\s*:\s*usize\s*,'); if ($ownerFields.Count -ne 3 -or $preservationFields.Count -ne 3) { throw 'CP442 exact three W/H/T owner and three unchanged-preservation counters drift' }
$warningCounterAccounting = 'outdoor_air_flow_maximum_heating_output_error_count_(?:state_)?owner_count|unchanged_outdoor_air_flow_maximum_heating_output_error_count_preservation_count|warning_counter_(?:owner|preservation)_count'; if ($stateText -match $warningCounterAccounting) { throw 'CP442 must not add warning-counter owner/preservation state' }
$transitionText = Read-RepoText -Path $transition; $routeMatch = [regex]::Match($transitionText, '(?s)struct\s+PurchasedAirCalcHeatingOutdoorAirMaximumFlowFirstWarningGuardElseBranchEntryRetainedRoute\s*\{(?<body>.*?)\}')
if (-not $routeMatch.Success) { throw 'CP442 retained Route declaration drift' }; $routeFields = @([regex]::Matches($routeMatch.Groups['body'].Value, '(?m)^\s*pub\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*:') | ForEach-Object { $_.Groups['name'].Value })
$expectedRouteFields = @('logical_index','predecessor_guard_false_fallthrough','predecessor_guard_body_entered','predecessor_assignment_executed','predecessor_first_warning_guard_evaluated','predecessor_first_warning_branch_entered','predecessor_first_warning_guard_false_fallthrough','predecessor_counter_increment_executed','predecessor_first_warning_call_site_reached','predecessor_continue_warning_call_site_reached','predecessor_continue_warning_timestamp_call_site_reached','entered')
if (($routeFields -join '|') -cne ($expectedRouteFields -join '|')) { throw 'CP442 exact twelve-component retained Route drift' }
foreach ($pattern in @('entered:\s*predecessor_route\.predecessor_first_warning_guard_false_fallthrough','predecessor\.heating_outdoor_air_maximum_flow_first_warning_guard_false_fallthrough\s*!=\s*predecessor_route\.predecessor_first_warning_guard_false_fallthrough','advance_heating_outdoor_air_maximum_flow_first_warning_guard_else_branch_entry_state_with_validated_route')) { Assert-Contains -Path $transition -Pattern $pattern -Description 'CP442 explicit guard-false retained-route derivation' }
if ($transitionText -match 'entered\s*:\s*![^,;\r\n]*continue_warning_timestamp') { throw 'CP442 must not infer else entry from timestamp absence' }
foreach ($pattern in @('heating_outdoor_air_maximum_flow_first_warning_guard_else_branch_entered:\s*route\.entered','assigned_outdoor_air_flow_maximum_heating_output_error_count:\s*predecessor\.assigned_outdoor_air_flow_maximum_heating_output_error_count','resulting_supply_humidity_ratio:\s*predecessor\.resulting_supply_humidity_ratio','resulting_supply_enthalpy_j_per_kg:\s*predecessor\.resulting_supply_enthalpy_j_per_kg','resulting_supply_temperature_c:\s*predecessor\.resulting_supply_temperature_c')) { Assert-Contains -Path $snapshot -Pattern $pattern -Description 'CP442 marker/counter/WHT preservation' }
foreach ($pattern in @('cp442_boundary_maps_structural_2375_and_excludes_recurring_call_2376','exhaustive_67_routes_have_exact_three_private_else_entries','cp442_new_state_has_exactly_two_zeroed_route_arrays_and_no_counter_owner','every_cp442_and_supplied_cp441_route_component_forgery_is_transactional','all_count_route_and_wht_overflows_are_transactional','release_uses_cp441_committed_seal_and_rejects_public_else_entry','cp442_subtree_is_twelve_files_and_every_file_is_bounded','predecessors\.len\(\),\s*67','\(public,\s*67\s*-\s*public\),\s*\(20,\s*47\)','\(public_entries,\s*private_entries\),\s*\(0,\s*3\)','state\.transition_count,\s*67','state\.inactive_transition_count,\s*64','state\.source_site_execution_count,\s*3','expected\[0\]\[1\],\s*9','expected\[1\]\[1\],\s*3','cp441_supply_humidity_ratio_state_owner_count,\s*37','unchanged_supply_humidity_ratio_preservation_count,\s*37','cp441_supply_enthalpy_state_owner_count,\s*42','unchanged_supply_enthalpy_preservation_count,\s*42','cp441_supply_temperature_state_owner_count,\s*57','unchanged_supply_temperature_preservation_count,\s*57')) { Assert-Contains -Path $tests -Pattern $pattern -Description 'CP442 exhaustive/transaction/topology regression' }
foreach ($pattern in @('cp442_schema_is_exact_430_with_cp441_first_429_and_one_marker','predecessor_reconstruction_and_cold_validated_paths_are_bit_exact_for_all_67_routes','assert_eq!\(&cp442\[\.\.429\],\s*cp441\.as_slice\(\)\)')) { Assert-Contains -Path $schemaTests -Pattern $pattern -Description 'CP442 schema/prefix/cold-route regression' }
foreach ($pattern in @('heating_outdoor_air_maximum_flow_continue_warning_timestamp_call_committed_latest_route','snapshots_match_bit_exact','predecessor_counts_match')) { Assert-Contains -Path $predecessorCommitted -Pattern $pattern -Description 'CP441 committed predecessor seal' }
foreach ($pattern in @('cp441_committed_seal_is_bounded_and_accepts_both_guard_outcomes','cp441_committed_seal_rejects_witness_route_and_accounting_forgeries','predecessor_first_warning_guard_false_fallthrough')) { Assert-Contains -Path $predecessorCommittedTests -Pattern $pattern -Description 'CP441 committed-seal regression' }
foreach ($pattern in @('cp441_guard_false_fixture_unit_for_successor_tests','outdoor_air_flow_maximum_heating_output_error_count_before,\s*Some\(1\)','outdoor_air_flow_maximum_heating_output_error_count_less_than_one,\s*Some\(false\)','assigned_outdoor_air_flow_maximum_heating_output_error_count,\s*None')) { Assert-Contains -Path "$predecessorRoot\tests.rs" -Pattern $pattern -Description 'CP442 explicit active guard-false fixture operands' }
Assert-Contains -Path $release -Pattern 'heating_outdoor_air_maximum_flow_continue_warning_timestamp_call_committed_latest_route\s*\(' -Description 'CP442 release consumes sealed CP441 route'
foreach ($pattern in @('predecessor_first_warning_guard_false_fallthrough_route_counts','first_warning_guard_else_entry_route_alias','public_else_entry_count','source_site_execution_count','cp441_supply_humidity_ratio_state_owner_count','cp441_supply_enthalpy_state_owner_count','cp441_supply_temperature_state_owner_count')) { Assert-Contains -Path $coupled -Pattern $pattern -Description 'CP442 coupled alias/count/WHT validation' }
$coupledProduction = (Read-RepoText -Path $coupled) -split '#\[cfg\(test\)\]', 2 | Select-Object -First 1; if ($coupledProduction -match 'DirectZonePurchasedAirCouplingInput|private_characterization|warning_counter_(?:owner|preservation)') { throw 'CP442 coupled production replay/feed/warning-counter drift' }
foreach ($pattern in @('cp442_contract_locks_routes_schema_json_and_current_binding','cp442_new_state_has_two_zeroed_lossless_route_partitions','cp442_is_ordered_after_cp441_and_does_not_feed_numerics_or_services','\[67usize,\s*64,\s*3,\s*3\]','20usize\s*\+\s*47','\[0usize,\s*3\]\.into_iter\(\)\.sum::<usize>\(\)','fields\.len\(\),\s*133','fields\[131\][\s\S]*continue_warning_timestamp_call','fields\[132\][\s\S]*first_warning_guard_else_branch_entry')) { Assert-Contains -Path $coupledTests -Pattern $pattern -Description 'CP442 coupled route/schema/binding/no-feed regression' }
Assert-Contains -Path $coupledOutput -Pattern 'cp442_marker_mutation_cannot_change_the_unchanged_numerical_coupling_output' -Description 'CP442 no-feed mutation regression'
foreach ($pattern in @('validate_direct_lifecycle','validate_public_route_contract','lineage_is_exact','predecessor_first_warning_guard_false_fallthrough_route_counts','heating_outdoor_air_maximum_flow_first_warning_guard_else_branch_entry_route_counts','public_else_branch_entry_count')) { Assert-Contains -Path $pipelineValidation -Pattern $pattern -Description 'CP442 pipeline direct route/count/lineage seal' }
foreach ($pattern in @('lineage_is_exact','predecessor_cp441_snapshot','first_warning_guard_false_fallthrough','cp441_snapshot_json')) { Assert-Contains -Path $pipelineLineage -Pattern $pattern -Description 'CP442 exact guard-false lineage seal' }
foreach ($pattern in @('serializer_source_preserves_cp441_json_and_appends_only_the_entry_marker','cp441_snapshot_json\(predecessor\)','heating_outdoor_air_maximum_flow_first_warning_guard_else_branch_entered')) { Assert-Contains -Path $serializationSnapshot -Pattern $pattern -Description 'CP442 CP441-prefix/marker serializer contract' }
$snapshotSerializerProduction = (Read-RepoText -Path $serializationSnapshot) -split '#\[cfg\(test\)\]', 2 | Select-Object -First 1; $targetInsertPattern = [regex]::Escape(('tar' + 'get' + '.insert')) + '\s*\('; if ([regex]::Matches($snapshotSerializerProduction,$targetInsertPattern).Count -ne 4) { throw 'CP442 exact four snapshot serializer insertions drift' }
$lifecycleSerializerProduction = (Read-RepoText -Path $serializationRoot) -split '#\[cfg\(test\)\]', 2 | Select-Object -First 1; if ([regex]::Matches($lifecycleSerializerProduction,'route_counts"\s*:').Count -ne 2 -or $lifecycleSerializerProduction -match $warningCounterAccounting) { throw 'CP442 exact two lifecycle route arrays/no warning-counter accounting drift' }
foreach ($pattern in @('actual\.len\(\),\s*576','ends_with\("_ieee_bits"\)\)\s*\.count\(\),\s*146','fields\.len\(\),\s*430','snapshot\.matches\("Option<f64>"\)\.count\(\),\s*146','snapshot\.matches\("Option<bool>"\)\.count\(\),\s*9','snapshot\.matches\("Option<usize>"\)\.count\(\),\s*2','fields\.len\(\),\s*133','fields\[131\][\s\S]*continue_warning_timestamp_call','fields\[132\][\s\S]*first_warning_guard_else_branch_entry')) { Assert-Contains -Path $arbitrary -Pattern $pattern -Description 'actual CP442 JSON/IEEE/schema/binding contract' }
foreach ($pattern in @('cp442_assertions::assert_direct\(runtime,\s*results\)','cp442_assertions::assert_non_direct\(runtime\)')) { Assert-Contains -Path $arbitraryPredecessor -Pattern $pattern -Description 'CP442 direct/non-direct arbitrary delegation' }
Assert-PatternsInOrder -Path $binding -Patterns @("let\s+calculation_$predecessorStem\s*=","let\s+calculation_$stem\s*=",'let\s+unit_available\s*=','let\s+coupling\s*=') -Description 'CP441-to-CP442-to-numerical order'
$scheduledFields = @([regex]::Matches((Read-RepoText -Path $scheduled), '(?m)^\s*(?:#\[doc\s*=\s*"[^"]*"\]\s*)?pub\s+(?<name>calculation_[A-Za-z0-9_]+)\s*:') | ForEach-Object { $_.Groups['name'].Value }); if ($scheduledFields.Count -ne 133 -or $scheduledFields[131] -cne "calculation_$predecessorStem" -or $scheduledFields[132] -cne "calculation_$stem") { throw 'CP442 exact binding index 131/132/current 133 drift' }
$staleScheduledParsers = @(Get-ChildItem 'crates\ep_runtime','crates\ep_run' -Recurse -File -Filter '*.rs' | Select-String -Pattern '(?:matches\("    pub calculation_"|starts_with\("[^"]*pub calculation_"\))'); if ($staleScheduledParsers.Count) { throw "CP442 inline-doc-incompatible scheduled binding parser remains in $($staleScheduledParsers[0].Path):$($staleScheduledParsers[0].LineNumber)" }
foreach ($test in @('scheduled_binding_advances_cp442_after_cp441_before_unchanged_coupling','cp442_adapter_accepts_only_the_cp441_snapshot_and_no_scalar_input','cp442_extends_current_scheduled_binding_from_132_to_133_snapshots')) { Assert-Contains -Path $adapterTests -Pattern $test -Description 'CP442 adapter/current-binding regression' }
Assert-Contains -Path $pipelineRoot -Pattern 'non_direct_runtime_rejects_cp316_through_cp442_lifecycle_evidence' -Description 'CP442 non-direct firewall'; Assert-Contains -Path $pipelineRoot -Pattern 'purchased_air_calc_heating_outdoor_air_maximum_flow_first_warning_guard_else_branch_entry_lifecycle' -Description 'CP442 lifecycle JSON field'
$heading = 'CP442 heating outdoor-air maximum-flow first-warning guard else-branch entry'; $manualSuffixLength = 3743; $manualSuffixHash = 'D7664FDE09658F283C3DB7C7250440A6D733923D41B590161FB283D7C282FB49'
$manuals = @([PSCustomObject]@{Path='docs\src\current\current-status.md';Length=511717;Hash='ECFDC3663DE97E3613A247DF38CBB4A7EFA54BE366E9B9528D575C8632ED35D0'},[PSCustomObject]@{Path='docs\src\current\project-contract.md';Length=1463165;Hash='45B40E1D4ABEA8BCDB7B3C94BD3DDD06E86CFCABBC5ED1739EB2D737E32C80DF'},[PSCustomObject]@{Path='docs\src\porting-map\heat-balance-source-map.md';Length=3927951;Hash='459C6EA818DF868089E55CBF3EDB250DEDFD72C2EE54B5791B4639668D192914'},[PSCustomObject]@{Path='docs\src\porting-map\ideal-loads-source-map.md';Length=1467292;Hash='462F18750F1733A8484E03BC9F4623A9F3F2720F71F2E994FB719859BE88FC2C'},[PSCustomObject]@{Path='docs\src\porting-map\zone-air-update-map.md';Length=1666730;Hash='E431AD804FF6FEBE9B7C7738F90991E30EFBCF55ED996D91B5F351B46FF53041'})
$canonical = $null; foreach ($manual in $manuals) { $bytes = [IO.File]::ReadAllBytes($manual.Path); if ($bytes.Length -ne $manual.Length + $manualSuffixLength -or [Array]::IndexOf($bytes,[byte]13) -ne -1 -or $bytes[-1] -ne 10) { throw "CP442 manual byte shape drift $($manual.Path)" }; $head = New-Object byte[] $manual.Length; [Array]::Copy($bytes,$head,$manual.Length); if ((Get-Cp442Sha $head) -cne $manual.Hash) { throw "CP442 manual prefix drift $($manual.Path)" }; $suffix = New-Object byte[] $manualSuffixLength; [Array]::Copy($bytes,$manual.Length,$suffix,0,$manualSuffixLength); if ((Get-Cp442Sha $suffix) -cne $manualSuffixHash) { throw "CP442 manual suffix drift $($manual.Path)" }; $text = [Text.UTF8Encoding]::new($false,$true).GetString($suffix); if ([regex]::Matches($text,"(?m)^## $([regex]::Escape($heading))$").Count -ne 1) { throw "CP442 manual heading drift $($manual.Path)" }; if ($null -eq $canonical) { $canonical = $text } elseif ($text -cne $canonical) { throw "CP442 canonical manual drift $($manual.Path)" } }
foreach ($pattern in @('physical-line-2375 structural/control','enter-heating-outdoor-air-maximum-flow-first-warning-guard-else-branch-after-guard-false-fallthrough','line 2376.*first excluded','T442=67','Z442=64','E442=3','S442=3','20/47','active public/private 0/3','two width-36 arrays','false-fallthrough array','timestamp calls and three CP442 else entries','Absence of a timestamp call is\s+insufficient','Some\(1\)','Some\(false\)','assigned-counter carrier remains `None`','all 429 CP441 fields','430 unique Rust fields','146','nine `Option<bool>`','six optional enums','two\s+`Option<usize>`','576 unique keys','37/42/57','index 132','current count 133','380 total','240 public','140 internal')) { if ($canonical -notmatch "(?is)$pattern") { throw "CP442 documentation claim missing $pattern" } }
$ledger = Read-RepoText -Path 'specs\algorithm_ledger.toml'; $capabilities = Read-RepoText -Path 'specs\capabilities.toml'; if ([regex]::Matches($ledger,[regex]::Escape('CP442 supersedes only CP441')).Count -ne 1 -or [regex]::Matches($capabilities,[regex]::Escape('CP442 additionally requires')).Count -ne 1) { throw 'CP442 bounded spec addendum drift' }
foreach ($text in @($ledger,$capabilities)) { foreach ($claim in @('54D960BCBFDF4F424A84BA73BF62040677424AD93E2F9362584898B0B146C005','physical-line-2375','enter-heating-outdoor-air-maximum-flow-first-warning-guard-else-branch-after-guard-false-fallthrough','two width-36','guard-false','430','576','380 total','240 public','140 internal')) { if (-not $text.Contains($claim)) { throw "CP442 spec claim missing $claim" } } }
if ([regex]::Matches($ledger,'(?m)^\[\[algorithm\]\]\r?$').Count -ne 32 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"state_mapped"\r?$').Count -ne 58 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.completion_status\s*=\s*"source_mapped"\r?$').Count -ne 235 -or [regex]::Matches($ledger,'(?m)^routine\.[A-Za-z0-9_]+\.required_for_full_domain\s*=\s*true\r?$').Count -ne 170) { throw 'CP442 unchanged algorithm/routine count drift' }
Assert-NotContains -Path 'docs\src\current\roadmap.md' -Pattern '(?m)^## CP442\b' -Description 'Roadmap non-promotion'; Assert-NotContains -Path 'docs\src\porting-map\psychrometrics-source-map.md' -Pattern '(?m)^## CP442\b' -Description 'psychrometrics non-promotion'
$auditRoot = 'scripts\quality\ideal-loads-structure-audit'; $audits = @(Get-ChildItem $auditRoot -Filter 'cp*.ps1' -File)
$historical = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -eq 326) -or ([int]$Matches.n -ge 329 -and [int]$Matches.n -le 441)) }); if ($historical.Count -ne 114 -or @($historical | Where-Object { $_.BaseName -match '^cp(?:327|328)-' }).Count) { throw 'CP442 exact 114 historical leaf set drift' }
$firewall = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 334 -and [int]$Matches.n -le 442 }); $script = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 337 -and [int]$Matches.n -le 442 }); $internal = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 367 -and [int]$Matches.n -le 442 }); $generated = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 335 -and [int]$Matches.n -le 442 }); if ($firewall.Count -ne 109 -or $script.Count -ne 106 -or $internal.Count -ne 76 -or $generated.Count -ne 108) { throw 'CP442 propagation range cardinality drift' }
foreach ($file in $firewall) { if (-not (Read-RepoText -Path $file.FullName).Contains('non_direct_runtime_rejects_cp316_through_cp442_lifecycle_evidence')) { throw "CP442 firewall propagation drift $($file.Name)" } }; foreach ($file in $script) { if (-not (Read-RepoText -Path $file.FullName).Contains('script_count = 380')) { throw "CP442 inventory-total propagation drift $($file.Name)" } }
$internalClassification = '\[regex\]::Matches\(\s*\$[A-Za-z_][A-Za-z0-9_]*\s*,\s*''\(\?m\)\^classification\s*\=\s*"internal"(?:\\r\?)?\$''\s*\)\s*\.Count\s*-ne\s*(?<count>\d+)'; foreach ($file in $internal) { $matches = [regex]::Matches((Read-RepoText -Path $file.FullName),$internalClassification); if ($matches.Count -ne 1 -or $matches[0].Groups['count'].Value -cne '140') { throw "CP442 internal propagation drift $($file.Name)" } }; foreach ($file in $generated) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('\| 380 \|') -or -not $text.Contains('\| 140 \|')) { throw "CP442 generated propagation drift $($file.Name)" } }
$helpers = @((Get-ChildItem $auditRoot -Filter 'cp326-*.ps1' -File); Get-ChildItem $auditRoot -Filter 'cp3*.ps1' -File | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 329 -and [int]$Matches.n -le 344 }); if ($helpers.Count -ne 17) { throw 'CP442 helper set drift' }; foreach ($file in $helpers) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains("calculation_$stem") -or -not $text.Contains("advance_$stem") -or -not $text.Contains('CP340 through CP442')) { throw "CP442 helper strip/whitelist drift $($file.Name)" } }
$helperLiteral = @($helpers; $audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 434 -and [int]$Matches.n -le 441 }); if ($helperLiteral.Count -ne 25) { throw 'CP442 helper-literal set drift' }; foreach ($file in $helperLiteral) { if (-not (Read-RepoText -Path $file.FullName).Contains('CP340 through CP442')) { throw "CP442 helper-literal propagation drift $($file.Name)" } }
$terminal = @((Get-ChildItem $auditRoot -Filter 'cp345-*.ps1' -File); $audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and (([int]$Matches.n -ge 377 -and [int]$Matches.n -le 392) -or ([int]$Matches.n -ge 394 -and [int]$Matches.n -le 441)) }); if ($terminal.Count -ne 65) { throw 'CP442 terminal set drift' }; foreach ($file in $terminal) { $text = Read-RepoText -Path $file.FullName; if (-not $text.Contains('$cp442Call') -or -not $text.Contains('CP441-to-CP442') -or -not $text.Contains('CP442-to-numerical') -or $text.Contains('CP441-to-numerical')) { throw "CP442 terminal propagation drift $($file.Name)" } }
$live = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 421 -and [int]$Matches.n -le 441 }); if ($live.Count -ne 21) { throw 'CP442 live binding set drift' }; foreach ($file in $live) { $text = Read-RepoText -Path $file.FullName; if ($text -notmatch 'current_133_snapshot_binding|binding_is_133|Count-ne133|Count -ne 133|,\s*\\s\*133') { throw "CP442 current-133 propagation drift $($file.Name)" } }
$witnessCaps = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 426 -and [int]$Matches.n -le 441 }); if ($witnessCaps.Count -ne 16) { throw 'CP442 witness-cap set drift' }; foreach ($file in $witnessCaps) { if ((Read-RepoText -Path $file.FullName) -notmatch "witnesses\.rs'\)\.Count\s*-ne\s*279") { throw "CP442 witness-cap propagation drift $($file.Name)" } }
$recent = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 425 -and [int]$Matches.n -le 441 }); if ($recent.Count -ne 17) { throw 'CP442 recent registration set drift' }; foreach ($file in $recent) { if (-not (Read-RepoText -Path $file.FullName).Contains("calculation_$stem")) { throw "CP442 recent registration drift $($file.Name)" } }; $cp424 = @(Get-ChildItem $auditRoot -Filter 'cp424-*.ps1' -File); if ($cp424.Count -ne 1 -or (Read-RepoText -Path $cp424[0].FullName).Contains("calculation_$stem")) { throw 'CP442 CP424 rolling-recent exclusion drift' }
$manualAudits = @($audits | Where-Object { $_.BaseName -match '^cp(?<n>\d+)-' -and [int]$Matches.n -ge 424 -and [int]$Matches.n -le 441 }); if ($manualAudits.Count -ne 18) { throw 'CP442 manual-shape set drift' }; foreach ($file in $manualAudits) { $text = Read-RepoText -Path $file.FullName; $number = [int]([regex]::Match($file.BaseName,'^cp(\d+)-').Groups[1].Value); $pattern = if ($number -eq 441) { '\$manual\.Length\s*\+\s*3850\s*\+\s*3743\s*-or' } else { '3653\s*\+\s*3850\s*\+\s*3743\s*-or' }; if ($text -notmatch $pattern) { throw "CP442 manual-shape propagation drift $($file.Name)" } }
$master = Read-RepoText -Path 'scripts\quality\ideal-loads-structure-audit.ps1'; $leaf = Split-Path -Leaf $audit; $previous = $master.IndexOf('cp441-heating-outdoor-air-maximum-flow-continue-warning-timestamp-call.ps1'); $current = $master.IndexOf($leaf); $done = $master.IndexOf('Write-Host "IdealLoads structure audit complete."'); if ($previous -lt 0 -or $current -le $previous -or $done -le $current -or [regex]::Matches($master,[regex]::Escape($leaf)).Count -ne 1) { throw 'CP442 master order/uniqueness drift' }
if ((Get-Content 'scripts\quality\ideal-loads-structure-audit\cp345-cooling-positive-supply-post-capacity-limit-humidity-ratio-mixed-air-assignment.ps1').Count -ne 1200 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\calc.rs').Count -ne 99 -or (Get-Content 'crates\ep_runtime\src\ideal_loads\init\state\witnesses.rs').Count -ne 279 -or @(Get-Content 'crates\ep_runtime\src\ideal_loads\init\state.rs' | Where-Object { $_ -match '\S' }).Count -ne 380 -or (Get-Content $scheduled).Count -gt 500) { throw 'CP442 fixed cap drift' }
$inventoryText = Read-RepoText -Path 'specs\script_inventory.toml'; foreach ($pattern in @('script_count = 380','dev_command_count = 238','unused_script_count = 0','unreachable_count = 0')) { if ($inventoryText -notmatch $pattern) { throw "CP442 inventory missing $pattern" } }; if ([regex]::Matches($inventoryText,'(?m)^classification = "public"$').Count -ne 240 -or [regex]::Matches($inventoryText,'(?m)^classification = "internal"$').Count -ne 140) { throw 'CP442 inventory classification drift' }
Assert-Contains -Path 'specs\script_inventory.toml' -Pattern 'cp442-heating-outdoor-air-maximum-flow-first-warning-guard-else-branch-entry\.ps1' -Description 'CP442 inventory record'; Assert-CanonicalBoundary -Registry algorithm -Id "ideal_loads_zone_equipment_purchased_air_source_order" -Pattern 'CP442 supersedes only CP441' -Description 'canonical algorithm addendum'; Assert-CanonicalBoundary -Registry capability -Id "ideal_loads_no_oa_sensible" -Pattern 'CP442 additionally requires' -Description 'canonical capability addendum'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 380 \|' -Description 'generated total'; Assert-Contains -Path 'docs\src\generated\script-index.md' -Pattern '\| 140 \|' -Description 'generated internal'
Write-Host 'CP442 heating outdoor-air maximum-flow first-warning guard else-branch entry structure audit passed.'
}
