# Add ZON-01 only, retaining every previous target and source/flags.
if(NOT DEFINED ZON01_REPOSITORY_ROOT)
  message(FATAL_ERROR "ZON-01 requires an explicit repository root")
endif()
include("${ZON01_REPOSITORY_ROOT}/tools/porting/geo03_reference.cmake")
if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
  get_property(_zon01_scheduled GLOBAL PROPERTY ZON01_REFERENCE_SCHEDULED)
  if(NOT _zon01_scheduled)
    set_property(GLOBAL PROPERTY ZON01_REFERENCE_SCHEDULED TRUE)
    set_property(GLOBAL PROPERTY ZON01_REFERENCE_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}")
    function(zon01_add_original_reference)
      if(NOT TARGET energypluslib)
        message(FATAL_ERROR "ZON-01 requires the verified unchanged original GNU core")
      endif()
      get_property(_zon01_dir GLOBAL PROPERTY ZON01_REFERENCE_DIRECTORY)
      get_target_property(_zon01_target_defs energypluslib COMPILE_DEFINITIONS)
      get_directory_property(_zon01_directory_defs DIRECTORY "${CMAKE_SOURCE_DIR}/src/EnergyPlus" COMPILE_DEFINITIONS)
      set(_zon01_defs ${_zon01_target_defs} ${_zon01_directory_defs})
      list(FILTER _zon01_defs EXCLUDE REGEX "-NOTFOUND$")
      list(REMOVE_DUPLICATES _zon01_defs)
      add_executable(zon01_reference "${_zon01_dir}/zon01_reference.cpp")
      target_include_directories(zon01_reference PRIVATE "$<TARGET_PROPERTY:energypluslib,INCLUDE_DIRECTORIES>")
      target_compile_definitions(zon01_reference PRIVATE ${_zon01_defs})
      target_link_libraries(zon01_reference PRIVATE project_options project_fp_options project_warnings objexx bcrypt)
      target_compile_features(zon01_reference PRIVATE cxx_std_20)
      if(NOT DEFINED ZON01_BULK_FRAGMENT OR NOT EXISTS "${ZON01_BULK_FRAGMENT}")
        message(FATAL_ERROR "ZON-01 requires exact HeatBalanceSurfaceManager.cc2231-2239")
      endif()
      add_executable(zon01_reference_helper "${_zon01_dir}/zon01_reference_helper.cpp")
      target_compile_definitions(zon01_reference_helper PRIVATE ${_zon01_defs} ZON01_BULK_FRAGMENT="${ZON01_BULK_FRAGMENT}")
      target_link_libraries(zon01_reference_helper PRIVATE energypluslib project_options project_fp_options project_warnings)
      target_compile_features(zon01_reference_helper PRIVATE cxx_std_20)
    endfunction()
    cmake_language(DEFER CALL zon01_add_original_reference)
  endif()
endif()
