# Append one CLK-02 parser helper; preserve all historical targets and fragments.
if(NOT DEFINED CLK02_REPOSITORY_ROOT)
  message(FATAL_ERROR "CLK-02 requires an explicit repository root")
endif()
include("${CLK02_REPOSITORY_ROOT}/tools/porting/zon01_reference.cmake")
if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
  get_property(_clk02_scheduled GLOBAL PROPERTY CLK02_REFERENCE_SCHEDULED)
  if(NOT _clk02_scheduled)
    set_property(GLOBAL PROPERTY CLK02_REFERENCE_SCHEDULED TRUE)
    set_property(GLOBAL PROPERTY CLK02_REFERENCE_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}")
    function(clk02_add_original_reference)
      if(NOT TARGET energypluslib)
        message(FATAL_ERROR "CLK-02 requires the unchanged genuine GNU core")
      endif()
      get_property(_clk02_dir GLOBAL PROPERTY CLK02_REFERENCE_DIRECTORY)
      get_target_property(_clk02_target_defs energypluslib COMPILE_DEFINITIONS)
      get_directory_property(_clk02_directory_defs DIRECTORY "${CMAKE_SOURCE_DIR}/src/EnergyPlus" COMPILE_DEFINITIONS)
      set(_clk02_defs ${_clk02_target_defs} ${_clk02_directory_defs})
      list(FILTER _clk02_defs EXCLUDE REGEX "-NOTFOUND$")
      list(REMOVE_DUPLICATES _clk02_defs)
      add_executable(clk02_reference_helper "${_clk02_dir}/clk02_reference_helper.cpp")
      target_include_directories(clk02_reference_helper PRIVATE "$<TARGET_PROPERTY:energypluslib,INCLUDE_DIRECTORIES>")
      target_compile_definitions(clk02_reference_helper PRIVATE ${_clk02_defs})
      target_link_libraries(clk02_reference_helper PRIVATE energypluslib project_options project_fp_options project_warnings bcrypt)
      target_compile_features(clk02_reference_helper PRIVATE cxx_std_20)
    endfunction()
    cmake_language(DEFER CALL clk02_add_original_reference)
  endif()
endif()
