//! Persistent CP385 post-saturation supply-enthalpy assignment state.

use ep_model::IdealLoadsAirSystemId;

use super::PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputSupplyEnthalpyAssignmentSnapshot;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(in crate::ideal_loads::calc) enum PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputSupplyEnthalpyAssignmentRetainedRoute
{
    UnitOff,
    NonCooling,
    PositiveGuardFalseFallthrough,
    HeatingAvailabilityGuardFalseFallthroughCapacityLimitGuardFalseFallthrough,
    HeatingAvailabilityGuardFalseFallthroughDehumidificationGuardFalseFallthrough,
    HeatingAvailabilityGuardFalseFallthroughDehumidificationTotalOutputCapacityGuardFalseFallthrough,
    HeatingAvailabilityGuardFalseFallthroughDehumidificationTotalOutputMaximumCapacityAssigned,
    HumidificationControlGuardFalseFallthroughCapacityLimitGuardFalseFallthrough,
    HumidificationControlGuardFalseFallthroughDehumidificationGuardFalseFallthrough,
    HumidificationControlGuardFalseFallthroughDehumidificationTotalOutputCapacityGuardFalseFallthrough,
    HumidificationControlGuardFalseFallthroughDehumidificationTotalOutputMaximumCapacityAssigned,
    DehumidificationControlHumidistatMaximumAssignmentExecutedCapacityLimitGuardFalseFallthrough,
    DehumidificationControlHumidistatMaximumAssignmentExecutedDehumidificationGuardFalseFallthrough,
    DehumidificationControlHumidistatMaximumAssignmentExecutedDehumidificationTotalOutputCapacityGuardFalseFallthrough,
    DehumidificationControlHumidistatMaximumAssignmentExecutedDehumidificationTotalOutputMaximumCapacityAssigned,
    DehumidificationControlNoneMaximumAssignmentExecutedCapacityLimitGuardFalseFallthrough,
    DehumidificationControlNoneMaximumAssignmentExecutedDehumidificationGuardFalseFallthrough,
    DehumidificationControlNoneMaximumAssignmentExecutedDehumidificationTotalOutputCapacityGuardFalseFallthrough,
    DehumidificationControlNoneMaximumAssignmentExecutedDehumidificationTotalOutputMaximumCapacityAssigned,
    DehumidificationControlGuardFalseFallthroughCapacityLimitGuardFalseFallthrough,
    DehumidificationControlGuardFalseFallthroughDehumidificationGuardFalseFallthrough,
    DehumidificationControlGuardFalseFallthroughDehumidificationTotalOutputCapacityGuardFalseFallthrough,
    DehumidificationControlGuardFalseFallthroughDehumidificationTotalOutputMaximumCapacityAssigned,
}

/// Persistent bounded state and exact CP384/CP385 route and source-site counters.
#[allow(missing_docs)]
#[derive(Clone, Debug, PartialEq)]
pub struct PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputSupplyEnthalpyAssignmentRuntimeState
{
    pub system: IdealLoadsAirSystemId,
    pub transition_count: usize,
    pub unit_off_skip_count: usize,
    pub non_cooling_skip_count: usize,
    pub positive_guard_false_fallthrough_skip_count: usize,
    pub heating_availability_guard_false_fallthrough_count: usize,
    pub humidification_control_guard_false_fallthrough_count: usize,
    pub dehumidification_control_humidistat_supply_humidity_ratio_maximum_assignment_count: usize,
    pub dehumidification_control_none_supply_humidity_ratio_maximum_assignment_count: usize,
    pub dehumidification_control_guard_false_fallthrough_count: usize,
    pub heating_availability_guard_false_fallthrough_capacity_guard_false_count: usize,
    pub heating_availability_guard_false_fallthrough_dehumidification_guard_false_count: usize,
    pub heating_availability_guard_false_fallthrough_dehumidification_total_output_assignment_count: usize,
    pub heating_availability_guard_false_fallthrough_dehumidification_total_output_capacity_guard_false_fallthrough_count: usize,
    pub heating_availability_guard_false_fallthrough_dehumidification_total_output_maximum_capacity_assignment_count: usize,
    pub humidification_control_guard_false_fallthrough_capacity_guard_false_count: usize,
    pub humidification_control_guard_false_fallthrough_dehumidification_guard_false_count: usize,
    pub humidification_control_guard_false_fallthrough_dehumidification_total_output_assignment_count: usize,
    pub humidification_control_guard_false_fallthrough_dehumidification_total_output_capacity_guard_false_fallthrough_count: usize,
    pub humidification_control_guard_false_fallthrough_dehumidification_total_output_maximum_capacity_assignment_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_capacity_guard_false_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_dehumidification_guard_false_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_assignment_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_capacity_guard_false_fallthrough_count: usize,
    pub dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_maximum_capacity_assignment_count: usize,
    pub dehumidification_control_none_maximum_assignment_capacity_guard_false_count: usize,
    pub dehumidification_control_none_maximum_assignment_dehumidification_guard_false_count: usize,
    pub dehumidification_control_none_maximum_assignment_dehumidification_total_output_assignment_count: usize,
    pub dehumidification_control_none_maximum_assignment_dehumidification_total_output_capacity_guard_false_fallthrough_count: usize,
    pub dehumidification_control_none_maximum_assignment_dehumidification_total_output_maximum_capacity_assignment_count: usize,
    pub dehumidification_control_guard_false_fallthrough_capacity_guard_false_count: usize,
    pub dehumidification_control_guard_false_fallthrough_dehumidification_guard_false_count: usize,
    pub dehumidification_control_guard_false_fallthrough_dehumidification_total_output_assignment_count: usize,
    pub dehumidification_control_guard_false_fallthrough_dehumidification_total_output_capacity_guard_false_fallthrough_count: usize,
    pub dehumidification_control_guard_false_fallthrough_dehumidification_total_output_maximum_capacity_assignment_count: usize,
    pub dehumidification_total_output_capacity_guard_evaluation_count: usize,
    pub dehumidification_total_output_capacity_guard_false_fallthrough_count: usize,
    pub dehumidification_total_output_maximum_capacity_assignment_count: usize,
    pub post_saturation_capacity_limited_dehumidification_supply_enthalpy_assignment_count: usize,
    pub source_site_execution_count: usize,
    pub cp379_retained_supply_enthalpy_owned_read_count: usize,
    pub cp329_retained_mixed_air_enthalpy_owned_read_count: usize,
    pub mixed_air_enthalpy_read_count: usize,
    pub cp384_retained_cooling_total_output_owned_read_count: usize,
    pub cooling_total_output_read_count: usize,
    pub cp330_retained_supply_mass_flow_rate_owned_read_count: usize,
    pub supply_mass_flow_rate_read_count: usize,
    pub specific_cooling_output_calculation_count: usize,
    pub supply_enthalpy_difference_calculation_count: usize,
    pub supply_enthalpy_assignment_write_count: usize,
    pub latest: Option<PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputSupplyEnthalpyAssignmentSnapshot>,
    pub(super) latest_route: Option<PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputSupplyEnthalpyAssignmentRetainedRoute>,
    pub(super) latest_transition_ordinal: Option<usize>,
}

impl PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationTotalOutputSupplyEnthalpyAssignmentRuntimeState {
    /// Creates zeroed CP385 state for one system.
    #[must_use]
    pub const fn new(system: IdealLoadsAirSystemId) -> Self {
        Self {
            system,
            transition_count: 0,
            unit_off_skip_count: 0,
            non_cooling_skip_count: 0,
            positive_guard_false_fallthrough_skip_count: 0,
            heating_availability_guard_false_fallthrough_count: 0,
            humidification_control_guard_false_fallthrough_count: 0,
            dehumidification_control_humidistat_supply_humidity_ratio_maximum_assignment_count: 0,
            dehumidification_control_none_supply_humidity_ratio_maximum_assignment_count: 0,
            dehumidification_control_guard_false_fallthrough_count: 0,
            heating_availability_guard_false_fallthrough_capacity_guard_false_count: 0,
            heating_availability_guard_false_fallthrough_dehumidification_guard_false_count: 0,
            heating_availability_guard_false_fallthrough_dehumidification_total_output_assignment_count: 0,
            heating_availability_guard_false_fallthrough_dehumidification_total_output_capacity_guard_false_fallthrough_count: 0,
            heating_availability_guard_false_fallthrough_dehumidification_total_output_maximum_capacity_assignment_count: 0,
            humidification_control_guard_false_fallthrough_capacity_guard_false_count: 0,
            humidification_control_guard_false_fallthrough_dehumidification_guard_false_count: 0,
            humidification_control_guard_false_fallthrough_dehumidification_total_output_assignment_count: 0,
            humidification_control_guard_false_fallthrough_dehumidification_total_output_capacity_guard_false_fallthrough_count: 0,
            humidification_control_guard_false_fallthrough_dehumidification_total_output_maximum_capacity_assignment_count: 0,
            dehumidification_control_humidistat_maximum_assignment_capacity_guard_false_count: 0,
            dehumidification_control_humidistat_maximum_assignment_dehumidification_guard_false_count: 0,
            dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_assignment_count: 0,
            dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_capacity_guard_false_fallthrough_count: 0,
            dehumidification_control_humidistat_maximum_assignment_dehumidification_total_output_maximum_capacity_assignment_count: 0,
            dehumidification_control_none_maximum_assignment_capacity_guard_false_count: 0,
            dehumidification_control_none_maximum_assignment_dehumidification_guard_false_count: 0,
            dehumidification_control_none_maximum_assignment_dehumidification_total_output_assignment_count: 0,
            dehumidification_control_none_maximum_assignment_dehumidification_total_output_capacity_guard_false_fallthrough_count: 0,
            dehumidification_control_none_maximum_assignment_dehumidification_total_output_maximum_capacity_assignment_count: 0,
            dehumidification_control_guard_false_fallthrough_capacity_guard_false_count: 0,
            dehumidification_control_guard_false_fallthrough_dehumidification_guard_false_count: 0,
            dehumidification_control_guard_false_fallthrough_dehumidification_total_output_assignment_count: 0,
            dehumidification_control_guard_false_fallthrough_dehumidification_total_output_capacity_guard_false_fallthrough_count: 0,
            dehumidification_control_guard_false_fallthrough_dehumidification_total_output_maximum_capacity_assignment_count: 0,
            dehumidification_total_output_capacity_guard_evaluation_count: 0,
            dehumidification_total_output_capacity_guard_false_fallthrough_count: 0,
            dehumidification_total_output_maximum_capacity_assignment_count: 0,
            post_saturation_capacity_limited_dehumidification_supply_enthalpy_assignment_count: 0,
            source_site_execution_count: 0,
            cp379_retained_supply_enthalpy_owned_read_count: 0,
            cp329_retained_mixed_air_enthalpy_owned_read_count: 0,
            mixed_air_enthalpy_read_count: 0,
            cp384_retained_cooling_total_output_owned_read_count: 0,
            cooling_total_output_read_count: 0,
            cp330_retained_supply_mass_flow_rate_owned_read_count: 0,
            supply_mass_flow_rate_read_count: 0,
            specific_cooling_output_calculation_count: 0,
            supply_enthalpy_difference_calculation_count: 0,
            supply_enthalpy_assignment_write_count: 0,
            latest: None,
            latest_route: None,
            latest_transition_ordinal: None,
        }
    }
}
