//! JSON serialization for one CP391 supply-enthalpy overdrying-limit snapshot.

use ep_model::DehumidificationControlType;
use ep_runtime::PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationControlConstantSensibleHeatRatioOverdryingLimitSnapshot;
use serde_json::{Value, json};

pub(super) fn snapshot_json(
    snapshot: PurchasedAirCalcCoolingPostSaturationCapacityLimitDehumidificationControlConstantSensibleHeatRatioOverdryingLimitSnapshot,
) -> Value {
    json!({
        "source": snapshot.source,
        "first_excluded_source": snapshot.first_excluded_source,
        "source_order": snapshot.source_order,
        "system": snapshot.system.0,
        "parent_call_ordinal": snapshot.parent_call_ordinal,
        "controlled_zone": snapshot.controlled_zone.0,
        "unit_off_skipped": snapshot.unit_off_skipped,
        "non_cooling_skipped": snapshot.non_cooling_skipped,
        "positive_guard_false_fallthrough_skipped": snapshot.positive_guard_false_fallthrough_skipped,
        "heating_availability_guard_false_fallthrough": snapshot.heating_availability_guard_false_fallthrough,
        "humidification_control_guard_false_fallthrough": snapshot.humidification_control_guard_false_fallthrough,
        "dehumidification_control_humidistat_maximum_assignment_executed": snapshot.dehumidification_control_humidistat_maximum_assignment_executed,
        "dehumidification_control_none_maximum_assignment_executed": snapshot.dehumidification_control_none_maximum_assignment_executed,
        "dehumidification_control_guard_false_fallthrough": snapshot.dehumidification_control_guard_false_fallthrough,
        "predecessor_capacity_limit_guard_evaluated": snapshot.predecessor_capacity_limit_guard_evaluated,
        "predecessor_capacity_limit_body_entered": snapshot.predecessor_capacity_limit_body_entered,
        "predecessor_active_capacity_limit_guard_false_fallthrough": snapshot.predecessor_active_capacity_limit_guard_false_fallthrough,
        "predecessor_dehumidification_guard_evaluated": snapshot.predecessor_dehumidification_guard_evaluated,
        "predecessor_dehumidification_body_entered": snapshot.predecessor_dehumidification_body_entered,
        "predecessor_dehumidification_guard_false_fallthrough": snapshot.predecessor_dehumidification_guard_false_fallthrough,
        "predecessor_dehumidification_total_output_assignment_executed": snapshot.predecessor_dehumidification_total_output_assignment_executed,
        "predecessor_dehumidification_total_output_capacity_guard_evaluated": snapshot.predecessor_dehumidification_total_output_capacity_guard_evaluated,
        "predecessor_dehumidification_total_output_capacity_adjustment_body_entered": snapshot.predecessor_dehumidification_total_output_capacity_adjustment_body_entered,
        "predecessor_dehumidification_total_output_capacity_guard_false_fallthrough": snapshot.predecessor_dehumidification_total_output_capacity_guard_false_fallthrough,
        "dehumidification_total_output_capacity_guard_false_fallthrough": snapshot.dehumidification_total_output_capacity_guard_false_fallthrough,
        "dehumidification_total_output_maximum_capacity_assignment_executed": snapshot.dehumidification_total_output_maximum_capacity_assignment_executed,
        "predecessor_supply_enthalpy_assignment_executed": snapshot.predecessor_supply_enthalpy_assignment_executed,
        "predecessor_dehumidification_control_type_read": snapshot.predecessor_dehumidification_control_type_read,
        "predecessor_dehumidification_control_type": snapshot.predecessor_dehumidification_control_type.map(control_type_name),
        "predecessor_dehumidification_control_switch_dispatched": snapshot.predecessor_dehumidification_control_switch_dispatched,
        "predecessor_dehumidification_control_constant_sensible_heat_ratio_case_entered": snapshot.predecessor_dehumidification_control_constant_sensible_heat_ratio_case_entered,
        "predecessor_dehumidification_control_constant_sensible_heat_ratio_cp_air_assignment_executed": snapshot.predecessor_dehumidification_control_constant_sensible_heat_ratio_cp_air_assignment_executed,
        "predecessor_mixed_air_humidity_ratio_read": snapshot.predecessor_mixed_air_humidity_ratio_read,
        "predecessor_mixed_air_humidity_ratio": json_number(snapshot.predecessor_mixed_air_humidity_ratio),
        "predecessor_mixed_air_humidity_ratio_ieee_bits": ieee_bits(snapshot.predecessor_mixed_air_humidity_ratio),
        "predecessor_psychrometric_cp_air_evaluated": snapshot.predecessor_psychrometric_cp_air_evaluated,
        "predecessor_psychrometric_cp_air_result_j_per_kg_k": json_number(snapshot.predecessor_psychrometric_cp_air_result_j_per_kg_k),
        "predecessor_psychrometric_cp_air_result_j_per_kg_k_ieee_bits": ieee_bits(snapshot.predecessor_psychrometric_cp_air_result_j_per_kg_k),
        "predecessor_cp_air_assigned": snapshot.predecessor_cp_air_assigned,
        "predecessor_cp_air_j_per_kg_k": json_number(snapshot.predecessor_cp_air_j_per_kg_k),
        "predecessor_cp_air_j_per_kg_k_ieee_bits": ieee_bits(snapshot.predecessor_cp_air_j_per_kg_k),
        "predecessor_dehumidification_control_constant_sensible_heat_ratio_sensible_output_assignment_executed": snapshot.predecessor_dehumidification_control_constant_sensible_heat_ratio_sensible_output_assignment_executed,
        "predecessor_cp384_retained_cooling_total_output_owned_read": snapshot.predecessor_cp384_retained_cooling_total_output_owned_read,
        "predecessor_cp385_cooling_total_output_bit_corroborated": snapshot.predecessor_cp385_cooling_total_output_bit_corroborated,
        "predecessor_cooling_total_output_read": snapshot.predecessor_cooling_total_output_read,
        "predecessor_cooling_total_output_w": json_number(snapshot.predecessor_cooling_total_output_w),
        "predecessor_cooling_total_output_w_ieee_bits": ieee_bits(snapshot.predecessor_cooling_total_output_w),
        "predecessor_cooling_sensible_heat_ratio_read": snapshot.predecessor_cooling_sensible_heat_ratio_read,
        "predecessor_cooling_sensible_heat_ratio": json_number(snapshot.predecessor_cooling_sensible_heat_ratio),
        "predecessor_cooling_sensible_heat_ratio_ieee_bits": ieee_bits(snapshot.predecessor_cooling_sensible_heat_ratio),
        "predecessor_cooling_sensible_output_calculated": snapshot.predecessor_cooling_sensible_output_calculated,
        "predecessor_calculated_cooling_sensible_output_w": json_number(snapshot.predecessor_calculated_cooling_sensible_output_w),
        "predecessor_calculated_cooling_sensible_output_w_ieee_bits": ieee_bits(snapshot.predecessor_calculated_cooling_sensible_output_w),
        "predecessor_cooling_sensible_output_assigned": snapshot.predecessor_cooling_sensible_output_assigned,
        "predecessor_cooling_sensible_output_w": json_number(snapshot.predecessor_cooling_sensible_output_w),
        "predecessor_cooling_sensible_output_w_ieee_bits": ieee_bits(snapshot.predecessor_cooling_sensible_output_w),
        "predecessor_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_resulting_supply_enthalpy_j_per_kg),
        "predecessor_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_resulting_supply_enthalpy_j_per_kg),
        "predecessor_dehumidification_control_constant_sensible_heat_ratio_supply_temperature_assignment_executed": snapshot.predecessor_dehumidification_control_constant_sensible_heat_ratio_supply_temperature_assignment_executed,
        "predecessor_cp379_retained_supply_temperature_state_owned": snapshot.predecessor_cp379_retained_supply_temperature_state_owned,
        "predecessor_preexisting_supply_temperature_c": json_number(snapshot.predecessor_preexisting_supply_temperature_c),
        "predecessor_preexisting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_preexisting_supply_temperature_c),
        "predecessor_cp329_retained_mixed_air_temperature_owned_read": snapshot.predecessor_cp329_retained_mixed_air_temperature_owned_read,
        "predecessor_mixed_air_temperature_read": snapshot.predecessor_mixed_air_temperature_read,
        "predecessor_mixed_air_temperature_c": json_number(snapshot.predecessor_mixed_air_temperature_c),
        "predecessor_mixed_air_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_mixed_air_temperature_c),
        "predecessor_cp388_retained_cooling_sensible_output_owned_read": snapshot.predecessor_cp388_retained_cooling_sensible_output_owned_read,
        "predecessor_cooling_sensible_output_read": snapshot.predecessor_cooling_sensible_output_read,
        "predecessor_cp389_cooling_sensible_output_w": json_number(snapshot.predecessor_cp389_cooling_sensible_output_w),
        "predecessor_cp389_cooling_sensible_output_w_ieee_bits": ieee_bits(snapshot.predecessor_cp389_cooling_sensible_output_w),
        "predecessor_cp387_retained_cp_air_owned_read": snapshot.predecessor_cp387_retained_cp_air_owned_read,
        "predecessor_cp_air_read": snapshot.predecessor_cp_air_read,
        "predecessor_cp389_cp_air_j_per_kg_k": json_number(snapshot.predecessor_cp389_cp_air_j_per_kg_k),
        "predecessor_cp389_cp_air_j_per_kg_k_ieee_bits": ieee_bits(snapshot.predecessor_cp389_cp_air_j_per_kg_k),
        "predecessor_cp330_retained_supply_mass_flow_rate_owned_read": snapshot.predecessor_cp330_retained_supply_mass_flow_rate_owned_read,
        "predecessor_cp329_supply_mass_flow_rate_bit_corroborated": snapshot.predecessor_cp329_supply_mass_flow_rate_bit_corroborated,
        "predecessor_supply_mass_flow_rate_read": snapshot.predecessor_supply_mass_flow_rate_read,
        "predecessor_supply_mass_flow_rate_kg_per_s": json_number(snapshot.predecessor_supply_mass_flow_rate_kg_per_s),
        "predecessor_supply_mass_flow_rate_kg_per_s_ieee_bits": ieee_bits(snapshot.predecessor_supply_mass_flow_rate_kg_per_s),
        "predecessor_cp_air_times_supply_mass_flow_rate_calculated": snapshot.predecessor_cp_air_times_supply_mass_flow_rate_calculated,
        "predecessor_cp_air_times_supply_mass_flow_rate_w_per_k": json_number(snapshot.predecessor_cp_air_times_supply_mass_flow_rate_w_per_k),
        "predecessor_cp_air_times_supply_mass_flow_rate_w_per_k_ieee_bits": ieee_bits(snapshot.predecessor_cp_air_times_supply_mass_flow_rate_w_per_k),
        "predecessor_cooling_sensible_output_over_air_capacity_rate_calculated": snapshot.predecessor_cooling_sensible_output_over_air_capacity_rate_calculated,
        "predecessor_cooling_sensible_output_over_air_capacity_rate_k": json_number(snapshot.predecessor_cooling_sensible_output_over_air_capacity_rate_k),
        "predecessor_cooling_sensible_output_over_air_capacity_rate_k_ieee_bits": ieee_bits(snapshot.predecessor_cooling_sensible_output_over_air_capacity_rate_k),
        "predecessor_supply_temperature_calculated": snapshot.predecessor_supply_temperature_calculated,
        "predecessor_calculated_supply_temperature_c": json_number(snapshot.predecessor_calculated_supply_temperature_c),
        "predecessor_calculated_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_calculated_supply_temperature_c),
        "predecessor_supply_temperature_assigned": snapshot.predecessor_supply_temperature_assigned,
        "predecessor_assigned_supply_temperature_c": json_number(snapshot.predecessor_assigned_supply_temperature_c),
        "predecessor_assigned_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_assigned_supply_temperature_c),
        "predecessor_resulting_supply_temperature_c": json_number(snapshot.predecessor_resulting_supply_temperature_c),
        "predecessor_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_resulting_supply_temperature_c),
        "predecessor_cp390_resulting_supply_enthalpy_j_per_kg": json_number(snapshot.predecessor_cp390_resulting_supply_enthalpy_j_per_kg),
        "predecessor_cp390_resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.predecessor_cp390_resulting_supply_enthalpy_j_per_kg),
        "dehumidification_control_constant_sensible_heat_ratio_supply_temperature_mixed_air_limit_executed": snapshot.dehumidification_control_constant_sensible_heat_ratio_supply_temperature_mixed_air_limit_executed,
        "cp389_retained_supply_temperature_state_owned": snapshot.cp389_retained_supply_temperature_state_owned,
        "preexisting_supply_temperature_c": json_number(snapshot.preexisting_supply_temperature_c),
        "preexisting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.preexisting_supply_temperature_c),
        "cp389_retained_supply_temperature_owned_read": snapshot.cp389_retained_supply_temperature_owned_read,
        "supply_temperature_for_minimum_read": snapshot.supply_temperature_for_minimum_read,
        "supply_temperature_before_mixed_air_limit_c": json_number(snapshot.supply_temperature_before_mixed_air_limit_c),
        "supply_temperature_before_mixed_air_limit_c_ieee_bits": ieee_bits(snapshot.supply_temperature_before_mixed_air_limit_c),
        "cp329_retained_mixed_air_temperature_owned_read": snapshot.cp329_retained_mixed_air_temperature_owned_read,
        "cp389_mixed_air_temperature_bit_corroborated": snapshot.cp389_mixed_air_temperature_bit_corroborated,
        "mixed_air_temperature_for_minimum_read": snapshot.mixed_air_temperature_for_minimum_read,
        "mixed_air_temperature_c": json_number(snapshot.mixed_air_temperature_c),
        "mixed_air_temperature_c_ieee_bits": ieee_bits(snapshot.mixed_air_temperature_c),
        "source_shaped_two_argument_minimum_evaluated": snapshot.source_shaped_two_argument_minimum_evaluated,
        "minimum_supply_temperature_c": json_number(snapshot.minimum_supply_temperature_c),
        "minimum_supply_temperature_c_ieee_bits": ieee_bits(snapshot.minimum_supply_temperature_c),
        "supply_temperature_assignment_performed": snapshot.supply_temperature_assignment_performed,
        "assigned_supply_temperature_c": json_number(snapshot.assigned_supply_temperature_c),
        "assigned_supply_temperature_c_ieee_bits": ieee_bits(snapshot.assigned_supply_temperature_c),
        "predecessor_cp390_resulting_supply_temperature_c": json_number(snapshot.predecessor_cp390_resulting_supply_temperature_c),
        "predecessor_cp390_resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.predecessor_cp390_resulting_supply_temperature_c),
        "dehumidification_control_constant_sensible_heat_ratio_overdrying_limit_executed": snapshot.dehumidification_control_constant_sensible_heat_ratio_overdrying_limit_executed,
        "cp390_retained_supply_enthalpy_state_owned": snapshot.cp390_retained_supply_enthalpy_state_owned,
        "preexisting_supply_enthalpy_j_per_kg": json_number(snapshot.preexisting_supply_enthalpy_j_per_kg),
        "preexisting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.preexisting_supply_enthalpy_j_per_kg),
        "cp390_retained_supply_enthalpy_owned_read": snapshot.cp390_retained_supply_enthalpy_owned_read,
        "supply_enthalpy_for_overdrying_limit_maximum_read": snapshot.supply_enthalpy_for_overdrying_limit_maximum_read,
        "supply_enthalpy_before_overdrying_limit_j_per_kg": json_number(snapshot.supply_enthalpy_before_overdrying_limit_j_per_kg),
        "supply_enthalpy_before_overdrying_limit_j_per_kg_ieee_bits": ieee_bits(snapshot.supply_enthalpy_before_overdrying_limit_j_per_kg),
        "cp390_retained_supply_temperature_owned_read": snapshot.cp390_retained_supply_temperature_owned_read,
        "supply_temperature_for_minimum_humidity_ratio_enthalpy_read": snapshot.supply_temperature_for_minimum_humidity_ratio_enthalpy_read,
        "supply_temperature_c": json_number(snapshot.supply_temperature_c),
        "supply_temperature_c_ieee_bits": ieee_bits(snapshot.supply_temperature_c),
        "psychrometric_minimum_supply_enthalpy_evaluated": snapshot.psychrometric_minimum_supply_enthalpy_evaluated,
        "psychrometric_minimum_supply_enthalpy_j_per_kg": json_number(snapshot.psychrometric_minimum_supply_enthalpy_j_per_kg),
        "psychrometric_minimum_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.psychrometric_minimum_supply_enthalpy_j_per_kg),
        "source_shaped_two_argument_maximum_evaluated": snapshot.source_shaped_two_argument_maximum_evaluated,
        "maximum_supply_enthalpy_j_per_kg": json_number(snapshot.maximum_supply_enthalpy_j_per_kg),
        "maximum_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.maximum_supply_enthalpy_j_per_kg),
        "supply_enthalpy_assignment_performed": snapshot.supply_enthalpy_assignment_performed,
        "assigned_supply_enthalpy_j_per_kg": json_number(snapshot.assigned_supply_enthalpy_j_per_kg),
        "assigned_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.assigned_supply_enthalpy_j_per_kg),
        "resulting_supply_enthalpy_j_per_kg": json_number(snapshot.resulting_supply_enthalpy_j_per_kg),
        "resulting_supply_enthalpy_j_per_kg_ieee_bits": ieee_bits(snapshot.resulting_supply_enthalpy_j_per_kg),
        "resulting_supply_temperature_c": json_number(snapshot.resulting_supply_temperature_c),
        "resulting_supply_temperature_c_ieee_bits": ieee_bits(snapshot.resulting_supply_temperature_c),
    })
}

fn control_type_name(control: DehumidificationControlType) -> &'static str {
    match control {
        DehumidificationControlType::None => "None",
        DehumidificationControlType::ConstantSensibleHeatRatio => "ConstantSensibleHeatRatio",
        DehumidificationControlType::Humidistat => "Humidistat",
        DehumidificationControlType::ConstantSupplyHumidityRatio => "ConstantSupplyHumidityRatio",
    }
}

fn json_number(value: Option<f64>) -> Value {
    value
        .filter(|value| value.is_finite())
        .map_or(Value::Null, |value| json!(value))
}

fn ieee_bits(value: Option<f64>) -> Option<String> {
    value.map(|value| format!("0x{:016x}", value.to_bits()))
}

#[cfg(test)]
mod tests;
#[cfg(test)]
pub(in crate::pipeline) use tests::snapshot as test_snapshot;
